### ISSUE TITLE
Kit de com' | Changer les liens

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#1000]
Contexte : on ne parlait que de BE et pas d'agence d'urbanisme, les contenus ont été modifiés.

Il faudrait changer les contenus des liens ci-dessous : 

- remplacer le contenu de ce [lien](https://docurba.beta.gouv.fr/pdf/kitdecom/BE/pourquoiutiliserdocurba.pdf) par ce [contenu](https://drive.google.com/file/d/19nPK50TGf0JrpFWYqsjasfgxStG2yVdc/view?usp=sharing)

- remplacer le contenu de ce [lien](https://docurba.beta.gouv.fr/pdf/kitdecom/BE/pasapas.pdf) par ce [contenu](https://drive.google.com/file/d/1xPBRGvqO4BLj7TvnjxfXvRgoNeLXQdET/view?usp=sharing)

**Comment by rik** [comment]
C'est en ligne!

**Comment by Octaviedebs** [comment]
Super merci bcp !
