### ISSUE TITLE
Pipedrive | Suppression du champ Date d'édition de la FRP

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#1007]
Clé API = 9f1578c96655a81a330eb09912f0a9b5c1f40d8b

- [x] Supprimer les références à ce champ Date d'édition de la FRP dans le code
- [ ] Puis supprimer le champ Date d'édition de la FRP sur Pipedrive

**Comment by rik** [comment]
@Octaviedebs C'est bon le champ n'est plus utilisé en production, tu peux le supprimer.

**Comment by Octaviedebs** [comment]
C'est fait - merci !
