### ISSUE TITLE
Les infos des groupements (PETR, SMF,...) s'affichent parfois et parfois ne s'affichent pas dans le TdB DDT

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#1012]
Pour les PETR du Pays Barrois et Coeur de Lorraine
Sur Firefox (ok sur Chrome) :
![image](https://github.com/user-attachments/assets/1fb657cf-3a4e-42a6-ac2a-3b2199b7d395)

Mais quand je recharge la page
![image](https://github.com/user-attachments/assets/fea022ce-caca-489e-9993-ae8d5d39d8cf)

Pour les SMF, Tdb vide sur Chrome et Firefox et même lorsque je recharge la page.
![image](https://github.com/user-attachments/assets/6f3d95b0-b106-4773-8140-ca66126e09d1)

Bloquant pour la validation des SCoT lors de l'enquête les DDT ayant Firefox par défaut.

**Comment by HermanceGauth** [comment]
résolu en dev

**Comment by rik** [comment]
En prod, j'ai vérifié et je ferme.
