### ISSUE TITLE
3 procédures secondaires chargent à l'infini + "null" dans le titre. 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#1027]
[demo](https://jam.dev/c/feb7fac1-d832-48d5-bd03-24ea3d1153f8) 
CT concernée : [Breteville sur odon](https://docurba.beta.gouv.fr/ddt/14/collectivites/14101/commune) (14) dans les PS du PLU en cours (et qui devrait être opposable mais c'est un autre sujet) 

### Les 3 procédures secondaires en doublons : 
https://docurba.beta.gouv.fr/frise/a1c13396-a448-4abd-83bd-d43ed2b0cd74 _♻️ -> update 5h plus tard, elle apparait avec le msg "nous n'avons pas pu trouver cette procédure"_ + n'apparait plus dans la liste 🧐
https://docurba.beta.gouv.fr/frise/6cb769f0-6a24-42d3-81c4-b1aea9066f31 _♻️ -> update 5h plus tard, elle apparait avec le msg "nous n'avons pas pu trouver cette procédure"_ + n'apparait plus dans la liste 🧐
https://docurba.beta.gouv.fr/frise/cc442646-421e-41c3-af44-eaea59e69058 _♻️ -> update 5h plus tard, elle apparait avec le msg "nous n'avons pas pu trouver cette procédure"_ + n'apparait plus dans la liste 🧐

### Observations : 
* ce sont 3 procédures identiques - même numéro de proc. - même commentaire renseigné par la DDT 
* ce sont 3 procédures créées sur Docurba 
* "null" dans le titre -> 1ere fois que je vois ça personnellement 

<img width="1109" alt="Capture d’écran 2024-12-09 à 12 02 53 PM" src="https://github.com/user-attachments/assets/7a923c23-991c-4b4f-8b44-a1bd11976593">

FYI - je demande à la DDT si jamais ça leur dit quelque chose - ils ont peut-être eu des problèmes pour créer la proc en étant ensuite absent de la liste des collaborateurs d'où le _triplon_

**Comment by CeliaVermicelli** [comment]
### update 5h plus tard : la liste des procédures secondaires est bien plus longue que lors de ma première demo.. 

voir ici : https://jam.dev/c/90a78c87-fd33-488d-8c50-01e17831d7b8

### Ce qui me surprend : 
* ce matin il n'y avait **que** les 3 modification nº4 citées plus haut, qui maintenant n'apparaissent plus alors que je n'avais pas encore précisé ces ID de procédures à julien pour les cacher 
* à 17h30 je vois une liste pas anodine de nouvelles PS pour cette commune - toutes issues de sudocuh - sauf erreur de ma part l'import n'a pas eu lieu ce matin
*  la ddt m'indique les éléments suivants dans un email à 17h ([voir email](https://app.sparkmailapp.com/web-share/iVXWbCPIGtPKv4CIE-xFVcL6jIJPwN73CdIzHfp8)) : c'est une liste de procédure qui devraient rester dans la page de la commune mais cette liste est bien moindre que celle que je vois à 17h30 -> ça a encore évolué cette aprem ? La ddt ne voit pas la même chose que moi ? 

@rik Help 😅 pour comprendre si possible

**Comment by rik** [comment]
Note de notre conversation d'hier midi : Je ne vois pas de raisons côté staff Docurba pour que l'on ait touché à ces données. Comme les procédures ont été supprimées, il est difficile d'enquêter sur ce qui s'est passé (il faudra aller chercher dans un backup de la base de données). Sans enquête, je suppose une suppression manuelle de la DDT ou collectivité.

Du coup @CeliaVermicelli, je t'assigne l'issue car je ne vois plus d'actions côté dev.

**Comment by CeliaVermicelli** [comment]
Merci pour le résumé @rik ! 

yes je prends la main pour vérifier les attentes de la DDT sur l'existant et basculerai en fonction les différents commentaires obtenus dans de possibles issues

**Comment by CeliaVermicelli** [comment]
En attente du retour de la DDT - je close l'issue pour le moment car la DDT a la main sur la suppression de la proc principale qui n'a pas lieu d'être et semble être le "pb" principal. 
En contact avec Valéry C.
