### ISSUE TITLE
onglet validation des procédures 

### ISSUE THREAD

**Issue by lerayj** [MTES-MCT/Docurba#103]
(1ere version à montrer semaine du 06 novembre?)

**Comment by HermanceGauth** [comment]
Première version pour début novembre finalement donc bien d'être dans cette milestones. N'hésite pas à me dire s'il faut faire des choix pour sortir une première version dans les temps, on les ferra.

**Comment by HermanceGauth** [comment]
D'ailleurs en regardant de nouveau la maquette, il faut l'adapter par rapport à ce qu'on a fait sur les pages collectivités pour que ça reste cohérent, on va garder que le nom de la commune, le code insee et pour la colonne Situation soit :
- DU opposable avec date approbation
- DU en cours avec date de lancement
- tag RNU 
je rajoute @julienzdocurba sur cette issue
![image (1)](https://github.com/MTES-MCT/Docurba/assets/91552054/2cb8a4c8-d271-42de-b515-7d2e769180da)

**Comment by julienzdocurba** [comment]
Tu parles bien d'être consistent avec cette page @HermanceGauth ?
<img width="2560" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/72ee192c-b250-42f7-afc4-f9c0f9499ba6">

**Comment by HermanceGauth** [comment]
yes!

**Comment by julienzdocurba** [comment]
Ok oui c'est clair, ça serait pas mal d'harmoniser ça. Je vais regarder.
