### ISSUE TITLE
Passer l'import quotidien en matinée

### ISSUE THREAD

**Issue by rik** [MTES-MCT/Docurba#1038]
Une fois que `docurba-nuxt3` sera hébergé sur Scalingo (https://github.com/MTES-MCT/Docurba/issues/888) :
- [x] Réaliser l'import le matin à 04h10 UTC (car le dump est déposé à 03h00 UTC ou 04h00 UTC)
- [x] Changer la phrase d'explication par : "Les nouvelles procédures et événements saisis dans Sudocuh sont visibles dans Docurba dès le lendemain matin."

**Comment by CeliaVermicelli** [comment]
Note à moi même, prévenir  : 

- [ ] Sandrine R. 26 
- [ ] Julien G. 60 
- [ ] Arnaud A. 81

**Comment by rik** [comment]
C'est en prod, je te passe la main @CeliaVermicelli.
