### ISSUE TITLE
[ Erreur manuelle ] Changer la valeur Other Poste en Vide pour un user de la commune de Roques

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#1049]
**Contexte** : par erreur j'ai ajouté une valeur à Other Poste au user : urbanisme@mairie-roques.fr
**Conséquence** : ce poste apparait dans le libellé des Collaborateurs pour ce user 

<img width="239" alt="Capture d’écran 2024-12-12 à 13 42 15" src="https://github.com/user-attachments/assets/6519c6a9-a3ec-4839-80c5-e6290e94cf88" />

Il faudrait donc passer le champ Other Poste sur ce User en Vide.
Je ne peux pas le faire depuis Retool (je peux que modifier la valeur mais pas la rendre vide).

Merci ! (aucune urgence)

PS : c'est pas vraiment un bug, donc je l'ai labellisé en ops et 0 prio

**Comment by rik** [comment]
Et voilà, champ vidé.
