### ISSUE TITLE
URGENT : la trame de PAC charge et n'aboutit pas

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#105]
j'ai une session de prise en main des PAC le 5 octobre :/ 

https://docurba.beta.gouv.fr/trames/dept-8
Plusieurs essais, plusieurs minutes d'attentes
Cf PJ 

![Capture d’écran 2023-09-28 à 18 52 21](https://github.com/MTES-MCT/Docurba/assets/111045572/bc9d03de-78e4-4850-998a-c35f75330ca1)

**Comment by UngererFabien** [comment]
Je passe ça en prio demain matin.

**Comment by UngererFabien** [comment]
Correctif en prod à cette date.
