### ISSUE TITLE
Ajouter le formulaire "signaler un problème" sur l'app

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#1064]
### Le lien du form : https://tally.so/r/3qjW27

Ajouter "Signaler un problème" sur l'app pour renvoyer vers le formulaire Tally. 

### Champs à faire remonter automatiquement
Comme on en avait parler, on souhaiterait récupérer les infos de l'user actif sur le site : 

Les données remontent de Tally vers [ce doc excel](https://docs.google.com/spreadsheets/d/1hardYOOOhYPfululLPVwk_aHqg1eQJI6TTsGX4S1SpM/edit?usp=sharing)
Les champs en gris sont idéalement à remonter automatiquement, soit : 
* email user 
* Side User (CT ou Etat)
* Périmètre de validation du compte (numéro du dpt ou code insee/siren)
* URL actif : la page sur laquelle ils se trouve lorsqu'ils remplissent le formulaire.

### 2. depuis les pages EPCI/communes et les FRP, donc url de type : 
* https://docurba.beta.gouv.fr/collectivites/200039824/?isEpci=false
* https://docurba.beta.gouv.fr/ddt/56/collectivites/200027027/epci
* https://docurba.beta.gouv.fr/frise/8ace23d5-aed1-482c-80ab-d9677cf017d3
On te laisse voir visuellement où c'est le plus judicieux et quick win pour toi ? 

### 3. Popup latérale au clic sur "Signaler un problème"
- width = 500px si possible.

Je peux te passer mes identifiants Tally pour que tu explores leurs options pour l'intégration/affichage - je t'écris sur Slack
<img width="1441" alt="Capture d’écran 2024-12-17 à 7 26 37 PM" src="https://github.com/user-attachments/assets/8a635d2d-caa6-4b9d-84c9-be6b384f082e" />

@Octaviedebs 
---

Pour info, le canal "bot-problèmes" est créé sur Slack et nous permet d'être notifié dès qu'il y a une nouvelle entrée sur le formulaire. L'intégration Tally/Slack est prête et on invitera l'ensemble de l'équipe.

**Comment by rik** [comment]
En preview https://github.com/MTES-MCT/Docurba/pull/1087#issuecomment-2563451196. Il faudra se coordonner pour les `hiddenFields`.
