### ISSUE TITLE
Des groupements sans compétence sont visibles sur la page Mes Collectivités

### ISSUE THREAD

**Issue by rik** [MTES-MCT/Docurba#1067]
Étapes pour reproduire :
1. Se connecter avec un profil `departement=55`
2. Visiter https://dev.docurba.beta.gouv.fr/ddt/55/collectivites
3. Cliquer sur "Mes Procédures"
4. Cliquer sur "Nouvelle procédure"
6. Cliquer sur "Mes Collectivités"

Résult constaté :
Le groupement "200032738 SM de la gendarmerie de Bouligny" est visible (et d'autres n'ayant pas la compétence) et l'encart pour l'enquête nous indique 586 collectivités.

Résultat attendu :
Pas de groupement "200032738 SM de la gendarmerie de Bouligny" visible et l'encart pour l'enquête nous indique 514 collectivités.

Note :
Quand on recharge la page "Mes collectivités", le SM gendarmerie disparait et on retrouve bien 514 collectivités.

**Comment by UngererFabien** [comment]
Fixed by: https://github.com/betagouv/docurba-nuxt3/pull/6
