### ISSUE TITLE
Cacher les évènements suggérés pour les procédures SCoT

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#1077]
En attendant que j'ai pu retravailller la colonne scope sugg du tableau.

Actuel : On suggère des évènements aux utilisateurs lorsqu'ils sont dans une procédure SCoT (tout type de procédure), en haut de la FRP de la procédure, comme c'est le cas pour les autres types de DU.
Attendu : Cacher cette suggestion d'évènements uniquement pour les SCoT
![image](https://github.com/user-attachments/assets/a90b8694-0881-4987-bc1d-767a99f12eb0)

**Comment by rik** [comment]
C'est en production !
