### ISSUE TITLE
Pipedrive > Docurba : Exclure des créations d'affaires les comptes créés en préprod 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#108]
Quand on créé des comptes en pré prod, cela créé automatiquement des affaires sur Pipedrive = ce qui fausse un peu la visibilité des vrais pipes.
Il faudrait exclure de l'intégration les comptes créés en pré prod ou les comptes avec des adresses yopmail ou autres critères pertinents.

Merci bcp et à dispo pour en parler !

**Comment by UngererFabien** [comment]
La seule problématique que je vois c'est les phases de test avec la validation des webhooks qui ont besoin d'être test en preprod. Mais on peut améliorer ce process.

**Comment by Octaviedebs** [comment]
Yes clairement c'est ce que je me disais - après c'est pas urgent, je les supprime du coup de pipedrive sur le pipe collectivités manuellement
