### ISSUE TITLE
(enquête) Les users ne peuvent pas annuler leur validation

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#1091]
D'après le retour d'une DDT et mes tests, seul un user admin peut annuler la validation de l'état d'une collectivité. 

**Or il nous semblait utile que les agents puissent annuler quelconque validation sur leur département (ou du moins c'est ce que j'avais compris)** 

Voici la capture de la DDT qui n'a pas accès à "annuler la validation". 
![njofjbbflmpfaiic](https://github.com/user-attachments/assets/e5a8ad80-ae0f-4374-a791-455fe899d6ce)

FYI 1 : J'ai testé la même chose avec mon compte test verified sur le dpt 16 (celia.vermicelli+@gmail.com) qui n'est donc pas admin : je n'avais pas non plus l'option d'annuler la validation

FYI 2 : RAS (Rien à Signaler ;)) depuis mon compte admin, j'ai bien accès à l'annulation de la validation. 

- [ ] Sylvie ddt 16

**Comment by rik** [comment]
L'intention initiale, expliquée dans https://github.com/MTES-MCT/Docurba/issues/817#issuecomment-2501270716 : 
> Validation annulable que par la personne qui a fait la validation : règle OK pour l'instant, on verra si on la fait évoluer courant décembre.

C'est l'intention mais on n'a pas vérifié si elle fonctionne bien. Je vois dans [Metabase](https://metabase.docurba.beta.gouv.fr/question/283-enquete-validateurs-par-departement) que c'est bien Sylvie qui a fait la validation donc je m'attends à ce qu'elle puisse supprimer sa validation.

Est-ce que dans le retour qu'on t'a fait, c'est bien Sylvie qui n'arrive pas à dévalider ?

**Comment by CeliaVermicelli** [comment]
Effectivement c'est bien Sylvie qui avait validé la CT 
Et cela correspond au test que j'ai fait - je venais de valider, puis annulation impossible de ma propre validation.
