### ISSUE TITLE
c'est possible d'indiquer la date du dernier dump sudocuh ?

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#111]
On en avait parlé avant l'été dans l'idée de rassurer les DDT. 
J'imagine que la date pourrait apparaitre sur la page EPCI/commune, voire sur chacune des FRP.

Exemple _"Date du dernier extract de données Sudocuh vers Docurba : 10 juillet 2023."_ 

Pour info @HermanceGauth

**Comment by UngererFabien** [comment]
C'est possible, si on le fait je pense que ça sera manuel jusqu'à ce qu'on implémente la mise à jour quotidienne.

**Comment by HermanceGauth** [comment]
Ok, même si c'est manuel je pense que c'est important pour que tout le monde puisse faire ses tests. Ca peut être mis qu'à un endroit, sur la page Mes collectivités quand les DDT se connectent si c'est plus simple dans un premier temps
