### ISSUE TITLE
Bandeau outil des pac 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#112]
@UngererFabien 

_Partage des PAC : les fonctionnalités d'export .pdf et de partage par email seront bientôt disponibles à nouveau. Merci de votre patience et compréhension._ 

Où mettre ce bandeau, si possible : 
- depuis l'édition d'un projet de PAC 
- depuis la trame départementale du PAC. 
Et pas ailleurs si possible !

**Comment by lerayj** [comment]
@CeliaVermicelli Cette issue a été fix non? On peut close ? ou je confond ?

**Comment by CeliaVermicelli** [comment]
yes @lerayj on a maintenant le bouton pour télécharger les pdf, je close !
