### ISSUE TITLE
Commit 3 articles de la FAQ

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#117]
Il faudrait : 

~~commit ce nouveau [Guide FRP](https://github.com/MTES-MCT/Docurba/blob/dev/content/Guide/guide_FRP.md)~~ 

- commit ce nouvel article de la FAQ https://github.com/MTES-MCT/Docurba/blob/dev/content/FAQ/Premi%C3%A8re%20connexion/GuideFRPall.md = pour info j'ai mis le bon lien, celui du PAD désormais car j'ai migré le guide sur le PAD donc all good

- commit ce nouvel article de la FAQ : https://github.com/MTES-MCT/Docurba/blob/dev/content/FAQ/Premi%C3%A8re%20connexion/WebinaireCTBE.md

Et répondre aux questions suivantes sur le process  : 

- dès que je fais une modification > je clique sur Commit Changes = et je fais une issue ? 
- et ensuite vous vous commit la dernière version de mon fichier ?

**Comment by Octaviedebs** [comment]
Pour le 1er point, le Guide FRP a désormais été migré sur le PAD : célia a fait une issue mais du coup ça a écrasé son guide PAC.

**Comment by Octaviedebs** [comment]
Pour ajouter à cette issue : j'ai également créé une autre FAQ dans une autre section, qu'il faudrait commit en même temps, merci ! : https://github.com/MTES-MCT/Docurba/blob/dev/content/FAQ/Outil%20de%20suivi%20des%20proc%C3%A9dures%20comment%20%C3%A7a%20fonctionne/Guidefrpall.md

**Comment by Octaviedebs** [comment]
@UngererFabien est-ce que tu penses que pour ces 3 FAQ qui sont juste à commit ce serait bon dans la prochaine mep ?

**Comment by CeliaVermicelli** [comment]
Hello @UngererFabien, j'ai aussi mis à jour des questions dans la FAQ (commit dans la branche dev) - si possible de les merge pour le prochain passage en prod. Mercii !

**Comment by UngererFabien** [comment]
Je pense que j'ai tout rajouté et les liens fonctionnent bien.
