### ISSUE TITLE
Bug dimension images dans les trames + PAC 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#122]
**Emplacement pour lesquels j'ai repéré ce problème CJ capture d'écran (image très grande donc illisible. ):** 
Dans cadre juridique -> Lois sur la planif -> Loi Climat et résilience
Dans cadre juridique -> Lois sur la planif -> qu'est-ce qu'un PLU -> le contenu

(Le problème est le même que ce soit dans la trame ou dans le PAC récemment créé)

![Capture d’écran 2023-10-05 à 07 53 18](https://github.com/MTES-MCT/Docurba/assets/111045572/20a23f9d-f0ba-4acb-9a24-1d40929815e9)

![Capture d’écran 2023-10-05 à 07 57 35](https://github.com/MTES-MCT/Docurba/assets/111045572/37fa984c-dd1d-4eda-8530-07eab253b3df)

**Comment by HermanceGauth** [comment]
Je sais pas si c'est vraiment un bug, mais dans ce cas là ça vient du fait qu'on ne peut pas régler la taille des images dans l'édition de PAC (demande que nous ont fait les DDT depuis longtemps) du coup ça donne ça (qui est pas top j'en conviens)

**Comment by UngererFabien** [comment]
J'ai mis une taille maximal de 100% de la largeur de la section. On fera une autre issue @HermanceGauth pour la modification de la taille d'image dans les sections.
