### ISSUE TITLE
Commentaire UX_outil des PAC

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#123]
Cécile Rolant-Guyot

a besoin de voir direct les PAC en cours, validé, etc. 
On lui demande souvent "quels sont les PAC en cours" -> elle ne peut pas aller consulter chacune des collectivités pour voir s'il y a un PAC.

**Comment by julienzdocurba** [comment]
Juste pour que je comprenne:
1. Cécile Rolant-Guyot est une DDT c'est bien ça?
2. On parle bien de vérifier l'état des PaC ici et pas des procédures? Et donc je comprends qu'on peut avoir plusieurs PaC dans un département et qu'ils ont des status comme validé / en cours d'écriture.
3. Et donc en gros on aimerait que les DDT puissent facilement voir l'état de tous les PaC de leur département.

**Comment by CeliaVermicelli** [comment]
Exact (désolée si j'étais pas claire) 
1. Cécile est de la DDT 38 et est cheffe de pôle, donc ne fait pas de PAC mais a besoin de communiquer les avancées des PAC que rédigent son équipe à ses supérieurs
2. Oui, un pac peut être en cours de rédaction, en cours de validation par le préfet, et validé
3. Oui, en tout cas c'est une demande qui rejoint aussi le besoin des personnes qui ne font "que" des PAC et qui voudraient retrouver plus facilement les PAC en cours, sans avoir à re-consulter la collectivité - se souvenir que c'est un PAC pour telle ou telle collectivité 

Remarque : c'est un retour qui nait aussi du besoin d'avoir un "mode brouillon" -> les DDT en général veulent faire des PAC tests sur n'importe qu'elle commune donc c'est aussi lorsqu'elle veulent retrouver ces tests et jongler avec leur PAC réel : elles ne sont plus sûre sur quelle commune/EPCI elles ont fait leur PAC test.

**Comment by julienzdocurba** [comment]
Ok c'est super clair merci beaucoup!

**Comment by CeliaVermicelli** [comment]
ajouté au feedback utilisateur.
