### ISSUE TITLE
Toujours mettre le code INSEE ou SIREN entre parenthèse après le nom d’une commune/EPCI 

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#128]
notamment en haut de la page de la commune ou de l'EPCI

**Comment by HermanceGauth** [comment]
car certaines communes ont le même nom

**Comment by lerayj** [comment]
![Capture d’écran 2023-10-17 à 14 53 18](https://github.com/MTES-MCT/Docurba/assets/5832419/67544423-13a8-45f2-82b2-29f130c786ca)
C'est déjà la cas - peux tu donner des liens précis ou il faudrait mettre ca ?

**Comment by HermanceGauth** [comment]
Oui effectivement je pense que ce feedback datait un peu. Je me dis que ça peut être bien aussi de l'avoir au niveau de la page mes collectivités.
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/d72a7bdf-7cc5-4d5a-866a-eec316159a08)

**Comment by UngererFabien** [comment]
Je l'ai ajouter sous forme de colonne en plus dans le tableau pour plus de lisibilité.
