### ISSUE TITLE
Ajout d'événement = afficher les descriptions courtes indiquées lors de l'ajout (accès connecté)

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#133]
Lorsqu'on ajoute un événement > et qu'on ajoute une courte description, elle ne s'affiche pas sur la FRP.

[cette vidéo ](https://www.loom.com/share/6207fcefae6f4e40b977ea7bda850d32) pour plus de précisions (28sec).

Visibilité : la courte description ne doit apparaitre que dans la Feuille de Route Partagée et pas la Feuille de Route Publique

cf [cette issue](https://github.com/MTES-MCT/Docurba/issues/126)

**Comment by Octaviedebs** [comment]
@HermanceGauth Tu confirmes que pour l'affichage de la courte description d'un événement, on ne veut permettre cette affichage que dans la Feuille de Route Partagée, et pas dans la Feuille de Route Publique (dans le prolongement de la distinction que tu as remise dans cette [issue](https://github.com/MTES-MCT/Docurba/issues/126))

**Comment by HermanceGauth** [comment]
Je confirme!

**Comment by lerayj** [comment]
Done, live au prochain deploy.
