### ISSUE TITLE
DDT_TdB : autres infos à remonter via Sudocuh

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#134]
1. Voir pour avoir un espace commentaire au niveau de la page EPCI/communes pour les remarques de DDT (les BE auront peut-être la même demande pour s'y retrouver dans leur dossiers) qui remontent les commentaires de Sudocuh ou permettent au DDT de rajouter un commentaire quand il n'y en a pas (dans tous les cas non visibles pour le Be ou la collectivité) -> à voir si ça rejoint le besoin "d'excel DDT". 
2. Pb de remontée de commentaires de sudocuh : on ne remonte pas les bons commentaire qui lui permettait de faire la différence entre 2 PLUi sectoriels. (cf PJ 2 Sudocuh) 

Cela donne suite au mail reçu de KEYSER Valérie - DDT 54 : 

_"J'ai quand même quelques questions : En ce qui concerne la commune de Villers-les-Moivrons, la remarque enregistrée dans le Sudocuh" Cette commune n'est pas concernée par les PLUi partiels de secteur Seille et secteur Grand Couronné", je ne la retrouve pas sur DOCURBA. C'est normal ? Cela nous sert d'aide mémoire.

Egalement, je n'arrive pas à différencier, au premier abord, sur le DOCURBA les 2 PLUi de la CC Seille et Grand Couronné - celui du secteur Seille et celui du secteur Grand Couronné.  On a pour chacun en haut PLU-iS. Est-ce normal ?

Vous ne reprenez pas les commentaires faits dans le Sudocuh ou bien cela va-t-il se faire ultérieurement ?

Est-ce moi qui cherche mal ?"_

![Capture d’écran 2023-10-05 à 17 38 47](https://github.com/MTES-MCT/Docurba/assets/111045572/cfb7600b-104c-4049-87c2-1b6906e64f4b)
![image (2)](https://github.com/MTES-MCT/Docurba/assets/111045572/e44c5a7c-fe96-46cd-9630-827a51be1a73)

**Comment by HermanceGauth** [comment]
De mon côté je vois des commentaires mais ce n'est pas les bons
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/55f7f54f-1766-48a2-aee6-5e2a05791704)

**Comment by CeliaVermicelli** [comment]
Je comprends que ce nouveau retour de la DDT 22 vient compléter cette issue : 

> Il manque l'objet de la procédure (commentaire pour décrire la procédure)
> Je me sers de la case 'commentaire' quand je décris l'objet d'une procédure car parfois les communes en lancent plusieurs de même type (exemple modifications)  en même temps, sans toutefois indiquer leur numéros dans les délibérations. Ainsi, ça me permet de savoir à laquelle les actes correspondent.
> Mais cela peut aussi servir à mettre d'autres informations utiles à tout utilisateur de SUDOCUH.

**Comment by CeliaVermicelli** [comment]
Autre retour (de LEMDANI Marie - DDT66) qui rejoint les précédents, si je comprends bien : 

> Je reviens vers vous car je ne retrouve pas dans DOCURBA le n° des procedures (modifications, modifications simplifiées, le nom des DP / MEC....) qui étaient dans Sudocuh.

(pour info, ces ajouts de commentaires sur des issues existantes sert surtout à me rappeler de prévenir ces personnes quand ce sera corrigé)

**Comment by HermanceGauth** [comment]
@lerayj pour résumer : les commentaires qui remontent ne sont pas les bons. Tu as un exemple avec une capture d'écran pour un EPCI du 54 mais n'hésite pas à m'en demander d'autres si tu as besoin.

**Comment by CeliaVermicelli** [comment]
Arnaud Aldiguier de la DDT 81 Tarn 

> Les documents d'urbanisme font l'objet de nombreuses évolutions au cours de leur existence : modifications, révisions, mises à jour et mises en compatibilité. J'ai constaté que Docurba ne reprend pas les numéros et les objets de ces différentes procédures dites "secondaires" contrairement à ce que j'ai pu renseigner dans Sudocuh (se reporter à mes exemples en pièces jointes). Dans ce cas, comment s'y retrouver quand on a plusieurs procédures secondaires en cours ? Vous serait-il possible de compléter Docurba de ces informations indispensables ?

**Comment by HermanceGauth** [comment]
Dans le même mail du Tarn, les PJ avec les deux colonnes qu'ils ne retrouvent pas dans Docurba
[Ex_Docurba.pdf](https://github.com/MTES-MCT/Docurba/files/13217038/Ex_Docurba.pdf)
[Ex_Sudocuh.pdf](https://github.com/MTES-MCT/Docurba/files/13217042/Ex_Sudocuh.pdf)
