### ISSUE TITLE
Spécificité de référentiel dans le Calvados - communes fusionneés

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#137]
Retour de la DDT 14 (Calvados) : 
@lerayj 

_Bonjour, J'attire votre attention sur quelques spécificités dans le Calvados qui pourraient nécessiter d'intervenir dans le paramétrage de Docurba, comme ça a été le cas dans Sudocuh : 

- l'arrêté de création de la commune nouvelle de Saline, qui réunit Sannerville et Troarn, a été abrogée. Sannerville et Troarn ne sont donc pas des communes déléguées ; 
- la commune nouvelle de Cambremer réunit deux communes, Cambremer et Saint-Laurent-du-Mont, qui ne partagent pas le même document d'urbanisme. Il faut donc pouvoir assigner un document d'urbanisme à chacune des deux entités ; 
- Deux PLUi s'appliquent sur la commune nouvelle de Livarot Pays d'Auge. Les communes déléguées de Familly, Préaux-Saint-Sébastien, Cerqueux et Meulles sont concernées par le PLUi du Pays de L'Orbiquet, les autres par le PLUi Pays de Livarot. Il doit donc être possible de sélectionner certaines communes déléguées seulement._ 

Note pour Célia : retour de Marion Roussel

**Comment by HermanceGauth** [comment]
Très bons cas d'usage pour le cas des communes fusionnées dont nous parle Claire. J'ai voulu chercher ce qu'on affiche nous aujourd’hui mais quand je vais dans le Calvados j'ai aucune commune qui s'affiche 
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/d34a2629-8d3f-4d56-811a-6f4cbebc203c)

**Comment by lerayj** [comment]
Sannerville et Troarn ne sont donc pas des communes déléguées
=> Oui, il y a donc bien les 2 mais pas Saline, je ne vois pas de probleme ici
![Capture d’écran 2023-10-17 à 14 03 28](https://github.com/MTES-MCT/Docurba/assets/583241
![Capture d’écran 2023-10-17 à 14 03 44](https://github.com/MTES-MCT/Docurba/assets/5832419/9104abcf-f654-473d-b70b-278f3d7dc4fd)
9/bbf0253c-55fd-4dcc-bfde-dab8ef707777)

La commune nouvelle de Cambremer réunit deux communes, Cambremer et Saint-Laurent-du-Mont, qui ne partagent pas le même document d'urbanisme. Il faut donc pouvoir assigner un document d'urbanisme à chacune des deux entités ;
=> Ce pas me paraît improbable - Saint-Laurent-du-Mont n'existe plus dans le référentiel. Est-ce qu'on veut vraiment traiter ce genre de cas ?

Même problème pour Livarot Pays d'Auge. La commune a été créée en 2016, il y a 7 ans, et ils ont encore des PLU séparés entre communes fusionnées (qui n'existent plu de coup, ça n'a pas de sens) ? Là on rentre dans des mailles d'exception.

En gros on est en train de dire que des communes ont fusionnée mais en fait non.

Qu'est ce que vous en pensez ?

**Comment by HermanceGauth** [comment]
Pour le point 1 d'accord avec toi, peut-être qu'ils n'ont pas pu faire le test car ils n'avaient pas accès à leurs communes. @CeliaVermicelli dans le cadre d'un échange avec eux tu pourras re-checker ce point là.

Pour les deux autres points, la situation sera résolue quand ils referont des DU mais effectivement en attendant deux DU perdurent sur des communes fusionnées. C'est là que pour moi il faudrait un affichage similaire au PLUiS. Fabien disait qu'on avait en mémoire les communes fusionnées dans l'INSEE donc je pensais que ça serait ok. 
- pour Cambremer, dans la liste des communes n'afficher que Cambremer mais quand on consulte la page de la collectivité, retrouver la commune de Saint-Laurent-du-Mont et son DU;
- pour Livarot Pays d'Auge idem, il y a que cette commune qui s'affiche dans la liste des communes mais quand on la consulte on retrouve l'historique avec les anciennes communes (et les PLUi qui les concerne)

J'ai pas accès là donc je ne sais pas si c'est ce qu'on fait déjà ou pas.

**Comment by lerayj** [comment]
yes pour que tu vois il faut que @UngererFabien fasse la mis en prod ce soir pour fix le Calvados de cette issue #144

**Comment by HermanceGauth** [comment]
Yes j'ai regardé du coup et donc on ne remonte pas les infos des anciennes communes dans l'historique. C'est ça le point de Claire sur les communes fusionnées et pour le coup je pense qu'on va avoir pas mal de cas. @UngererFabien dans l'INSEE on a bien la trace des anciennes communes, est-ce que tu penses que c'est faisable un affichage comme je l'ai mis dans mon commentaire précédent sur le modèle des PLUi sectoriels? (pas dans le tableau de bord où on est bien dans la situation actuelle mais dans l'historique une fois qu'on est sur la page collectivité).

**Comment by CeliaVermicelli** [comment]
Hello ! Update suite à un échange avec 7 personnes de la DDT 14 : 

Verbatims : 

> "on a besoin de pouvoir assigner des DU en propre à des communes déléguées sinon les données sont faussées et ne peuvent pas faire le suivi correctement" 
> "on a besoin que ce paramétrage soit effectif" 

Ils se sont créés un tableur interne qui est exhaustif face à ces fusions de communes car Sudocuh en l'état est très peu fonctionnel pour eux à cause de ces cas particuliers. 
Ils me partagent leur tableur, je vous tiendrai au courant. 

Dernière question de l'entretien : **"Qu'est-ce qui serait un frein à l'utilisation de Docurba ?"** : 

- extraction de données : qu’on ne puisse pas refaire les cartes qu’on nous demande

- historique Sudocuh VS état actuel des compétences : qu’on ne puisse pas retrouver le niveau de détails des DU - ex communes historiques (pleins de cas particuliers dans le Calvados)"

Donc oui ça semble être un sujet important.

**Comment by CeliaVermicelli** [comment]
Vous retrouver leur tableur interne de suivi et leur utilisation de la data [via ce lien](https://drive.google.com/drive/folders/1pqP3cokw3hQ63WYJBVrD9HSTS66yx4A2?usp=sharing)

**Comment by HermanceGauth** [comment]
@UngererFabien sur Cambremer on voit bien les deux PLU avec le bon statut!! Mais il ne trouve pas le nom de la deuxième COMD (a priori Saint-Laurent-du-Mont)
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/88d7c6d2-8141-4307-9a59-f78cce2281d9)

**Comment by HermanceGauth** [comment]
@UngererFabien pour Livradot pays d'auge : https://dev.docurba.beta.gouv.fr/ddt/14/collectivites/14371/commune
On retrouve bien tous les DU mais ils sont tous sous l'étiquette de la nouvelle commune et non pas en COMD. Après la DDT a mis les commentaires qui vont bien donc je pense que c'est ok.

**Comment by HermanceGauth** [comment]
idem je close l'issue pour en ouvrir une par cas
