### ISSUE TITLE
FAQ : mauvais renvois des url de la recherche de question par mots clefs.

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#141]
FYI @Octaviedebs 

Voici ce que j'ai mentionné ce matin. le partage de question de la FAZ via l'url de la recherche par mot clef fonctionnait au début, j'ai remarqué hier que les liens ne renvois plus à la bonne "action rapide" de la FAQ - et donc aucune question de la FAQ n'est mise en valeur : 

**Exemple avec comme mot clef "obligatoire"** -> en partageant cette url, je cherche à renvoyer la personne à la lecture de la question "est-ce obligatoire de renseigner les actes sur docurba", question appartenant à l'action rapide "outil de suivi des procédures" cf PJ, et voir résultat plus bas. 

![Capture d’écran 2023-10-11 à 11 59 09](https://github.com/MTES-MCT/Docurba/assets/111045572/2fae6757-8fe3-426c-9e14-deaf6324f58a)

**---> Résultat** ; une fois l'url partagée, elle renvoit bien sur ce mot clef "obligatoire" mais dans l'action rapide _"qu'est-ce que Docurba"_ donc aucune question n'est mise en valeur.

![Capture d’écran 2023-10-11 à 11 59 30](https://github.com/MTES-MCT/Docurba/assets/111045572/f7747e93-b853-4035-8b28-c64b83b11d8c)

(j'ai aussi fait le test avec "EnR" - même résultat pas utilisable)

**Comment by Octaviedebs** [comment]
ok très clair !

**Comment by UngererFabien** [comment]
J'ai rajouter l'action rapide dans l'url comme fix. Mais du coup l'url est bien moins jolie à partager.

/faq?scope=1&action=Outil%20de%20suivi%20des%20procédures&recherche=obligatoire

Il faut fix ça pour chercher dans toutes les questions celle qui match le scope et le titre. A réouvrir après le travail sur le CMS en fonction de la gestion de contenu de la FAQ.
