### ISSUE TITLE
Guide outil des PAC : nouveau lien à intégrer au site

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#142]
@lerayj peut-on changer le lien du guide outil des PAC actuel https://docurba.beta.gouv.fr/guide pour ce lien : https://pad.incubateur.net/s/zG4jtJNL9

je voudrais que de la même manière il apparaisse ici : 
![Capture d’écran 2023-10-12 à 12 50 26](https://github.com/MTES-MCT/Docurba/assets/111045572/e9a7691c-1454-429d-ab95-f17c66a4ca66)

**Comment by CeliaVermicelli** [comment]
Et attention, ce lien de guide [https://docurba.beta.gouv.fr/guide](https://docurba.beta.gouv.fr/guide ) contient maintenant des instructions FRP pour les CT/BE (alors que c'était l'url partagé aux DDT pour l'outil des PAC) :_ j'imagine que vous avez juste utiliser la même url pour les deux types de guide.

FYI @Octaviedebs

**Comment by CeliaVermicelli** [comment]
@UngererFabien c'est possible de passer ça dans la mise en prod de demain ?

**Comment by UngererFabien** [comment]
Je le passe aujourd'hui avec les KPIs
