### ISSUE TITLE
Bug tableau de bord Calvados (14) : l'onglet commune est vide

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#144]
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/2202a6e6-837a-438b-8e5d-f02e05f38ceb)
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/757b3b3e-d6cd-4066-b8d3-a4d06c084bc5)

**Comment by UngererFabien** [comment]
A régler en urgence

**Comment by lerayj** [comment]
Done
