### ISSUE TITLE
Sendgrid | Confirmation puis mise en production des nouveaux emails

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#145]
**Contexte** : 

- on a uniformisé en terme de design et de structure des emails, tous les emails transactionnels qui partent de Sendgrid
- une nouvelle version a été ajoutée pour chaque email présent sur Sendgrid
- ils ont également été renommés
- un template est désormais enregistré pour les futurs emails

**Contenu de l'issue** : 

- Il faudrait donc valider ensemble les éléments que j'ai mis {{ ... }} qui correspondent, comme convenu, aux éléments à faire remonter dans les emails (ex : nom du département etc) mais je n'avais donc pas le bon wording correspondant
- dans un des emails par exemple je n'ai pas encore le lien d'un article de la FAQ qui n'est pas encore publié via github, je le modifierai le cas échéant mais à checker avant la mep si j'oublie haha
- il faut mettre les URL pour les CTA = par exemple dans un des emails, il faudrait qu'il redirige vers la FRP nouvellement créée suite dépôt d'acte - or le lien n'est pas encore techniquement fait, donc à suivre et maj le moment venu
- et donc ensuite les mettre en prod

Si besoin d'une précision n'hésitez pas ! merci bcp !

**Comment by Octaviedebs** [comment]
**UPDATE** :

Contenu de l'issue :

💬 _Il faudrait donc valider ensemble les éléments que j'ai mis {{ ... }} qui correspondent, comme convenu, aux éléments à faire remonter dans les emails (ex : nom du département etc) mais je n'avais donc pas le bon wording correspondant -_ @UngererFabien n'hésite pas à me dire si tu as besoin qu'on s'aligne

✅ _dans un des emails par exemple je n'ai pas encore le lien d'un article de la FAQ qui n'est pas encore publié via github, je le modifierai le cas échéant mais à checker avant la mep si j'oublie haha_ = c'est bon !

💬 il faut mettre les URL pour les CTA = par exemple dans un des emails, il faudrait qu'il redirige vers la FRP nouvellement créée suite dépôt d'acte - or le lien n'est pas encore techniquement fait, donc à suivre et maj le moment venu
et donc ensuite les mettre en prod

**Comment by Octaviedebs** [comment]
Hello @UngererFabien ! Petit up sur cette issue :) 

Je pense que ce serait pertinent de se prévoir un rapide point pour dérouler l'issue + pour valider les attributs des emails Sendgrid comme on se l'était dit.

Notamment un point d'attention sur l'email lié au lien de connexion (aucun email de confirmation de validation de notre côté une fois qu'on a validé via le bot -   j'avais modifié la V1 en ce sens mais peut être pertinent de séparer plutôt confirmation email + validation email  tu me diras) + comprendre ce qu'il se passe derrière

**Comment by Octaviedebs** [comment]
Hello ! Désolée de revenir dessus mais est-ce que (si vous avez besoin de précisions) ce ne serait pas l'occasion mercredi d'avancer dessus ? Merci !

**Comment by UngererFabien** [comment]
A date j'ai mis à jour tous les templates qui étaient déjà présents sur la branche 145-sendgrid-confirmation-puis-mise-en-production-des-nouveaux-emails

Il manque encore les emails lié au partage et aux updates de PAC.

@lerayj je veux bien que tu regardes pour [ce template](https://mc.sendgrid.com/dynamic-templates/d-ff4df2141eda4723800cae1f0a63982c/version/86f38678-f2e1-4207-9688-f1d58483d656/editor) sur le dépôt d'acte.

**Comment by Octaviedebs** [comment]
@UngererFabien est-ce que je peux modifier directement le template pas encore Actif du coup ? J'ai juste une mini modif à faire sur 2 emails

**Comment by Octaviedebs** [comment]
Peut être que ça n'a aucun rapport mais j'ai essayé de modifier le texte (je dois juste ajouter un lien hypertexte notamment sur une phrase pour pousser l'inscription à la NL, et impossible de l'ajouter ce lien, pourtant je peux ajouter du texte

C'est peut être juste Sendgrid qui bugue 

https://jam.dev/c/2bb9bf59-2fc0-4d67-bc19-4c0f6b8d9188

**Comment by UngererFabien** [comment]
Si tu modifies direct un template actif et que tu ne rajoutes pas de valeurs dynamiques entre {{}} il n'y a même pas besoin de passé en prod, la modification est instantanée. Perso je ne vois aucune contre-indication à faire ça.

Si tu as besoin de nouvelles valeurs dynamiques c'est mieux effectivement que tu créer une nouvelle version de template et que tu fasses une issue. Donc exactement ce que tu proposes.

**Comment by Octaviedebs** [comment]
Super @UngererFabien merci !pour la postérité je continue ici aussi haha mais j'ai un petit souci avec le nouveau email que j'ai créé https://jam.dev/c/274aca42-f1df-4665-afaa-a38c5c4cdce0
Il se met en ligne automatiquement (je l'ai bien reçu en me créant un compte) et je n'arrive pas à le désactiver - or en principe tu as dû ne rien mettre pour les conditions d'envoi pour cet email je comprends pas haha
