### ISSUE TITLE
Accès DDT bloqué à leur département

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#146]
Mais attention dans le cas de PLUi interdépartementaux, il y a une DDT pilote/référente pour toutes les communes du PLUi et qui doit donc pouvoir intervenir sur les communes qui sont dans ce PLUi mais pour un département autre que le sien. Elle pourrait avoir accès à ces communes en partant de l'EPCI interdépartemental mais il ne faut pas que l'outil la bloque.

Exemples :
- EPCI CC Mad et Moselle (54/57)
- EPCI CC Coeur du Pays du Haut (54/55)

**Comment by HermanceGauth** [comment]
@lerayj pour le chantier droit d'accès?

**Comment by HermanceGauth** [comment]
Pour les SCoT interdépartementaux aujourd'hui les deux DDT ont bien accès donc on a le comportement attendu.
L'issue ici concerne le fait de pouvoir aller d'un département à l'autre en changeant l'URL.

**Comment by HermanceGauth** [comment]
Je résume le comportement attendu :
- ne pas pouvoir avoir les droits sur les autres départements en changeant l'URL ou en passant pas la page d'accueil de Docurba
- pour procédure interdépartementale : droit en écriture de toutes les DDT concernées mais ne doit pas donner accès aux autres procédure de l'autre département qui ne sont pas interdépartementale
- si enquête : DDT  de la collectivité de référence qui doit avoir les droits (info trouvable sur banatic d'après Claire)

**Comment by CeliaVermicelli** [comment]
Test en dev  :

* _ne pas pouvoir avoir les droits sur les autres départements en changeant l'URL ou en passant pas la page d'accueil de Docurba_ -> **OK** ✅
* _pour procédure interdépartementale : droit en écriture de toutes les DDT concernées mais ne doit pas donner accès aux autres procédure de l'autre département qui ne sont pas interdépartementale_ -> OK ✅ cf demo depuis un accès 81 et pour consulter une commune d'un EPCI à cheval sur le 81 et le 34 : https://jam.dev/c/9a3a0862-32a8-4d3d-a31f-71a4426de39d _-> le retour me renvois sur la CT du 81 (accès initial) et non comme avant à basculer dans le 34._
Dans l'autre sens : cf demo https://jam.dev/c/555723b4-e3cd-4af8-b08a-d719b4e346ef. Depuis un accès du 34, je consulte la commune de l'EPCI à cheval sur le 81 ; je peux accéder aux PLUi (géré par le 81), le retour au tdb me fait bien revenir au 34. 
* _si enquête : DDT de la collectivité de référence qui doit avoir les droits (info trouvable sur banatic d'après Claire) ->_ voir démo précédente. Le 81 devrait avoir tous les droits, mais le 34 peut aussi accéder au PLUi (d'après les retours utilisateurs ça n'est pas un problème). 
Les communes à valider entre le 56 et 35 par exemple apparaissent bien pour un seul département dans ce cas d'usage et je comprends que c'est le plus important pour le sujet de l'enquête.

**Comment by HermanceGauth** [comment]
Ok avec les commentaires de Célia par contre j'ai pu créer une procédure pour une collectivité d'un département qui n'était pas le mien (cf cette issue : https://github.com/orgs/MTES-MCT/projects/37/views/6?pane=issue&itemId=63613698) et ce jam : https://jam.dev/c/ff0c0ea6-9247-4aae-a1a9-66bdbad760d0 donc il faut régler ce cas avant la mise en prod

**Comment by UngererFabien** [comment]
J'ai modifier pour que seul les admin de la collectivité ddt ou collectivite puisse faire une nouvelle procédure. Si jamais ils sont admin non vérifié ils sont redirigés sur la page d'attente de validation.

https://www.loom.com/share/271ef47892ad47f79aefbd665e117dd5?sid=aa4762a0-75a8-4848-9014-a280e8e8f00b

**Comment by CeliaVermicelli** [comment]
Suite à ton loom @UngererFabien : 

* l'écran à afficher pour un user admin pas encore vérifié ce serait plutôt le "en attente de validation" qui existe déjà - cf capture. 
* sur l'accès en lecture du tdb ddt, ça me semble ok du moment qu'ils n'ont la possibilité de faire aucune action (pas d'ajout event ni procédure ni PAC) - en plus on valide très rapidement ces comptes en général


<img width="1467" alt="Capture d’écran 2024-08-28 à 5 19 28 PM" src="https://github.com/user-attachments/assets/727a0237-2b5f-4bb1-b5f1-f22ebb5ae5bd">

**Comment by CeliaVermicelli** [comment]
on a la page en attente de validation. je close l'isssue.
