### ISSUE TITLE
Socle de PAC/trame _ certaines sections du CJ n'apparaissent pas suivant les dpt

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#147]
Je crois que c'est un sujet qui est repris dans 1-2 issues mais je ne les retrouve pas. 
Comment s'assurer que tous les départements profitent de toutes les mises à jour du socle de PAC ? 

Le 22 cherchait la sous section sur la loi du 20 juillet 2023 (sous section de la loi climat et résilience - lois planif - CJ) : 
- je retrouve cette section sur le socle de certains dpt (et pas sur l'01 par exemple), 
- idéalement la ddt 22 voudrait le retrouver dans sa trame ; voici son retour.

Retour de Bellay DDT 22 : 
 

> depuis l'onglet "trame départementale", cadre juridique -> lois sur la planif -> lois climat et résilience et je ne trouve pas la sous section dont vous parlez, alors que mon collègue voit cette sous-section, en faisant la même chose. 
Alors, j'ai fait F5 pour voir si ça rafraîchissait la page : rien de mieux
Je vais laisser reposer jusqu'à jeudi, je réessayerai et je vous redis...

(Je pense que son collègue devait être au niveau du socle)
pour info je lui ai envoyé cette video de demo pour lui montrer où la trouver : https://drive.google.com/file/d/1uGucHgkTN_LJAIll7KEebIcMr1S94Zmw/view?usp=sharing

**Comment by UngererFabien** [comment]
Je vais regarder. Pas sur que ça soit un bug. Normalement les trames sont à jour. Ce qui peut manquer c'est les sections fantomes.

**Comment by CeliaVermicelli** [comment]
Nouveau retour Cecilia Bellay (22)

> J'ai revu avec mon collègue. Il voit la sous-section de la loi Climat et résilience en mode "déconnecté". D'ailleurs, on voit 2 fois la section sur la loi LCR: 1 avec la sous-section , l'autre sans.
> Moi aussi, en mode déconnecté.
> Mais lorsque je me connecte soit avec mon accès perso soit avec l'accès du service, je ne vois qu'une fois LCR et je ne vois pas la sous-section de la loi du 20/07/23 dans ma trame départementale.

-> je comprends qu'il y a des confusions entre socle de PAC et trame - et ce qu'ils imaginent obtenir automatiquement dans leur trame (on en revient à la MAJ auto des trame suite aux maj du cadre juridique) 
et effectivement ce que tu disais sur les sections fantômes.

**Comment by CeliaVermicelli** [comment]
Nouvel exemple de **différences entre les socle de PAC** suivant les départements : 

### La section "Qu'est-ce qu'un SCoT" : 
- est disponible pour une [EPCI de l'Aisne](https://docurba.beta.gouv.fr/collectivites/200040426/pac?document=PLUi&isEpci=true&path=PAC%2FCadre-juridique-et-grands-principes-de-la-planification%2FQu%27est-ce%20qu%27un%20SCoT%3F), [une commune des Alpes maritimes](https://docurba.beta.gouv.fr/collectivites/06021/pac?document=PLU&isEpci=false&path=PAC%2FCadre-juridique-et-grands-principes-de-la-planification%2FQu%27est-ce%20qu%27un%20SCoT%3F)
- n'est **pas dispo** pour [une commune de l'Ain](https://docurba.beta.gouv.fr/collectivites/03001/pac?document=PLU&isEpci=false), [une EPCI de l'Allier( 03 -Aura)](https://docurba.beta.gouv.fr/collectivites/200071082/pac?document=PLUi&isEpci=true)

-> **le conditionnement d'apparition des sections suivant le type de collectivité choisi au moment de la recherche publique est effectif en Aura et pas dans les autres régions ?** -> si c'est le cas c'est top si possible de l'appliquer à toutes les régions. 
Mais tant que les MAJ de QV4 sur les cadre juridique n'est pas "forcé" sur toutes les trames, alors on "perdrait" ce contenu lié au SCoT par exemple (car on ne peut pas choisir les SCoT dans la recherche publique) 


### La sous-section "Loi nº2023-630 du 20 juillet 2023" de la Loi Climat et Résilience : 

- est disponible pour : [une EPCI des Alpes MAritimes](https://docurba.beta.gouv.fr/collectivites/240600551/pac?document=PLUi&isEpci=true), [une commune de l'Aube](https://docurba.beta.gouv.fr/collectivites/11005/pac?document=PLU&isEpci=false&path=PAC%2FCadre-juridique-et-grands-principes-de-la-planification%2FLois%20sur%20la%20planification%2FClimat%20et%20R%C3%A9silience%2FLoi%20n%C2%B02023-630%20du%2020%20juillet%202023.md)
- **n'est pas disponible** pour : [EPCI de l'Ain](https://docurba.beta.gouv.fr/collectivites/200040350/pac?document=PLUi&isEpci=true) et [commune de l'Ardèche](https://docurba.beta.gouv.fr/collectivites/07007/pac?document=PLU&isEpci=false)

-> ce "pb" est probablement différent ; cette nouvelle section n'a pas été pushé sur tous les socles de tous les dpt ?
De manière générale les versions ont l'air d'être géré différemment entre l'Aura et les autres régions

FYI @HermanceGauth

**Comment by CeliaVermicelli** [comment]
Résolu avec la MEP de février : section fantômes, harmonisation des titres, maj du socle de PAC/Main automatique sur les trames dpt.
