### ISSUE TITLE
Design création de compte collectivité

### ISSUE THREAD

**Issue by julienzdocurba** [MTES-MCT/Docurba#148]
Les changements qu'on souhaite apporter au flow de création de compte pour les collectivités.

Sur Figma (regardez seulement la partie "Proposition"): https://www.figma.com/file/4W463mFBKoDzf4mgJAhW9y/Docurba-(V2)?type=design&node-id=3402-145912&mode=design&t=cKwCRPPolV2siwNK-0

On peut en parler lors d'un call quand on priorisera ça.

**Comment by Octaviedebs** [comment]
@julienzdocurba @lerayj Est-ce que je peux avoir un peu de contexte sur la fermeture de cette issue ? Sauf erreur de ma part en regardant le figma il n'y a pas eu les changements évoqués non ? 
ou elle est juste périmée cette issue du coup ? Merci pour vos précisions

**Comment by julienzdocurba** [comment]
Il me semble qu'on avait implémenté l'essentiel de la proposition et comme l'issue est super vieille ca me va de la fermer pour l'instant.
