### ISSUE TITLE
FRP : indiquer sur chaque évènt quelle entité l'a créé (DDT/collectivité/BE)

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#153]
A la manière du tag Sudocuh

**Comment by julienzdocurba** [comment]
Est-ce qu'il serait intéressant de préciser la personne spécifique dans l'entité qui a créé l'événement? Par exemple pour savoir qui contacter en cas de question etc.

**Comment by HermanceGauth** [comment]
Ca sera certainement un plus à termes mais l'entité suffit dans un première version. Ça rejoint aussi la question d'avoir quelque part les noms et adresse mail pro de toutes les personnes qui collaborent sur une FRP.

**Comment by HermanceGauth** [comment]
Ce matin j'ai eu de nouveau ce retour avec effectivement a minima l'entité (DDT, collectivté, BE) et dans l’idéal jusqu'au nom de la personne qui a rentré l'event (mais ils avaient la crainte que certaine personne comme les secrétaires de mairie par exemple, ne veuillent pas que leur nom apparaissent)

**Comment by julienzdocurba** [comment]
Oui on peut garder un oeil sur ce genre de retours mais ca me semble être une feature intéressante (pour savoir qui contacter à propos d'une procédure par exemple) et assez standard (sur tous les outils de collaboration on a les noms des différents acteurs).

**Comment by CeliaVermicelli** [comment]
Hello, je rajoute un retour obtenu de NAQ la semaine dernière : 

Les personnes ayant déjà bien manipulé Docurba auparavant et plus "tatillones" trouvaient que de savoir en DDT qui avait renseigné l'event serait important + la date d'ajout de l'évent -> je pense que ça vient d'une "peur" de ne pas savoir qui doit faire quoi à quel moment et si jamais le site ne s'actualise pas rapidement

**Comment by HermanceGauth** [comment]
Chantier droit d'accès

**Comment by HermanceGauth** [comment]
Je close car cela correspond à cette issue dans le sprint actuel : https://github.com/MTES-MCT/Docurba/issues/616
