### ISSUE TITLE
Ajout d'évènement : mettre la visibilité par défaut sur "Privé"

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#154]
A la place de "publique"

**Comment by lerayj** [comment]
done

**Comment by julienzdocurba** [comment]
Désolé je viens de voir que l'issue avait été fermée mais je voulais en parler sur le redesign de la FRP parce que je voulais proposer de garder public par défaut. Vous êtes sûrs que vous voulez mettre les événements en privé par défaut? Ca peut avoir un gros impact parce qu'il y a rien qui incite vraiment les utilisateurs à changer un événement en "public" et du coup on va peut être se retrouver avec une majorité de FRP inaccessibles au public.

**Comment by HermanceGauth** [comment]
Hello, oui on est vraiment sûr car tous les event n'ont pas vocation à être public d'ailleurs c'est plutôt une minorité. Dans une deuxième version on pourrait peut-être mettre public par défaut pour des éléments qu'on voudrait voir public et privé sinon? Mais ça risque d'être un peu confus pour les utilisateurs?

**Comment by julienzdocurba** [comment]
Oui je pense que c'est risqué de changer ce comportement en fonction du type d'événement. On pourra y réfléchir mais je pense qu'il y a des chances que ca génère des erreurs.

Ok si on pense que la majorité des événements doivent être privés c'est bon!
