### ISSUE TITLE
[ FRP ] Les dates des événements (à gauche) ne correspondent pas aux dates de modifications (à droite)

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#157]
Les dates des événements (à gauche) ne correspondent pas aux dates de modifications (à droite) voir par exemple sur cette procédure = https://docurba.beta.gouv.fr/frise/139304

Par ailleurs, l'année n'apparait pas dans modifications, mais c'est peut être un choix

Si vous avez besoin de + d'éléments ou de + d'exemples, n'hésitez pas !

**Comment by lerayj** [comment]
outdated
