### ISSUE TITLE
[FRP - accès DDT - event ] : consultation du fichier joint impossible 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#164]
Cf pj 1 et 2 (avec détails console) 

**Bug : on ne peut pas consulter le fichier joint dans un event** (je pensais qu'une issue avait déjà été ajoutée mais je ne l'ai pas retrouvée)

La DDT voudrait vérifier/consulter le fichier joint dans les événements tout juste créé -> pas possible depuis la création de l'event, pas possible non plus une fois que l'event est ajouté dans la FRP. 
![Capture d’écran 2023-10-23 à 13 13 02](https://github.com/MTES-MCT/Docurba/assets/111045572/6a0935cc-c6a1-4271-820c-1ffd011a37bd)
![Capture d’écran 2023-10-23 à 13 13 46](https://github.com/MTES-MCT/Docurba/assets/111045572/9cda5f82-2d82-454c-9532-7087dfd9fcf8)

**Comment by CeliaVermicelli** [comment]
(DDT 38 - chantal.charles@isere.gouv.fr)

**Comment by lerayj** [comment]
outdated
