### ISSUE TITLE
Test et validation Données GPU

### ISSUE THREAD

**Issue by UngererFabien** [MTES-MCT/Docurba#166]
Retour d'Ines

Sur la Communauté d’agglomération Durance-Lubéron-Verdon Agglomération:
- “halage et marche pied” me renvoie vers un territoire près de Paris
- des jeux de données supposés différents renvoient vers la même carte
sur la communauté val de charente
- lien vers GPU non disponible sur certains jeux de données

Et je ne sais pas si c’est l’intégration ou le GPU lui-même mais les légendes (i) ne sont pas disponibles pour savoir à quoi correspond l’aplat de couleur.

![Service indisponible GPU](https://github.com/MTES-MCT/Docurba/assets/2676385/3a09aa99-a3b7-4543-854f-ec35cb8c9510)
![SUP réserve naturelle_CC Val de Charente](https://github.com/MTES-MCT/Docurba/assets/2676385/a00b5e97-5d3d-452d-bf3c-ebc7c21d9f03)
![SUP Halage et marchepied_CC Lubéron](https://github.com/MTES-MCT/Docurba/assets/2676385/6d582d10-18db-4fbd-9ae6-394d5529d5a9)
![SUP Plan prévention risques + foret protection + site inscrit et classé_CC Lubéron ](https://github.com/MTES-MCT/Docurba/assets/2676385/f20a84be-27c3-4db3-8ec6-22f0991f8839)

**Comment by UngererFabien** [comment]
Retour Celia

Sur mes tests tout semble fonctionner (pas de "non disponible") mais le résultat obtenu sur la carte ne parait pas correspondre :thinking_face:
Ex : recherche de données pour la CC Centre Morbihan Communauté (56) - click sur "voir la carte" des canalisations électriques 444619258_SUP_R53_I4 et le résultat : [cette carte](https://www.geoportail-urbanisme.gouv.fr/map/?document=bb22f6a21d3068d9b490f7d94b1f7ed6#tile=1&lon=-3.8356618001214984&lat=48.29897197403949&zoom=9) (on arrive sur la Bretagne Nord (dans le 29 et 22) avec une légende qui ne pointe pas de

![Capture d’écran 2023-10-24 à 13 03 04](https://github.com/MTES-MCT/Docurba/assets/2676385/44ea9312-1f31-4f59-bcaa-815035f67d33)

**Comment by nyko28** [comment]
Pour le problème de localisation lorsqu'on clique sur des couches régionales ou nationales, je peux forcer la carte à s'afficher directement sur la commune souhaitée.

Cependant, la carte est toujours la même car le GPU affiche par défaut toutes les couches disponibles, malgré l'identifiant du document passé en paramètre de l'URL. Le comportement est similaire aux liens présents sur le site du GPU. De mon côté je n'ai aucun moyen d'afficher uniquement la bonne couche.

S'ils ne sont pas prêts à corriger ça, on devra se tourner vers l'implémentation de notre propre carte.
