### ISSUE TITLE
[Liste des communes concernées par une procédure ] Le lien de redirection vers chaque commune de la liste est cassé

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#168]
[Liste des communes concernées par une procédure ] Le lien de redirection vers chaque commune de la liste est cassé

**Exemple avec département 17 > Thénac**  : lorsqu'on clique sur la 1ère procédure et la liste des 36 communes concernées, aucun lien ne marche dans cette liste, si on veut par exemple cliquer sur Luchat, on a page introuvable.

https://docurba.beta.gouv.fr/?isEpci=false

<img width="1223" alt="Capture d’écran 2023-10-26 à 15 08 49" src="https://github.com/MTES-MCT/Docurba/assets/144041896/f0b7dfce-eb7c-4884-ac70-ad6a0a338b1b">

**Comment by CeliaVermicelli** [comment]
FYI doublon avec cette issue : https://github.com/MTES-MCT/Docurba/issues/165

**Comment by Octaviedebs** [comment]
ah bien vu, désolée ! j'aurais dû faire attention
