### ISSUE TITLE
[MAJ astuces github]  Astuces outil des PAC 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#170]
Hello @UngererFabien, si possible de pusher à la prochaine MEP les modifications faites sur les astuces dans github : https://github.com/MTES-MCT/Docurba/tree/dev/content/PAC_Advices

Merci !

**Comment by UngererFabien** [comment]
J'ai changer la version pour être sur que tout le monde vois la nouvelle version.
