### ISSUE TITLE
[Export PDF du PAC] REX

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#172]
@UngererFabien Je mets par ici les retours obtenus, qui rejoignent probablement ta conversation avec Laurence : 

- il faut cocher chacune des sections ET sous-sections afin de les retrouver dans le fichier PDF (-> avant en cochant la section mère, ses sous-sections étaient automatiquement inclues et ça paraissait pertinent et visuellement compréhensible, ce n'est plus le cas, 
- la fonction de coche/decoche des sections n'a plus autant d'intérêt maintenant que le partage par email et la consultation en ligne par la collectivité n'est plus possible -> quand une DDT veut le fichier PDF du PAC, elle veut tout le PAC par défaut, 
- il semblent y avoir des bug de téléchargement des pdf des "anciens PAC" (créés avant juillet), exemple
-> [ce PAC du 22](https://docurba.beta.gouv.fr/trames/projet-47e7dad0-9f7b-4cfb-b92d-50b64348cfc9) - ça rejoint mon dernier commentaire de cette issue : https://github.com/MTES-MCT/Docurba/issues/61
- les liens des titres dans le sommaire ne sont pas "cliquables", 
- Perte de la mise en page sur le PDF : 
-> les éléments en gras et en italique sur le PAC en ligne, ne le sont pas dans le fichier PDF,
-> les sauts de ligne ne sont pas respectés,
-> bug dans la hiérarchisation des titres ? (cf PJ avec exemple sur la section de le hiérarchie des normes. [Voici le lien de mon PAC](https://docurba.beta.gouv.fr/trames/projet-223531e8-aa71-4242-8500-80e02c72a689))
- La taille de police est trop grande, 
- idéalement le nom du fichier téléchargé devrait être le nom du PAC choisi par l'user (pour les aider à le retrouver dans leurs téléchargements)

**Bug taille des titres** : Le titre de la section "Principe de la hiérarchie des normes" est aussi gros que le "a) Document dans l'évolution est engagé, etc." alors que c'est le corps du texte. 

![Capture d’écran 2023-10-27 à 18 15 59](https://github.com/MTES-MCT/Docurba/assets/111045572/aa6c0694-bd92-4386-bea1-f5f1343be798)

![Capture d’écran 2023-10-27 à 18 16 05](https://github.com/MTES-MCT/Docurba/assets/111045572/0e1fcc90-b62c-4d80-ab17-d9b2a09e112d)

FYI @HermanceGauth

**Comment by HermanceGauth** [comment]
Le PAC commenté de la DDT38 (qui date d'il y a 1an et demi)
[MOD_PAC sec DREAL.odt.pdf](https://github.com/MTES-MCT/Docurba/files/13206027/MOD_PAC.sec.DREAL.odt.pdf)

**Comment by CeliaVermicelli** [comment]
Hello @UngererFabien, je veux bien une update du bug du téléchargement du PAC du 22, [celui là](https://docurba.beta.gouv.fr/trames/pr
![Capture d’écran 2023-11-11 à 14 52 20](https://github.com/MTES-MCT/Docurba/assets/111045572/a54f0878-1a10-46bd-8806-6ea731cd4e94)
ojet-47e7dad0-9f7b-4cfb-b92d-50b64348cfc9). J'en parlais dans l'issue #61 

Merci d'avance !

**Comment by nyko28** [comment]
Hello @CeliaVermicelli,
Pour le PAC du 22 qui bug à l'export PDF, c'est dû à une image hébergée sur sante.gouv.fr. Les CORS (politique de partage de ressource entre les sites) bloque le téléchargement de l'image pour l'inclure dans le PDF. J'ai édité le PAC pour remplacer l'image par la même image mais hébergée sur nos serveurs supabase directement. Elle devrait maintenant pouvoir l'exporter en PDF.

Pour le voir les dernières corrections sur ma version en local, je te mets l'export ici :
[PLU - Trédaniel - 2023_07_20.pdf](https://github.com/MTES-MCT/Docurba/files/13368756/PLU.-.Tredaniel.-.2023_07_20.pdf)

**Comment by CeliaVermicelli** [comment]
Génial @nyko28 !! Merci pour ces nouvelles, je la préviens et te tiens au courant si elle nous fait un retour. 

**Pour info, j'en ai profité pour retester les liens des titres du sommaire du .pdf qui devraient être cliquables** et c'est assez aléatoire ; certaines fois ils sont cliquables et d'autres fois non, je n'arrive pas à trouver la constante. :/
J'ai remarqué que les sections mères sont cliquables quand il n'y a pas de sous-sections cochées pour qu'elles apparaissent dans le PAC. Et ensuite, sur le même PAC, une fois des sous-sections cochées sur la version en lignes, ces sous-sections sont bien cliquables mais alors leurs sections parentes ne le sont plus.. ? -> pas très digestes comme explications, n'hésite pas à me dire tes besoins.

**Comment by CeliaVermicelli** [comment]
Et @nyko28 une question au sujet de ces images et politique de partage de ressource entre les sites qui bloque l'export .pdf -> à ce stade on est capable de savoir comment contourner ce problème "automatiquement" ? 

(ou bien avoir une alerte en interne quand un user clique plusieurs fois en peu de temps sur le bouton "PDF" pour lui venir en aide rapidement ?)

**Comment by nyko28** [comment]
Oui il y a plusieurs solutions, je vais voir avec Fabien pour qu'on soit ok sur ce qui convient le mieux et je te tiens au courant

**Comment by nyko28** [comment]
Update : le problème ne se posera pas pour les nouvelles images, car les utilisateurs ne peuvent pas insérer des images directement depuis une URL. Ils doivent la télécharger puis l'upload sur le PAC, ce qui n'entrainera pas de soucis.

L'image de sante.gouv.fr qui pose problème fait partie du PAC d'origine. Je vais faire un correctif pour que l'erreur ne se répète pas sur d'autres exports PDF.
