### ISSUE TITLE
QA ajout de data dans le PAC

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#185]
Hello @UngererFabien voici mes premiers retours :

### Tests sur [ce PAC existant](https://dev-dot-docurba.ew.r.appspot.com/trames/projet-f757a786-b664-40f9-900b-3222c4f1ed7c) (PAC PLU)

* manque de tooltip "ajouter une donnée" sur l'icône du traitement de texte
![Capture d’écran 2023-11-07 à 10 28 16](https://github.com/MTES-MCT/Docurba/assets/111045572/6d614378-5731-4f5c-a3fa-8a2da0395347)
* manque de tooltip/CTA "ajouter cette donnée dans la section du PAC" sur le "+" de la fenêtre 
![Capture d’écran 2023-11-07 à 10 30 22](https://github.com/MTES-MCT/Docurba/assets/111045572/ae0c83e1-3841-4ec8-8edf-82b0491e7947)
* j'ai téléchargé le PDF et pas de mention de jeux de donnée 

### Test sur [ce PAC existant](https://dev-dot-docurba.ew.r.appspot.com/trames/projet-a3414621-8425-45b6-8586-13d5049aec17) (PAC PLUi)
* ❌ Je n'ai pas l'icône d'ajout de data sur ce PAC (dans aucune des sections - doc supra comme pp du territoire, dans une nouvelle section comme une section existante)
![Capture d’écran 2023-11-07 à 10 32 34](https://github.com/MTES-MCT/Docurba/assets/111045572/66e4219f-88dc-4d77-8057-ded4eda50eab)

### Test sur [ce PAC créé pour ces tests](https://dev-dot-docurba.ew.r.appspot.com/trames/projet-70c10b72-26fb-43fc-b6a9-58eb8a146105) 
*  à ce niveau d'ajout de data INPN on se demande ce qui va être ajouté au PAC : les znieff? natura 2000? tout? (note pour moi même : voir si les DDT sont satisfaites avec un lien vers le site de référence à ce stade)
![Capture d’écran 2023-11-07 à 10 40 51](https://github.com/MTES-MCT/Docurba/assets/111045572/0e5515eb-ef41-49ad-9911-9d02b67f701f)
* * j'ai téléchargé le PDF du PAC: [file (2).pdf](https://github.com/MTES-MCT/Docurba/files/13278355/file.2.pdf) et il ne comporte pas de mention des jeux de données joints -> est-ce que mettre le lien de "voir la ressource" comme dans la version en ligne serait déjà un bon début ? - cf capture d'écran : 
![Capture d’écran 2023-11-07 à 10 47 43](https://github.com/MTES-MCT/Docurba/assets/111045572/b962be04-c571-483d-9029-ffae85c35128)
* onglet base territoriale (je suis connectée à la DDT 08 donc pas de données régionales ) : si pas de données il faudrait un disclaimer "_pas de données référencées sur Docurba pour le moment_" au lieu du cercle de chargement
![Capture d’écran 2023-11-07 à 10 56 18](https://github.com/MTES-MCT/Docurba/assets/111045572/a980c3c5-a033-4b9e-8475-0c032e9338f0)

### Tests [sur ce PAC créé pour les tests](https://dev-dot-docurba.ew.r.appspot.com/trames/projet-cd212f72-982f-4055-a86b-b225b6c50beb) - trame de l'Ain 

* ajout de date de la base territoriale : on retrouve bien les jeux de données dans la section du PAC en ligne mais pas sur le pdf du pac : [file (3).pdf](https://github.com/MTES-MCT/Docurba/files/13278533/file.3.pdf)
![Capture d’écran 2023-11-07 à 11 06 36](https://github.com/MTES-MCT/Docurba/assets/111045572/bd938105-297a-44d3-9d0b-747a0f65cac0)

### Remarque générale : 

* Si c'est nécessaire de décomposer l'ajout d'image/annexes/data je pense qu'il faut un tooltip à chaque icône 
![Capture d’écran 2023-11-07 à 10 48 09](https://github.com/MTES-MCT/Docurba/assets/111045572/15398910-ed85-4fc7-bc98-64b1e6ec0f55)

FYI @HermanceGauth

**Comment by CeliaVermicelli** [comment]
Hello @nyko28 

Voici mes nouveaux retours :) 

- Sur [ce PAC (PLU)](https://dev-dot-docurba.ew.r.appspot.com/trames/projet-fae50f07-4b17-4c05-b94a-c588d717700e) je ne vois plus l'icône d'ajout de données (elle est bien présente coté PAC PLUi - donc à l'inverse de ma premie`re phase de tests eheh)
![Capture d’écran 2023-11-14 à 19 37 16](https://github.com/MTES-MCT/Docurba/assets/111045572/95f4962f-bba3-4df9-9142-5f1f20bd3a47)
- Petite faute d'orthographe dans le tooltip : selon moi on dit toujours qu'il y a "plusieurs données dans un jeu" donc "jeu de donnée**s**", tu confirmes @HermanceGauth 
![Capture d’écran 2023-11-14 à 19 33 02](https://github.com/MTES-MCT/Docurba/assets/111045572/60543f14-e08b-4f12-a011-4aa4e116d2d3)
- je n'ai pas de référence aux jeux de données ajoutés dans les .pdf des PAC, mais tu n'as peut-être pas eu le temps de terminer ça aujourd'hui. (test effectué sur [ce PAC PLUi](https://dev-dot-docurba.ew.r.appspot.com/trames/projet-6cab1025-74c5-4df9-9a33-ab7e91cfddde) créé pour le test

Et je crois que c'est tout pour moi !

**Comment by HermanceGauth** [comment]
Oui effectivement je confirme qu'on met un S à données.
Sur le pdf j'ai l'impression que du coup Nico va travailler dessus en même temps que cette issuer https://github.com/MTES-MCT/Docurba/issues/172
Je pourrai faire d'autres test jeudi ou vendredi si besoin.

**Comment by nyko28** [comment]
Hello,

Merci pour vos retours !
En effet, les liens de jeux de données dans le PDF seront intégrés avec la PR de l'issue 172.

@CeliaVermicelli pour l'icône d'ajout de données non présente, je viens de faire un correctif.
J'en ai aussi profité pour ajouter le "s" manquant :)

**Comment by HermanceGauth** [comment]
Hello, je n'ai pas pu refaire de test ce matin car sur la version dev avec l'ajout de procédure on n'a plus accès aux PAC communaux ou intercommunaux.
