### ISSUE TITLE
[Retour UX - partage du PAC depuis la FRP]

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#189]
Ping @UngererFabien @HermanceGauth @julienzdocurba 

Retour UX qui me parait intéressant à vous partager, de la part de Cécilia Bellay (DDT22 - une des personnes qui a le plus manipulé l'outil des PAC) : 

> Ma collègue ne peut plus accéder au PAC que je lui demandais de relire.
> Dans la nouvelle version de DOCURBA, j'ai compris qu'il fallait cocher sur la case du service qui peut accéder au PAC: j'ai coché "DDT", et mis "Publique". Toujours pas d'accès.
> Pouvez-vous m'éclairer ?

en lien 
-> avec le parcours utilisateur de la FRP pour Julien Z - nos conversations sur l'intuitivité du choix des "parties prenantes" et la privacité de l'event,
-> et l'[issue 164](https://github.com/MTES-MCT/Docurba/issues/164) sur le fichier joint d'un event impossible à ouvrir (sa collègue ne peut donc pas consulter le PDF du PAC directement depuis la FRP et donc sans avoir à partager le fichier .pdf par email)
-> et l'[issue 61 - closed](https://github.com/MTES-MCT/Docurba/issues/61) sur comment partager le PAC entre collègues et/ou par email - consultation du PAC en ligne et [la check list de Fabien](https://github.com/MTES-MCT/Docurba/issues/61#issuecomment-1733662613) (cf capture d'écran -> )
![Capture d’écran 2023-11-08 à 08 03 42](https://github.com/MTES-MCT/Docurba/assets/111045572/53b06bc9-8b59-4372-9992-014758e91513)

**Comment by julienzdocurba** [comment]
Pour info on a supprimé l'option "Parties prenantes" sur le nouveau design:
![image](https://github.com/MTES-MCT/Docurba/assets/147177148/75ee8f56-9b75-4543-bfbc-134ee3f039f6)

Mais dans tous les cas il semble que sa configuration était correcte nan? (DDT + Publique)

**Comment by CeliaVermicelli** [comment]
Yes, normalement sa collègue aurait du voir l'event du PAC sur cette FRP - et d'ailleurs en choisissant "publique" elle permettait la lecture du PAC (pas validé) à toute personne qui consulte la FRP en mode non connecté -> ça confirme le manque de compréhension de ce paramétrage de visibilité de l'event (et top que "parties prenantes" disparaissent dans le nouveau parcours). Ici de toute façon : 
- elle n'a pas pu joindre son fichier à l'event car il y a un bug : elle n'arrive pas à export ce PAC en pdf - issue #61 
- même si elle avait pu joindre le pdf du PAC dans l'event, sa collègue n'aurait pas pu le consulter - issue #164

**Comment by julienzdocurba** [comment]
> d'ailleurs en choisissant "publique" elle permettait la lecture du PAC (pas validé) à toute personne qui consulte la FRP en mode non connecté -> ça confirme le manque de compréhension de ce paramétrage de visibilité de l'event

On est certains de ça? Parce qu'il est possible qu'elle ait choisi "publique" pour être sûre que sa collègue pourrait accéder au PAC. On a déjà vu des gens ne pas comprendre l'option de visibilité privée / publique? Parce que si c'est un problème ça restera un problème sur le nouveau design.

PS: Je viens de me rendre compte que j'avais collé la mauvaise image dans mon commentaire précédent. C'est le nouvel ajout d'événement:
![image](https://github.com/MTES-MCT/Docurba/assets/147177148/d0441540-8d0b-45e1-86fb-4605e752db9f)

**Comment by CeliaVermicelli** [comment]
> On est certains de ça? Parce qu'il est possible qu'elle ait choisi "publique" pour être sûre que sa collègue pourrait accéder au PAC. On a déjà vu des gens ne pas comprendre l'option de visibilité privée / publique? 

Je pense qu'avec les difficultés actuelles (#164, bug sur son téléchargement du PAC + option de partager plus possible et #118 ) elle a effectivement dû essayer d'autres options. Je pourrai revérifier avec elle quand on aura avancé de notre côté.

**Comment by HermanceGauth** [comment]
J'ajoute un commentaire suite à ma session de formation ce matin, les DDT que j'ai vu s'attendaient à ce que leur PAC soit directement accessible à tout leur collègue sans avoir besoin de le partager via le raccourci dans l'encadré de la procédure, cf cette issue : https://github.com/MTES-MCT/Docurba/issues/94

**Comment by julienzdocurba** [comment]
C'est quoi le raccourci dans l'encadré de la procédure? Et sinon oui il semble logique qu'un PAC soit accessible à toutes les DDT non? La plupart du temps ils sont même accessibles au public non?

**Comment by HermanceGauth** [comment]
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/b326e587-e248-46f5-afd8-febc6ae30d68)
En surligné. Aujourd'hui ils ne sont pas accessibles au public alors que c'est une pièce de l'enquête publique donc oui on soit ils pourraient être accessibles à tout le monde (sauf quelques données qui ne sont pas publiques pour des raisons de sécurité). Dans notre version de Docurba actuellement, seule la personne qui a crée le PAC peut y accéder mais ce n'est pas ce qui est souhaité pour la suite.

**Comment by CeliaVermicelli** [comment]
Précision du retour de Cécilia Bellay (22) et son incompréhension du lien entre la FRP et l'outil des PAC : 
Depuis la FRP de la procédure de la collectivité concernée, elle pensait créer un nouveau PAC en ajoutant un event dans la FRP et la sélection de l'intitulé "Étude du Porter à connaissance" ou "Porter à Connaissance complémentaire". cf capture d'ecran : 
![Capture d’écran 2023-11-14 à 19 19 12](https://github.com/MTES-MCT/Docurba/assets/111045572/e4c8e360-17c6-4112-a131-2b9fcbdf13ed)

**Depuis cet event, elle pensait retrouver la possibilité de modifier son PAC et le partager (visibilité publique).** Je ne dis pas qu'il faut forcément faire le lien entre PAC et FRP de cette manière mais c'est intéressant de voir ce qui leur parait "logique" une fois sur l'outil.

**Comment by UngererFabien** [comment]
@CeliaVermicelli @julienzdocurba Je vous laisse close cette issue si toutes les remarques ont été prise en compte. Quite à en rouvrir une qui reprend les même besoins sur le design qu'a intégré @lerayj.
