### ISSUE TITLE
[PAC-DDT connectée] impossible de modifier les titres 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#198]
### Retour de Frédéric Tahier (35) lié à [cette issue](https://github.com/MTES-MCT/Docurba/issues/177) 

> Je souhaite modifier ce titre de section en "Politiques-publiques-spécifiques-à-votre-territoire" pour plus de clarté mais l'application mouline sans prendre en compte ma demande (j'ai bien mis des tirets pour éviter les bugs) 

cf video avec console : 

https://github.com/MTES-MCT/Docurba/assets/111045572/15c7d9d8-f4e3-40f2-ac5c-3058cef0de5b

### Est-ce que ce serait utile de penser à une solution intermédiaires (si quick win car pas prio?) : 
- remplacer "PP du territoire" par "Politiques publiques s'appliquant sur le territoire"
- Visuellement faire comprendre que les titres ne sont pas modifiables, il ne devrait pas y avoir la barre grise d'édition du titre lorsque l'on click sur le crayon d'édition de la section, cf PJ : 
![Capture d’écran 2023-11-11 à 14 31 07](https://github.com/MTES-MCT/Docurba/assets/111045572/68b27d09-3322-405e-8867-1b64d58ab91e)

FYI @HermanceGauth

**Comment by CeliaVermicelli** [comment]
**Confirmation de Frédéric :** 

> Pour ma part la structure globale me va bien, donc OK pour figer certains titres sections :
> c'est juste l'utilisation d'acronymes/ d'abréviations ou autre qui sont à proscrire il me semble.

**Comment by UngererFabien** [comment]
@CeliaVermicelli Normalement cette régréssion est corrigé depuis 1 semaine. Je n'ai pas eu de problème sur la trame test. N'hésite pas à réouvrir l'issue et tag @nyko28 si jamais tu as de nouveau ce retour.

@nyko28 si l'issue est re ouverte. Le problème venait des titres de sous sections hors cadre juridique donc assez spécifique.
