### ISSUE TITLE
[Historique proc.] Retour sur les com. déléguées

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#199]
### Mme Noel Evain (DDT 76 - Normandie) :

> Lorsque l'on cherche les documents approuvés et en cours sur un EPCI, le traitement des documents des communes déléguées est illisible et incorrect.
> Par exemple pour la communauté de communes Caux Seine Agglo, il est indiqué:
> - un PLU Terres-de-Caux statut opposable approuvé le 26/06/2018
> - des PLU Terres-de-Caux statut précédent approuvés les 26/06/2018, 10/04/018 (3 fois)  et 27/06/2017
> - des CC Terres-de-Caux statut précédent approuvées les 21/06/2013, 27/09/2011, 11/12/20009 et  11/02/2004
> En fait il s'agit des PLU des communes délégués de Terres-de-Caux:
> - Sainte-Marguerite-sur-Fauville et Saint-Pierre-Lavis approuvés le 26/06/2018
>  - Bermonville, Auzouville-Auberbosc, et Bennetot approuvés le 10/04/2018
> - Fauville-en-Caux approuvé le 27/06/2018
> et des CC de
> - Bermonville approuvée le 21/06/2013
> - Ricarville approuvée le 27/09/2011
> - Bennetot approuvée le 11/12/2009
> - Bermonville approuvée le  11/02/2004
> 
> Sur ces procédures, tous les PLU sont opposables ainsi que la CC de Ricarville contrairement à ce qui est indiqué et seules les CC appouvées le 21/06/2013,
> 11/12/2009 et 11/02/2004 ont réellement un statut Précédent.
> Comme il est impossible de savoir à quelle commune déléguées chaque procédure est rattachée, est-ce qu'il serait possible, en plus de corriger les anomalies de statut,
>  d'ajouter entre parenthèse après Terres-de-Caux la commune déléguée concernée ?

### Semble rejoindre l'issue #137 et les retours du Calvados sur les communes délégués : 

- **Exemple avec l'EPCI de Caen la Mer** : "il y 47 communes : ce sont uniquement les communes principales et pas les communes déléguées. En plus, Saline apparaît dans la liste alors que ça ne devraient pas -> la fusion a été abbrogée)
- Il faut selon eux bien séparer les deux : communes déléguées et communes.
- Ils ont besoin de pouvoir assigner des DU en propre à des communes déléguées sinon les données son faussées et ne peuvent pas faire le suivi correctement, c'est pour Sudocuh était devenus obsolète pour eux et qu'ils se basaient d'avantage sur le tableur interne.

**Comment by UngererFabien** [comment]
Est ce qu'ils ont donné une source ou une définition pour les communes déléguées ? Ce n'est pas une notion que je vais chercher si dans les données de l'INSEE on a cette information.

**Comment by CeliaVermicelli** [comment]
oui, cette définition parait cohérente par rapport aux retours. 

Du coup, quelle est notre position par rapport à ces différences d'historique Sudocuh - Docurba - réalité des DDT ? 
Est-ce que l'on souhaite mettre ce retour de côté et attendre les nouveaux DU des nouvelles communes/EPCI ayant la compétences car cela "écrasera" ce pb ? 
Je revois toutes les DDT de Normandie + la DREAL le 30.11 en présentiel donc ça m'aiderait d'avoir votre avis là dessus et/ou savoir ce que l'on souhaite faire à ce sujet. 

@HermanceGauth

**Comment by HermanceGauth** [comment]
On pourrait effectivement dire que ce n'est que de l'historique, malheureusement certain DU avec des procédures secondaires vivent encore sur ces communes. Effectivement ça rejoins la question du Calvados. Je pense qu'il faudrait qu'on arrive à avoir quelque chose de propre sur ce sujet. J'ai compris que c'était possible grâce au fichier mouvement de l'INSEE mais que le fichier est difficile à interpréter donc ça prend du temps, est-ce que tu me confirmes @UngererFabien ?

**Comment by CeliaVermicelli** [comment]
(note personnelle : retour similaire de l'Orne 61 (Séverine Lesenechal)
_"quid affichage des DU pour les communes fusionnées"._

**Comment by CeliaVermicelli** [comment]
FYI, le Calvados a 218 communes déléguées - "_même si toutes ne posent pas problème_" -> elle vérifie celles concernées par l'enquête annuelle.

**Comment by CeliaVermicelli** [comment]
Retour similaire de la part de Sandrine Belleoeil (63): 

> pas de visibilité sur les PLU infra-communautaires

**Comment by HermanceGauth** [comment]
J'ai l'impression que c'est résolu ? https://docurba.beta.gouv.fr/ddt/76/collectivites/200010700/epci

**Comment by CeliaVermicelli** [comment]
yes effectivement, je préviens la DDT concernée et close l'issue. 
Si jamais sont retour dit le contraire je créerai une nouvelle issue
