### ISSUE TITLE
[DDT connectée - TdB & Page EPCI/commune] : retours UX et visibilité sur les procédures.

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#200]
@julienzdocurba 

Je te partage quelques retours de DDT sur le visuel suivant : 

> Un affichage plus compact serait aussi apprécié, actuellement il est possible de visualiser 2 ou 3 procédures par page, lorsqu'un EPCI possède beaucoup de documents
> ce n'est pas très pratique. (Noel Evain Marie du 76)

> Et, à titre personnel, je suis gêné par l'aspect graphique de la feuille de route avec les grands encadrés pour chacune des procédures. Ça ne permet pas d'avoir rapidement une vue synthétique sur les procédures. (Cf capture qui ne fait apparaître que 3 procédures, la procédure principale et deux secondaires). (Bastien Ruamps - ddt 56)
CF PJ pour la commune d'Allaire (56) : liste des procédures visibles sans "jouer de la molette" - comparaison avec tout ce qui peut se voir sur Sudocuh. 

**Ses suggestions :** 
- Réduire la taille des encadrés de façon à afficher plus de procédures sans avoir à jouer de la molette
- Modifier la couleur des procédure pour distinguer celle qui sont terminées (document exécutoire), celles annulées, celles en cours
![Capture d’écran 2023-11-11 à 15 26 33](https://github.com/MTES-MCT/Docurba/assets/111045572/eb69d5a8-f6e6-4323-ad93-807cf4961916)
![Capture d’écran 2023-11-11 à 15 26 42](https://github.com/MTES-MCT/Docurba/assets/111045572/f45e3ac9-991d-4a2c-941e-b26ca172eaa4)

**Comment by lerayj** [comment]
A pointé niveau Hermance / Julien avant issue - en attendant j'ai augmenté la limite a 50 lignes
