### ISSUE TITLE
QA création de procédure

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#205]
### Bug pour consulter les EPCI :  
Côté Commune ça fonctionne donc je continue les tests.

https://github.com/MTES-MCT/Docurba/assets/111045572/7de3b5da-efcc-4d19-ac87-cc034ede7192

**Comment by CeliaVermicelli** [comment]
### Test création de proc principale sur une commune : 
Il faut actualiser la page pour voir la procédure effectivement créée dans l'historique de la commune.

**Comment by CeliaVermicelli** [comment]
### Une procédure créée s'enregistre sur la page d'autres communes : 

### Test 1 : 
j'ai créé une nouvelle proc. princ. pour Aubrives (je ne l'ai pas enregistré en video) et je retrouve cette new proc. dans l'historique de la commune de Anchamps (alors que j'avais bien seulement laissé coché Aubrives). 


https://github.com/MTES-MCT/Docurba/assets/111045572/d2b24c75-7e65-4696-ab69-892ac3baabd7

### Test 2 : 
j'ai enregistré une nouvelle création de proc. pour te montrer : je suis positionnée sur la page de la commune "La Chapelle", voici mes remarques : 
- je retrouve également ma toute première proc crée pour Aubrives -> proc. créée sur Aubrives qui se retrouve sur plusieurs autres page communes.
- je dois actualiser la page pour voir effectivement ma proc. créée sur La chapelle. 
- la création d'une 2eme nouvelle proc. (La Chapelle) a écrasé la 1ere proc. créé (Aubrives) -> sur l'historique de Anchamps où je voyais ma proc. pour Aubrives, je ne retrouve plus que la toute récente proc. "La chapelle". 


https://github.com/MTES-MCT/Docurba/assets/111045572/20b86d49-f255-45ae-808f-404848b29a65

**Comment by CeliaVermicelli** [comment]
### Création de proc. secondaire possible alors que pas de proc. principale de premier abord ? 

Peut-être que je n'ai pas tout compris des liens possibles entre différentes proc., mais j'ai quand même l'impression que ce comportement n'est pas "normal" :


https://github.com/MTES-MCT/Docurba/assets/111045572/526f5145-577b-465e-9907-c0f90cc87395

**Comment by HermanceGauth** [comment]
**Formulaire de création - procédure principale**

1.  Cette procédure concerne : il faut soit :

- permettre d'écrire du texte libre lorsqu'on sélectionne autre
- soit mettre un champ supplémentaire de texte libre pour décrire la procédure 

2. Type de DU : il existe aussi des PLUiHM
3. Moins important : dans le cas d'une révision, il faudrait aussi pouvoir mettre le numéro de procédure révision n°1, n°2, il n'y a que l'élaboration pour laquelle ça n'a pas de sens car forcément n°1

**Comment by HermanceGauth** [comment]
**Formulaire de création - procédure secondaire** CCLA (73)
Au début j'ai bien le message qui s'affiche comme quoi il n'y a pas de procédure principale mais juste après le formulaire apparaît et je peux sélectionner la procédure en cours ce qui ne devrait pas être possible.
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/bc36a695-1704-4eb9-8c77-046483536c97)

**Comment by HermanceGauth** [comment]
**Remarques structurantes sur le fonctionnement**
1. Il faut recharger la page pour afficher l'historique ou les nouvelles procédures créées.
2. J'ai les mêmes problèmes d'écrasement et de réplication d'une procédure créé sur toutes les collectivités du département. 
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/8fdf90c2-35d0-4235-b183-8ebc558bc550)
3. Il faut que le renvoie vers la FRP permette la création d'évènement, sinon ça sert à rien de pouvoir créer une procédure.
4. Il faut que le lien vers le PAC renvoie vers la possibilité de créé un PAC sinon on perd cette fonctionnalité (impossible).
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/7c28e422-1845-4b23-93cd-b419de3ea5fc)

**Remarques moins structurantes**
1. Griser les liens dgd et infos générale qui ne renvoient à rien (d'ailleurs pour les infos générales c'est pareil pour les proc historique le rendu est pas top donc le grisé serait mieux)

**Comment by Octaviedebs** [comment]
J'ai exactement les mêmes remarques que ci-dessus donc je vous évite des doublons mais j'ajoute **une autre remarque structurante** :

1. j'ai créé une procédure pour la commune Abergement clemenciat **côté DDT**
2. Puis j'ai créé un **compte CT pour cette commune** là, pour voir comment ma nouvelle procédure apparaissait 
3. La nouvelle procédure n'apparait pas et il n'y a que les procédures secondaires, l'écran général a changé cf vidéo
4. En accès public c'est pareil cf screen
5. Quand je retourne en accès DDT sur cette commune, je dois encore à nouveau recharger la page pour que la nouvelle procédure apparaisse bien (précision = en accès CT + accès public le fait de recharger la page ne change rien)

<img width="1429" alt="Capture d’écran 2023-11-17 à 11 58 52" src="https://github.com/MTES-MCT/Docurba/assets/144041896/1961e3ef-2d5d-445e-93f8-ff70bfa63cc2">

https://github.com/MTES-MCT/Docurba/assets/144041896/f0d472ba-b0d4-48cc-823a-1791ee9508ab
<img width="1429" alt="Capture d’écran 2023-11-17 à 11 57 30" src="https://github.com/MTES-MCT/Docurba/assets/144041896/744cff42-a391-4c2e-afc9-d0fe332ea70e">





Pas de notif créationd e compte

**Comment by lerayj** [comment]
@HermanceGauth  @CeliaVermicelli  @Octaviedebs J'ai corrigé le bug majeur qui était cause de pas mal de retours (ce n'était pas écrasé, mais il y a ait un problème de routage au moment de la navigation). Si vous refaite une passe les bugs manquants seront plus clair et ca donnera moins l'impression d'un hasard complet.

**Comment by lerayj** [comment]
J'ai rajouté une fonction de delete procédure principale des epci uniquement pour le moment, je rajoute le reste ce week end.
Il me reste certains de tes points Hermances - il faut nottament que je décide quel events je creer par defaut, ou meme si j'en créer un quand c'est une ddt qui le fait

**Comment by CeliaVermicelli** [comment]
### Pas de "delete procédure principale" 

> J'ai rajouté une fonction de delete procédure principale des epci uniquement pour le moment, je rajoute le reste ce week end.

Je ne la vois pas (j'ai cru l'apercevoir ce matin pourtant! et je suis bien sur une EPCI) cf video


https://github.com/MTES-MCT/Docurba/assets/111045572/de576733-4d0b-4c09-aa8d-a8c66ca70078

**Comment by CeliaVermicelli** [comment]
### Le nb de communes concernées diffère au moment de la création de la procédure et une fois dans l'historique 

Test ici sur une EPCI : crea d'une proc. principale avec 39 communes sélectionnées. Une fois créée et dans l'historique, il n'y a plus que 37 communes) 
cf video. 

https://github.com/MTES-MCT/Docurba/assets/111045572/eb8e8a09-c801-4896-9ab8-74567308df06

###  il manque les communes  de BAY (08051) et Foulzy (08177) - pas rangées dans l'ordre alphabétique d'ailleurs : 

**Encadré de crea de proc. -> 39 communes sélectionnées**
![Capture d’écran 2023-11-20 à 19 23 10](https://github.com/MTES-MCT/Docurba/assets/111045572/5c0e13a8-c444-4df4-9f6e-44c0491c2619)

**Encadré "liste des communes concernées"  - 37 communes - en manque 2.**

![Capture d’écran 2023-11-20 à 19 23 16](https://github.com/MTES-MCT/Docurba/assets/111045572/d318d1d9-9bd8-4501-b73d-c9cf21d86c03)

**Comment by CeliaVermicelli** [comment]
### Creation de proc secondaire possible même sans proc. principale

Pas sûre de comprendre l'interconnexion des proc. : l'historique est vide mais au moment de la crea de la proc. seocndaire on me propose bien de la rattacher à une proc. principale de PLU de la CA Ardennes Metropole (qui correspond bien à la 200041630) -> c'est normal de ne pas la voir dans l'historique de base mais qu'elle soit quand même proposée ?

https://github.com/MTES-MCT/Docurba/assets/111045572/c1b1e9ad-019d-44e7-bdfc-52e5913f2f3e


### (pas urgent) Ce serait possible de se défaire du rapide passage du message "pas de procédure principale" au moment du passage à l'onglet de la création de la procédure secondaire _qui finalement abouti._ 

Je suis bien d'accord d'avoir ce message quand il doit effectivement avoir lieu. 

https://github.com/MTES-MCT/Docurba/assets/111045572/264133c0-cb2d-4568-a718-c161273ffd41

**Comment by CeliaVermicelli** [comment]
### Rajouter un accent à "Sélectionner" 

Dans l'encadré d'ajout de procédure principale et secondaire

![Capture d’écran 2023-11-20 à 19 44 14](https://github.com/MTES-MCT/Docurba/assets/111045572/43d3be0d-8f19-4606-8be8-5e86a9068c76)

**Comment by CeliaVermicelli** [comment]
### Communes proposées en double dans la liste à cocher

+ certaines communes ne sont pas rangées dans l'ordre alphabétiques

https://github.com/MTES-MCT/Docurba/assets/111045572/b3ccaf29-bf46-46c8-8e8e-bfff58f0511b

**Comment by CeliaVermicelli** [comment]
### Remarque par urgente :

Je me demande si une barre de recherche pour identifier plus rapidement les communes à cocher leur serait utile ? (à faire tester avec les DDT - est-ce qu'elles ont en tête les communes concernées par les procédures et seraient plus rapide à écrire les premières lettres de la commune pour ensuite les cocher - à voir si quick win)

**Barre de recherche de ce type :** 
![Capture d’écran 2023-11-20 à 19 51 57](https://github.com/MTES-MCT/Docurba/assets/111045572/4d7dfe3b-571e-45a7-a617-f3104c0811f4)

**Comment by CeliaVermicelli** [comment]
### Recherche de la procédure parente 

et pour faire suite au commentaire d' @HermanceGauth : 

> Dans le cas de l'ajout sur un PLUi, impossible de retrouver la procédure principale sur laquelle je veux mettre la procédure secondaire

-> je retrouve bien la procédure parente sur laquelle je veux ajouter une proc. secondaire (testé sur PLUi et PLU) mais cela devient fastidieux quand la liste est longue.


https://github.com/MTES-MCT/Docurba/assets/111045572/f6a1555e-0f78-4f5b-843d-ce71ef22f194

**Comment by HermanceGauth** [comment]
J'ai les mêmes retours que Célia sur le périmètre qui varie entre la création de la procédure et l'affichage et je ne vois pas non plus le bouton pour supprimer la procédure.

En complément le lien entre les procédures : Effectivement, lors de la création de procédure secondaire on devrait proposer comme procédure parente uniquement les DU opposables et il faudrait que le numéro de la collectivité porteuse soit remplacée par son nom pour qu'on puisse s'y retrouver. On nous demandera effectivement sûrement de pouvoir rechercher mais si c'est ranger par ordre alphabétique avec uniquement les procédures opposables et les noms des collectivités c'est déjà plus facile. Peut-être de l'autocomplétion comme les events (les DDT adorent ce fonctionnement). On avait prévu que la création de procédure secondaire puisse aussi se faire directement depuis la FRP de la procédure principale, à mon avis ça sera plus simple mais à voir (je ne sais pas si on pourra traquer par où ils préfèrent le faire).

**Comment by HermanceGauth** [comment]
**Mauvais affichage**
Lors de l'affichage (par ordre de prio) :
1. il manque le numéro de la procédure qui est toujours "1" même quand je rentre autre chose dans le cas d'une révision
2. il y a un "-i" qui traine dans le cas d'un PLUiH qui devient PLUiH-i
3. si on coche des cases et qu'on écrit des compléments en ayant coché "autre" on ne voit dans les commentaires que ce qu'on a tapé et pas les autres choses que l'on a coché
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/bb09a271-f246-4dbf-b194-ebcfe8b047f1)

**Comment by HermanceGauth** [comment]
Plus qu'un bouton pour supprimer, un bouton pour modifier (incluant la possibilité de supprimer) serait le bienvenue, un peu comme pour les event.

**Comment by CeliaVermicelli** [comment]
### Emplacement du CTA création d'une nouvelle procédure

**Commentaire d'Hermance, que je rejoins:** 
> On avait prévu que la création de procédure secondaire puisse aussi se faire directement depuis la FRP de la procédure principale, à mon avis ça sera plus simple mais à voir (je ne sais pas si on pourra traquer par où ils préfèrent le faire).

FYI @julienzdocurba 

Je me demandais aussi si le CTA `créer une nouvelle procédure` depuis l'encadré de la procédure principale serait utile et plus direct pour la création des procédures secondaires qui s'y rattachent. J'imaginerai donc que suite au click sur "créer une nouvelle proc." on me propose directement/uniquement la création de nouvelle procédure secondaire rattachée par défaut à la proc. principale sur laquelle j'ai cliqué sur `créer une nouvelle procédure`

**Comment by HermanceGauth** [comment]
@lerayj @julienzdocurba désolé j'ai oublié un sujet c'est dans le cas de la création d'une procédure pour un PLUiS, pouvoir donner un nom au PLUiS pour les différencier entre eux. A la base c’était la case commentaire/description mais comme finalement on a orienté cette case vers l’objet de la procédure "cette procédure concerne" et bien maintenant on n'a plus d'endroit pour donner un nom aux PLUiS et c'est assez important pour que les DDT puisse s'y retrouver et c'était justement ce que sudocuh ne permettait pas vraiment

**Comment by lerayj** [comment]
> ### Creation de proc secondaire possible même sans proc. principale
> Pas sûre de comprendre l'interconnexion des proc. : l'historique est vide mais au moment de la crea de la proc. seocndaire on me propose bien de la rattacher à une proc. principale de PLU de la CA Ardennes Metropole (qui correspond bien à la 200041630) -> c'est normal de ne pas la voir dans l'historique de base mais qu'elle soit quand même proposée ?
> 
>  crea.proc.secondaire.et.historique.mov 
> ### (pas urgent) Ce serait possible de se défaire du rapide passage du message "pas de procédure principale" au moment du passage à l'onglet de la création de la procédure secondaire _qui finalement abouti._
> Je suis bien d'accord d'avoir ce message quand il doit effectivement avoir lieu.
> 
>  msg.erreur.mov

Il y a des procédures principales communales pour cette EPCI, du coup normal, pas de bug ici.

**Comment by julienzdocurba** [comment]
Hello et désolé d'arriver un peu tard, je ne bossais ni Vendredi ni Lundi et hier j'ai essayé de catch up sur toutes les questions bloquantes pour le dev. Du coup je vais faire ma QA aujourd'hui mais je peux essayer de répondre déjà à certains points:

> Cette procédure concerne : il faut soit :
permettre d'écrire du texte libre lorsqu'on sélectionne autre
soit mettre un champ supplémentaire de texte libre pour décrire la procédure

On avait repris exactement ce qu'on avait dans le dépôt d'acte et il me semble que "Autre" ne permettait pas de saisie de texte libre. Mais oui ça semble logique, je vais regarder le design dans la journée.

> Dans le cas d'une révision, il faudrait aussi pouvoir mettre le numéro de procédure révision n°1, n°2, il n'y a que l'élaboration pour laquelle ça n'a pas de sens car forcément n°1

Ok j'avais compris que ce n'était que sur les procédures secondaires (cf maquettes) mais du coup il va falloir faire des changements. Je vais regarder ca.

> Il faut que le renvoie vers la FRP permette la création d'évènement, sinon ça sert à rien de pouvoir créer une procédure.

Ca viendra avec le dev de la nouvelle FRP je pense. Il faudra juste qu'on se mette d'accords sur quels événements on veut pousser.

> Il faut que le lien vers le PAC renvoie vers la possibilité de créé un PAC et qu'on y retrouve les PAC déjà créé sur cette commune sinon on perd cette fonctionnalité.

Je ne comprends pas ce point, est-ce que tu pourrais l'expliquer @HermanceGauth  ?

> Il faut pouvoir supprimer une procédure en cas d'erreur

Ok il me semblait qu'on avait dit qu'on ne voulait pas de suppression de procédures mais j'ai peut être mal compris désolé. Je vais regarder ca.

> Griser les liens dgd et infos générale qui ne renvoient à rien ou bien renvoyer vers les écrans prévus pour la DGD (d'ailleurs pour les infos générales c'est pareil pour les proc historique le rendu est pas top donc le grisé serait mieux)

Est-ce que c'est un changement qu'on a introduit avec la création de procédure? Parce que si non, peut être qu'on pourrait revoir ça lorsque l'on bossera sur le design de ces éléments (je suis pas certain de comprendre à quoi servent ces liens).

> Je me demandais aussi si le CTA créer une nouvelle procédure depuis l'encadré de la procédure principale serait utile et plus direct pour la création des procédures secondaires qui s'y rattachent.

Oui c'est ce qui est prévu dans la nouvelle FRP.

> désolé j'ai oublié un sujet c'est dans le cas de la création d'une procédure pour un PLUiS, pouvoir donner un nom au PLUiS pour les différencier entre eux

Ok pas de problème je vais regarder ça.

**Comment by julienzdocurba** [comment]
Question complémentaire:
Si je choisie "Révision" sur une procédure principale, est-ce qu'il y a d'autres choses qui doivent changer? Par exemple est-ce que tous les objets de procédure sont toujours utiles etc? Il me semble qu'on en avait parlé mais je veux juste vérifier pour être vraiment sûr.

**Comment by julienzdocurba** [comment]
Et sur ce point: https://github.com/MTES-MCT/Docurba/issues/205#issuecomment-1820865898

Pourquoi exactement les PLUiS on besoin d'un nom mais pas les autres types de documents?

**Comment by julienzdocurba** [comment]
Et désolé j'enchaine les questions mais on n'a pas de "PLUiS" dans la liste des types de documents d'urbanisme. Est-ce qu'un PLUiS c'est quelque chose qui est juste déduis du périmètre d'un PLUi / PLUiH / PLUiM / PLUiHM ?

**Comment by HermanceGauth** [comment]
> Je ne comprends pas ce point, est-ce que tu pourrais l'expliquer @HermanceGauth ?

Dans ce qui est proposé il n'y a plus d'accès à toutes les fonctionnalités qui concerne les PAC, on avait prévu un accès en raccourci depuis l'encadré de la procédure au même titre que la frp, je crois que Fabien et Julien L voient le truc pour connecter ces deux entités (cf le surligné jaune sur ma copie d'écran).

>Est-ce que c'est un changement qu'on a introduit avec la création de procédure? Parce que si non, peut être qu'on pourrait revoir ça lorsque l'on bossera sur le design de ces éléments (je suis pas certain de comprendre à quoi servent ces liens).

Non c'est pas une nouveauté donc oui ça peut être revu plus tard. C'est juste que je me dis que ça peut embrouiller de garder des liens qui ne mènent à rien.

> Si je choisis "Révision" sur une procédure principale, est-ce qu'il y a d'autres choses qui doivent changer? Par exemple est-ce que tous les objets de procédure sont toujours utiles etc? Il me semble qu'on en avait parlé mais je veux juste vérifier pour être vraiment sûr.

Non il n'y a rien d'autre qui doit changer. Par rapport à l'élaboration juste mettre le numéro de la procédure.

> Pourquoi exactement les PLUiS on besoin d'un nom mais pas les autres types de documents?

En fait les documents où [périmètre du territoire] = [périmètre de la procédure] n'ont pas besoin de nom car le nom est automatiquement par exemple "Révision du PLU de la commune X" ou "élaboration du PLUi de l'EPCI X". En revanche pour les PLUi sectoriel on ne peut pas écrire "élaboration du PLUi sur l'EPCI X" parce que le PLUi ne couvre pas tout l'EPCI et donc il y a besoin de pouvoir le nommer pour le retrouver.

>Et désolé j'enchaine les questions mais on n'a pas de "PLUiS" dans la liste des types de documents d'urbanisme. Est-ce qu'un PLUiS c'est quelque chose qui est juste déduis du périmètre d'un PLUi / PLUiH / PLUiM / PLUiHM ?

Yes le PLUis c'est uniquement une question de périmètre alors que PLUiH,M,HM c'est une question de thématique traité dans le PLUi.

**Comment by CeliaVermicelli** [comment]
@lerayj je remets par ici l'issue https://github.com/MTES-MCT/Docurba/issues/124 _"Historique Sudocuh : faire apparaître le H, le D ou le HD en cas de PLUi-H, PLUi-D, PLUi-HD"_ en vue du prochain dump.

**Comment by CeliaVermicelli** [comment]
### Nouvelle session de tests : 

- il y a encore un "i" qui traine dans le nom de la procédure tout juste ajoutée. _cf commentaire d'Hermance plus haut._
![Capture d’écran 2023-11-28 à 15 39 36](https://github.com/MTES-MCT/Docurba/assets/111045572/4f4c1ecb-f55e-4cb4-8e9a-fed267477779)
- l'objet de la procédure n'est pas remonté entièrement, pour celle -ci (cf capture d'écran) j'avais coché Zone ENR + autre, en écrivant "test" dans l'objet -> l'objet des zones ENR n'est pas remonté.
![Capture d’écran 2023-11-28 à 15 40 55](https://github.com/MTES-MCT/Docurba/assets/111045572/a751553f-b516-4878-9a5b-abcb23d24c5f)
- je souhaite donc vérifier/modifier les infos mais je n'ai accès qu'a la fonction "supprimer".
- Dans le titre de la procédure j'avais aussi précisé "test 28.11 Célia" -> ça n'est pas remonté au niveau du nom de la procédure. 

https://github.com/MTES-MCT/Docurba/assets/111045572/ea36d74f-0750-40ce-a23d-b429746e6608

**Comment by CeliaVermicelli** [comment]
### Pas possible d'ajouter une proc secondaire alors que proc principale récemment ajoutée.

https://github.com/MTES-MCT/Docurba/assets/111045572/3a286dc4-7b09-4976-9b9a-3d83339f50c7

**Comment by lerayj** [comment]
> ### Pas possible d'ajouter une proc secondaire alors que proc principale récemment ajoutée.
>  Enregistrement.de.l.ecran.2023-11-28.a.15.47.49.mov

Normal, on ne peut faire de procédure secondaire que si il y a une procédure principale opposable

**Comment by CeliaVermicelli** [comment]
> > ### Pas possible d'ajouter une proc secondaire alors que proc principale récemment ajoutée.
> > Enregistrement.de.l.ecran.2023-11-28.a.15.47.49.mov
> 
> Normal, on ne peut faire de procédure secondaire que si il y a une procédure principale opposable

ah mais oui désolée my bad

**Comment by CeliaVermicelli** [comment]
Pour reprendre ton com @lerayj 
> Normal, on ne peut faire de procédure secondaire que si il y a une procédure principale opposable

Si on sait qu'il n'y pas de proc opposable, est-ce que ce serait "facile" de ne pas proposer d'ajouter de proc secondaire depuis la FRP ? 
C'est peut-être pas prio par rapport au reste, et probablement logique pour les DDT mais elles vont surement nous faire la remarque en nous disant que c'est une erreur de laisser cette possibilité.

Capture d’écran 2023-11-28 à 16.02.40

**Comment by CeliaVermicelli** [comment]
Pour reprendre ton com @lerayj

> Normal, on ne peut faire de procédure secondaire que si il y a une procédure principale opposable

Si on sait qu'il n'y pas de proc opposable, est-ce que ce serait "facile" de ne pas proposer d'ajouter de proc secondaire depuis la FRP ?
C'est peut-être pas prio par rapport au reste, et probablement logique pour les DDT mais elles vont surement nous faire la remarque en nous disant que c'est une erreur de laisser cette possibilité.
![Capture d’écran 2023-11-28 à 16 02 40](https://github.com/MTES-MCT/Docurba/assets/111045572/02cbe740-f503-47bb-9207-bb8a485ffe75)

**Comment by CeliaVermicelli** [comment]
### Ajout de proc secondaire 

- commentaire d'hermance _"il faudrait que le numéro de la collectivité porteuse soit remplacée par son nom pour qu'on puisse s'y retrouver."_
![Capture d’écran 2023-11-28 à 16 09 59](https://github.com/MTES-MCT/Docurba/assets/111045572/638b70f1-88e0-473e-9f4f-d5cf72d370e0)

Top d'avoir que la liste des proc. opposables

- je ne retrouve pas directement ma nouvelle proc secondaire -> cf video ci après. Je comprends qu'elle se trouve dans l'onglet DU, sous une des proc principale de l'historique ; est-ce que c'est un peu casse tête pour les DDT d'aller fouiller dans l'autre onglet pour bien vérifié que ça a été ajouté ? Ou bien ce sera évident pour elles quand le nom de la collectivité porteuse de cette proc principale sera annoncé dans la liste ?
- ce dernier commentaire me fait penser qu'une fois une procédure ajoutée, est-ce que ce serait plus logique de les faire arriver directement sur cette procédure ajoutée - autrement dit la FRP associée - plutôt que le comportement actuel qui les fait "revenir" sur l'historique. @HermanceGauth j'ai l'impression qu'une ddt qui ajoute une proc c'est qu'elle veut dans la foulée ajouter une delib ? @julienzdocurba curieuse de savoir ce que tu préconise là dessus

idée quick win pour mes deux commentaires précédents : rajouté un msg en vert pour quelques secondes "votre procédure XXX a bien été créé" -> histoire de les rassurer. 

https://github.com/MTES-MCT/Docurba/assets/111045572/fa30d614-ed25-4fd6-b1eb-e9493b664791

**Comment by CeliaVermicelli** [comment]
### Suppression proc secondaire : 

- besoin de recharger la page pour effectivement prendre en compte ma suppression de proc. -> on a vraiment l'impression que le bouton "supprimer" n'aboutit pas car la page ne change pas - cf video. - tester sur un EPCI et commune, même comportement.
- pour info : la suppresion de proc principale fonctionne correctement. 


https://github.com/MTES-MCT/Docurba/assets/111045572/b422d968-aa6d-4690-b92b-50b841fab6bb

**Comment by lerayj** [comment]
> **Création de procédure PLU** Depuis une commune pour créer une élaboration ou révision de PLU, on me propose toutes les communes de l'EPCI et le PLU est directement catalogué en PLUS au lieu de PLU tout court. Exemple pour un PLU sur la commune d'Ancemont ![image](https://private-user-images.githubusercontent.com/91552054/286296804-388be520-84b9-48c3-af3d-474c8b4403f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTEwNzcsIm5iZiI6MTcwMTE5MDc3NywicGF0aCI6Ii85MTU1MjA1NC8yODYyOTY4MDQtMzg4YmU1MjAtODRiOS00OGMzLWFmM2QtNDc0YzhiNDQwM2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE2NTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2Y2RiM2YwZTkwYWUzYzQ2NTJiOGFjNzRiZmMyZWEzZGNlYjgyNTcxMWIzY2I2YWQ2MDRkNDIxM2MyZjBiN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fegycS1X4beA5W_IqA8SJ8UBW96Mk1h4hICbUZ1hPl8) ![image](https://private-user-images.githubusercontent.com/91552054/286297122-c90c93ae-baa6-4def-aad0-a50b8ddcf566.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTEwNzcsIm5iZiI6MTcwMTE5MDc3NywicGF0aCI6Ii85MTU1MjA1NC8yODYyOTcxMjItYzkwYzkzYWUtYmFhNi00ZGVmLWFhZDAtYTUwYjhkZGNmNTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE2NTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwZTcwMmQ2M2RjZDQ0NjAzODA0OGI1M2RiNTUzNzc5MGJmYTM4NjFiYWRhYjU0MzM5MTUxM2ZiMWQwYTA5YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iqMh0Sc-IIvi_Szf3OWG2WQF1WsmQflc86gIsqBnIRU)

Question la dessus, effectivement ca me semblait bizarre mais il me semblait qu'on voulais laisser le choix de perimètre meme au niveau commune. Du coup je ne le permet pas ou juste je coche uniquement la commune concernée ?

**Comment by HermanceGauth** [comment]
**Communes du périmètre**
On avait relevé une différence entre le moment où on créé la procédure et où elle s'affiche, j'ai l'impression que c'est résolu. Par contre dans le cas d'un EPCI, on propose toujours deux communes de moins que l'EPCI total (si y a 25 communes dans l'EPCI on aura 23 communes dans la création de procédure).
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/48c99d00-5562-4e5c-a55d-e81c699c5f3e)
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/8fff90f9-df60-4d99-9ae1-3b103905cf24)

**Comment by HermanceGauth** [comment]
> Question la dessus, effectivement ca me semblait bizarre mais il me semblait qu'on voulais laisser le choix de perimètre meme au niveau commune. Du coup je ne le permet pas ou juste je coche uniquement la commune concernée ?

@lerayj cocher que la commune concernée mais surtout que ça ne s'affiche pas comme un PLU sectoriel

**Comment by HermanceGauth** [comment]
**Procédure secondaire**
>commentaire d'hermance "il faudrait que le numéro de la collectivité porteuse soit remplacée par son nom pour qu'on puisse s'y retrouver."

Pour moi reste le point le plus structurant pour les procédures secondaires. Ou si c'est trop compliqué on dit que pour faire une procédure secondaire on part nécessairement de la principale concernée et c'est automatiquement la parente.

> je ne retrouve pas directement ma nouvelle proc secondaire -> cf video ci après. Je comprends qu'elle se trouve dans l'onglet DU, sous une des proc principale de l'historique ; est-ce que c'est un peu casse tête pour les DDT d'aller fouiller dans l'autre onglet pour bien vérifié que ça a été ajouté ? Ou bien ce sera évident pour elles quand le nom de la collectivité porteuse de cette proc principale sera annoncé dans la liste ?

Pour moi pas une difficulté si la proc sec créé apparaît bien en haut de la liste des proc sec quand on ouvre l'onglet (c'est le cas)

> ce dernier commentaire me fait penser qu'une fois une procédure ajoutée, est-ce que ce serait plus logique de les faire arriver directement sur cette procédure ajoutée - autrement dit la FRP associée - plutôt que le comportement actuel qui les fait "revenir" sur l'historique. @HermanceGauth j'ai l'impression qu'une ddt qui ajoute une proc c'est qu'elle veut dans la foulée ajouter une delib ? @julienzdocurba curieuse de savoir ce que tu préconise là dessus

Oui pour le coup je suis assez d'accord, c'est un des cas où on pourrait faire arriver direct sur la FRP de la procédure qu'on vient de créer

**Comment by HermanceGauth** [comment]
**Navigation**

> ce dernier commentaire me fait penser qu'une fois une procédure ajoutée, est-ce que ce serait plus logique de les faire arriver directement sur cette procédure ajoutée - autrement dit la FRP associée - plutôt que le comportement actuel qui les fait "revenir" sur l'historique. @HermanceGauth j'ai l'impression qu'une ddt qui ajoute une proc c'est qu'elle veut dans la foulée ajouter une delib ? @julienzdocurba curieuse de savoir ce que tu préconise là dessus

Oui pour le coup je suis assez d'accord, c'est un des cas où on pourrait faire arriver direct sur la FRP de la procédure qu'on vient de créer

**Comment by HermanceGauth** [comment]
- [ ] Problème sur les périmètres (structurant)
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/84c0a345-d05e-4af2-b1a6-9affa2aaf45c)
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/90dbf4f7-00f3-429c-aec9-1dd94f50de38)
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/0e780dac-a5da-43a4-b5fc-a97daf74fea4)
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/729d97b2-bdf1-4803-ba31-f8ec7c8ec472)

- [ ]  si on coche des cases et qu'on écrit des compléments en ayant coché "autre" on ne voit dans les commentaires que ce qu'on a tapé et pas les autres choses que l'on a coché (moins structurant)

**Comment by HermanceGauth** [comment]
**Procédures secondaires**
- [ ] bouton d'ajout depuis la FRP ne fonctionne pas
- [ ] impossible de reconnaitre la procédure parente
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/11dbaa52-f1af-4c95-9c93-ea616b4f1ccf)
- [ ] titre généré incomplet (pa ex ici : modification n°9 du PLUI des Porte de la Meuse)
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/d0a31cec-2153-4be7-abdb-ae2a9bd7e20f)

**Comment by HermanceGauth** [comment]
**Ajout d'event sur nouvelle procédure**
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/29c4239e-dfbb-4003-bfc6-f59025094163)
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/019e7cb1-a40d-4ab6-994b-9548ef1c4d9c)

**Comment by lerayj** [comment]
close pour la meme raison que #224 .
