### ISSUE TITLE
QA retours sur l'historique des SCoT 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#207]
Hello @lerayj , l'historique des SCoT en pre-prod et en prod semble correspondre, je retrouve les même dates, noms et commentaires. J'ai testé pour le 08, 14 et 56. 
FYI @HermanceGauth 

J'ai juste une remarque : 

### Le lien vers "liste des communes concernées" n'apparaît plus. 
en pre prod on n'a plus le lien "communes concernées" sur les SCoT opposable, que ce soit en proc. principale ou secondaire. Je pense que c'est important de le garder ? .cf captures d'écran

**pre-prod :**
![Capture d’écran 2023-11-20 à 18 40 25](https://github.com/MTES-MCT/Docurba/assets/111045572/81f07e0c-cad6-4200-8226-de62012f0734)

**En ligne :** 
![Capture d’écran 2023-11-20 à 18 40 30](https://github.com/MTES-MCT/Docurba/assets/111045572/b3d0e174-e053-4623-99aa-c8b57a9b5179)

**Comment by HermanceGauth** [comment]
Oui effectivement je confirme que c'est intéressant de garder la liste des communes concernées. Et je confirme que je n'ai pas de différence non plus par exemple dans l'Ain je retrouve bien tous les SCoT contrairement à l'excel envoyé à Claire.

**Comment by CeliaVermicelli** [comment]
Retour toujours d'actualité avec les 4 SCOT cités plus haut du 71 qui n'apparaissent pas depuis les collectivités citées. 
à voir si on aboutit effectivement à faire une entrée par procédure qui résoudrait le problème.

**Comment by HermanceGauth** [comment]
Non résolu par la mep sur les périmètres. Solution de contournement par l'onglet SCoT qui permet d'accéder à la procédure.

**Comment by HermanceGauth** [comment]
Je fais une issue spécifique sur ce sujet

**Comment by HermanceGauth** [comment]
@CeliaVermicelli pourras-tu me dire si tu es d'accord avec ça? https://jam.dev/c/32247f82-d7b7-4d43-a166-c3302cd14e6a

**Comment by CeliaVermicelli** [comment]
yes c'est bon !! merci, je n'avais plus en tête cette issue ! 

Je ferme et attend résolution de ta nouvelle issue #571 avant de prévenir la DDT qu'on est ok là dessus.
