### ISSUE TITLE
[SCOT manquant] Bordeaux Metropole le SCOT n'est pas référencé

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#208]
Hello ! Sur Bordeaux Metropole, il n'y a rien dans l'onglet SCOT mais on dirait qu'il est écrasé (cf vidéo).

Merci bcp ! 

https://github.com/MTES-MCT/Docurba/assets/144041896/cad99533-b65a-4cc0-8cf8-fd7c63af9839

<img width="1080" alt="Capture d’écran 2023-11-21 à 17 45 26" src="https://github.com/MTES-MCT/Docurba/assets/144041896/c0404307-1df3-4fd4-832d-fe61e4f9ece1">

**Comment by HermanceGauth** [comment]
Ca m'a l'air résolu, @Octaviedebs à vérifier
