### ISSUE TITLE
[ Socle de PAC Cadre juridique ] | Doublons Loi Climat & Résilence + Qu'est ce qu'un SCOT (pas dans ts les départements que pour le par défaut ? )

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#211]
J'ai constaté dans le 22 par exemple sur n'importe quelle commune que  :
- Loi Climat & Résilience apparait 2 fois dans la partie cadre juridique (cf vidéo)
- Qu'est ce qu'un SCOT ? apparait aussi 2 fois dans la partie cadre juridique (cf vidéo)

https://github.com/MTES-MCT/Docurba/assets/144041896/37d22460-92fb-4680-9875-d37b11fb96f0

En revanche, par exemple dans le 01 tout est ok (AURA)

Piste : j'ai l'impression que les doublons concernent les socles de PAC par défaut ( = donc dans les départements où le socle de PAC n'a pas été personnalisé ) 

Merci bcp !

**Comment by HermanceGauth** [comment]
Ca m'a l'air résolu @Octaviedebs à vérifier
