### ISSUE TITLE
Synchro Pipedrive > Numéro tel nouvel inscrit | Le numéro de tel ne remonte pas sur Pipedrive

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#215]
**Exemple pour Laurence Tartocchi dans le Pipe Procédures CT/BE** 
https://docurba2.pipedrive.com/person/1395
= le numéri de tel qu'elle saisit à l'inscription ne remonte pas dans le champ Numéro de tel de la fiche Personne sur Pipedrive.

Or cf Metabase elle l'a bien rempli : https://docurba-metabase.osc-fr1.scalingo.io/question/51-liste-des-inscrits-ct

**Comment by UngererFabien** [comment]
Est ce que c'est possible qu'il ne l'indique pas ?

**Comment by Octaviedebs** [comment]
C'est obligatoire 

<img width="1171" alt="Capture d’écran 2023-11-27 à 09 54 04" src="https://github.com/MTES-MCT/Docurba/assets/144041896/a727e513-8ef9-492e-a464-54d9e4f3af65">
