### ISSUE TITLE
Mauvaise remonté des informations à la connexion

### ISSUE THREAD

**Issue by UngererFabien** [MTES-MCT/Docurba#219]
Il y a des lignes dans la table profiles qui n'ont pas de poste et département.

**Comment by CeliaVermicelli** [comment]
Exemple : 
![Capture d’écran 2023-11-23 à 07 15 16](https://github.com/MTES-MCT/Docurba/assets/111045572/46d705cb-05c0-499d-a71b-869a020f6073)

**Comment by CeliaVermicelli** [comment]
résolu, je close
