### ISSUE TITLE
QA Feuille de Route Partagée (Vx Julien)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#224]
Suite à rapide navigation d'une FRP (presque vide) - cf video.

- **Apparition conditionnelle des events** (_je ne sais pas techniquement où on en est là dessus et ce qui est faisaible_) : si la prescription est déjà renseignée, il ne faudrait pas proposer aussi la prescription en event suggéré 
- ~~Manque un accent à "Ev**é**nement suggéré"~~
- ~~Le tag "Sudocu" sans le "H" est volontaire car on ne fait pas la partie Habitat @HermanceGauth ? j'ai peut-être raté des msg qui en parlait pour cette nouvelle MEP,~~ 
- ~~Il me semble qu'on avait acté que les event provenant de Sudocuh n'était pas modifiable depuis les FRP -> je ne retrouve plus le fil de ces msg pour vérifier l'info, désolée!~~ 
- ~~pour les event effectivement modifiables, il faudrait que les infos préalablement enregistrées apparaissent dans le form de modification de l'evenement. Dans la video, l'intitulé de l'event est vide (bug), la date est celle d'auj et non celle de l'event en question~~ -> manque seulement la PJ cf mes commentaire s du 29.11 ci après. 
- ~~depuis la modification de l'event, le click sur "annuler" n'aboutit pas.~~
- tag pour identifier qui a ajouté l'event : je comprends que lorsque l'event provient de Sudocuh alors le tag "DDT" n'apparait pas -> je me demande si ça sera pas utile de préciser les deux quand même en terme de base de données (Côté CT/BE on va vouloir garder ce tag "ddt" et pas celui "sudocuh")

https://github.com/MTES-MCT/Docurba/assets/111045572/a4c2c88e-98fe-4412-bc0c-611d6707dc27

**Comment by HermanceGauth** [comment]
Sudocu je crois que c'était une erreur au départ mais on la justifié comme ça oui.

Par si possible private -> privé et de manière générale pas d'anglais ;)

Sur la modif des éléments venant de Sudocuh je crois que la conclusion c'était : pendant la transition avec les dump ça serait trop le bazar s'ils pouvaient les modifier. Par contre à partir du moment où Sudocuh ne sera plus accessible je pense que c'est bien qu'ils puissent modifier ou qu'on leur laisse 1 mois pour faire les modifs avec de fermes Sudocuh.

**Comment by CeliaVermicelli** [comment]
### Consultation FRP

_(j'avais mis un commentaire là dessus hier qui n'a pas dû s'enregistrer :()_ 

Cf video, plusieurs remarques : 

- l'ordre des events n'est pas cohérente : ce n'est pas classé par date donc difficile de s'y retrouver. 
- l'apparition conditionnelle de l'event suggéré n'a pas de sens à l'arrivée sur la FRP. La delib de prescription est suggérée alors qu'on a déjà l'arrêté du projet. 
- Date des event : je pense que les DDT ont besoin d'un 01/04/2005 et non un "01/05/04" comme c'est actuellement, 
- L'encart de droite sur les event clefs devrait être clickable, non ? Ex : je click sur "début de l'enquête" et la page scroll down jusqu'à l'envent en question, 
- L'encart ressources : les pièces jointes mises en valeur ici n'ont pas trop d'intérêt je trouve, les fichiers n'ont pas de noms compréhensibles, est-ce que le terme "ressources" est approprié/utile côté DDT ? 


https://github.com/MTES-MCT/Docurba/assets/111045572/0790be93-9a08-40c2-8195-8dc441ad3106

**Comment by lerayj** [comment]
> ### Consultation FRP
> _(j'avais mis un commentaire là dessus hier qui n'a pas dû s'enregistrer :()_
> 
> Cf video, plusieurs remarques :
> 
> * l'ordre des events n'est pas cohérente : ce n'est pas classé par date donc difficile de s'y retrouver.
> * l'apparition conditionnelle de l'event suggéré n'a pas de sens à l'arrivée sur la FRP. La delib de prescription est suggérée alors qu'on a déjà l'arrêté du projet.
> * Date des event : je pense que les DDT ont besoin d'un 01/04/2005 et non un "01/05/04" comme c'est actuellement,
> * L'encart de droite sur les event clefs devrait être clickable, non ? Ex : je click sur "début de l'enquête" et la page scroll down jusqu'à l'envent en question,
> * L'encart ressources : les pièces jointes mises en valeur ici n'ont pas trop d'intérêt je trouve, les fichiers n'ont pas de noms compréhensibles, est-ce que le terme "ressources" est approprié/utile côté DDT ?
> 
>  Enregistrement.de.l.ecran.2023-11-29.a.13.23.03.mov

Pour les bug ca va etre fix dans la release preprod de ce soir, le reste c'est de l'UX UI, le mieux c'est d'en discuter avec @julienzdocurba  pour ce genre de retour pour que les maquettes colle au mieux et qu'on ai pas des questions de ce genre a postériori. Je vais faire comme prévu pour le moment, mais hésite pas a re challenger avec lui

**Comment by julienzdocurba** [comment]
> je comprends que lorsque l'event provient de Sudocuh alors le tag "DDT" n'apparait pas -> je me demande si ça sera pas utile de préciser les deux quand même en terme de base de données

Est-ce qu'un event Sudocu peut être entré par un autre acteur qu'une DDT?

> Date des event : je pense que les DDT ont besoin d'un 01/04/2005 et non un "01/05/04" comme c'est actuellement,

Est-ce que le problème c'est l'ordre année / mois ou bien le format de la date (mettre l'année entière) ?

> les pièces jointes mises en valeur ici n'ont pas trop d'intérêt je trouve, les fichiers n'ont pas de noms compréhensibles

Il me semble qu'on en avait parlé avec Julien et on avait suggéré l'idée de reprendre le nom de l'événement mais je crois qu'on n'avait pas pris de décision. Pas sûr que ce soit une bonne idée si le nom de l'événement ne correspond pas toujours au nom du doc. Je trouve que c'est pas une mauvaise idée de laisser les choses comme ça pour l'instant et de "responsabiliser" les gens sur la manière dont ils nomment leurs fichiers (on peut pas résoudre tous les problèmes de notre côté).

> est-ce que le terme "ressources" est approprié/utile côté DDT ?

Qu'est-ce qui te semble pas approprié pour les DDT?

> pièce jointe : à ce niveau dans l'encadré de l'ajout d'event je trouverais plus utile de pouvoir la consulter que de la retélécharger

Je sais pas pourquoi mais j'arrive pas à voir la vidéo donc je loupe peut être un truc mais c'est quoi la différence pour toi entre consulter et retélécharger? (parce que pour consulter il faut télécharger la pièce jointe et ensuite savoir si le navigateur l'ouvre ou pas c'est en fonction du type de document et c'est géré par le navigateur)

Dites moi si j'ai raté des retours de design!

**Comment by julienzdocurba** [comment]
> mais quid des events qui selon Docurba sont des events Collectivité ?

Du coup c'est des events importés depuis Sudocu, qui ont donc été entrés dans Sudocu par une DDT mais qui selon notre définition à nous sont censés être entrés par une collectivité? Si c'est le cas je pense qu'il faut être fidèles à ce qui s'est réellement passé et considérer qu'ils sont tous entrés par une DDT. Dans ce cas je trouve ça ok de mettre simplement "Sudocu" partout.

**Comment by lerayj** [comment]
https://jam.dev/c/cdb95c88-5a2a-4357-b208-d1c6b1e26619

**Comment by HermanceGauth** [comment]
>   je comprends que lorsque l'event provient de Sudocuh alors le tag "DDT" n'apparait pas -> je me demande si ça sera pas utile de préciser les deux quand même en terme de base de données
Est-ce qu'un event Sudocu peut être entré par un autre acteur qu'une DDT?
Tous les event sudocu proviennent de DDT donc le tag sudocu suffit

>Date des event : je pense que les DDT ont besoin d'un 01/04/2005 et non un "01/05/04" comme c'est actuellement,
Est-ce que le problème c'est l'ordre année / mois ou bien le format de la date (mettre l'année entière) ?

C'est l'ordre qui doit être l’ordre français jour mois année

>Il me semble qu'on en avait parlé avec Julien et on avait suggéré l'idée de reprendre le nom de l'événement mais je crois qu'on n'avait pas pris de décision. Pas sûr que ce soit une bonne idée si le nom de l'événement ne correspond pas toujours au nom du doc. Je trouve que c'est pas une mauvaise idée de laisser les choses comme ça pour l'instant et de "responsabiliser" les gens sur la manière dont ils nomment leurs fichiers (on peut pas résoudre tous les problèmes de notre côté).

Totalement d'accord ici c'est un problème de nommage de fichier pas de notre fait, voir pq ils nomment comme ça (obligation ou choix) et si choix les faire évoluer.


>est-ce que le terme "ressources" est approprié/utile côté DDT ?
Qu'est-ce qui te semble pas approprié pour les DDT?

Je propose de garder ce terme et de voir en fonction des retours quand on aura mis aussi les collectivités dessus

**Comment by lerayj** [comment]
Je ferme et on rajoutera des Issues individuelles au besoin, de toute facon c'est en prod maintenant et la plupart des retours de cette issue on été traités
