### ISSUE TITLE
QA navigation générale : TdB-FRP-PAC (DDT connectée)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#226]
- si un PAC est relié à une proc. , il faudrait pouvoir le retrouver depuis l'encadré de la proc en question,
![Capture d’écran 2023-11-28 à 17 37 55](https://github.com/MTES-MCT/Docurba/assets/111045572/bf5b45ba-4e89-403a-b192-93bdf9ef52e4)
- il faudrait pouvoir créer un PAC depuis l'encadré de la procédure voir même depuis la FRP ? (2 personnes en DDT pensait générer un nouveau PAC en créant un event "PAC" depuis la FRP de la procédure -> je ne trouve pas ça dénué de sens) cf issue #189 
- ~~ou se trouve le CTA "créer un nouveau PAC" ? (relié à mon commentaire précédent)~~
- est-ce que les liens DGD et info générale vont finalement être grisé. Remarque d'Hermance à ce sujet dans[ le commentaire de cette issue ](https://github.com/MTES-MCT/Docurba/issues/205#issuecomment-1816137016)
> Griser les liens dgd et infos générale qui ne renvoient à rien ou bien renvoyer vers les écrans prévus pour la DGD (d'ailleurs pour les infos générales c'est pareil pour les proc historique le rendu est pas top donc le grisé serait mieux)

**Comment by CeliaVermicelli** [comment]
### Onglet Mes PAC



- dans l'encadré du PAC, préciser la date de création et la date de dernière modification par l'agent de DDT ?
![Capture d’écran 2023-11-28 à 17 59 27](https://github.com/MTES-MCT/Docurba/assets/111045572/6ef3abab-6ac3-42d2-8ea5-e0cb04f5abff)

- une fois dans le PAC, préciser en haut le nom du PAC : le nom de la collectivité concernée ? _(un peu comme dans la nouvelle FRP où le nom de la proc est répétée)_
![Capture d’écran 2023-11-28 à 18 00 51](https://github.com/MTES-MCT/Docurba/assets/111045572/e0c6c773-1d66-4d1b-9478-ce306650709e)

- on ne souhaite pas mettre de CTA de creation de PAC à ce niveau ? 
![Capture d’écran 2023-11-28 à 18 01 44](https://github.com/MTES-MCT/Docurba/assets/111045572/663f4d33-62b2-413b-9bb4-9d9fcf82d3af)


https://github.com/MTES-MCT/Docurba/assets/111045572/839baccc-15db-4d09-9334-e0396329d090

**Comment by CeliaVermicelli** [comment]
### Présence de l'onglet Validation des proc.

Rappel dans [le commentaire de Julien](https://github.com/MTES-MCT/Docurba/issues/214#issuecomment-1828554307) sur cette issue

**Comment by CeliaVermicelli** [comment]
### Bouton Tableau de bord et confusions à la connexion

1. Je remets cette issue closed qui pose encore "problème" #64 -> je continue à avoir des retours réguliers de DDT qui ne comprennent pas qu'ils sont déjà connectés. (le fait que le navigateur conserve leurs identifiants - même si pratique - n'est pas un comportement habituel pour eux) 

Même si déjà la DDT est déjà connectée avec le bouton "tableau de bord" en haut à droite de la page d'accueil, ils sont plus attirés par le CTA de connexion juste en dessous de la recherche publique (voir issue #64 justement) 
-> c'est possible de retirer ce CTA de connexion si déjà connecter ?
-> à voir si cela suffit à ce qu'ils voient le bouton TdB, sinon aussi ajouter un message temporaire en vert "Vous êtes déjà connecté, cliquez sur TdB pour accéder à votre espace DDT" 
_(j'imagine que ce sont des choses qui vont aussi évoluer avec l'arrivée de la landing page)_


2. Une fois dans l'espace DDT, je me demande si le bouton TdB est toujours utile puisqu'il correspond à l'onglet "mes collectivités" - si jamais c'est pertinent de faire de la place à ce niveau 
![Capture d’écran 2023-11-28 à 18 07 51](https://github.com/MTES-MCT/Docurba/assets/111045572/79ae0848-5a85-4abb-9bde-864769555dfe)



3. En parlant de faire de la place, avec @Octaviedebs on aimerait mettre plus valeur les contenus/guides utilisateurs disponibles aujourd'hui. 
On a créé ce lien vers un pad : [Sommaire guides et webinaires](https://pad.incubateur.net/s/MVwW7cGNh) 
-> est-ce que ça serait pertinent de l'avoir à côté de "besoin d'aide" ? -> ces guides sont également glissés dans "Besoin D'aide" et les différentes questions de la FAQ mais il faut chercher, c'est moins direct
-> Si pertinent, l'intitulé du bouton  pourrait être "Tutoriel d'utilisation"

@julienzdocurba preneuse de tes recommandations là dessus. Je suis consciente que ce n'est pas en mettant plus de liens, plus de guides et contenus qu'ils vont davantage les lire. 

Pour rappel, aujourd'hui le guide priorisé est celui des PAC, visible ici (donc pas très obvious) : 


![Capture d’écran 2023-11-28 à 18 25 16](https://github.com/MTES-MCT/Docurba/assets/111045572/16902f6b-8124-433f-9d45-b5d30c95fc58)

**Comment by julienzdocurba** [comment]
J'ai commencé à regarder certains de ces retours avec le sujet de la navigation PAC / Procédures hier mais je vais répondre aux points qui sont un peu en dehors de ce scope.

> si un PAC est relié à une proc. , il faudrait pouvoir le retrouver depuis l'encadré de la proc en question

Je pense qu'il faudrait vraiment prioriser le redesign de cette liste de procédures parce qu'on commence à lister pas mal de retours là-dessus. En attendant on peu bosser sur des petits fix mais il faut juste garder à l'esprit qu'on va certainement vouloir changer cet écran assez largement et donc ne pas investir trop de temps dessus.

> Je remets cette issue closed qui pose encore "problème" UX parcours connecté DDT : arrivée dans leur espace DDT VS cliquer sur le bouton "TdB" #64 -> je continue à avoir des retours réguliers de DDT qui ne comprennent pas qu'ils sont déjà connectés.

Du coup on ne redirige pas directement vers le tableau de bord quand on est connecté? C'est ce qui était mentionné dans l'issue.

> Une fois dans l'espace DDT, je me demande si le bouton TdB est toujours utile puisqu'il correspond à l'onglet "mes collectivités"

Oui totalement je pense qu'il faudra prioriser un boulot sur la navigation principale.

> est-ce que ça serait pertinent de l'avoir à côté de "besoin d'aide" ? -> ces guides sont également glissés dans "Besoin D'aide" et les différentes questions de la FAQ mais il faut chercher, c'est moins direct

Pareil je pense que ca ferait partie du boulot sur la navigation et il faudra explorer ca plus en détails mais j'imagine qu'on pourrait conserver le lien "Ressources" qu'on a créé pour la landing page (avec tous ces guides dans le sous menu).

**Comment by CeliaVermicelli** [comment]
> Du coup on ne redirige pas directement vers le tableau de bord quand on est connecté? C'est ce qui était mentionné dans l'issue.
@julienzdocurba non, aujourd'hui une DDT connectée qui revient sur Docurba arrive sur la page d'accueil et ne voit pas forcément le bouton "tableau de bord" en haut à droite. 
Le pb aujourd'hui c'est qu'elles ont le bouton "tableau de bord" ET aussi le CTA pour se créer un compte qui apparaît juste en dessous de la recherche publique -> pas cohérent. Et si elles suivent ce CTA de connexion/creation de compte avec qu'elles sont déjà connectées et bien elles sont "bloquées" car pas de msg d'erreur et elles ne comprennent pas qu'elles sont déjà connectées.

**Comment by julienzdocurba** [comment]
Ok ok mais c'est juste que dans l'issue qui était liée (https://github.com/MTES-MCT/Docurba/issues/64), il y avait des commentaires disant que le comportement avait été changé pour rediriger les DDT sur leur tableau de bord et pas la landing page.

**Comment by HermanceGauth** [comment]
Lors de la connexion on est bien redirigé vers le tableau de bord mais le problème c'est quand on revient sur Docurba, on arrive sur la landing page tout en étant déjà connecté et c'est là que les personnes cherchent à se reconnecter alors qu'elles le sont déjà.

**Comment by julienzdocurba** [comment]
Ok j'avais compris qu'on redirigeait tout le temps vers le tableau de bord. Genre chaque fois que j'ouvre `https://docurba.beta.gouv.fr/` on me redirigerait vers le tableau de bord si je suis connecté. Tu penses que ça résoudrait le problème de faire ca?

**Comment by HermanceGauth** [comment]
> Tu penses que ça résoudrait le problème de faire ca?

Oui je pense que ça résoudrait le pb.

**Comment by UngererFabien** [comment]
Je close cette issue pour en créer une nouvelle sur l'intégration du design de la liste des PAC par @julienzdocurba
