### ISSUE TITLE
QA MEP du 7.12 nouvelles proc. : la consultation d'une FRP d'un SCoT n'aboutit pas. 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#232]
Entrée par le TdB du dpt - Onglet SCoT :
https://jam.dev/c/8527973e-4994-4b0c-a9db-886bffa1d1b3

Entrée par la page ECPI/commune - onglet SCoT :
https://jam.dev/c/750e4dd8-452c-4b13-93f9-84b1131d9e20

@UngererFabien

**Comment by lerayj** [comment]
done
