### ISSUE TITLE
[FRP : visibilités des event] : les events "privés" sont visibles dans les FRP publiques

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#239]
Comportement attendu : les event ajoutés par les DDT en mode "privé" ne devraient pas êtres visibles dans les FRP publiques 

Cf demo jam avec un event ajouté le 1.12.  : 
https://jam.dev/c/e22f786b-67fc-40b3-83d1-4318a7814be9 

Vérification faite aussi avec des event ajoutés le 11.12 -> tous les events privés sont visibles en mode pas connecté.

**Comment by Octaviedebs** [comment]
Pour précision dans la vidéo de Célia elle est connectée sur un compte mais sans être connectés c'est pareil sur la visibilité

**Comment by Octaviedebs** [comment]
Pour suivi
