### ISSUE TITLE
Mise en place du tag de la nouvelle instance de Matomo

### ISSUE THREAD

**Issue by NicolasM92** [MTES-MCT/Docurba#241]
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://stats.beta.gouv.fr/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '69']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

<img width="1115" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/60889390/4148980f-223c-4dbe-ad20-97aafb2cf270">

**Comment by lerayj** [comment]
J'ai peut etre pas bien suivi le sujet mais pourquoi on aurait une deuxieme instance de matomo ?

**Comment by NicolasM92** [comment]
L'instance actuelle n'appartient pas à Beta. Du coup toutes les startups
d'état doivent migrer vers la nouvelle instance créée par Beta.


*Nicolas Mouanga*Chargé de déploiement Senior
***@***.***
06 66 22 88 96


Le mer. 20 déc. 2023 à 11:23, Julien Leray ***@***.***> a
écrit :
