### ISSUE TITLE
[ Suivi DU & remontées Sudocuh ] Erreur sur le statut + remontées d'event 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#243]
Hello à tous ! 

**Erreurs de statut =**
- par exemple sur cette [CT](https://docurba.beta.gouv.fr/collectivites/200040715/?isEpci=true) :   le statut de la 1ère procédure par exemple devrait être opposable et non pas en cours (il y a une délib d'approbation) - 

**Plusieurs évent Débat sur le PADD remontent en très grand nombre : bug ou amélioration produit ?** 
- sur cette [procédure](https://docurba.beta.gouv.fr/frise/5c47473e-3b23-4c0a-8f7e-2bb32660cb0f) : il y a plusieurs événements Débat du PADD même certains le même jour qui sont remontés - Hermance suppose qu'ils ont rentré ceux de toutes les communes de l'epci dans sudocuh => mais ça poserait question pour qu'on puisse tout **rassembler** dans un event sur Docurba.

**Events clefs**
- la délibération d'approbation devrait apparaître en évent clé de la procédure or ce n'est pas le cas 

Illustration en vidéo 
- cette vidéo Jam = https://jam.dev/c/5d397771-9f92-40a3-a98d-cc6de7f3ee3d

à voir si ce n'est pas le cas pour d'autres CT si la délib d'approbation remonte mal (ce qui expliquerait qu'elle n'apparaisse pas dans event clefs + que le statut soit faux)

PS : les event privé apparaissent alors qu'on est en public mais ça sauf erreur de ma part ce sera corrigé à la prochaine mep cf cette [issue](https://github.com/MTES-MCT/Docurba/issues/239) qui vient d'être closed 

Merci ! 

FYI @HermanceGauth

**Comment by HermanceGauth** [comment]
Sur la question public/privé je pense que le problème vient du fait que tous les event de Sudocuh sont remontée en privé alors que l'on a décidé de les afficher dans la FRP publique. Pour éviter la surcharge des FRP publique avec les event de sudocuh je préconise de ne garder en publique que les event de Sudocuh correspondant à des event identifiés comme event clés. Dispo pour échanger sur ce point si besoin.

**Comment by Octaviedebs** [comment]
Yes c'est résolu - je vais close 
J'ai créé une nouvelle [issue](https://github.com/MTES-MCT/Docurba/issues/578) pour 1 sujet + je vais faire un feedback pour l'autre sujet
