### ISSUE TITLE
[FRP] Mauvaise implémentation des event suggérés (cf scope sugg)

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#246]
Pour rappel la colonne I ici : https://docs.google.com/spreadsheets/d/1zgC0vMOh-VPxUeboYz8gi0Tz5Xs5yxDdno1gUi26C9E/edit#gid=1392334617

![image](https://github.com/MTES-MCT/Docurba/assets/91552054/a5b1436a-1fbb-4f34-8d3e-34c782bdd5ac)

![image](https://github.com/MTES-MCT/Docurba/assets/91552054/c1a6ad17-9daf-4202-8566-8ed48491e0ca)

**Comment by lerayj** [comment]
duplicate #344
