### ISSUE TITLE
[Suivi DU & FRP ] Données Sudocuh ne remontent pas + pas de mise à jour de l'étape de la procédure

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#248]
Désolée pour les 9 premières secondes haha 

https://jam.dev/c/161c7921-36ea-4f26-a966-d48c42947529

Peut être en revanche que c'est normal que l'étape de la procédure ne remonte pas mais le souci est donc vraiment dans la FRP ou il y a 0 event - tout est dans la vidéo ! n'hésitez pas si besoin de + d'infos

**Comment by HermanceGauth** [comment]
J'ai l'impression que ce problème ne concerne que les EPCI

**Comment by Octaviedebs** [comment]
pourtant j'ai l'impression que pour les communes aussi cf https://jam.dev/c/d1a3f95c-c966-463f-988a-607a9f1ce471

j'ai juste testé sur 2 communes dont celle là - sur quelle commune ça marchait toi ? (au cas où ce soit mon ordi ?)

**Comment by lerayj** [comment]
c'est sur des frise sudocu qui sont en privé par default en non conecté.
Hermance proposait de mettre quand meme les events structurant meme en cas de privé, mais du coup il me faut un matching parfait des nouveaux event et ancien event sudocu (ce que m'aide a faire hermance en me rajoutant des id sur les ancien). Du coup c'est un comportement attendu

**Comment by Octaviedebs** [comment]
Ah yes désolée ! Effectivement sur le fait qu'il n'y a rien d'affiche dans la frise = j'étais en non connecté donc normal 
Sur la remontée des events structurants quand même = ok je vois !
Merci !
