### ISSUE TITLE
[ FRP ] Suppression des events par n'importe quel user connecté : comportement attendu ? 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#255]
Je ne suis pas sûre de moi (désolée par avance), mais est-ce qu'on avait déjà acté qu'on veut que n'importe quel user connecté puisse supprimer un event ajouté par qn d'autre ? 

Exemple ici : https://jam.dev/c/1d908687-bfff-4b46-ac6c-d854080a4f47

Une CT connectée peut ici supprimer un event ajouté par une DDT 

J'ai le sentiment que ce n'est pas le comportement optimal - mais cette issue pourra venir illustrer les réflex° sur les accès/visibilités

**Comment by CeliaVermicelli** [comment]
résolution en cours par julien, la ddt n'a pas encore tous les droits mais la CT et BE ne peuvent pas supprimer les choses de la DDT + pas de droits si pas connectés : https://github.com/MTES-MCT/Docurba/issues/236

**Comment by lerayj** [comment]
Done
