### ISSUE TITLE
FRP (DDT connectée) : certaines pièces jointes ne sont pas téléchargeables

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#256]
demo 1 : https://jam.dev/c/d29613f4-5ee0-40c2-a6c2-148655fcff25

Autre exemple où le téléchargement de se lance pas : https://jam.dev/c/8814e99f-ada7-4a8a-a49c-a93664e15c74

J'imagine que c'est dû au fichier de base ? Si c'est le cas, je ne sais pas si un msg d'erreur temporaire de type "erreur sur ce fichier", lorsque qu'un téléchargement n'est pas possible, permettrait de nous dédouaner de l'erreur  ? 

Autre commentaire : les pièces jointes sur la droite ne paraissent pas cliquables (à aucun moment pour le coup).

**Comment by lerayj** [comment]
Effectivement, la base de document en pièce jointe Sudocu (c'est différent de la base de donnée Sudocu) a été importé en Février, du coup toutes les pièces jointes ajouté sur des procédures Docurba plus récent que Février on va pas les avoir. Je vais demander le différentiel a Dominique - et contrairement aux procédures c'est simple, j'ai juste a upload les documents sur notre dépot de fichier.
Je vais mettre un tooltip "Sera disponible dans 1 semaine sur Docurba. Disponible Maintenant sur Sudocu" ou un truc du genre pour pas que ca fasse bizarre dans ces cas la.
