### ISSUE TITLE
[ Accès connecté BE/CT ] Limiter l'accès si compte non validé

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#259]
### Création de compte

Actuellement, lorsqu'un compte est créé : 
- il y a une notification sur le bot_admin 
- CTA valider : aucun impact 
cf cette vidéo https://jam.dev/c/5400f267-06a0-4db8-9e7e-399fe6550a16
(je sais que c'est normal hein de ce que j'ai compris ça n'avait été prévu)

Cependant, en attendant une auto-validation / validation GPU pour les CT / ou toutes autres automatisations, il faudrait a minima SI le compte n'a pas été validé / ou est en attente de validation (via le CTA Valider le compte dans bot_admin) et tant que la validation n'a pas été faite =

**Pour une CT :** 

ALORS : 
- ne pas permettre l'ajout d'event sur les FRP de toutes les procédures du territoire = être en accès public 

**Pour un BE :** 
- ne pas permettre l'ajout d'event sur les FRP de toutes les procédures du territoire sur lequel il s'est inscrit = être en accès public 

### Validation d'email quand dépôt d'acte (en vue des prochaines itérations sur le lien dépôt acte > FRP : autre issue ?)
Actuellement, lorsqu'un compte est créé : 
- il y a une notification sur le bot_admin 
- CTA valider : aucun impact sauf erreur de ma part ?

Il faudrait permettre l'ajout de cet event pour initier la nouvelle FRP que si et seulement si l'email a été validé.

@HermanceGauth pour avis / compléments etc merci !

**Comment by HermanceGauth** [comment]
Effectivement, tout comme pour les DDT, l'accès/dépôt ne doit pas être validé tant qu'on ne l'a pas validé.

**Comment by HermanceGauth** [comment]
@lerayj pour le chantier droit d'accès

**Comment by CeliaVermicelli** [comment]
* **en mode non connecté/accès public - création de nouvelle procédure :** 
-> j'ai accès au bouton "ajouter une nouvelle procédure" (c'est bien), puisque le bouton "créer la procédure" à la fin du form n'aboutit pas, je pense qu'il faudrait **rajouter un message/une alerte invitant la personne à se connecter/se créer un compte avant de commencer le renseignement des infos de la nouvelle proc**. cf demo : https://jam.dev/c/e84b5570-1b91-4a1d-84d0-f4c012e0396f

@Octaviedebs j'ai voulu test les actions CT/BE mais ça m'a rappelé que ça n'est pas possible en dev il me semble, je te laisse infirmer/confirmer car tu es plus au fait de ce côté là :)

**Comment by Octaviedebs** [comment]
La fonctionnalité de nouvelle procédure est juste en dev donc probablement pas encore finalisée - il est probablement prévu de moduler les droits d'accès concernant la création d'une nouvelle procédure (et donc limiter la possibilité de le faire hors connexion) : j'ajoute cela en commentaire dans l'autre [carte](https://github.com/MTES-MCT/Docurba/issues/612)

**Comment by HermanceGauth** [comment]
Voilà ce qui était prévu dans les maquettes :
![image](https://github.com/user-attachments/assets/eb76d110-0690-4450-bfdb-2d5624074dcf)

**Comment by Octaviedebs** [comment]
ajout nouvelle procédure en non connecté : Super merci @HermanceGauth  pour la précision - du coup si le compte n'est pas validé, il faudrait peut être ajouté une redirection vers une page En attente de validation ? 

@UngererFabien : compte non validé 
- ne pas afficher les events privés : l'accès est bien limité et on ne voit que les events publics tant que compte n'est pas validé ✅
- ne pas permettre ajouter un event ❌ : l'action est tjrs possible, mais je pense que cela a un lien avec l'autre carte en cours sur ce sujet

**Comment by Octaviedebs** [comment]
Pour compléter suite nvx tests : 

https://jam.dev/c/b440b567-9256-4877-8ba4-d730fb2064e4
- **accès public** : je ne vois pas le bouton Ajout événement - ok
- **accès connecté + non validé + sur mon périmètre** : je vois le bouton Ajout événement mais la complétion du form n'aboutit pas - vu ce matin, ok bouton a ne pas afficher
- **accès connecté + non validé + en dehors de mon périmètre** : je vois le bouton Ajout événement mais la complétion du form n'aboutit pas - vu ce matin, ok bouton a ne pas afficher

**MAIS effets de bord : https://jam.dev/c/5fe07459-a7d7-4a55-8711-276086649699**
- **accès connecté + validé + sur mon périmètre** : quand j'ajoute l'event sur la frp, j'ai bien la notif slack (donc l'ajout fonctionne) mais ça ne s'affiche pas
- **accès connecté + validé + hors de mon périmètre** : quand j'ajoute l'event sur la frp, j'ai bien la notif slack (donc l'ajout fonctionne) mais ça ne s'affiche pas (ce qui est ok en soit, mais le fait que l'ajout de l'event fonctionne indique que ce n'est pas le comportement attendu)

@CeliaVermicelli @HermanceGauth n'hésitez pas à révérifer mes tests mais je l'ai fait plusieurs fois en pp

**Comment by HermanceGauth** [comment]
Ok avec ce commentaire d'Octavie. Pour résumer, il faut :
- cacher toutes les actions non possibles
- renvoyer vers les pages connexion ou en attente de validation lorsque des utilisateurs sans compte ou compte non validé tentent de faire ces actions
- les actions que l'on a testé ici : créer, modifier, supprimer une procédure doivent être possible pour les DDT et collectivités/BE connecté sur leur périmètre d'action (DDT : département + invitation collaborateur dans l'avenir, collectivité : périmètre d'inscription + invitation collaborateur dans l'avenir)

**Comment by Octaviedebs** [comment]
Il y a encore un problème : en accès public donc non connecté, le comportement attendu est le suivant :
**- si l'utilisateur clique sur Nouvelle procédure il doit atterrir sur la page de sign in quelque soit le territoire**

OR pour les pages EPCI (pas pour les communes) on atterrit sur la page de validation (ce qui n'a pas de sens puisqu'on est en accès public)
<img width="1406" alt="Capture d’écran 2024-09-03 à 15 04 26" src="https://github.com/user-attachments/assets/fabfd7dc-815a-4338-b525-540afb4de48c">

Voici la vidéo (un peu long mais muté en pp) - j'essayais de trouver le pourquoi (j'étais partie sur une autre piste au début)

https://jam.dev/c/f5b93774-c172-4c66-a06a-cc92c6b0ded4

**Comment by Octaviedebs** [comment]
Je close - le reste est dans cette issue https://github.com/MTES-MCT/Docurba/issues/795
