### ISSUE TITLE
[ Recherche d'un territoire ] Pouvoir rechercher son territoire directement par le nom de la commune / EPCI (et pas que par le département)

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#261]
Je m'étais déjà fait le constat moi-même, mais je l'ai constaté en live dans une démo personnalisée : une utilisatrice va instinctivement directement dans le champ commune (et pas département) de la barre de recherche.

Grazie !

**Comment by HermanceGauth** [comment]
Je crois que le pb la dessus c'est que si on ne filtre pas par département la liste des communes/EPCI est trop longue

**Comment by lerayj** [comment]
Yep. Ce n'est pas possible techniquement sans exploser les temps de chargement et les PC pas assez puissant. On peut rien faire la dessus a part de l'UX @julienzdocurba . Je ferme l'issue en attendant qu'il y ai une action possible.
