### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by nyko28** [MTES-MCT/Docurba#264]
https://www.figma.com/file/4W463mFBKoDzf4mgJAhW9y/Docurba-(V2)?type=design&node-id=4648-6040&mode=design&t=CdpAVmPrDsLM3VQF-0

**Comment by Octaviedebs** [comment]
Hello @UngererFabien du coup pour cette issue, qu'est ce qui est prévu en terme de délais (à peu près ?) ? Il me semble que vous avez fait un point semaine dernière si je dis pas de bêtises

@CeliaVermicelli FYI
