### ISSUE TITLE
BUG chargement des proc secondaire de modification simplifiée + ajout d'event impossible 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#265]
Test sur une modif simplifié de Carnac : bug
https://jam.dev/c/147f720e-c9d1-4638-bf27-998815146893

Test sur une modif simplifiee de Questembert : fonctionne !
https://jam.dev/c/cce68e21-f287-4f21-aafa-4b2390cfa214  

J'ai testé les autres proc secondaires et tout semble fonctionner normalement.

**Comment by CeliaVermicelli** [comment]
à priori c'est bon cf conversation Slack avec Julien. canal produit.

**Comment by CeliaVermicelli** [comment]
Hello @lerayj ! je réouvre cette issue car le Tarn (81) a un cas similaire à ce que tu avais débugué pour Carnac (56) : 
Lien vers[ la CT concernée](https://docurba.beta.gouv.fr/frise/e77399ce-8fd1-44c1-906e-2801e55fd465)

Voir demo : https://jam.dev/c/c93b3f5c-5140-43e0-bb39-a58fe747a724 

Peut-être que toutes les procédures de MS se retrouvent dans cette même situation ? C'est assez chronophage pour moi d'en identifier d'autres pour aller tester donc si jamais tu les spot rapidement n'hésite pas à me dire et je les testerai si c'est utile :) merci !

**Comment by HermanceGauth** [comment]
J'ai l'impression que c'est résolu @CeliaVermicelli
