### ISSUE TITLE
Export .pdf : le contenu du sommaire parait aléatoire

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#268]
Sur ce PAC test : https://docurba.beta.gouv.fr/documents/projet-5b012f82-630c-4d19-86da-5dffadf8ede9/pac

**Dans le sommaire :** 

Il manque les sous sections des doc locaux : 
PCAET
PDH 
PLH
Alors que le titre Le SCoT est repris dans le sommaire et est du même niveau hiérarchique que les autres. 

Aussi, les titres des sous sections de Le SCoT (nommées ScoT Nord Ardennes et SCoT Grand Ardennes) ne sont pas repris dans le sommaire. 

**PB avec le contenu du PAC dans le pdf :** 
Les titres des sections ScoT Nord Ardennes et SCoT Grand Ardennes ne sont pas non plus reprises dans le texte du PAC et on n'a que leur contenu texte -> c'est peut-être un bug différent ? Dites moi si ça devrait faire l'objet d'une nouvelle issue. 

Demo video : 
https://github.com/MTES-MCT/Docurba/assets/111045572/722f95e9-5456-4a2e-92a4-dd307f78a752

Exemple similaire dans les pp du territoire: 

https://github.com/MTES-MCT/Docurba/assets/111045572/e09c0a05-908b-4963-b18c-4558b1d9d5c7

**Comment by nyko28** [comment]
Lié à l'issue #161
