### ISSUE TITLE
Export pdf : les titres de nouvelles sections ne sont pas repris dans le contenu

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#272]
PAC test : https://docurba.beta.gouv.fr/trames/projet-5b012f82-630c-4d19-86da-5dffadf8ede9

On retrouve dans le PDF du PAC uniquement les titres des sections proposées initialement ? 
Seul le contenu des nouvelles sections créés est repris dans le PDF, il manque leurs titres et donc la hiérarchisation de ces titres pour aussi s'y retrouver visuellement.

https://github.com/MTES-MCT/Docurba/assets/111045572/da8e6ef8-f08f-402b-8bec-2fa5a1470ad0

**Comment by nyko28** [comment]
Les sections pour lesquelles les titres apparaissent bien dans le PDF sont celles dont le titre est aussi repris dans le contenu. En lien avec cette issue : https://github.com/MTES-MCT/Docurba/issues/161

Il faudrait changer de stratégie : effacer les titres des contenus, et reprendre directement de la section pour la génération du PDF.

**Comment by nyko28** [comment]
Lié à l'issue #161
