### ISSUE TITLE
[FRP_DDT_connectée] le tag de la visibilité "publique" d'une event ajouté ne ressort pas correctement 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#278]
Même pb sur tout type de procédure (principale ou secondaire, nouvelle ou ancienne). 

Aussi : le copy du tooltip n'est pas correct. 
Demo : https://jam.dev/c/02a9d6f0-3962-4cb6-a9e0-b403e3b10dee

![Capture d’écran 2023-12-27 à 16 37 49](https://github.com/MTES-MCT/Docurba/assets/111045572/b4a85bad-b8d6-4842-9c31-b9869f880214)

**Comment by lerayj** [comment]
Done, par défaut si c'est publique on met pas de tag ca sert a rien
