### ISSUE TITLE
[FRP_DDT_connectée] perte de la suggestion d'event dans certains cas 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#279]
"bug" dans le cas des : 
- procédures principales nouvelles - après l'ajout d'un premier event
- procédures secondaires nouvelles ET anciennes 

Demo : https://jam.dev/c/bb68d4ba-c810-47ec-9070-7cc681da0b52

**Comment by lerayj** [comment]
Duplicate #344
