### ISSUE TITLE
QA preprod 27.12 : sections fantômes ; parcours utilisateur complexe

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#282]
Je découvre la fonctionnalité en même temps que j'ai fait ces vidéos. En l'état je pense que les agents de DDT ne vont pas comprendre ce qui est attendu. Je relève les questionnements suivants : 

- est-ce que les sections fantômes viennent remplacer la fonctionnalité de comparaison à la trame du niveau supérieur ? cela donne cette impression dans le cas de ma section ScoT (voir demo)
- je crois que le copy du tooltip n'est pas correct tout le temps (voir demo au niveau d'un PAC).
- peut-être qu'un disclaimer dans l'encadré de la nouvelle section du type aiderait à comprendre ce qui est de leur intérêt, exemple : _"rédaction proposée par le niveau régional le 23 novembre 2023"_ 

**Mes rélfexions**:
Demo au niveau d'un PAC : https://jam.dev/c/b8582afd-76ca-4885-a1c6-5cf6c32933ed
Demo au niveau de la trame : https://jam.dev/c/a4fb0e91-356a-4f91-b331-fb23802d6779
Demo sur la trame avec récupération de contenu déjà présent dans le socle de PAC : https://jam.dev/c/697aec85-0b61-4f28-98d9-8b78182ef07f  (sur ce cas là j'ai tout compris et je trouve ça top!) -> peut-être qu'un disclaimer dans la section du type : _"rédaction proposée par le niveau régional le 23 novembre 2023"_ aiderait à comprendre.

**Comment by UngererFabien** [comment]
@lerayj je veux bien que tu regarde pour ce template: https://mc.sendgrid.com/dynamic-templates/d-ff4df2141eda4723800cae1f0a63982c/version/86f38678-f2e1-4207-9688-f1d58483d656/editor sur le depot d'acte.

**Comment by nyko28** [comment]
@CeliaVermicelli Merci pour tes retours !

> est-ce que les sections fantômes viennent remplacer la fonctionnalité de comparaison à la trame du niveau supérieur ? cela donne cette impression dans le cas de ma section ScoT (voir demo)

Les sections fantômes ne remplacent pas la fonction de comparaison à la trame supérieure, mais je comprends la confusion étant donné qu'une section déjà existante peut aussi apparaître sous la forme d'une section fantôme. Cela arrive quand la section fantôme (donc de la trame supérieure) n'a plus le même nom que la section que l'on veut comparer.

Pour l'instant, on ne se fie qu'aux noms des sections pour savoir si elles ont une section correspondante au niveau supérieur. Si on change le nom de la section dans la trame supérieure ou dans le PAC actuel, on ne peut plus établir de lien et de suivi entre les deux. La section de la trame supérieure n'apparait donc pas dans la comparaison et devient fantôme. 

C'est déjà un problème de la version actuelle, donc il n'y pas de régression sur ce point. On compte travailler sur une solution pour établir le lien entre les sections malgré les changements de nom.

<br>

> je crois que le copy du tooltip n'est pas correct tout le temps (voir demo au niveau d'un PAC).

En effet, il y a une erreur de wording sur le tooltip. Pour l'instant, j'ai modifié en limitant juste à "Ajouter la section".
Sinon, le comportement est le même à tous les niveaux. Le bouton copie la section du niveau supérieur dans le niveau actuel, que l'on soit sur une trame ou un PAC.

<br>

> peut-être qu'un disclaimer dans l'encadré de la nouvelle section du type aiderait à comprendre ce qui est de leur intérêt, exemple : "rédaction proposée par le niveau régional le 23 novembre 2023"

En effet, on va voir comment l'intégrer au mieux et sans doute voir avec Julien Z pour l'UX sur ce point et les sujets du dessus.

**Comment by HermanceGauth** [comment]
J'identifie deux soucis liés au parcours :

1) les sections fantômes dues aux changements de titre -> proposition de cleaner tous les titres et toutes les trames régionales et départementales à la main avec Célia, nous attendons le feu vert pour faire cela depuis l'été dernier

2) le fait que les sections fantômes "ne sautent pas" une échelle : ex une modification de la trame régionale doit d'abord être prise en compte dans la trame départementale avant d'apparaître en section fantôme au niveau des PAC comm/intercomme or les DDT ne vont pas consulter leur trame départementale avant de travailler sur un PAC communal/intercommunal donc ne seront pas au courant de cette modification. Par contre si on permet que la section fantôme saute une échelle et puisse être ajoutée au niveau PAC comm/intercomm il faudrait pouvoir l'ajouter en même temps au PAC en cours et à la trame départementale -> voir si quick win mais sinon pourra être résolu par une page d'atterrissage prévenant des différentes modifications faites aux différentes échelles

**Comment by CeliaVermicelli** [comment]
Pour résumer les conversations avec @hermance @nyko28 et @julienzdocurba d'aujourd'hui: 

1. pour faire face aux conflits suite aux titres modifiés des sections par les DDT, est-ce que c'est ok pour toi @UngererFabien si on le fait à la mano avec Hermance ? 

2. pour essayer de rentre plus cohérent le parcours utilisateurs et les A/R entre Mes PAC et Trame de PAC départementale, on propose : d'ajouter une popup au niveau de l'onglet "Mes PACs" qui indique à la DDT dès qu'une section fantôme est proposé au niveau de sa trame -> de cette manière ça lui permet de mettre à jour sa trame régulièrement avant de toucher à ses PAC. Julien est déjà entrain de faire des essais là dessus. 
![image (5)](https://github.com/MTES-MCT/Docurba/assets/111045572/ae627b1f-4de4-4b70-b9cd-af570f048591)


Cela dit : Julien soulève tout de même le fait que le parcours utilisateur entre trame et pac, et un possible futur "vrai mode brouillon" demande un travail de fond supplémentaire, mais que cette option présentée peut être un quick win et éviter trop de frustrations des utilisateurs.
