### ISSUE TITLE
QA preprod 27.12 : Enquête/SCOT : bug sur le chargement des FRP de ScoT ?

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#284]
Les frp des proc principale comme secondaires des SCOt ne finissent jamais de charger

https://jam.dev/c/9ae29017-a851-4171-be58-0a785b33a737

**Comment by UngererFabien** [comment]
@lerayj à voir si ce n'est pas lié au référenciel avec des collectivité manquante.

**Comment by UngererFabien** [comment]
Problème d'ID de procédure dans l'URL. J'ai test exactement le même parcourt en prod et le bug est résolu c'est bien la bonne ID dans l'URL et la FDR se charge correctement.
