### ISSUE TITLE
[ Dépôt d'acte ] Pouvoir déposer des actes relatifs aux SCOT

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#286]
Hello ! Je sais que c'est un point déjà remonté, mais j'ai eu ce retour donc je voulais le partager - l'utilisatrice s'attendait en tout cas à pouvoir déposer son acte de prescription pour le SCOT :)

<img width="756" alt="Capture d’écran 2023-12-28 à 14 52 36" src="https://github.com/MTES-MCT/Docurba/assets/144041896/9730c99d-9399-4985-b875-47a6108f11d1">

**Comment by Octaviedebs** [comment]
Avant passage en prod pinguer Octavie pour que je prévienne Paola OCAÑA-SEGUIN (https://docurba2.pipedrive.com/person/1590) qui avait remonté cette demande

**Comment by HermanceGauth** [comment]
Sera normalement résolu avec cette issue : https://github.com/MTES-MCT/Docurba/issues/612

**Comment by Octaviedebs** [comment]
doublon je close
