### ISSUE TITLE
Landing page: Ajustement sur le footer

### ISSUE THREAD

**Issue by julienzdocurba** [MTES-MCT/Docurba#298]
Pareil, je regroupe les petits changements du footer dans une seule issue.

Le footer sur dev:
<img width="2089" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/48c1c658-b514-43b1-ae44-2f9acff53348">

Sur les maquettes:
<img width="1429" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/a9d43dd0-f9c1-4615-9c53-3fa0ff8272fd">

Les changements:
- Utiliser une max-width égale à la largeur des blocs du centre de la landing page.
- Utiliser un bouton aux coins arrondis (idéalement en "secondaire" donc sans le background et juste avec la border) pour le bouton "S'abonner" de la newsletter.
- Je pense qu'on peut supprimer la mention "En renseignant votre adresse électronique..." sous le champs de la newsletter. Je le vois jamais sur des champs d'inscription + on peut expliquer ca dans l'email de confirmation si besoin. Mais à voir peut être avec @HermanceGauth ou @CeliaVermicelli . Si on veut le conserver, je pense qu'il faudrait réduire l'espacement entre le champs de la newsletter et ce texte à 0px.
- A voir avec @CeliaVermicelli et @Octaviedebs si on veut ajouter plus de liens vers nos réseaux sociaux (je crois qu'on avait parlé des 3 sur la maquette).

**Comment by Octaviedebs** [comment]
- supprimer la mention "En renseignant votre adresse électronique..." = je suis d'avis de le supprimer - @CeliaVermicelli il est dans l'email de confirmation non ? 
- On a uniquement Linkedin comme réseau social

**Comment by julienzdocurba** [comment]
Ok il me semblait qu'on avait demandé les 3 réseaux sociaux, j'ai du mal comprendre. Du coup si on a juste Linkedin ca va faire étrange la mise en page actuelle, je vais bosser sur un changement.
