### ISSUE TITLE
[ Support user ]  Avoir un accès Super Admin pour éviter de devoir se créer des comptes pour chaque CT/DDT quand on doit traiter des tickets utilisateurs par exemple 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#299]
Actuellement, par exemple quand un user rencontre un souci sur sa FRP (en mode connecté), ou qu'on veut vérifier qqch ou faire une action pour le user on doit se créer autant de comptes que de CT/BE/DDT en fonction des cas. 
C'est très très chronophage.

Solution : **avoir un accès superadmin** qui nous permettrait d'accéder : 
- à toutes les fonctionnalités du mode connecté
- pour tous les territoires

-  = un mode « super admin » pour l'équipe Docurba sans aucune contrainte et qui nous éviterait de créer des comptes à chaque fois pour tout

@CeliaVermicelli FYI

**Comment by Octaviedebs** [comment]
Précision : avec les accès différents à venir cela sera encore plus chronophage

**Comment by CeliaVermicelli** [comment]
+1000 !

**Comment by UngererFabien** [comment]
@CeliaVermicelli @Octaviedebs vous pouvez me m'envoyer une invitation pour un call de 30min sur ce sujet ? Normalement vous avez déjà accès à tous les périmètres, je ne vois pas les cas où il faut se créer plusieurs comptes.

**Comment by Octaviedebs** [comment]
autre illustration @UngererFabien : j'ai besoin d'accéder à la FRP d'une 20taine de communes là pour vérifier si la dernière procédure remontée sur docurba est bien la bonne, et pour ça j'ai besoin de créer un compte pour chaque CT = assez chronophage.

Pour précisions dans le prolongement de ce qu'on disait : il faudrait donc qu'on puisse passer d'un accès à l'autre sur n'importe quel page territoire donc passer de l'accès public à tous les accès possibles en mode connecté sur ce territoiree

**Comment by Octaviedebs** [comment]
Résolu par la brique dépannage Accès superadmin de Julien L

**A améliorer : avoir ces actions directement depuis l'interface user (via des accès violets invisibles par le user par exemple)**

**Comment by Octaviedebs** [comment]
**Ne résous pas vraiment le fait de pouvoir passer d'un accès à l'autre sur n'importe quel page territoire donc passer de l'accès public à tous les accès possibles en mode connecté sur ce territoire, car la solution de contournement grâce à l'interface superadmin est encore vraiment trop chronophage malheureusement.** 

Pour le reste c'est tout bon

**Comment by Octaviedebs** [comment]
Je reprécise ici le besoin : 

`**Exemple 1 : Activation des départements prioritaires**
`J'ai une liste d'EPCI (à qui j'envoie une capture écran de la FRP en cours pour l'engager dessus)
_**Actuellement**_ :
- je recherche l'EPCI sur Docurba
- je me crée un compte
- je retourne sur l'accés en mode connecté
- je fais ma capture et envoi mon email

**Ce qui prendrait moins de temps :**
- je vais sur la page territoire de mon EPCI
- je switch de l'accès public > privé CT par exemple
- je fais ma capture écran de la FRP avec event privé et j'envoie mon email

`Exemple 2 : Notif slack ajout event`
**Actuellement** :
- je me crée un compte sur la collectivité concernée
- je retourne sur le slack pour cliquer sur la frise et accéder à la frise en mode connecté CT
- je fais ma capture et envoi mon email

**Ce qui prendrait moins de temps :**
- je clique sur la frise et arrive directement sur la frise en mode connecté CT (ou DDT si besoin etc)
- je fais ma capture écran de la FRP avec event privé et j'envoie mon email

Est-ce que c'est plus clair ?
