### ISSUE TITLE
[Bug validation des proc.] tag PLUi/PLU

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#301]
Dans l'onglet validation des procédures, il apparait " PLUi en cours " pour la commune de Le Guerno alors qu'elle n'est pas concernée par un PLUi 

https://jam.dev/c/db0a5629-2f74-491b-b7dc-2667b0103b53

**Comment by UngererFabien** [comment]
Problème de lecture des procédures archivées.
