### ISSUE TITLE
QA référentiel - communes fusionnées : ça n'a pas résolu le retour du 35 qui date de mi-décembre. 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#303]
Retour de Clément (35)
> Prise en compte des communes nouvelles. Exemple d'une commune nouvelle (piré-chancé), pour cette commune nouvelle il existe 2 PLU en vigueur : un pour la commune déléguée de piré-sur-seiche  et un pour la commune déléguée de chancé. Or Docurba affiche des informations incomplètes faisant penser qu'il n'existe qu'un seul PLU opposable qui couvre toute la commune nouvelle.

(je pense qu'il voulait dire "piré sur seiche = commune déléguée" et "commune nouvelle = piré chancé"

https://jam.dev/c/a0191930-d4fd-4333-bf49-c1c769af2dc6 

### Au cas où : voici les cas où je pense que les changements sur le référentiel ont bien été pris en compte : 

- Cas de St Brice sur Vienne (87) : 
https://jam.dev/c/022642ac-d06d-42c4-afae-278e66bba0b8
Retour de la DDT 87 du 12 décembre : 
> Saint Brice sur Vienne (87) ; le PLU est remis en vigueur mais le statut de la proc. sur Docurba est resté "annulé".
- Cas de Grand Angoulème (16) 
https://jam.dev/c/d07f103d-22e1-49c7-a07d-5d53526ac072
Retour de la DDT 16 du 15 décembre : 
> c'est le cas des communes fusionnées - il y a 39 communes dans l'EPCI (Saint Estèphe est en trop) et 38 communes sont concernées dans le PLUi en cours.

**Comment by lerayj** [comment]
ouep, il faut que je reflechisse a comment faire parceque les 2 on les mêmes code INSEE du coup...

**Comment by HermanceGauth** [comment]
Je ne sais pas si c'est un problème tech ou d'affichage mais pour l'affichage j'avais fait une issue ici : https://github.com/MTES-MCT/Docurba/issues/100 et repris quelques éléments dans mes commentaires ici : https://github.com/MTES-MCT/Docurba/issues/137

**Comment by HermanceGauth** [comment]
Nouveau retour de la part du 29 sur le même sujet
[DOCURBA-et-Plouneour-Brignogan-Plages.pdf](https://github.com/MTES-MCT/Docurba/files/13938156/DOCURBA-et-Plouneour-Brignogan-Plages.pdf)

**Comment by HermanceGauth** [comment]
Nouveau retour toujours côté 29 : 
"Pour les communes fusionnées tel que Milizac et Guipronvel, les 2 PLU sont toujours opposables.
Or seul celui de Milizac apparaît en opposable dans DOCURBA
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/238ee1fc-9383-42f7-aa7c-00c719975eed)


Comme je le disais je pense que la solution c'est de faire comme pour les PLUi sectoriel et de regarder le périmètre pour savoir si on est sur un précédent et un opposable ou deux opposables.

**Comment by lerayj** [comment]
Je rajoute @UngererFabien dessus, il a bossé dessus la semaine derniere avec Claire

**Comment by CeliaVermicelli** [comment]
Doute sur le comportement attendu pour l'exemple du 35 et la commune nouvelle de Piré-chancé : https://jam.dev/c/c5ef77c8-950f-4f13-b19f-26101cd0e89c

On ne retrouve pas le nom "correct" de la comd "piré sur Seiche". Est-ce que c'est normal ? @lerayj 
![Capture d’écran 2024-04-23 à 09 42 51](https://github.com/MTES-MCT/Docurba/assets/111045572/858df62e-ffc7-4c66-9597-8c9e7a9fb0a1)
![Capture d’écran 2024-04-23 à 09 43 02](https://github.com/MTES-MCT/Docurba/assets/111045572/1a8c1f61-1052-4e5a-ab30-77d8a97c7d3f)

**Comment by HermanceGauth** [comment]
@UngererFabien @CeliaVermicelli je closed cette issue pour en créer des spécifiques car bizarrement le cas de Milizac-Guipronvel est résolu en pre-prod mais pas les autres cas
