### ISSUE TITLE
[ FRP | CT/BE ] Pouvoir créer une procédure et avoir ainsi une FRP pour les procédures pour lesquelles il n'y aura qu'une délibéra° d'approba°

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#304]
Certaines procédures de modification n'auront que la délibération d'approbation comme actes, car il s'agit du cas où ils ne sont pas soumis à l'obligation qu'il y ait un arrêté pour commencer cette procédure.

Donc : 
-  il n'y aura jamais de 1er acte qui déclencherait la création de la FRP
- manque à gagner sur ces procédures pour les suivre sur Docurba !

Il faudrait pouvoir couvrir ces cas et permettre la création d'une « procédure » décorrélée du dépôt d'acte

**Comment by Octaviedebs** [comment]
Avant mep, pinguer Octavie pour information de l'utilisatrice concernée Léa Dentz

**Comment by UngererFabien** [comment]
Ce genre d'issue rentre dans le scope FDR 2.0 où on regroupera les fonctionnalitées d'intéractions des collectivités sur les procédures.

**Comment by julienzdocurba** [comment]
Juste pour être sûr de comprendre: Le problème c'est qu'actuellement seules les DDT peuvent créer une procédure sans dépôt d'acte c'est ca? Une fois que les CT pourront le faire également, cette issue ne sera plus pertinente c'est ca?

**Comment by Octaviedebs** [comment]
Oui, plus précisément, cette issue est donc un **besoin** à prendre en compte pour affine ce qu'on attend du comportement de la feature côté CT/BE

**Comment by HermanceGauth** [comment]
Devrait être résolu par cette issue : https://github.com/MTES-MCT/Docurba/issues/612

**Comment by HermanceGauth** [comment]
@Octaviedebs je close et te ping comme demandé
