### ISSUE TITLE
[ Transfert de compétence ] Transfert de compétence vers la CC Val de Charente qui est beta testeurs & questions 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#305]
Hello ! Un transfert de compétence n'a pas été pris en compte concernant la CC Val de Charentes.

Comment pouvez-vous procéder à la mise à jour ? Il s'agit d'une bêta testeuse - j'ai récupéré les infos en principe + j'ai qq questions pour anticiper la suite. 

**De ma compréhension, suite aux transferts de compétence (depuis novembre 2022, effectif en février 2023), la CC Val de Charente est compétente en matière de PLU pour les communes suivantes (cf site internet + délib en PJ qu'elle m'a transmise):** 
Les Adjots
Barro 
Bernac 
Bioussac 
Brettes 
La Chèvrerie 
Condac 
Courcôme : qui a fusionné avec Tuzie et Villegâts
Couture 
Empuré 
La Faye 
La Forêt-de-Tessé 
Londigny 
Longré 
La Magdeleine 
Montjean 
Nanteuil-en-Vallée
Paizay-Naudouin-Embourie 
Poursac 
Raix 
Ruffec 
Saint-Georges 
Saint-Gourson 
Saint-Martin-du-Clocher 
Saint-Sulpice-de-Ruffec 
Salles-de-Villefagnan 
Souvigné 
Taizé-Aizie 
Theil-Rabier 
Verteuil-sur-Charente 
Villefagnan 
Villiers-le-Roux

----------------------------
**QUESTIONS** : 

**Concernant la commune de **Ruffec | Révision allégée n° 1 PLU** : 
- il y a donc une procédure en cours qui datait d'avant le transfert :
-  la délibération d'approbation aura lieu mi janvier à la prochaine réunion du conseil municipal
- elle prévoit le téléversement des délibérations et du zonage graphique et écrit  le 25 janvier avec la DDT 
- comme le dépôt de la prescription de cette procédure n'avait pas été renseigné par la DDT : il n'y a pas de FRP existante associée cf https://docurba.beta.gouv.fr/frise/54925f39-6835-4a88-a011-628b14d0cef3
**=> est-ce que j'ai bien tout intérêt à lui dire de déposer tous ces actes sur Docurba PUIS de téléverser sur le GPU ?** 
Cela donnerait : 
- la délibération de prescription (le type d'acte existe)
- la délibération d'approbation (le type d'acte existe)
- la catégorie autre pour mettre le zonage graphique et écrit ? 
= et est-ce que pour chacun de ces dépôts d'acte elle recevra bien le lien URL pour téléverser ensuite sur le GPU ? @HermanceGauth pour tes conseils 
= dans tous les cas, le fameux lien entre dépôt d'acte et FRP sera ensuite essentiel haha 🙏🏻

=> ** par ailleurs, est-ce qu'une fois le transfert effectué vers la CC, on pourra bien accéder à cette procédure pour cette commune Ruffec, ou bien on perdra l'historique de Ruffec qui apparaitra comme sans compétence urba, et donc elle ne pourra plus déposer les actes concernant cette commune (question peut être bête) ?** 

**CC Val de Charentes | Elaboration PLUi :** 
L'élaboration du nouveau PLUi est donc en cours :
- avec une délib de prescription effectuée le 28 avril 2023 
- téléversement GPU pas encore fait, elle le fera quand ce sera à jour sur docurba = à nouveau assez déterminant que le lien dépôt d'acte > FRP soit effectif ! 🙏🏻

Merci bcp ! A dispo de vive voix 

[2022-11-15-Délib CC PlUI  PRISE DE COMPETENCE DOCUMENTS D_URBANISMEPLAN LOCAL D_URBANISME INTERCOMMUNAL.pdf](https://github.com/MTES-MCT/Docurba/files/13832582/2022-11-15-Delib.CC.PlUI.PRISE.DE.COMPETENCE.DOCUMENTS.D_URBANISMEPLAN.LOCAL.D_URBANISME.INTERCOMMUNAL.pdf)

**Comment by Octaviedebs** [comment]
Avant mise en prod pinguer Octavie pour qu'elle informe Marie Amélie Rivet (user concernée)

**Comment by UngererFabien** [comment]
On a reparler des périmètres et des compétences aujourd'hui et si c'est bloquant dans le système actuel on devrait le débloquer.

La notion de compétence n'est pas indispensable dans la donnée d'une procédure donc on devrait pouvoir s'en défaire. Et si il y a un transfert de compétence, c'est la collectivité porteuse de la procédure qui devrait être mise à jour et il faudrait le rajouter dans les design @julienzdocurba

**Comment by Octaviedebs** [comment]
hello @UngererFabien du coup comment tu penses qu'on va pouvoir avancer sur cette issue ? 

Car elle ne peut pas déposer l'acte de prescription pour l'élabora° du PLUi par exemple car la liste de toutes les communes du périmètre de l'EPCI n'apparait pas pour CC Val de Charentes -

**Comment by HermanceGauth** [comment]
J'ai du mal à comprendre car pourtant on a la bonne liste des communes pour cet EPCI
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/4a2832b9-edc4-40d2-9f07-38f721a8a99d)

**Comment by Octaviedebs** [comment]
Ca a changé ! @lerayj top si tu peux me l'indiquer quand ça change comme ça je préviens l'utilisatrice ! :) mercii

Avant lorsqu'on déposait un acte pour la CC Val de charente j'avais pas ttes les communes dans le périmètre du coup :
![Capture d’écran 2024-01-08 à 16 24 14](https://github.com/MTES-MCT/Docurba/assets/144041896/3cdc9489-c112-4308-997a-ea76c399369c)

**Comment by Octaviedebs** [comment]
@lerayj 

**En fait, les DU communaux ne sont pas accessibles depuis l'EPCI :**

https://jam.dev/c/d143fbec-9186-4d10-91de-f1d259d407cb

**Seuls les DU intercommunaux sont accessibles depuis la commune**

https://jam.dev/c/e4fc4d34-753d-4702-8990-d4460ee7f5d7

Dans mon cas pour ma beta testeuse du coup ça l'oblige à se créer un autre accès pour retrouver tout au meme endroit (elle avait un accès EPCI et pas un accès commune) = je vais lui dire de faire ça pour l'instant mais pas optimal : tu penses que ce serait possible de résoudre ce petit bug bientôt ? 

Merci bcp !

**Comment by Octaviedebs** [comment]
Vu avec Fabien, comportement attendu

**Comment by Octaviedebs** [comment]
`**Point Fabien -** `

Pb de mise à jour de compétence vu avec Fabien 

**Quick win** : si la compétence est pas bonne, CTA voir les DU non rattachés à l'EPCI 
pallierait les cas où erreurs de compétence

**Long terme :**
- voir si Banatic est à jour
- mettre à jour

**Comment by julienzdocurba** [comment]
Est-ce qu'il y a une urgence à s'occuper du quick win? Parce que j'imagine qu'on va re-designer cette page à un moment.

**Comment by Octaviedebs** [comment]
Je ne me rends pas compte du temps que ça peut prendre de faire ce quick win - mais ce qui est sûr c'est que ça aura un gros impact : 
- à la fois pour cette beta testeuse et ça envoie un bon message
- ET de tte façon ça palliera un pb qu'on risque d'avoir vraiment pendant longtemps sur le long terme car la mise à jour des compétence via banatic est un vaste sujet pas prio

Donc si rapide, autant le faire tt de suite // OU l'intégrer dans le périmètre de refonte du design de cette page mais je ne suis pas sure que ce soit prévu tt de suite

Que penses tu du temps design dessus ? côté dev ça avait l'air rapide de ce que j'ai compris je crois

**Comment by julienzdocurba** [comment]
Ok du coup je pense que le mieux ce serait de prioriser ca proprement et de voir a quel point c'est intéressant en terme d'impact et d'effort comparé aux autres projets potentiels. Je pense qu'on peut rentrer ce genre de feedback directement sur la page de feedback Notion (https://www.notion.so/docurba/7ed7389e9d9446b4aa3f696a476b5b62?v=23e53c0c33354264884261c914ab5c0e) comme ca on le prendra en compte pour prioriser.

**Comment by Octaviedebs** [comment]
@UngererFabien en revanche tu me confirmes que pour ce user spécifiquement, de tte façon la compétence n'est pas bonne donc tu vas pouvoir corriger cela - tu me diras quand grosso modo tu penses pouvoir le faire (genre cette semaine ou semaine pro ? )

**Comment by HermanceGauth** [comment]
A mon sens le quickwin c'est de corriger manuellement la compétence et de le noter dans le référentiel de compétence Sudocuh qui va devenir Sudocuh/Docurba en attendant de faire converger avec Banatic

**Comment by UngererFabien** [comment]
Il faut relancer le script sur les compéteces effectivement voir si ça se corrige tout seul. Sinon implémenté un quick win comme dit Hermance ou designé par Julien Z pour l'accès aux procedures.

**Comment by HermanceGauth** [comment]
@Octaviedebs j'ai l'impression que cette issue est résolu pour ce qui est de l'affichage des DU communaux et que la question de l'affichage de la compétence va être traitée par ailleurs? Si c'est bien cela je te laisse closed ou sinon recommenter
