### ISSUE TITLE
[ QA Sendgrid | Accès CT/BE ] Formulaire d'inscription impossible | apparemment cela vient du champ prénom 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#310]
Pas en lien direct avec les emails mais ça a cassé depuis la mise en production : j'ai essayé avec plusieurs prénoms, en changeant l'email (yopmail, gmail) et rien ne change 

<img width="1050" alt="Capture d’écran 2024-01-04 à 18 52 24" src="https://github.com/MTES-MCT/Docurba/assets/144041896/aa6ae778-4bec-4373-b70d-bb290e3e1d4c">

**Comment by Octaviedebs** [comment]
et le jam que j'avais zappé haha https://jam.dev/c/205a3907-2ca5-467b-8eef-067939f3ff5b

**Comment by UngererFabien** [comment]
Plusieurs bugs, @lerayj j'ai fais plusieurs changements sur la création de user et profile coté server. Et au moment de la redirection on ne sauvegardait pas le bon code collectivité. A voir si ce bug n'est pas présent dans le signup DDT/DEAL suite au changement de reférenciel.
