### ISSUE TITLE
[ QA Sendgrid ]Durée d'expiration du lien de 1ère connexion pour moduler les emails en fonction de si c'est 1ère ou > 1ère connexion

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#311]
**[parcours de connexion] lien magique - Connect** 

Questions déjà évoquées dans cette [issue](https://github.com/MTES-MCT/Docurba/issues/135) pour info mais besoin du coup de confirmation : 
- 1ère connexion : a priori la durée d'expiration est de 24h = c'est bien ça ? 
- en revanche post 1ère connexion ? : j'avais vérifié et c'est bien 1h

Une fois confirmation de ces éléments, @UngererFabien est-ce que c'est possible de distinguer, dans tes conditions de déclenchement des emails, selon qu'il s'agit d'une 1ère ou post 1ère connexion ? 
Si oui : 
- je créerai un nouvel email avec le délai de 24h pour 1ère connexion 
- je te ferai une issue pour le mettre en ligne

Si non : je garde cet email et module juste la phrase pour indiquer que c'est 24h en cas de 1ère connexion

**Comment by Octaviedebs** [comment]
<img width="1014" alt="Capture d’écran 2024-01-05 à 10 54 53" src="https://github.com/MTES-MCT/Docurba/assets/144041896/25d088d4-6ecf-4999-875b-985625524905">

Email actuel : 
<img width="1014" alt="Capture d’écran 2024-01-05 à 10 55 35" src="https://github.com/MTES-MCT/Docurba/assets/144041896/6e85fb36-6b8c-4bb9-a901-dee6a0525153">

**Comment by Octaviedebs** [comment]
Message slack Fabien : c'est possible.

Hey @UngererFabien ! 
Dans le prolongement de nos échanges slack, j'ai créé un autre email afin de distinguer entre : 
- email sign up
-email sign in

TO DO : 
- https://mc.sendgrid.com/dynamic-templates/d-766d017b51124a108cabc985d0dbf451/version/703eac2a-98a5-4b5d-b8c6-73fe3578606d/editor : c'est l'email pour le sign up déjà en ligne : il faut que la condition d'envoi soit uniquement pour le sign up (=1ère co)
- mettre en ligne l'email nouveau pour le sign in (post 1ère co) :  ce nouvel [email](https://mc.sendgrid.com/dynamic-templates/d-7a75390ea3334b66a5d9cfb9fa76e077/version/df812a3b-5d98-4581-a816-67199568c770/editor)
- le CTA doit renvoyer sur le tableau de bord aussi
- me répondre pour les délais d'expiration du lien de connexion pour que je puisse modifier à la marge dans le corps des emails le délai que je mentionne

**Comment by Octaviedebs** [comment]
Durée du lien d'expiration identique  que ce soit sign up ou sign in. 

Donc je remets la TO DO : 

Distinguer entre :

email sign up
email sign in

TO DO :

https://mc.sendgrid.com/dynamic-templates/d-766d017b51124a108cabc985d0dbf451/version/703eac2a-98a5-4b5d-b8c6-73fe3578606d/editor : c'est l'email pour le sign up déjà en ligne : il faut que la condition d'envoi soit uniquement pour le sign up (=1ère co)
mettre en ligne l'email nouveau pour le sign in (post 1ère co) : ce nouvel [email](https://mc.sendgrid.com/dynamic-templates/d-7a75390ea3334b66a5d9cfb9fa76e077/version/df812a3b-5d98-4581-a816-67199568c770/editor)
le CTA doit renvoyer sur le tableau de bord aussi

**Comment by UngererFabien** [comment]
Should be good. Je passe en prod demain.
