### ISSUE TITLE
[ QA Sendgrid ] Email « Tous - confirmation envoi msg de “besoin d’aide” - RAS » ne fonctionne pas 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#312]
Il s'agit de cet email https://mc.sendgrid.com/dynamic-templates/d-23a3309075ab4710af6028e4639bf6dc/version/b2088694-c817-43af-9835-814430a421b9/editor

Il ne marche pas cf jam https://jam.dev/c/b0697714-b41e-4aaf-87a5-df137d4d7e21

Merciii !

**Comment by UngererFabien** [comment]
C'était un bug si tu demandais de l'aide sans être connecter. C'est corrigé mais dans ce cas il n'y a pas le firstname/lastname dans l'email.
