### ISSUE TITLE
[ QA Sendgrid ] Email 🟦 - validation de compte - guideDDT ne fonctionne pas 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#313]
il s'agit de cet email https://mc.sendgrid.com/dynamic-templates/d-939bd4723dd04edcad17e6584b7641f3/version/19f52cb7-13ff-46d3-a6b1-234341e27189/editor

Il ne fonctionne pas cf jam https://jam.dev/c/ec6e1a0e-49b3-4d48-971b-70ac9ce39a88

**Comment by UngererFabien** [comment]
Devrait être réglé. A test et re ouvrir si ce n'est pas le cas.
