### ISSUE TITLE
QA suite MEP du 4.12 : bug sur la selection de section dans un PAC + le contenu pas repris dans le PDF

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#318]
PAC sur lequel j'ai testé (nouveau PAC) : https://docurba.beta.gouv.fr/trames/projet-05e4a99d-1a9e-44b1-aa6f-8e6ffe263db3

Demo video (désolé je n'ai pas pu faire avec jam) : 
https://github.com/MTES-MCT/Docurba/assets/111045572/f953a06c-3fa4-4c2e-ab8b-5c82a36f6b94

**Problèmes identifiés :** 
- entre "modifier le PAC" et "consulter" : les sections que j'avais cochées ne sont pas tout le temps prises en compte
- le contenu du pdf est donc affecté : les titres des grandes sections sont repris, mais pas les sous sections qui sont pourtant bien cochées dans mon PAC. 

@nyko28 pour info car lié au issue déjà remontées.

**Comment by nyko28** [comment]
Hello,

Je vois pas de bug à ce niveau là, tu ne retrouves pas les bonnes sections cochées dans la vidéo entre l'édition et la consultation car tu as confondu le "PAC test **5.12**" (projet-05e4a99d-1a9e-44b1-aa6f-8e6ffe263db3) et le "PAC test **5.01**" (projet-e32107b0-004f-46f1-9100-90480c18b2d6)

**Comment by CeliaVermicelli** [comment]
My bad @nyko28 j'ai fait la confusion deux fois (en testant seule et au moment d'enregistrer le jam!)
