### ISSUE TITLE
[ Stonly | Form d'acquisition ] Intégration 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#320]
Hello @UngererFabien ! En amont de notre point et pour la suite : 

- tu es ajouté à l'équipe Docurba donc tu peux y avoir accès 
- voici la doc de leur centre d'aide [https://stonly.com/kb/guide/fr/comment-creer-un-trigger-7tJ3W53Xea/Steps/82157,2058851,84316](https://www.google.com/url?q=https://stonly.com/kb/guide/fr/comment-creer-un-trigger-7tJ3W53Xea/Steps/82157,2058851,84316&sa=D&source=calendar&ust=1705132704071168&usg=AOvVaw2FyNMdF5eE7CvBE4UjU8NR)

**Conditions de déclenchement/Pré-requis** : 
- lancement sur la LP ppl 
- est-ce possible de le lancer sur le mode connecté BE/CT (pas DDT) ?

**Comment by UngererFabien** [comment]
Script en prod à ce jour. A réouvrir si vous êtes bloqués.
