### ISSUE TITLE
[ Création compte Agence urba ] (Urgent) Impossible de créer un compte en tant qu'agence urba

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#321]
<img width="891" alt="Capture d’écran 2024-01-08 à 11 20 18" src="https://github.com/MTES-MCT/Docurba/assets/144041896/68d760e3-39e3-418b-836e-94d57b3bf2d3">
Hello ! Même souci que vendredi suite QA Sendgrid, pour l'accès Agence urba ça n'a pas été résolu : impossible de créer un compte 

Pour rappel, je fais une présentation demain aux agences d'urbanisme donc très important qu'ils puissent se créer un compte

Merci bcp

**Comment by Octaviedebs** [comment]
QUand mep pinguez Octavie pour qu'elle prévienne le user loic.isnard@atd31.fr

**Comment by UngererFabien** [comment]
@Octaviedebs je close, hésite pas à réouvrir si tu arrive à reproduire.
