### ISSUE TITLE
Bug : la FRP de l'élaboration du PLU d'une commune ne charge pas. Proc. en statut "précédent"

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#322]
lien de la FRP concernée : https://docurba.beta.gouv.fr/frise/9770a9ec-17cf-4f5b-9280-d4b40c16aa14

demo : https://jam.dev/c/4ae17193-d565-479c-9bdb-db80d12a5620

**Comment by lerayj** [comment]
done
