### ISSUE TITLE
Modifier les droits d'édition sur les SCoTs inter-départementaux (pour éviter les doublons)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#323]
Le morbihan (56) est concerné par 3 SCoT inter-départementaux. 
Sur Sudocuh ils sont rattachés : 
- au 29 pour le [SCoT du COB](https://docurba.beta.gouv.fr/frise/700d5a92-feb5-4ba7-a4a9-652a53c5a43e), 
- au 35 pour le SCoT de Redon 
- et au 44 pour le [Scot de Cap Atlantique](https://docurba.beta.gouv.fr/frise/024b9bf0-3b05-4768-ae8c-3ac47195ac3e), 

-> le 56 n'a pas la main pour modifier et valider les procédures (sur Sudocuh). Doc Urba permet de les modifier et de les valider. **Pour éviter des doublons, il faudrait supprimer les droits sur ces 3 SCoT pour le morbihan.**

FYI @HermanceGauth 

**Question pour l'équipe transverse et tech :** 
Quel est notre process là dessus ? Est-ce que c'est ok de compter sur les DDT pour nous remonter ces besoins au fil de l'eau et on se charge de modifier les droits au fur et à mesure ?

**Comment by CeliaVermicelli** [comment]
Cas similaire dans la Nièvre (58) :

SCoT Puisaye Forterre --> DDT 89
SCoT Moulins Communauté --> DDT 03

**Comment by CeliaVermicelli** [comment]
> Voir avec la DDT s'il y a un moyen automatique de savoir qui doit avoir la main (siège du groupement qui porte le SCoT?)

@HermanceGauth @lerayj 
Retour de Claire : l'info est trouvable dans Banatic, c'est la collectivité de référence, et donc son dpt, qui doit avoir les droits sur ces SCoT.

**Comment by CeliaVermicelli** [comment]
Le pb se posait au moment de l'enquête de fin d'année mais je n'ai plus eu cette remarque. 

Il faudrait voir si la fonctionnalité de partage de procédure sera suffisant pour les DDT dans ce genre de cas ?

**Comment by HermanceGauth** [comment]
Je comprends que le problème initial c'est qu'ils avaient trop d'accès (accès à des procédures qu'ils n'étaient pas censé valider pendant l'enquête) plutôt que pas assez d'accès (ce qui aurait effectivement pu être résolu avec le partage de procédure). Je vois par exemple que le SCoT de Redon est encore accessible dans le 35 et dans 56 alors que d'après Claire on devrait pouvoir voir grâce à Banatic que seul le 35 devrait avoir la main dessus au moment de l'enquête.
@CeliaVermicelli est-ce que tu penses que hors enquête, la DDT 56 est satisfaite de pouvoir avoir accès à ce SCoT et y ajouter des infos? Ou elle préférerai ne plus du tout avoir la main?

**Comment by CeliaVermicelli** [comment]
J'ai récemment creusé ce sujet avec le 81 et une EPCI à cheval sur le 34 -> lui ne voyait pas l'inconvénient à avoir des droits d'édition car les responsabilités de chacun étaient claires, mais le cas d'une EPCI interdépartementale est probablement plus limpide que pour les SCoT. 

Je vérifie auprès du 56 mais je crois savoir qu'ils ont le même état d'esprit que le 81.

**Comment by CeliaVermicelli** [comment]
**Retour du 56 :** 
-> ils sont surpris d'y avoir accès en mode édition mais après réflexion ils n'y voient pas d'inconvénient, pour les personnes à charge actuellement il n'y a pas de doutes sur "qui fait quoi" sur ces SCoT donc ok ! 



_Pour info, je n'ai pas pointé du doigt le fait qu'en rentrant par la commune concernée par un scot interdépartemental cela leur permettait d'accéder au tdb de l'autre dpt en cliquant sur "les retours"_ 

**Exemple** : Pénestin (56), commune concernée par le SCOT géré par CAP atlantique (44). 
Rentrée par la commune de Pénestin, click sur la FRP su SCOT en cours de CAP atlantique, retour proposé = retour sur la page de CAP atlantique puis sur le tdb d'où provient la CC CAP atlantique ("donc" celui du 44 et pas du 56)
Retour enregistré [sur notion et dans le backlog](https://www.notion.so/docurba/Retour-en-arri-re-pas-intuitif-pas-logique-depuis-une-FRP-de-commune-voir-d-tails-dans-la-carte-76e53f1bc21c46eb8507868e584dcdb8?pvs=4)

**Comment by HermanceGauth** [comment]
Ok oui intéressant de noter qu'ils peuvent passer d'un département à l'autre alors qu'ils ne devraient pas, j'avais fais cette issue à ce sujet : https://github.com/MTES-MCT/Docurba/issues/146

**Comment by HermanceGauth** [comment]
Normalement ok suite à cette issue : https://github.com/MTES-MCT/Docurba/issues/146 mais revérifier avant de close
