### ISSUE TITLE
Pb sur l'enquête suite à la MEP du 4.01 : des communes fusionnées sont "réaparrues" 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#324]
Commentaire de la Nièvre : 
> Toutes les procédures avaient été validées à mon départ (en congés). A mon retour ce jour, j'ai de nouvelles procédures à valider (qui correspondent à des communes maintenant fusionnées). Toutefois, il m'est impossible de les valider.

-> je ne veux pas test la validation des communes pour confirmer ou non le bug 
-> pas sûre de comprendre ce qu'il s'est passé et pourquoi ces communes fusionnées sont réaparrues dans la liste des communes à valider. @lerayj 
-> Même commentaire remonté du 56
Lien direct vers son enquête : https://docurba.beta.gouv.fr/ddt/58/collectivites/enquete
![Capture d’écran 2024-01-08 à 13 32 43](https://github.com/MTES-MCT/Docurba/assets/111045572/54c2b06a-a2a0-4ca6-8a6a-8aaaffa003f2)

**Comment by UngererFabien** [comment]
Lié au nouveau référentiel. J'ai retiré les commune délégué pour le moment. A voir avec @HermanceGauth si on les rajoute et dans ce cas ce qu'on fait de leur status.

**Comment by CeliaVermicelli** [comment]
ça marche merci ! 

Note à moi même, retour similaire du 81 avec la commune de Roumégoux réapparues dans l'onglet de validation. Appartient à ouvelle commune de [Terre de Bancalié](https://docurba.beta.gouv.fr/ddt/81/collectivites/81233/commune)

**Comment by HermanceGauth** [comment]
Pour l'affichage de ces communes je proposais un système similaire aux PLUi sectoriel, j'avais fait une issue ici : https://github.com/MTES-MCT/Docurba/issues/100 et repris quelques éléments dans mes commentaires ici : https://github.com/MTES-MCT/Docurba/issues/137
