### ISSUE TITLE
Enquête : bug sur les statuts procédures à valider ?

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#327]
Retour de la DDT 25 : je m'aperçois qu'il y a des communes pour lesquelles le PLU est approuvé et sont indiquées comme étant en cours : par ex: Les Auxons, Avanne-Aveney, Chaleze et encore d'autres.

lien vers l'enquête du Doubs : https://docurba.beta.gouv.fr/ddt/25/collectivites/enquete -> toutes les communes de l'onglet "communes à valider"

Est-ce que c'est un pb lié aux statuts ? même hors enquête ?

(liée à la #143 )

**Comment by CeliaVermicelli** [comment]
> Retour de la DDT 25 : je m'aperçois qu'il y a des communes pour lesquelles le PLU est approuvé et sont indiquées comme étant en cours : par ex: Les Auxons, Avanne-Aveney, Chaleze et encore d'autres.

-> update à 11h30 elle a validé toutes les communes car les statuts étaient à nouveau bons (PLUi en cours pour les Auxons = c'est bon ! + PLU opposable Les Auxons = bon aussi).

**Comment by lerayj** [comment]
je ferme puisque c'est réglé
