### ISSUE TITLE
Statut pas à jour (procédures de l'enquête)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#329]
SCoT du Grand Nevers --> la procédure de modification (procédure secondaire) est finalisée. Son caractère éxecutoire est bien enregistré mais il est toujours indiqué "en cours", alors qu'il devrait être opposable 

procédures concernée : https://docurba.beta.gouv.fr/frise/fc069cc4-8fd5-4475-86c5-b08100e5c502

Rejoint l'issue #327 et #143

**Comment by CeliaVermicelli** [comment]
FYI, la DDT (Elisa) a validé cette proc. du Grand Nevers même si le statut n'était pas correct. À garder en tête si cela pose pb pour les résultats de l'enquête ?

**Comment by UngererFabien** [comment]
@CeliaVermicelli Je close, la FDR que tu as link correspond à une procédure secondaire d'un SCOT qui est bien en approuvé.

Ca à probablement été mis à jour lors du dernier dump ;)
![Screenshot 2024-01-26 at 17 02 08](https://github.com/MTES-MCT/Docurba/assets/2676385/88945200-ca6d-4214-b7c2-5d915141b178)
