### ISSUE TITLE
Bug : FRP SCoT DDT connecté : l'évènement créé n'apparaît pas

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#331]
https://jam.dev/c/0f2a7cdf-f864-405e-a844-5e95b82dc49f

**Comment by lerayj** [comment]
@HermanceGauth on sait quel type d'event il a essayé d'ajouté ? je le retrouve bien en base mais le champ type est vide, je sais pas c'est possible. Je peux le corriger en base rapidement si tu as le type
![Capture d’écran 2024-01-24 à 18 22 22](https://github.com/MTES-MCT/Docurba/assets/5832419/9cb43568-69a3-4470-8318-463652105502)

**Comment by HermanceGauth** [comment]
A priori il l'a du coup rempli dans Sudocuh et ça a été basculé
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/18f8a7f5-6817-4105-9ffc-d033a3b5f7ed)
Par contre ce qu'il s'est passé initialement c'est qu'il a choisit autre et n'a pas mis de titre. J'ai d'ailleurs répliqué ce problème pour un test et maintenant je n'arrive plus à supprimer la pièce jointe qui se retrouve dans ressource mais pas lié à un event.

**Comment by lerayj** [comment]
done - ne devrait plu ce reproduire avec le fait de rendre le champs obligatoire

**Comment by lerayj** [comment]
J'ai manuellement mis le nom a autre en base
