### ISSUE TITLE
Procédures | L'étape de la procédure n'est jamais remplie + changer le champ attendu ? 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#332]
Hello ! 

L'étape de la procédure n'est jamais remplie (je l'ai vu sur plusieurs CT), peut-être qu'il s'agit d'un bug déjà remonté (ou d'un comportement normal ?) si c'est le cas désolée pour la redite mais du coup cf vidéo 

https://jam.dev/c/2e25aa6f-1126-4344-a98e-533f2672db69

Par ailleurs, suite à un retour utilisateur, est-ce qu'on ne pourrait pas envisagé de mettre la date de la dernière étape ajoutée peut être plutôt dans ce champ ? 
Qu'est ce qui est prévu exactement initialement (quels sont les choix possibles) ?

**Comment by lerayj** [comment]
duplicate
