### ISSUE TITLE
Géorisques | Téléchargement des données directement en GeoJson

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#333]
Actuellement les données sont en json ce qui implique ensuite de devoir les éditer en Geojson (si j'ai bien le vocabulaire).
Suite retour utilisateur et car effectivement ce n'est pas un format très intuitif, « Il serait peut-être souhaitable que le téléchargement se fasse directement en GeoJSON, pour un souci de facilité d’utilisation pour les communes »

User := Augustin Suchanek Masse Faure
A PREVENIR si MEP

**Comment by lerayj** [comment]
On renvoie un fichier json et dedans y a de la donnée organisée avec des geojson correspondantes. Pour avoir les geojson directement, il faudrait faire toute une interface pour georisques. En soit c'est un problème d'utilisation avec Georisque directement, il aurait exactement la meme problématique sur le site directement.
On peut rien y faire sans faire une surcouche très overkill pour pas grand chose, je close pour le moment.
