### ISSUE TITLE
Bug remontée Pipedrive | Champ CT ne remonte plus dans le pipe Procédures

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#335]
Lors de la création d'un nouveau compte, le nom de la CT dans le titre de l'affaire sur Pipedrive ne remonte plus 

Il s'agit de ce funnel : https://docurba2.pipedrive.com/pipeline/11/user/everyone

Tt est dans cette vidéo https://jam.dev/c/c7f8e7b5-8abf-4433-8c5f-52eddebb6dee
Regardez la en accélérer absolue haha

Note à moi même post mep : supprimer ts les doublons et renommer si valide 

Merci !

**Comment by Octaviedebs** [comment]
@UngererFabien est-ce possible de corriger cela pour la prochaine mep ? 
Merciii

**Comment by UngererFabien** [comment]
Bug lié au changement de référenciel.

**Comment by UngererFabien** [comment]
Bug à corrigé aussi dans le bot slack.
