### ISSUE TITLE
[ Intégration SM  ] Aucune données ni DU communaux/intercommunaux sur les SM suite intégration (ex ici avec le SM du Pays de Saintonge romane)

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#337]
Hello ! Suite à la prise en compte des périmètres de SCOT dans DOCURBA, qui n’était pas possible lors de la création de son compte au mois d’octobre 2023 de Sandrine SIMON =  s.simon@payssaintongeromane.fr 

elle avait donc associé son compte à l’un des EPCI du territoire du SCOT : CDC Cœur de Saintonge.

=> pouvez-vous changer l'attribution ? 

Merci bcp !

**Comment by Octaviedebs** [comment]
Pinguez Octavie lors de la mep = informer Sandrine Simon

**Comment by Octaviedebs** [comment]
hello @UngererFabien son user est bien rattaché désormais mais il n'y a aucune info

Je me trompe peut être mais en pp on devrait retrouver les DU communaux et Intercommunaux
Là il y a que le SCOT

Pour info en PJ le fichier qu'elle m'a envoyé avec ses communes et numéro insee


Merciii

<img width="828" alt="Capture d’écran 2024-01-18 à 15 31 28" src="https://github.com/MTES-MCT/Docurba/assets/144041896/d699d186-1e6e-49c8-9432-36a20b4be575">


https://docs.google.com/spreadsheets/d/1OvapDF3bjRHQxg0_ql6lEmiyyM19t2fvVMoyGp_EJ6Q/edit#gid=588600652

**Comment by Octaviedebs** [comment]
FYI @HermanceGauth pour avis sur le comportement attendu

**Comment by Octaviedebs** [comment]
Update : les données ne sont pas non plus accessibles 

<img width="828" alt="Capture d’écran 2024-01-18 à 16 23 42" src="https://github.com/MTES-MCT/Docurba/assets/144041896/76269e22-374c-4b78-a715-464308351ca0">

**Comment by Octaviedebs** [comment]
Périmètre des SM : qu'est ce qu'on affiche ? Pas prio pour le moment, à garder en backlog.

Pas de données/procédures interco et co => car pas de base nationale pour ce SM, donc dans le référentiel pas de communes associées = il faudrait aller dans la procédure SCOT en cours ou opposable pour trouver les communes du périmètre donc pas actuel.

Pas d'arbitrage fait donc rien à afficher pour le moment => arbitrage à faire 

Voir déjà avec Sandrine = 
Est-ce que le SCOt géré par le SM a ttes les communes des 3 EPCI membre du SM ou est-ce un autre périmètre ?
Périmètre de la procédure ou périmètre des membres des membres du SM ?

**Comment by Octaviedebs** [comment]
**Quickwin backlog :** 

On pourrait permettre qu'ils créent leur périmètre et qu'ils choisissent les collectivités de leur périmètre pour lesquelles ils veulent voir les données/suivre les procédures : 

- soit juste lors de la sélection du groupement dans la barre de recherche publique (version simple)

- soit à la création d'un compte pour les groupements,  (à moduler par rapport au type d'accès)


**= ça permettrait de pallier le fait qu'on a pas cette info/ ce référentiel pour les SM et qu'on risque de tte façon de mettre du temps à avoir** 

@julienzdocurba @UngererFabien

**Comment by Octaviedebs** [comment]
@UngererFabien Du coup pour ce cas précis, pour ton info comme demandé :  **le Syndicat mixte du Pays de Saintonge Romane a le même périmètre que le SCOT du Pays de Saintonge Romane**, qui regroupe les 3 EPCI membres : CDA de Saintes, CDC Cœur de Saintonge, et CDC de Gémozac.

@julienzdocurba du coup j'imagine que pour le quickwin je continue dans le fichier de feedback du coup

**Comment by julienzdocurba** [comment]
Oui ca me semble bien!

**Comment by Octaviedebs** [comment]
je ferme car dans le backlog
