### ISSUE TITLE
Bug de la fonctionnalité "comparer à la trame départementale" au niveau d'un PAC 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#338]
https://jam.dev/c/57ad2941-24cc-486a-b233-31fabc4dbb31 

(pour info, c'est ok au niveau de la trame)

**Comment by nyko28** [comment]
Hello @CeliaVermicelli, j'arrive pas à reproduire sur mes projets, je voulais essayer sur le PAC que tu as filmé mais malheureusement Jam n'a pas enregistré l'url du projet, il n'a enregistré que la trame départementale dept-8.
Est-ce que tu pourrais retrouver le lien / l'identifiant du projet que tu filmes sur Jam stp ?

**Comment by CeliaVermicelli** [comment]
Hello @nyko28 désolée pour le retard, j'ai refais un test sur un autre PAC : [lien du nouveau PAC](https://docurba.beta.gouv.fr/trames/projet-c91b3fb3-1895-4f0c-acdc-30d03819d161)

et voici la demo : https://jam.dev/c/8dbdc7d1-bff9-4051-8240-0d6607334f65

**Comment by CeliaVermicelli** [comment]
@nyko28  J'ai poursuivi en faisant des tests sur le lien de pre-prod (je comprends que c'est ce qui va passer en prod cette semaine) 
[lien du PAC 
](https://dev-dot-docurba.ew.r.appspot.com/trames/projet-5808fd70-befa-44d5-b62b-a729a8d68665)
**test 1 :** on a bien la notif d'une nouvelle section (section fantome) : https://jam.dev/c/d9b8ad5c-9b13-47b4-bd38-70b35142b926
Test 2 : la trame a été modifiée, je reviens sur mon pac pour le mettre à jour avec les changements -> j'ai la notification de modif au niveau de la section de la fiche sur le ZAN mais pas au niveau de la sous-section où il y a effectivement eu des modifications. https://jam.dev/c/1690c58a-369b-4aa8-9086-668f51af76ef
En tout cas le bouton de comparaison à la trame supérieure fonctionne sur le lien de pre prod.
