### ISSUE TITLE
[ Page de connex°/Inscript° ] Ajouter un champ d'inscription à la Lettre d'Infos non obligatoire

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#339]
Sur la page d'inscri°/connex°, il faudrait ajouter une case (pas trop petite) avec écrit : 

Cochez cette case afin de recevoir nos lettres d'informations mensuelles pour ne rien louper aux dernières actualités de Docurba.
Promis, seul un contenu court et pertinent vous sera envoyé une fois par mois 🌎

Issue liée à : cette issue https://github.com/MTES-MCT/Docurba/issues/340

FYI @CeliaVermicelli

**Comment by julienzdocurba** [comment]
On peut partir là-dessus @UngererFabien :
![image](https://github.com/MTES-MCT/Docurba/assets/147177148/6f584c97-57ff-4674-9af9-222ef3dc3200)

@Octaviedebs j'ai modifié un peu le contenu mais n'hésite pas si tu as du feedback.

On pourra en parler demain lors de l'atelier mais je pense qu'il vaudrait mieux utiliser le backlog pour ce genre de taches (c'est pas vraiment un bug, c'est un truc complètement nouveau).

**Comment by Octaviedebs** [comment]
C'est parfait pour le wording ! Juste une mini coquille « lettre » et pas « lettre**s**» !

Pour le process oui trop bien qu'on s'en reparle demain, désolée si j'ai encore fait des bêtises haha : c'est vrai que c'est assez pratique d'utiliser github pour ça - on ne pourrait pas faire une milestone Backlog ? On s'en parle demain !

**Comment by lerayj** [comment]
Done

**Comment by Octaviedebs** [comment]
Hello @lerayj @julienzdocurba j'ai rouvert l'issue mais vous préférez peut être que j'en créé une nouvelle ? 

En faisant la QA je me rends compte que l'ajout de la case est top mais uniquement sur la page inscription CT et pas agent de l'Etat : je n'avais pas précisé le public car justement pas de distinction à faire, mais est-ce que j'aurais dû ? 

Il faudrait donc qu'il y ait également cette case sur la page inscription agent de l'Etat.

Merci à vous!

**Comment by julienzdocurba** [comment]
Ok j'avais pas comprise désolé!
