### ISSUE TITLE
[ Brevo > BDD ] Renvoi des emails qui acceptent de recevoir la NL vers liste Brevo

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#340]
Cette issue est reliée à cette issue : https://github.com/MTES-MCT/Docurba/issues/339

Une fois l'ajout du champ sur la page de connexion/inscription, alors ajouter tous ceux qui acceptent de recevoir la NL et qui ont donc coché la case à la liste Brevo Inscrits à NL (homepage) : https://app.brevo.com/contact/list/id/27

Si possible ajouter une colonne « Page d'inscription » remplit en « OUI » si email provient de notre page de connex°/inscrip°.

Pour toute question, slackez moi direct merci !

FYI : @CeliaVermicelli

**Comment by CeliaVermicelli** [comment]
FYI @Octaviedebs attribut "newuser-optin" ajouté directement dans la liste de contacts : 
![Capture d’écran 2024-01-24 à 15 21 18](https://github.com/MTES-MCT/Docurba/assets/111045572/83d7c420-2334-42f9-8554-bd4c7ac5e8ee)

**Comment by Octaviedebs** [comment]
@CeliaVermicelli donc si je comprends bien ton message, l'attribut a été ajouté ? c'est un booléen et donc c'est pour informer @UngererFabien de renvoyer l'info d'une inscrip° à la NL via page d'inscrip° vers ce champ c'est ça ?

**Comment by lerayj** [comment]
Done

**Comment by Octaviedebs** [comment]
Je n'avais peut être pas assez précisé mais le comportement attendu devait être effectivement identique à celui d'avant quand il y avait l'inscription à la NL uniquement depuis la home page = c'est à dire renvoyer les contacts attributes pour qu'ils puissent arriver automatiquement dans les listes liées : 

- donc tous : dans la liste d'inscription NL générale = https://app.brevo.com/contact/list/id/27 (ça ok )
- si rôle autre = https://app.brevo.com/contact/list/id/34
- rôle service de l'état = https://app.brevo.com/contact/list/id/33
- rôle collectivité = https://app.brevo.com/contact/list/id/22
- rôle BE/agence d'urba = https://app.brevo.com/contact/list/id/21

Ce qui diffère maintenant avec la nouvelle case d'inscription depuis la page d'inscription (ET sous réserve qu'elle puisse également être mise sur la page inscription service de l'état (cf cette [issue](https://github.com/MTES-MCT/Docurba/issues/339)) ) c'est que les rôles sont donc choisis depuis ces pages d'inscription et non plus via ce [formulaire](https://64935080.sibforms.com/serve/MUIFAM2dI0BxPNy4V1aGN5dCwbta7S_BgDXC0kofDFnHE9OeqmuHQLVY5mfyv49KuHgxvko7lYQdzHJKE5dQqaUkc7E2T2lUxe4GmSF-KuPPNBAEW5-wqTzyMwtZUqjwWLuoTWIxZYe_SnwNCqO2AF1CVmk0umqkkD0oerY9w-uGeISJMcKaV5MK-_Cg5bxmfyQW9gmuWrfxo6Ym) comme c'est le cas lors d'une inscription à la NL depuis le champ de la page d'accueil 

J'espère que je suis claire - est-ce que j'aurais dû préciser ces éléments ? Effectivement pour moi cela consistait uniquement en un ajout d'un canal d'inscription qui ne devait pas modifier le fonctionnement initial mais j'aurais peut être dû apporter plus de précisions. 

Merci !

**Comment by UngererFabien** [comment]
J'ai mis à jour avec les listes. Je le passe en preprod.

**Comment by Octaviedebs** [comment]
si agence d'urba ça va bien dans NL Générale mais pas dans BE/agence urba
si autre ça va bien dans NL Générale mais pas dans autre
