### ISSUE TITLE
FRP (pas urgent) : "event clefs" et event "invalide", quel est le comportement souhaité ?

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#344]
voir demo : https://jam.dev/c/7a0bcc57-1bcc-485c-bad2-dcd504e4fc3e

Retour du 83 à ce sujet : 

> Par contre j'ai du mal à comprendre à quoi sert la rubrique intitulée : "évènements clés" ?
> Qu'est-ce qui détermine que la date de début d'enquête publique est un évènement clé mais que la délibération d'approbation n'en est pas un ?

-> à ça je lui ai répondu que les delib d'approbation étaient bien des event clefs et elle m'a pointé ce cas particulier : 

> La délibération d'approbation du 10/07/2013 n'apparait pas comme "évènement clé", d'où mon interrogation, mais je suppose que c'est parce que cette délibération, partiellement annulée, apparait en invalide dans Docurba.

**Comment by HermanceGauth** [comment]
J'ai déterminé la liste des event clé de manière assez arbitraire ici : https://docs.google.com/spreadsheets/d/1zgC0vMOh-VPxUeboYz8gi0Tz5Xs5yxDdno1gUi26C9E/edit#gid=1392334617 dans la colonne K
Dans ce cas particulier effectivement c'est potentiellement dû au fait que l'event est invalide, à vérifier avec @lerayj

**Comment by lerayj** [comment]
@julienzdocurba bosse avec @HermanceGauth & Francois pour la nouvelle version de cette problematique - je close pour le moment, potentiellement a réouvrir plus tard
