### ISSUE TITLE
bug sur le chargement des page EPCI/commune et FRP : il faut parfois actualiser la page pour que les info terminent de charger.

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#346]
https://jam.dev/c/5fd96da8-d6c1-4ae3-b15f-eb3aeb9c8b79

Retour du 81 : "ça mouline" "le site est très lent aujourd'hui" 
Même retour du 47 jeudi et vendredi de la sem dernière

**Comment by CeliaVermicelli** [comment]
https://jam.dev/c/a82d2735-1a4e-40b5-8c7f-52fb28f5ce12 

même problème depuis la recherche publique.

**Comment by lerayj** [comment]
done.
