### ISSUE TITLE
Affichage des procédures secondaires de SCoT : le chemin est un peu "tordu"

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#347]
https://jam.dev/c/9aac7733-8c48-4fb8-9481-74cfeda4659f

Le menu déroulant des proc secondaire n'est pas là on on l'attend à première vue.

**Comment by HermanceGauth** [comment]
Maintenant qu'on a bien tous les groupements dans le référentiel je ne sais pas si c'est toujours justifié de différencier l'affichage de la liste des SCoT de l'affichage EPCI/communes. En tout cas si on peut je pense que ce serait bien d'uniformiser et ça résoudrait le pb évoqué
