### ISSUE TITLE
[ Accès BE/CT ] 1ère connexion = Atterrissage sur la page de recherche territoires et pas sur le tableau de bord en mode connecté

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#350]
https://jam.dev/c/3d5dfa20-69c1-4797-a0d9-153bf00001b6

Quand je me connecte pour la 1ère fois, cf vidéo, et que je clique sur le lien de connexion j'arrive sur la page recherche de territoires et je dois alors cliquer sur Ma collectivité en haut à droite,  non pas directement sur la page tableau de bord ma collectiivté

j'ai testé lors d'une 2ème connexion et là ça marche bien

**Comment by UngererFabien** [comment]
Je passe le fix en preprod. Le signup renvoit bien sur la page de la collectivite.
