### ISSUE TITLE
GPU - export du tableau des "arrêté de lancement" et "prescription" déposés dans Docurba avec url de l'acte

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#351]

**Comment by lerayj** [comment]
@HermanceGauth c'est une demande d'extract ? Pas sur de comprendre l'action a faire.

**Comment by HermanceGauth** [comment]
@UngererFabien doit voir de quoi je parle normalement mais en gros oui c'est avoir un extract de la liste des actes "arrêté de lancement" et "prescription" déposé chez nous avec dans une colonne l'URL correspondant. On l'avait dans metabase mais l'url était pas remonté. On veut initier un échange avec le GPU où on leur enverrai notre fichier tous les mois et eux également en attendant d'éventuelles API. Pour exemple le fichier que l'IGN nous a envoyé.
[data-1702995120404-1.csv](https://github.com/MTES-MCT/Docurba/files/14049553/data-1702995120404-1.csv)
