### ISSUE TITLE
[ QA LP ] Docurba est coupé en haut à gauche même sur un grand écran

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#352]
![Capture d’écran 2024-01-16 à 12 18 12](https://github.com/MTES-MCT/Docurba/assets/144041896/747bfe45-eb66-420a-96ba-085ce775a6f7)

@UngererFabien @julienzdocurba

**Comment by julienzdocurba** [comment]
Je n'arrive pas à reproduire de mon côté et je vois pas trop ce que ca pourrait être. Ca te le fait aussi @UngererFabien ?

**Comment by Octaviedebs** [comment]
plus de précisions si besoin https://jam.dev/c/cea88214-e6cd-483e-9e0d-cc3c5932794a

**Comment by julienzdocurba** [comment]
Oui ca me le fait aussi maintenant (pas sûr de comprendre pourquoi ce n'était pas le cas avant). Je pense que c'est parce qu'il y a une width fixe de 114px sur le conteneur du titre.

**Comment by nyko28** [comment]
Hello, j'arrive à reproduire en preprod mais pas en local. Je sais pas trop pourquoi mais c'est un comportement de Vuetify (la lib de composant qu'on utilise). J'ai refait le composant du titre sans la lib, ça devrait le faire mtn 👍

**Comment by Octaviedebs** [comment]
merci bcp ! donc si je comprends bien ce sera le cas à la prochaine mep
