### ISSUE TITLE
[ QA LP ] Espace un peu trop grand entre barre de recherches de territoires et « Un accompagnement à chaque étape » 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#354]
C'était peut être le comportement attendu mais l'espace me parait un chouille grand 

![Capture d’écran 2024-01-16 à 12 23 53](https://github.com/MTES-MCT/Docurba/assets/144041896/be1c1046-edb1-4450-82cd-8dad4aad42f0)

@julienzdocurba

**Comment by julienzdocurba** [comment]
Nan l'espace est correct là dessus! Je vais ouvrir une autre issue pour un espacement en haut par contre.
