### ISSUE TITLE
Landing page: Manque d'espace entre header et titre

### ISSUE THREAD

**Issue by julienzdocurba** [MTES-MCT/Docurba#355]
L'espacement entre le header est le titre de la landing page est d'environ 110px en ce moment sur dev:
<img width="976" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/0fc9136b-153d-46d2-9519-a7600a0d64b8">

Je pense qu'on pourrait l'augmenter d'environ 60px (sur les maquettes l'espacement n'est pas calculé tout à fait de la même facon):
<img width="1599" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/7695414e-3a4c-44de-9480-7b25170e603a">

**Comment by nyko28** [comment]
Hello, j'ai fais en sorte que ce soit calculé de la même façon en prenant en compte les mêmes espacements et padding que la maquette. Ca devrait être identique à la prochaine MEP ✅
