### ISSUE TITLE
QA_Cadre juridique et PDF : caractères spéciaux dans le texte

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#356]
Hello @HermanceGauth première fois que je remarque ça : 
(dans le CJ - > loi climat et résilience) 
[Lien du  PAC testé](https://dev-dot-docurba.ew.r.appspot.com/documents/projet-00f37d6d-76a0-4d7b-9f6d-45cce893fdbe/pac) (nouveau PAC créé pour la QA - mais même remarque pour les PAC déjà existants) 

![Capture d’écran 2024-01-16 à 12 44 51](https://github.com/MTES-MCT/Docurba/assets/111045572/ffbdad26-47af-4200-885a-b48e2c302dc5)

**Comment by HermanceGauth** [comment]
Je vois rien de spéciale sur ma trame main mais j'ai supprimé et refait ces espaces
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/7e298a2b-5af0-439c-853e-bc9c67f8bf34)
