### ISSUE TITLE
Event FRP : changer le copy explicatif de la différence entre la visibilité des event publique et privée 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#357]
**Phrase actuelle :** _"Si vous voulez uniquement afficher cet évènements aux agents de l'Etat et acteurs de collectivités, choissez 'Privé’."_ 
-> elle laisse penser que n'importe quelle collectivité aura accès aux event privé et on exclus le BE + il y a une coquille. 
![Capture d’écran 2024-01-16 à 10 45 38](https://github.com/MTES-MCT/Docurba/assets/111045572/d8464187-33a1-4ac6-85bf-1ce057a5b4bd)

### **à remplacer par :** 
_Les événements privés sont visibles uniquement par la DDT et la collectivité en charge de la procédure, ainsi que par le bureau d’études le cas échéant._

**Comment by lerayj** [comment]
Done
