### ISSUE TITLE
Cas Brenon (83) : le statut de la CC est "opposable" alors que refus d'apporbation de la part du prefet 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#363]
Demo : https://jam.dev/c/e0080cc6-f80c-469f-8880-d53de6457057
Proc. concernée : https://docurba.beta.gouv.fr/frise/4d1440ae-02cf-4793-9145-9ee9942a691d

Retour de la DDT : 

> commune de Brenon (83022).Cette commune est en élaboration de Carte Communale, elle vient de l'approuver mais de son côté le Préfet a refusé d'approuver dans l'attente que la commune prenne en compte ses observations.Je pense avoir noté correctement ces éléments dans SuDocuH, mais quand je vais dans Docurba, les mêmes éléments sont repris mais avec l'annotation en vert : OPPOSABLE, ce qui n'est pas le cas tant que le Préfet n'a pas approuvé la procédure, pour le moment cette commune est toujours soumis au Règlement National d'Urbanisme.”

**Comment by UngererFabien** [comment]
@lerayj Est ce que ça vient du dump ou d'un event rajouter dans Docurba qui n'a pas mis à jour le status ?

**Comment by CeliaVermicelli** [comment]
@UngererFabien toujours le même pb de statut pour Brenon (83)

**Comment by Octaviedebs** [comment]
nom ok et statut bien à jour pour la CC

**Comment by CeliaVermicelli** [comment]
ddt prévenue
