### ISSUE TITLE
Bug au sign in : impossible de créer un compte ; email déjà utilisé mais procédure de mdp oublié n'aboutit pas

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#364]
Hello, surtout @julienzdocurba 
Rien qui paraisse alarmant, mais ça me parait important de te montrer ce genre de retour. 
Contexte : c'est une personne de ddt que j'ai orienté directement avec le lien de login et en lui disant clairement qu'il fallait se créer un compte agent de l'état et voici son email : 
(peut-être que l'on peut réduire l'espace entre "inscription et connexion" et "vous représenter" ?
> Bonjour,
> Quand je clique sur le lien que vous m'avez envoyé j'accède à l'écran ci-joint.
> Sur cet écran dans la partie "services de l'Etat" il n'y a pas de lien pour aller plus loin.

![Sans titre 1](https://github.com/MTES-MCT/Docurba/assets/111045572/622a0c94-4520-49e9-98d3-581189361445)

**Comment by julienzdocurba** [comment]
Oui c'est un gros bug, le footer ne devrait pas recouvrir le contenu de la page comme ca.

**Comment by CeliaVermicelli** [comment]
mmm Ok je pensais que c'était juste qu'il n'avait pas descendu l'écran - je n'ai pas ce pb que ce soit sur mon PC ou sur un écran plus grand !

**Comment by julienzdocurba** [comment]
Oui il ne devrait pas avoir à scroller là, les boutons sont dans le viewport c'est juste que le footer les recouvre.

**Comment by CeliaVermicelli** [comment]
Hello @UngererFabien, je complète le retour de ce même utilisateur qui n'arrive pas à se connecter depuis jeudi dernier

> J'ai essayé sur google chrome et sur mon smartphone.
> Voici à chaque fois la réponse de la plate forme.
> Quand j'essaie de créer un compte il m'est dit qu'il existe déjà un compte enregistré avec cette adresse mail ([patrice.cereza@aude.gouv.fr](mailto:patrice.cereza@aude.gouv.fr))
> Quand je fais mot de passe oublié je ne reçois pas de lien pour réinitialiser mon mot de passe.
> Voici les démarches faites à ce jour sans succès.

-> pour info je ne trouve pas cet user dans la liste à laquelle j'ai accès sur Metabase, donc on ne devrait pas lui bloquer la création de compte.

**Comment by julienzdocurba** [comment]
@CeliaVermicelli est-ce que c'est aussi parce que l'utilisateur n'arrive pas à voir les boutons de connexion?

**Comment by CeliaVermicelli** [comment]
@julienzdocurba je ne suis pas certaine car s'il arrive quand même jusqu'au moment où on lui dit qu'il a déjà un compte (alors que non d'après la liste que j'ai sur metabase) à voir ce qu'en dit Fabien.

**Comment by julienzdocurba** [comment]
Ah oui ok du coup c'est probablement un problème / bug différent.

**Comment by lerayj** [comment]
[patrice.cereza@aude.gouv.fr](mailto:patrice.cereza@aude.gouv.fr) n'existe pas en base - c'est bizarre - certain qu'il a créer un compte déjà ?

**Comment by CeliaVermicelli** [comment]
@lerayj le pb c'est justement qu'il n'en n'a pas mais que les msg d'erreur lui dise le contraire : "email déja utilisé,connectez-vous" et quand il fait "mdp oublié" (au cas où) -> il ne se passe rien :/ 

Il vient de me dire qu'il va essayer sur son pc perso

**Comment by UngererFabien** [comment]
Hello ! C'est un user qui s'est connecter en Aout. Pour une raison que j'ignore il n'avait pas de profile alors qu'il était bien validé sur la trame du 11. 

@CeliaVermicelli je lui ai créer un profile. Il devrait pouvoir essayé de se connecter avec son mdp si il s'en souvient. Sinon l'email de récupération de mdp devrait fonctionner avec son nouveau profile.

Je close, mais à réouvrir si jamais il reste bloquer on peut suprimer son utilisateur et lui proposé de se re inscrire avec un nouveau mot de passe.

**Comment by Octaviedebs** [comment]
Célia est off mais je me le suis notée pour son retour elle vérifiera avec le user yes !
