### ISSUE TITLE
[New notif slack à créer] : être prévenus lorsque des CT/BE sont actif sur des FRP - reste à mettre nom de la collectivité

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#365]
Hello, 

Notre objectif est de pouvoir prévenir les DDT lorsque des CT/BE sont actifs sur les FRP. (c'est une dde des DDT + un besoin d'assurer le déploiement de "cycles complets")

### Proposition : 
**À l'image du canal "bot-admin", on voudrait être notifiées dans le **nouveau canal créé "ajout_event_ctbe"** dès qu'une collectivité ajoute un evenement dans une FRP.** 

Nom du canal slack : ajout_event_ctbe

**Champ utiles à faire ressortir dans la notification :** 

- [x] Nº du dpt 
- [ ] Nom de la collectivité
- [x] Intitulé de l'event ajouté
- [x] Nom de la personne qui a ajouté l'event
- [x] Email de la personne qui a ajouté l'event
- [x] Type d'user qui a ajouté l'event : CT ou BE.

FYI Octavie

**Comment by Octaviedebs** [comment]
J'ajouterai surtout le **nom et type de la procédure concernée** + éventuellement lien vers la FRP (et ensuite on peut se débrouiller pour retrouver cette FRP en mode connecté en se créant un compte)

**Comment by Octaviedebs** [comment]
message fabien = bien noté je pense que ça sera surtout une view dans le back office super admin qui arrivera plus vite que prévus

**Comment by UngererFabien** [comment]
Dans la notif, le titre de la notif est le type d'event. J'ai mis un lien vers la frise pour avoir direct toutes les autres infos sur la procedure et l'email et le poste de l'utilisateur.

**Comment by Octaviedebs** [comment]
**Mettre la collectivité concernée par le DU**

**Comment by CeliaVermicelli** [comment]
Testé - totu est ok je close :)

**Comment by Octaviedebs** [comment]
Il y a un bug 
<img width="972" alt="Capture d’écran 2024-07-23 à 14 56 06" src="https://github.com/user-attachments/assets/434c4c97-03c8-4062-977a-bbe9e687089f">

**Comment by UngererFabien** [comment]
Je close c'est corrigé en prod
