### ISSUE TITLE
[ Bug FRP ] Fichier PDF ne charge pas dans les event sudocuh

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#366]
https://jam.dev/c/9ff58b0b-7db9-49fa-864d-df1ecdd411a9

Hello ! Impossible d'ouvrir les fichiers joints aux events sudocu :/ merci bcp !

**Comment by lerayj** [comment]
Il faudrait qu'on redemande les pièces jointes upload sur Sudocu pour l'année 2023

**Comment by UngererFabien** [comment]
J'ai envoyé un mail à Dominique.

A suivre ;)

**Comment by lerayj** [comment]
Toujours en attente il faut relancer dominique

**Comment by Octaviedebs** [comment]
Yes c'est assez bloquant j'avoue ! j'avais refait un jam parce que je n'arrivais pas à retrouver cette issue 

au cas où => https://jam.dev/c/bf5d969b-7e6c-427f-84ce-ec55c57c5fcb

**Comment by HermanceGauth** [comment]
@Octaviedebs je close car normalement c'est bon

**Comment by Octaviedebs** [comment]
Sauf erreur de ma part ça ne fonctionne pas au niveau des PJ dans la barre latérale droite https://jam.dev/c/450dc0ea-4738-4cff-aa47-3f0852d90b07 

En gros c'est ok quand la PJ Sudocuh est dans l'event de la FRP > mais pas dans la barre latérale droite

**Comment by Octaviedebs** [comment]
géré ailleurs https://github.com/MTES-MCT/Docurba/issues/404 
https://github.com/MTES-MCT/Docurba/issues/622
