### ISSUE TITLE
[Ajout procédure secondaire ] Le titre doit préciser la procédure secondaire et non pas uniquement la procédure parente 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#371]
https://jam.dev/c/dc848fd1-44a6-4b10-b5bd-16264499dedb

Lorsqu'on ajoute une procédure secondaire, il faudrait que dans le titre il y ait le même titre que lorsqu'on créé cette nouvelle procédure . Ex : Modification du PLU de Fixem

**Comment by lerayj** [comment]
duplicate #297
