### ISSUE TITLE
[ Ajout procédure secondaire ] Ne pas suggérer la possibilité d'ajout d'une procédure secondaire dans une procédure secondaire

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#372]
Lorsque j'ajoute une procédure secondaire, il ne faudrait pas qu'on me suggère d'ajouter une procédure secondaire car ce n'est aps très logique . EN revanche, si je suis sur la FRP d'une PP alors oui c'est logique qu'on nous suggère d'ajouter une procédure secondaire, mais pas lorsqu'on est déjà sur une procédure secondaire : sauf s'il peut y avoir une procédure secondaire d'une procédure secondaire mais je ne crois pas 

<img width="821" alt="Capture d’écran 2024-01-18 à 15 03 29" src="https://github.com/MTES-MCT/Docurba/assets/144041896/58554c40-9111-4b8b-836e-de94ec05e928">

**Comment by lerayj** [comment]
Done
