### ISSUE TITLE
[ Bug déconnexion ] Temps de latence très long + pas de prise en compte de la déconnexion au clic

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#373]
Plusieurs fois, cela m'arrive sur ≠ accès de devoir m'y prendre à plusieurs fois avant de pouvoir réussir à me déconnecter vraiment
Voir ces vidéos 

https://jam.dev/c/2bfae011-ad44-48d6-b33e-78c7cc52fd5d
https://jam.dev/c/4f96f914-007e-44eb-85e5-d30ace8e49fd

**Comment by lerayj** [comment]
Done
