### ISSUE TITLE
[Recherche publique] Ne pas obliger l'écriture de l'accent dans l'orthographe d'une CT pour effectivement la voir apparaitre dans le menú déroulant

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#374]
Exemple avec “Châteauneuf-du-Faou” dans le 29 : en tapant Chateauneuf (sans accent sur le “a”) il ne trouve pas -> afficher toutes les EPCI correspondantes peu importe les accents. 
https://jam.dev/c/bf594d04-8522-450b-81bd-e8d28b2efba8 

Pour info, cette condition à bien été prise en compte côté DDT connectée et la recherche par CT dans le tableau de bord.

**Comment by lerayj** [comment]
Done
