### ISSUE TITLE
QA partage PAC : le partage d'un seul PAC semble s'appliquer à l'ensemble des PAC de ma liste 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#376]
video : les premières 40s secondes seulement : https://jam.dev/c/ceb1a6a5-b659-41ba-917c-42f33bd73499

**Comment by nyko28** [comment]
La liste n'est pas rafraichie car les requêtes sont bloquées : lié à l'issue #386
