### ISSUE TITLE
QA partage PAC : ajouter un message éphémère de partage du PAC réussi

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#379]
demo : https://jam.dev/c/6d0595d1-ce07-4896-ac29-c42676fa9c41

Message en vert qui apparaît quelques secondes seulement. 

Copy du message par exemple : 
_Partage réussi ! La personne vient de recevoir un e-mail l'invitant à consulter le PAC en ligne._

**Comment by CeliaVermicelli** [comment]
FYI @julienzdocurba

**Comment by julienzdocurba** [comment]
Oui on avait ca dans les maquettes qu'on avait faites rapidement: 
<img width="975" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/217492ac-a0fa-4275-bfcb-fc1edfca9771">

Mais en réalité je pense qu'on peut limite fermer cette issue comme on est en train de bosser sur le redesign du partage en ce moment.
