### ISSUE TITLE
Partage du PAC en mode edition : comportement attendu pour les personnes qui n'ont pas de compte Docurb? 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#381]
Hello, petite video hors jam car l'extension ne me laisse pas enregistrer mon desktop.
As-tu des recommandations pour le parcours @julienzdocurba ? 
Dans l'email qui me notifie qu'on m'a partager un pac pour l'éditer on pourrait aussi pour l'instant juste rajouter un msg du type _"si vous n'avez pas de compte Docurba pensez à en créer un afin de pouvoir accéder au PAC partagé avec vous"_

https://github.com/MTES-MCT/Docurba/assets/111045572/5d40dd07-ec4a-43a3-89c9-fea5bba075f8

**Comment by julienzdocurba** [comment]
Je pense que le mieux serait rediriger directement sur le PAC avec un écran de connexion si l'utilisateur n'est pas déjà connecté. Mais on va surement voir tout ca avec le travail sur les droits d'accès donc je pense qu'on peut fermer l'issue en attendant.

**Comment by CeliaVermicelli** [comment]
FYI, une mention dans l'email automatique reçu (mode lecture et mode edition) a été ajouté pour palier pour le moment à la redirection : 

> 🆕 Vous n'avez pas encore de compte Docurba ? Pensez à demander votre accès pour pouvoir accéder au PAC. 

-> je ferme l'issue.
