### ISSUE TITLE
Erreur de ma part dans l'harmonisation des trames - trame du 08

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#385]
@nyko28 Peux-tu supprimer la section qui comporte le point final dans la section "politiques publiques s'appliquant sur le territoire" stp ? 
trame : https://docurba.beta.gouv.fr/trames/dept-8 

(je me souviens que c'est le dernier titre que j'ai modifié la semaine dernière et je devais être très contente de mettre un point final à cette harmonisation manuelle ^^... )
J'ai vérifié toutes les autres trames et c'est la seule concernée. 

![Capture d’écran 2024-01-22 à 18 13 50](https://github.com/MTES-MCT/Docurba/assets/111045572/f6702225-2e39-484c-89b6-2330c6c6f3b4)

**Comment by nyko28** [comment]
Done ✅
