### ISSUE TITLE
Lenteur du site + besoin d'actualiser régulièrement la page pour que le chargement aboutisse

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#386]
Hello, j'essaye de reproduire ce bug observé par @HermanceGauth et @Octaviedebs également 
_Jam réalisés sur le lien de prod._

Au niveau de l'onglet "Mes PACs" : https://jam.dev/c/228187ea-e35c-4945-802d-ed9c66ddda05

Au niveau de la page ECPI/communes : https://jam.dev/c/f30829a3-fb1d-44e8-b7f3-3752520a71f0

**Comment by nyko28** [comment]
Hello,
J'ai eu le problème aussi. Je pense que c'est lié à notre intégration de Stonly, qui bloque les requêtes aléatoirement au bout d'un moment. J'ai trouvé une façon de reproduire, il faut changer d'onglet et de revenir sur l'onglet Docurba pour que les requêtes soient bloquées.

On vous tient au courant :)

**Comment by CeliaVermicelli** [comment]
Nouveau retour que je rajoute ici si jamais ça peut aider (j'imagine qu'ils s'agit du même problème)

Deux personnes pour qui le chargement des données depuis la recherche publique n'aboutit pas, je n'arrive pas à reproduire le bug car pour moi ça fonctionne (un peu lent et parfois besoin d'actualiser la page mai ça finit toujours par arriver), [voici la demo](https://jam.dev/c/94221abf-518b-4544-91c9-a9c06344d066) du parcours qui leur pose pb.

Info supplémentaire :
> Le navigateur utilisé est Firefox, en version 115.02, la dernière autorisée par le ministère de l'intérieur, responsable des SIC sur le périmètre dont nous assurons la maintenance.

(ma version Firefox 120.02 fonctionne parfaitement)

FYI @Octaviedebs

**Comment by lerayj** [comment]
@nyko28 A punaise bien vu, effectivement ca a commencer a apparaitre avec Stonly. C'est improbable encore cette histoire.

**Comment by lerayj** [comment]
done.

**Comment by Octaviedebs** [comment]
Ok top merci - donc besoin d'attendre la mise en prod' pour que ce soit effectif cette correction c'est ça ?

**Comment by CeliaVermicelli** [comment]
Je ne sais pas si c'est trop tard mais eventuellement pour la suite, j'ai eu plus d'info via téléphone, je cite : 
"Leur proxi orion bloque car c'est une requête multisite. "
La personne a prévu de nous envoyer une capture d'écran de l'erreur, il citait en plus "Crossed origin request" avec la mention d'un site qui contient "supabase"

**Comment by Octaviedebs** [comment]
Mess de fabien : 

Hum ... Vu l’erreur je suis pas sur de pouvoir faire quelque chose ... Je vais regarder mais je n’ai pas beaucoup d’espoir.

Ca peut être une extention ou un VPN qui bloque des request mais ça ne devrait pas empécher d’utiliser le site si ça bloque juste stonly.

**Comment by Octaviedebs** [comment]
@UngererFabien tu nous diras ce qu'il en est et peut être a minima expliquer un peu le pb qu'on ait des éléments de langage pour répondre aux users concernés dont je nous remets les emails ici pour follow-up

georges.ferret@rhone.gouv.fr
justine.sperandio-martinez@auvergne-rhone-alpes.gouv.fr

**Comment by Octaviedebs** [comment]
Hello petit up sur ça pour qu'on puisse tenir informés les users quoique ce soit le résultat merci !

FYI @CeliaVermicelli

**Comment by CeliaVermicelli** [comment]
Pour info moi je n'ai plus de problème avec ça depuis mon retour de vacances le 1er février
