### ISSUE TITLE
[ Metabase ] Accès impossible 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#388]
ex ce dashboard : https://docurba-metabase.osc-fr1.scalingo.io/dashboard/2-bizdev-suivi-hebdo

ou avec la page statistique : https://docurba-metabase.osc-fr1.scalingo.io/dashboard/6-page-statistiques-de-docurba-en-cours

https://jam.dev/c/d036bd90-6cb5-4398-aad2-f90994ba19fa

message erreur sur une question du dashboard bizdev  ![Capture d’écran 2024-01-23 à 15 59 46](https://github.com/MTES-MCT/Docurba/assets/144041896/c01a5a5a-c613-4a1b-aa61-c17824d824b0)

message d'erreur quand je recharge la page stat' : https://jam.dev/c/56861c0d-a928-4ae2-9cd4-5c769c9e6a3d

![Capture d’écran 2024-01-23 à 16 03 44](https://github.com/MTES-MCT/Docurba/assets/144041896/348b8140-a813-4f2c-94c0-aacb0ece3db9)

**Comment by CeliaVermicelli** [comment]
FYI j'ai aussi les même pb depuis hier

**Comment by Octaviedebs** [comment]
Fabien a répondu dans un thread slack, c'est lié à la migration matomo ;) https://docurba.slack.com/archives/C03MM1AD199/p1706024211547509

**Comment by UngererFabien** [comment]
Hello ! Ce n'est pas lié à Matomo mais à une mise à jour des servers de la BDD. On est en contact avec le support pour résoudre de le problème.

**Comment by UngererFabien** [comment]
Good depuis la mise à jour base de donnée.
