### ISSUE TITLE
Sendgrid & partage du PAC par email : mise à jour du template 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#390]
Hello @UngererFabien, 

Je remarque : 
- Les emails reçus au moment du partage du PAC correspondent aux anciens emails 
- le champ {{ collectivité }} n'est pas remonté. 

-> Quand un PAC est partagé en mode **lecture**, il faut envoyer [cet email ](https://mc.sendgrid.com/dynamic-templates/d-daf95559ce09481ca8d42d6e026fb9f3/version/091b6304-9a9c-4c6c-8f87-8980bfa05667/editor)(nouveau template)
-> Quand un PAC est partagé en mode **édition**, il faut envoyer [cet email ](https://mc.sendgrid.com/dynamic-templates/d-bdd5ef31891546bcb6401fb6cdf2d391/version/e561edea-0d62-4f94-aad1-e1ac8ad5ccb2/editor)(nouveau template)

Pour rappel, cela fait écho avec l'issue #145  et [ton commentaire](https://github.com/MTES-MCT/Docurba/issues/145#issuecomment-1872159973) au sujet des emails liés au partage

**Comment by UngererFabien** [comment]
Le boulot est fait mais il faut le test en activant les nouvelles versions sur sendgrid. Je ferais des test avant de le passé en prod.

**Comment by CeliaVermicelli** [comment]
Les nouveaux emails sont bien reçus mais il manque certains champs qui ne sont pas remontés : 

**Quand un PAC est partagé en mode lecture**, [cet email est reçu](https://mc.sendgrid.com/dynamic-templates/d-daf95559ce09481ca8d42d6e026fb9f3/version/091b6304-9a9c-4c6c-8f87-8980bfa05667/editor) mais il manque : 
-> le champ "numéro ou nom du département"
![Capture d’écran 2024-04-30 à 16 15 15](https://github.com/MTES-MCT/Docurba/assets/111045572/135ccbf5-5c59-4305-b429-48c80f8cc48c)


**Quand un PAC est partagé en mode édition**, [cet email est bien reçu ](https://mc.sendgrid.com/dynamic-templates/d-bdd5ef31891546bcb6401fb6cdf2d391/version/e561edea-0d62-4f94-aad1-e1ac8ad5ccb2/editor) mais il manque : 
-> le champ "numéro ou nom du département"
-> le champ "nom de la collectivité"
![Capture d’écran 2024-04-30 à 16 18 54](https://github.com/MTES-MCT/Docurba/assets/111045572/bb2c900b-a6ef-4ae0-8b6e-ed929fa0f78e)
