### ISSUE TITLE
[Parcours DREAL] : l'accès a des comportements inattendus et donne accès à une DDT d'une autre région

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#394]
Hello, 

On en parlait dans cette issue #45 
**Est-ce que le quickwin pourrait être de supprimer l'onglet "mes PAC" pour les comptes DREAL ?** 

-> des comportements surprenants sont observés en actualisant la page seulement, ça peut paraitre minime mais on le fait bcp en ce moment :) 

https://jam.dev/c/56daa3b8-2e80-40a3-98f7-afe4d73424cf

**Comment by UngererFabien** [comment]
J'ai caché le bouton "Mes PACs" pour les Dreal et j'ai pris note du blocage à faire sur la trame régionale.

**Comment by CeliaVermicelli** [comment]
hello @UngererFabien, je vois toujours l'onglet Mes PAC côté DREAL

https://jam.dev/c/334e21cb-0153-4515-b688-b84a40f3d083
