### ISSUE TITLE
[FRP] (Important) Events privés visibles et ajout d'event possibles depuis n'importe quel compte BE/CT même si pas sur le territoire concerné

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#395]
Lors d'une démo avec un utilisateur, je me suis rendue compte que : 

- l'utilisateur se connecte sur Docurba depuis son accès BE/CT pour le département X
- puis, depuis son accès, retourne dans la barre de recherche public et cherche un autre département Y
- **alors il peut complètement accéder à la FRP de ttes les procédures + voit les events privés + peut ajouter des events dessus ALORS qu'il n'est donc initialement pas du tout rattaché à ce département Y** 
= il devrait du coup voir comme l'accès public pour cette collectivité qui ne le concerne pas

J'ai fait une belle pirouette en démo haha

Sauf si j'ai loupé un élément ce n'est pas du tout le comportement attendu je pense

Merci ! @UngererFabien 
FYI @HermanceGauth 

Tout est dans cette vidéo :
https://jam.dev/c/6b3e8250-dc4f-41de-bf11-0418c4a191ed

**Comment by UngererFabien** [comment]
Je passe un fix en preprod. Un utilisateur collectivité ne peux ajouter/voir que les events de sa collectivité ou des collectivité de son EPCI si s'il est enregistrer avec un code siren d'EPCI.

**Comment by Octaviedebs** [comment]
**Deux soucis identifiés : 
- les events privés sont toujours visibles depuis n'importe quel accès** (mais on ne peut pas les modifier) : https://jam.dev/c/c574b072-2fe3-400f-8b7e-0f537b936a39
**- les events ne sont plus modifiables depuis le bon accès lié à cette CT** : https://jam.dev/c/07c89b7f-1095-429e-a42c-d3fc834c24d7

**Comment by UngererFabien** [comment]
Deux choses à régler:
1. La majorité des évents sont marqués comme privés dans la BDD. Donc je pense qu'il faut rajouter une règle pour évité d'avoir les FRP complètement vide.
2. Je n'ai pas touché à l'édition des events, juste leur affichage. Aujourd'hui la règle est la suivante. Les events Sudocuh ne sont pas modifiables. Les DDT peuvent éditer n'importe quel event Docurba. Un utilisateur collectivité ne peu modifier que les events qu'il a lui même créé.

**Comment by HermanceGauth** [comment]
@UngererFabien Pour le point 1, j'y avais répondu dans cette issue : https://github.com/MTES-MCT/Docurba/issues/243
= On met en public les events de Sudocuh qui sont des event clés pour ne pas avoir des FRP publique vide.
@lerayj l'avait bien en tête, il en reparlait ici : https://github.com/MTES-MCT/Docurba/issues/248
en disant que c'était dépendant du travail du travail sur le match des event Sudocuh+Docurba. J'ai mis les ID en décembre mais j'imagine que ça dépendait aussi du boulot sur les trigger?

**Comment by Octaviedebs** [comment]
@UngererFabien je te résume à nouveau les soucis ici avant notre point = 

- dans la [vidéo](https://jam.dev/c/c574b072-2fe3-400f-8b7e-0f537b936a39) que j'ai mise plus haut : quand on est connecté pour un territoire A,  les events privés (qui ne sont bien **pas issus de sudocu**) sont  donc encore **visibles** en allant sur un territoire B (depuis la barre de recherche)

- dans cette [vidéo](https://jam.dev/c/12f3d916-a33d-42b1-9dd2-8acd3be5d7b3) : je me suis bien connectée avec l'email que j'ai utilisée pour ajouter ces events (je l'avais notée dans un fichier octavie.dbs+lons@docurba.beta.gouv.fr) - on voit bien qu'il y a en plus désormais un problème de modification des events privés (encore une fois ils ne sont pas de sudocu) = je suis connectée en tant qu'employée de mairie pour la CA ECLA, je vais sur une FRP, et je peux plus modifier un event qui avait été ajouté **par ce user** 
_**Un utilisateur collectivité ne peu modifier que les events qu'il a lui même créé.**_ = pour ça, tu prends bien l'email de connexion par lql le user est passé pour ajouter l'event non ? 

Merci à toi

**Comment by Octaviedebs** [comment]
**RESUME**

**Ce qui a été corrigé =** 
- plus d'affichage d'event privé d'un territoire sur lql on est pas connecté
- plus d'ajout d'event possible sur un territoire sur lql on est pas connecté

**A FAIRE**
- tous les **event sudocuh structurants** à passer en public pour éviter FRP vide

**Comment by Octaviedebs** [comment]
résolu
