### ISSUE TITLE
[ Pipedrive > BDD ] Les affaires «non inscrites» n'évoluent plus dans le funnel Procédure une fois le lien de connexion expiré

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#401]
J'ai l'impression que quand un compte est créé mais reste en non inscrit dans le funnel car le user ne clique pas tt de suite sur le lien de connexion, alors les affaires «non inscrites» n'évoluent plus du tout dans le funnel Procédure et restent à l'étape non inscrits - j'ai l'impression que ce comportement a lieu une fois le lien de connexion expiré

J'ai eu ce cas avec ce user https://docurba2.pipedrive.com/deal/1253 lmagreault@ecla-jura.fr

- il a créé son compte et était en non inscrits
- il a du se reconnecter probablement après que le lien a expiré plusieurs jours après
- puis il m'a confirmé qu'il avait pu se connecter + déposer des actes

OR l'affaire n'évolue plus dans le pipe Procédures et restent en non inscrits

Merci !

**Comment by Octaviedebs** [comment]
@UngererFabien tu penses que cela pourrait se gérer en quickwin ?

**Comment by Octaviedebs** [comment]
![Capture d’écran 2024-03-05 à 19 21 44](https://github.com/MTES-MCT/Docurba/assets/144041896/cfd9cef3-3988-4317-8892-d3be76f60180)

Sur metabase par exemple, pour cet autre user, je sais qu'il a bien pu se connecter et recevoir ensuite le lien de connexion _(même si à l'inscription il n'a pas du cliquer dessus je pense)_ => ce champ ne se met donc pas à jour ce qui pourrait être l'explication

**Comment by UngererFabien** [comment]
@Octaviedebs Je ne vois pas d'endroit qui ferait évoluer les affaires de manière générale coté collectivité.

Du coup j'ia deux questions:
1. Est ce que certaines affaires avances d’elles-mêmes ? Si oui de quelle étape à quelle étape ?
2. Est ce que tu peux m'indiquer les ids des étapes procédures que tu voudrais automatisé ?

**Comment by Octaviedebs** [comment]
Hello ! 

1. Est ce que certaines affaires avances d’elles-mêmes ? Si oui de quelle étape à quelle étape ?
Je n'avais pas participé au paramétrage de pipedrive donc je ne sais pas ce qui était prévu initialement et quels étaient les déclencheurs pour passer de l'étape Tentative d'inscrits à Inscrits ni quel déclencheur/ quels cas quand un user arrive dans l'étape Tentative inscrits.

Actuellement quand tout va bien un user arrive dans Inscrits et quand ils déposent un acte dans Délib déposée.

**La question était pour commencer : qu'est ce qu'il y a derrière les « Tentative inscrits » et pourquoi certaines ne passent jamais en Inscrits alors qu'elles se sont bien connectés** ?

**Comment by Octaviedebs** [comment]
@lerayj pourquoi tu la closed du coup cette issue ?

**Comment by Octaviedebs** [comment]
Hello ! A nouveau exemple avec cette affaire https://docurba2.pipedrive.com/deal/1778

- création du compte le 18 mars 
-  il reste en Tentative d'inscrits
- pourtant il s'est bien connecté (cf son email de ce jour) [responsable-amenagement@cc-paysdopale.fr
<img width="793" alt="Capture d’écran 2024-04-03 à 12 33 16" src="https://github.com/MTES-MCT/Docurba/assets/144041896/87aed070-60bb-4d88-86fb-bc48f5cbc6a0">
](mailto:responsable-amenagement@cc-paysdopale.fr)
- c'est comme si le champ successfully logged once (celui utilisé sauf erreur de ma part) ne se mettait pas à jour du coup

**Comment by Octaviedebs** [comment]
@lerayj

**Comment by Octaviedebs** [comment]
Toujours d'actualité - en lien avec la refonte du CRM (= pas dans les prios mais les prochaines cartes pour la refonte du CRM devront résoudre cela).

**Comment by Octaviedebs** [comment]
Mais je close du coup car géré ailleurs
