### ISSUE TITLE
[ Bug FRP ] Ajout d'event a disparu seul le fichier reste

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#403]
Le user a ajouté un event, rattaché un fichier, mais après l'enregistrement seul le fichier est joint et reste dans la barre latérale droite ressources, mais il n'y a plus d'event dans le corps de la FRP

https://jam.dev/c/9df90c58-f655-420c-bbf4-5681f3ffb6c2

Merci ! 

User à contacter quand mep = Laurent Magréault

**Comment by CeliaVermicelli** [comment]
Note pour moi-même : 

Bug observé pour le 29 aussi : 
2 event "autres" inscrits dans [cette FRP](https://docurba.beta.gouv.fr/frise/bb8e7bb7-c74a-41fe-b2ba-febce33be02d) mais invisible du au bug - Gérald (29) a bien inscrit l'event avec son titre, le prévenir quand resolº du bug pour supprimer les deux autres qui apparaissent dans les ressources.

**Comment by UngererFabien** [comment]
Je vais passé un fix en preprod. Tous les events devraient s'afficher malgré l'absence de nom ou de type.

**Comment by Octaviedebs** [comment]
Pour la CA ECLA (39) je viens de vérifier et les events ne s'affichent tjrs 

J'ai vérifié en accès public et en accès connecté et dans les deux cas,  malgré qu'il y ait bien le fichier qui avait été joint, l'event Autre n'apparait pas 

![Capture d’écran 2024-02-19 à 15 52 31](https://github.com/MTES-MCT/Docurba/assets/144041896/74c04176-6142-4413-87fc-bb8976f96739)
<img width="764" alt="Capture d’écran 2024-02-19 à 15 55 52" src="https://github.com/MTES-MCT/Docurba/assets/144041896/696e78b6-4e8f-43e5-8c16-f1a238bba9e9">
pas

https://jam.dev/c/5686d238-3b31-474d-a84a-8e1205c520e3

**Comment by Octaviedebs** [comment]
résolu
