### ISSUE TITLE
bug Outil des PAC : les dates de dernières modifications des sections n'apparaissent plus au niveau des PAC

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#406]
hello @nyko28 

https://jam.dev/c/77bac0f0-07ae-4e16-8854-cb9020ae208a

il faut : la date de dernière modification par section, au niveau des PAC + au niveau de la trame. 
* Au niveau de la trame : il manque seulement celle sur le cadre juridique (c'est ok pour les sous sections)
* Au niveau des PAC : on a perdu toutes les dates -> prio !

Mercii

**Comment by nyko28** [comment]
Hello,

Les dates ne sont pas visibles au niveau du PAC car tu es en mode consultation. Elles deviennent visibles en mode édition.
Mais la date du cadre juridique est bien manquante. C'est liée à un mauvais nom du fichier d'introduction du Cadre juridique. Ça devrait se corriger automatiquement avec le merge du cadre juridique, le bon nom de fichier redescendra dans les trames inférieures.
