### ISSUE TITLE
bug FRP - modif simplifié : bug isolé à ces deux cas ?

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#408]
https://jam.dev/c/059e6cfa-8a30-4931-b7b4-41acae352f25

Il m'est impossible de renseigner sur Docurba les évènements suivants (le logiciel mouline sans fin même en rafraichissant la page) :

- CC Thoré Montagne Noire / PLUI / Procédure secondaire : modification simplifiée 1 -> évènement "Délibération précisant les modalités de concertation"

- Commune de Saint Benoit de Carmaux / DU communaux / PLU / Procédure secondaire : modification simplifiée 1 -> évènement "Délibération d'approbation"

**Comment by lerayj** [comment]
C'est fix 

Notes a moi même - 
Cas 1 -> Mauvaise liaison du doc_type qui aurait du être celui de ca procédure parente. Vérifier qu'on est bon la dessus
Cas 2 -> Les attachements étaient à NULL et non a [] - surement du legacy mais double check
