### ISSUE TITLE
PAC - sections fantomes : permettre de les cacher au niveau du pac ?

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#409]
https://jam.dev/c/065eb12b-e0e7-4c10-b6c1-3a67b5d14a11

**Comment by CeliaVermicelli** [comment]
fyi @HermanceGauth

**Comment by HermanceGauth** [comment]
Par rapport à sa crainte de ne pas les retrouver, je me dis qu'un système qui permettrait de les cacher(sans les supprimer)/afficher pourrait résoudre le problème?

**Comment by lerayj** [comment]
@julienzdocurba peut surement aider la dessus ?

**Comment by julienzdocurba** [comment]
Je suis pas sûr de tout comprendre à 100% mais est-ce qu'on ne devrait pas bouger ca dans le backlog? Parce que ca n'a pas l'air d'être un bug mais plutôt une nouvelle feature non? (je peux le bouger dans le backlog moi même si ca vous va)

**Comment by CeliaVermicelli** [comment]
@julienzdocurba yes, ça me va que tu le bouges dans le backlog !

**Comment by HermanceGauth** [comment]
ok pour moi aussi

**Comment by HermanceGauth** [comment]
Je close cette issue car nouvelle fonctionnalité
