### ISSUE TITLE
[Dépôt d'acte] la validation du form pour déposer un acte n'aboutit pas

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#413]
https://jam.dev/c/97e29736-dcd7-480e-bb5f-281a8109f1fb
Jam de plus d'1min ! 

j'ai testé le dépôt en mode CT connectée sur une FRP et tout fonctionne normalement.
J'ai fais ces tests suite au retour de cette personne mais je n'ai pas eu le même msg d'erreur (je n'ai peut-être pas attendu assez longtemps ?)

> Bonjour
> Je viens d'essayer de déposer un doc mais la plateforme DOCURBA m'a mis TypeError: Cannot read properties of undefined (reading 'map') Savez vous pourquoi ? Merci à vous !

**Comment by Octaviedebs** [comment]
+ 1 ça fait 20 min que j'essaie pour ma vidéo et effectivement impossible ça tourne en rond sans cesse et ça n'aboutit jamais quelle que soit le format de la PJ

FYI @HermanceGauth pour ta video démofast si tu montres cette fonctionnalité tu rencontreras peut être le mm souci, pour info pour moi ça n'aboutit jamais donc peut être attendre la résolu° de cette issue pour faire ta vidéo ou ne pas montrer cette feature en fonction de ce que tu as décidé

**Comment by Octaviedebs** [comment]
tt re fonctionne
