### ISSUE TITLE
QA landing page : écart des images

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#414]
Sur mon grand écran j'ai les images qui me semblent un peu décalées, je ne sais pas si c'est normal
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/a8aa4ec1-45e7-403e-8862-c92c3c4ca4f8)

**Comment by lerayj** [comment]
En soit ca respecte le design si on veux faire venir le screenshot de la droite. Mais effectivement sur grand ecran ca rend pas ouf
@julienzdocurba tu as une suggestion ?

**Comment by HermanceGauth** [comment]
Je crois que c'est réglé, je closed
