### ISSUE TITLE
Bug (DDT connectée) : accès FRP impossible sur deux proc. secondaires du Calvados.

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#415]
La FRP de ces procédures ne chargent pas, le nom de la FRP est même incomplet : 

MS5 : https://docurba.beta.gouv.fr/frise/8802746c-b5ec-4656-8565-2beb94d2c062

MS6 : https://docurba.beta.gouv.fr/frise/fc21a2f9-24dd-42fa-9fd8-25b9f165865f

(retour de Marion DDT Calvados)

**Comment by lerayj** [comment]
done
