### ISSUE TITLE
QA ? Lien entre LP principale et LP par cible : doutes sur le comportement attendu

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#416]
Hello, 

https://jam.dev/c/4d8fd285-58d8-4254-b589-fdcc0549ca49

@julienzdocurba @Octaviedebs

**Comment by julienzdocurba** [comment]
Oui on a des boutons "En apprendre plus" pour chacun des blocs:
<img width="1019" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/6354f68e-60f8-435f-86e3-e2349b1f5269">
