### ISSUE TITLE
Outil des PAC : où retrouver les PAC que l'on m'a partagé par email ?

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#424]
J'explique en démo https://jam.dev/c/beed46eb-7504-46ea-853e-2d11f16a19ad

Ex : la DDT 22 m'a partagé les PAC de Trédaniel et Tréméreuc et mon seul moyen de les retrouver aujourd'hui c'est de reprendre les emails transactionnels où l'on indique le lien des PAC. Mais c'est important pour les users de les retrouver direcement sur Docurba. 

@julienzdocurba désolée, je comprends que c'est un parcours qui est complètement passé à la trappe de notre côté lors de la QA. Dans la version pre-septembre 2023 on avait l'ensemble de la liste de nos PAC dans l'onglet "mes PAC" avec 2 parties : 
- la première contenant les PAC initiés par moi même
- la 2eme partie avec un titre "partagés avec moi" contenant la liste des PAC que l'on avait pu me partager par email en mode lecture ou édition. 

-> il y a probablement d'autres manières de les présenter mais en tout cas l'essentiel c'est de les retrouver donc "au plus quick win pour vous" !
Mercii !

**Comment by julienzdocurba** [comment]
Oui pour moi il était prévu de mettre tous les PAC auxquels j'ai accès dans cette liste, mais c'était sûrement mal communiqué désolé. Je pense pas qu'on n'ait besoin de 2 listes pour l'instant, je pense qu'on peut tout mettre dans la même liste et potentiellement ajouter des filtres ou onglets plus tard si on a vraiment besoin.

**Comment by CeliaVermicelli** [comment]
@julienzdocurba ça me parait cohérent que ça soit dans la même liste ! 
Donc @UngererFabien c'est pas un bug mais un oubli : il faut faire apparaitre les PAC partagés par email dans l'onglet Mes PAC (en plus de ceux que l'user crée lui même), pour les différencier ça serait possible de rajouté un "créé par" avec le nom de l'user ?

**Comment by julienzdocurba** [comment]
Tu pense vraiment que ca sera un problème de les mettre tous dans la même liste? Parce que si c'est le cas ca sera un problème pour d'autres choses comme la liste de procédures qu'on design en ce moment sur le dashboard. Perso je serai d'avis de juste avoir tout dans la même liste, voir si c'est un problème, et si c'est le cas ajouter des choses comme un champs "créé par" ou des filtres. Sauf si on est très confiants que ce sera un problème (par exemple on l'a déjà beaucoup entendu en retour utilisateur).

**Comment by CeliaVermicelli** [comment]
> Tu pense vraiment que ca sera un problème de les mettre tous dans la même liste? 
Non non justement, je disais que c'était cohérent de les avoir dans la même liste. On dit la même chose :) 
Idéalement avoir la précision de qui a créé le PAC serait utile mais si pas possible tout de suite on aura de toute façon les retours utilisateurs qui nous permettront de reprioriser cette précision, ou pas :)
