### ISSUE TITLE
Bug user : impossible d'accéder à son compte agent de DDT 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#431]
Hello @UngererFabien 

nadia.weill@var.gouv.fr du 83 :

- impossible de se créer un compte car "email déjà reconnu" (`créer un compte`)
- mais elle ne reçoit jamais l'email suite au process de mdp oublié (`j'ai déjà un compte je me reconnecte`)
- elle n'existe pas sur la bdd metabase des personnes inscrites 

-> peut-on supprimer toute trace de son compte pour qu'elle puisse s'en créer un nouveau, choisir son rôle + mdp ? 

Merci ! 

Je comprends que c'est un Bug similaire reporté ici : https://github.com/MTES-MCT/Docurba/issues/364 (closed)

**Comment by UngererFabien** [comment]
Je lui ai fais un profile. Normalement elle devrait pouvoir se connecter et accéder au dashboard ddt.

**Comment by CeliaVermicelli** [comment]
mercii @UngererFabien ! 
Tu lui a choisi un mdp du coup ? Elle doit faire le process de "mdp oublié" ?

**Comment by UngererFabien** [comment]
> mercii @UngererFabien ! Tu lui a choisi un mdp du coup ? Elle doit faire le process de "mdp oublié" ?

Oui sauf si elle se souvient de son mdp qu'elle semble avoir utilisé en décembre.

**Comment by CeliaVermicelli** [comment]
Hello @UngererFabien je rouvre cette issue suite à son retour : 

> Je fais un essai ce matin.... Sans succès, l'application ne reconnait 
> pas mon mot de passe et lorsque je fais mot de passe oublié, je ne 
> reçois aucun lien dans ma boite mail.... never ending story

Peux-tu supprimer son compte pour quelle recommence de zero s'il te plait ?

**Comment by CeliaVermicelli** [comment]
Re @UngererFabien elle préfère qu'on supprime son compte pour recommencer en connaissant son mdp ! :) 

Pour info, son problème d'hier était lié au pb de connexion en DDT (même problème qu'Hermance) -> donc elle a reçu les email de recup de mdp des heures plus tard...
