### ISSUE TITLE
[FRP Cabriès (13)] Pb lié à la mise à jour des statuts des procédures

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#432]
[Ce PLU](https://docurba.beta.gouv.fr/frise/d374ce59-423e-486c-bdfd-35084cc14a3d) devrait être opposable 

conséquence : elle voulait ajouter une proc. secondaire mais elle ne peut la relié qu'au SCOT qui est la seule autre proc. opposable de cette CT. 

Note perso : Prévenir Mme Maréchal DDT 13 quand résolu

**Comment by lerayj** [comment]
Pour infos les status vont être recalculés avec le dump journalier (conséquence de la semaine avec Claire). C'est pour cela que nous ne prenons en compte les retours sur les status de suite - on sait que ca va être chamboulé. 

Je passe en wontfix pour de la clareté.

**Comment by CeliaVermicelli** [comment]
@UngererFabien @lerayj ça n'a pas résolu le pb de statut de Cabriès (13)

**Comment by HermanceGauth** [comment]
Le soucis ici à mon avis c'est que la délibération d'approbation est en statut "invalide" dans Sudocuh donc on ne peut pas considérer que le PLU est opposable. Il faudrait savoir pourquoi la délib d'appro est invalide ?

**Comment by UngererFabien** [comment]
@CeliaVermicelli je pense qu'on est bon mais je suis pas sur à 100% pour le PLUi est ce que tu peux réouvrir si ce n'est pas bon ?

**Comment by Octaviedebs** [comment]
Le PLU de Cabrièes est bien opposable - mais je n'ai pas de précision de mon côté sur pourquoi la delib d'appro est en invalide du coup - @UngererFabien tu indiques ne pas être sûr pour le PLU**i** mais tu voulais dire PLU du coup j'imagine
