### ISSUE TITLE
QA merge de main : possibilité de modifier les nouvelles sections ajoutées au niveau nationale dans les trames dept et reg

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#434]
https://jam.dev/c/56ce81e7-fcab-43ad-a045-80f203275bca

(même pb au niveau reg)

**Comment by CeliaVermicelli** [comment]
note à moi même : prévenir D. Bian (29) quand c'est ok - ajout de sections dans CJ

**Comment by nyko28** [comment]
On utilisait un fichier statique qui listait les sections de main du CJ pour distinguer les sections modifiables. J'ai changé le comportement pour qu'on se réfère dynamiquement à la trame supérieure.
