### ISSUE TITLE
QA merge de main : ordre aléatoire si on laisse la nouvelle section à la suite des sections déjà créées

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#435]
https://jam.dev/c/6e0de6a7-1d97-48f0-9a5d-d0cfdffe8d35

une fois qu'on l'a fait bougé une fois ou si on écrit directement dedans c'est bon

**Comment by nyko28** [comment]
On sauvegarde désormais l'ordre des sections après la création d'une nouvelle section
