### ISSUE TITLE
MAJ des statuts - PLUi sectoriels : exemple de la CC St Cyr Mère Boitier (BFC)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#438]
Note pour moi même quand le pb sera résolu  : 

**Retour de Jenny (BFC)** 

Les PLUi sectoriels (portant sur une partie du territoire) n'apparaissent pas tous comme étant "opposables".
Exemple : CC St Cyr Mère Boitier entre Charolais et Mâconnais qui est couverte par 2 PLUi : le dernier en date (7 communes concernées) apparait avec le statut "opposable" donc ok. En revanche, le PLUi plus ancien (9 communes concernées) apparait avec le statut "précédent" alors qu'il est toujours "opposable" sur ces 9 communes

**Comment by HermanceGauth** [comment]
@UngererFabien @lerayj on n'a pas eu le temps d'en reparler du coup mais je voudrais comprendre pourquoi on applique pas la règle sur le périmètre qu'on a défini cet été (=s'il y a zéro commune en commun alors il s'agit de sectoriel et les deux sont opposables / s'il y a au moins une commune en commun c'est un précédent et un opposable).
Autre option permettre de le changer à la main en admin mais il y en a potentiellement pas mal.

**Comment by lerayj** [comment]
Pour infos les status vont être recalculés avec le dump journalier (conséquence de la semaine avec Claire). C'est pour cela que nous ne prenons en compte les retours sur les status de suite - on sait que ca va être chamboulé. 

Je passe en wontfix pour de la clareté.

**Comment by CeliaVermicelli** [comment]
@UngererFabien @lerayj ça n'a pas résolu ce pb de périmètre de PLUi sectoriel 
@HermanceGauth
