### ISSUE TITLE
Afficher l'état d'accessibilité dans le footer

### ISSUE THREAD

**Issue by julienzdocurba** [MTES-MCT/Docurba#439]
On doit afficher l'état de l'accessibilité (et pas seulement un lien vers la charte d'accessibilité comme actuellement) sur chaque page de l'app afin d'être en accord avec les obligations légales: https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/construire-un-service-accessible-et-inclusif/accessibilite-et-rgaa/obligations-legales

Actuellement, on affiche seulement un lien "Accessibilité" qui redirige vers la charte:
<img width="1219" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/311cfda0-6e96-478c-bc13-614e758a0cde">

On souhaiterait changer le label de ce lien pour montrer l'état "Accessibilité : non conforme":
![image](https://github.com/MTES-MCT/Docurba/assets/147177148/cf825b80-ed5a-4bc9-95f2-e2e9bf79c7d8)

**Comment by lerayj** [comment]
done
