### ISSUE TITLE
PAC_Advices : prendre en compte mes pull requests

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#440]
Hello @nyko28 , le mois dernier j'ai ajouté "visible : false" à chaque fichier .md des [PAC_advices ](https://github.com/MTES-MCT/Docurba/tree/master/content/PAC_Advices)

Ce sont des conseils d'utilisation visibles depuis la trame de PAC départementale et les PAC (voir PJ). -> je veux qu'ils disparaissent car, au-delà du côté esthétique, on chercher à diffuser ces astuces aux moments les plus pertinents via les form Stonly. 

Est-ce que c'est possible de merge les PR là dessus pour la MEP de demain ? 
Dis moi si les infos ne sont pas claires :) 

Mercii !

![Capture d’écran 2024-02-20 à 19 44 24](https://github.com/MTES-MCT/Docurba/assets/111045572/d9775a83-4f2a-44fa-ab31-4ea6d2eefea2)

**Comment by nyko28** [comment]
Done ! ce sera dans la MEP 😉
