### ISSUE TITLE
QA MEP PAC 2.0 : sections en doublon 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#443]
https://jam.dev/c/8aa20b27-9c77-4e6d-8b36-53feb750a725

**Comment by HermanceGauth** [comment]
J'avoue que ce n'est pas clair pour moi de savoir comment ces doublons ce sont créés parce que normalement dans ce cas sections fantômes + comparaison devrait suffire à récupérer le contenu national et regional. Les deux parties "Les différents risques à prendre en compte" n'ont pas le même contenu (l'un est national l'autre a priori départemental) donc je ne suis pas sûre qu'un script puisse savoir automatiquement lequel garder. Si la DDT a créer une nouvelle section avec ce nom parce que celle du national ne lui convenait pas (c'est exactement ce qu'on attend d'elle pour cette partie 3 qui n'est pas mis à jour nationalement), c'est à elle de supprimer si elle le souhaite la section nationale ou de la garder en mémoire si elle veut et de la décocher dans ces PAC communaux/intercommunaux.

**Comment by nyko28** [comment]
Le problème est certainement historique, dû à des bugs passés qui ne devraient plus se reproduire aujourd'hui.
Je pourrais faire tourner un script mais il ne saura pas quelle est la "bonne" section à garder, il faudrait choisir un critère de sélection comme la dernière date de modification par exemple.

J'ai fais un script pour lister les cas de doublons, j'en ai compté 34, je les mets ici si ça peut nous aider à choisir :

[dept-972] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/S’adapter et lutter contre le changement climatique/Adaptation au recul du trait de côte.md
[dept-78] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Promouvoir un urbanisme favorable à la santé.md
[dept-70] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Prévenir les risques naturels prévisibles/Dispositions à prendre en compte dans le PLU/Les différentes parties du PLU.md
[dept-89] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Promouvoir un urbanisme favorable à la santé.md
[dept-89] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Prévenir les risques naturels prévisibles/Dispositions à prendre en compte dans le PLU/Les différentes parties du PLU.md
[dept-89] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Prévenir les risques naturels prévisibles/Dispositions à prendre en compte dans le PLU/Les différents risques à prendre en compte.md
[dept-90] Duplicate : PAC/Dispositions de documents supra-territoriaux et doctrines/Les documents locaux/Le SCoT.md
[dept-67] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Promouvoir un urbanisme favorable à la santé.md
[dept-22] Duplicate : PAC/Cadre juridique et grands principes de la planification/Lois sur la planification/Loi littoral.md
[dept-29] Duplicate : PAC/Dispositions de documents supra-territoriaux et doctrines/Les documents régionaux/Le SRADDET.md
[dept-11] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Promouvoir un urbanisme favorable à la santé.md
[dept-3] Duplicate : PAC/Dispositions de documents supra-territoriaux et doctrines/Les documents locaux/Le Plan Climat Air Energie Territorial (PCAET).md
[dept-3] Duplicate : PAC/Dispositions de documents supra-territoriaux et doctrines/Les documents locaux/Le Programme Local de l'Habitat (PLH).md
[dept-3] Duplicate : PAC/Dispositions de documents supra-territoriaux et doctrines/Les documents locaux/Le SCoT.md
[dept-3] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Lutter contre l’artificialisation et préserver les espaces naturels, agricoles et forestiers/Dispositions à prendre en compte dans le PLU/Préservation des zones agricoles.md
[dept-3] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Préserver le patrimoine historique, naturel et géologique, mettre en valeur les paysages/Dispositions à prendre en compte dans le PLU/Outils d’aide à la décision ou à la protection.md
[dept-7] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Promouvoir un urbanisme favorable à la santé.md
[dept-15] Duplicate : PAC/Cadre juridique et grands principes de la planification/Grands principes primordiaux.md
[dept-15] Duplicate : PAC/Cadre juridique et grands principes de la planification/Lois sur la planification/ELAN.md
[dept-15] Duplicate : PAC/Cadre juridique et grands principes de la planification/Lois sur la planification/Lois montagne I et II/Loi montagne.md
[dept-15] Duplicate : PAC/Cadre juridique et grands principes de la planification/Principe de la hiérarchie des normes et la mise en compatibilité.md
[dept-15] Duplicate : PAC/Cadre juridique et grands principes de la planification/Qu'est-ce qu'un PLUi?/Le contenu/Le règlement.md
[dept-15] Duplicate : PAC/Cadre juridique et grands principes de la planification/Qu'est-ce qu'un PLUi?/Le contenu/Les annexes.md
[dept-15] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Lutter contre l’artificialisation et préserver les espaces naturels, agricoles et forestiers/Cadre juridique.md
[dept-15] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Mobilité/Cadre juridique.md
[dept-15] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Préserver le patrimoine historique, naturel et géologique, mettre en valeur les paysages/cadre juridique.md
[dept-42] Duplicate : PAC/Introduction/PAC validé.md
[dept-43] Duplicate : PAC/Cadre juridique et grands principes de la planification/Qu'est-ce qu'un PLUi?/Zoom sur/L’association des personnes publiques.md
[dept-69] Duplicate : PAC/Introduction/Socle de PAC.md
[dept-73] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Préserver l’accès et la qualité de la ressource en eau.md
[dept-73] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Prévenir les risques anthropiques [DDT73]/Sites et sols pollués (le cas échéant).md
[dept-73] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/S’adapter et lutter contre le changement climatique.md
[dept-74] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Lutter contre l’artificialisation et préserver les espaces naturels, agricoles et forestiers/Dispositions à prendre en compte dans le PLU/Préservation des zones agricoles.md
[dept-4] Duplicate : PAC/Politiques publiques s'appliquant sur le territoire/Promouvoir un urbanisme favorable à la santé.md

**Comment by CeliaVermicelli** [comment]
ok top, pour 34 conflit je trouve complètement faisable de le régler à la mano - chose que je fais petit bout par petit bout dès que j'ai un DDT au sujet du PAC, j'en profite pour les aider à mettre à niveau leur trame.

Si ça vous va je m'en occupe.

**Comment by CeliaVermicelli** [comment]
https://jam.dev/c/6dc00c45-2423-4141-b3ef-2eb3d968b21d
https://docurba.beta.gouv.fr/trames/dept-78
à voir si tu peux m'aider avec ça @nyko28 mercii !

**Comment by CeliaVermicelli** [comment]
Notes perso :

- voir si toujours un pb : https://jam.dev/c/7d965b71-3cb4-41ed-9c5d-d60f727c3ae3

**Comment by CeliaVermicelli** [comment]
Je continue à éliminer des doublons, petit doute sur le dernier texte "nouvelle section" et l'impossibilité de comparer à la trame supérieure.
Démo sur la trame du 70 : https://docurba.beta.gouv.fr/trames/dept-70

https://jam.dev/c/324ab947-6fd1-4ccf-bb44-0df7e864db36

**Comment by HermanceGauth** [comment]
Pas sûre de comprendre la question mais on a bien ce contenu dans la trame régionale de BFC 
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/a783b1b7-5ecb-43a1-967f-fddbde354f79)
https://docurba.beta.gouv.fr/trames/region-27

**Comment by CeliaVermicelli** [comment]
Suppression des doublons terminée ! 

@UngererFabien tu pourrais faire retourner le script de Nico pour s'assurer qu'il n'y en a pas de nouveau stp ? Mercii !

Et aussi, on se disait avec Hermance que ça serait utile de faire tourner le script de nico de temps en temps pour nous assurer de ne pas accumuler ce genre de doublons - s'assurer qu'il n'y aura pas d'incohérences dans le contenu proposé pour les DDT qui prenne en main l'outil. 

Tu penses que l'on pourrait le faire tourner : 
- dès qu'il y a une mise à jour de Main par Hermance 
- dès qu'il qu'il y a une amélioration des fonctionnalités PAC ?

**Comment by HermanceGauth** [comment]
J'ai ouvert une issue spécifique pour le script
