### ISSUE TITLE
Statut des proc. du 81 : Statuts pas à jour sur Vénès, CA Gaillac et Vals et plateau

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#447]
Hello ! 

- Vénès  : erreur sur les DU communaux de cette communes. [Cf page commune](https://docurba.beta.gouv.fr/ddt/81/collectivites/81311/commune)
-> il y a bien le PLUi en cours -> ok 
-> les DU communaux : 
la [CC opposable sur Docurba ](https://docurba.beta.gouv.fr/frise/05b5cfa4-ed7c-4299-b7b5-b31c4eebdbd7)devrait en fait avoir le statut "abandon" car il y a une delib d'abandon **-> @UngererFabien maj du 14.03 cette CC est maintenant en statut "en cours" - avec titre "undefined".**
la [CC précédent sur Docurba](https://docurba.beta.gouv.fr/frise/4899721d-23c2-4e0a-ad58-ce294aa410a3) devrait en fait avoir le statut "opposable". **-> maj du 14.03 sont statut est toujorus en "précédent".**

- CA Gaillac : 
-> le statut de [ce PLUi ](https://docurba.beta.gouv.fr/frise/40b7df8a-af5a-40da-807a-aaf474b09774)devrait être "abandon" car un event d'abandon a bien été renseigné dans la FRP par la DDT, mais aujourd'hui son statut est "en cours"

- [Vals et plateau](https://docurba.beta.gouv.fr/ddt/81/collectivites/200066561/epci)
-> ce 2eme PLUi devrait aussi avec un statut "opposable" et non "précédent" comme c'est actuellement. [cf FRP de ce PLUi](https://docurba.beta.gouv.fr/frise/93742394-3437-45ea-bde9-2515d6600634) -> maj du 14.03 le 2eme PLUi apparait bien en "opposable" donc ça semble bon ! @UngererFabien 

Remarque : c'est peut-être la cause de la différence des cartes produites par son SIG : la moitié de cette CC apparaissait comme étant au RNU sur la carte faite avec les données Docurba alors que sur la carte avec données Sudocuh toute la CC apparaissait bien avec un PLUi. FYI @Octaviedebs 

FYI @HermanceGauth

**Comment by lerayj** [comment]
Pour infos les status vont être recalculés avec le dump journalier (conséquence de la semaine avec Claire). C'est pour cela que nous ne prenons en compte les retours sur les status de suite - on sait que ca va être chamboulé. 

Je passe en wontfix pour de la clareté.

**Comment by HermanceGauth** [comment]
update : Vals et Plateau de nouveau plus bon voir les autres issues sur les PLUi sectoriel, ils sont maintenant les deux en précédent au lieu d'opposable

**Comment by Octaviedebs** [comment]
![Capture d’écran 2024-04-02 à 17 34 07](https://github.com/MTES-MCT/Docurba/assets/144041896/386b1d43-37fa-4f46-8450-a05da12059e0)
Tu es sur la pré- prod 😅 (j'ai fait pareil semaine dernière haha) en prod c'est bon

**Comment by HermanceGauth** [comment]
Oui je sais bien il me semble que c'est sur la pre-prod qu'il faut test les statuts?
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/5edf26f0-5b35-4d46-96de-a7294125b723)

**Comment by HermanceGauth** [comment]
Et normalement les deux devraient être opposables de ce que je comprends du commentaire de Célia

**Comment by Octaviedebs** [comment]
Ah mais pardon pardon je dis n'importe quoi !! mais oui oui exactement my bad

**Comment by Octaviedebs** [comment]
- Vals et Plateau : 2 PLUI opposables ok 
- Venes : 1 abandon et 1 opposable ok 
- CA Gaillac : page tournait en rond pas pu tester, je retesterai
