### ISSUE TITLE
Titre des FRP : faire la distinction entre PLUi et PLU dans les FRP des proc. remontées de Sudocuh.

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#452]
ce retour rejoint cette issue #297 

Aujourd'hui on ne fait pas la différence entre PLUi et PLU au niveau du nom d'une FRP, **pour les procédures remontées de Sudocuh** Pour les procédures ajoutées sur Docurba la distinction est faite et c'est top. 
-> il faudrait permettre cette distinction pour les procédures encore en cours remontées depuis Sudocuh ? 

https://jam.dev/c/53eada8a-cf32-4aef-afa4-9d8a81107f8c 

Retour de Frédéric du 35 : 

> Sur l’appellation des procédures de PLU intercommunaux ajouter le i Dans le libellé on voit PLU de CC de XXX. Ce serait idéal si on pouvait avoir plutôt PLUi de CC de XXX car ça prête confusion avec la gestion des PLU communaux. Ce serait bien si on puvait aussi avoir la finesse (PLUiH, PLUiHD, PLUiD) 

- [ ] prévenir frédéric 35

**Comment by HermanceGauth** [comment]
Liée à https://github.com/MTES-MCT/Docurba/issues/525

**Comment by CeliaVermicelli** [comment]
autre exemple dans le 39 
[
lien FRP de l'EPCI ECLA](https://docurba.beta.gouv.fr/frise/fecb9b51-e04a-4fb6-a2de-ee3e2d7b0e31)

![Capture d’écran 2024-09-03 à 4 24 45 PM](https://github.com/user-attachments/assets/9224a27b-d2cf-4614-8c38-993757c8c60b)


- [ ] prévenir Loic & Co. de la ddt

**Comment by CeliaVermicelli** [comment]
### Update/recap : 
[demo](https://jam.dev/c/382d4e61-e60b-427f-90b2-89eb2f4affa5)

### Le "i" de "PLUi" se perd dans les FRP des : 
* proc principales, provenant de **Sudocuh**, [exemple pour le PLUi val d'ille aubigné](https://docurba.beta.gouv.fr/frise/0f58e95b-9e23-414f-92d9-3afec77c0a06) - mais ça on l'avait déjà dans l'issue
* proc. secondaires, créées sur **docurba**.  [exemple Val d'ille aubigné](https://docurba.beta.gouv.fr/frise/39f18b72-81d6-427d-9617-a4980efec22d)

**Comment by HermanceGauth** [comment]
Je ferme car duplicate

**Comment by HermanceGauth** [comment]
Pour le 39 résolu ici : https://docurba-pr1057.osc-fr1.scalingo.io/frise/fecb9b51-e04a-4fb6-a2de-ee3e2d7b0e31
Pour le 35 résolu ici : https://docurba-pr1057.osc-fr1.scalingo.io/frise/0f58e95b-9e23-414f-92d9-3afec77c0a06 mais pas pour la modification
