### ISSUE TITLE
BDD Metabase : harmoniser les codes départements 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#457]
**Problèmes** : 
- certains users DDT n'ont pas de département associé -> [cf question metabase profile sans dpt.](https://docurba-metabase.osc-fr1.scalingo.io/question/134-profiles-sans-dpt) 
- les users du side CT/BE des départements 01,02 [...] 09, sont enregistrés avec les codes département "1", "2", etc. (et non "01", "02, etc,) -> [cf question metabase](https://docurba-metabase.osc-fr1.scalingo.io/question/133-dpt-1-2-3-etc-au-lieu-de-01-02-etc)
- bcp d'user en .gouv sont en side collectivité au lieu du side Etat. Ex : le Mr Desmaretz du Pas de Calais est en side collectivité -> à modifier manuellement pour tous les emails en .gouv concernés. 

FYI @UngererFabien @Octaviedebs

**Comment by UngererFabien** [comment]
J'ai mis à jour les profiles et corrigé dans la valeur assigné dans le signup.

**Comment by CeliaVermicelli** [comment]
(note à moi-même : je n'arrive pas à vérifier avec Metabase qui ne termine pas de charger ma question)

**Comment by Octaviedebs** [comment]
https://docurba-metabase.osc-fr1.scalingo.io/question/134-profiles-sans-dpt 

Il y a peut être qqch qui m'échappe @UngererFabien mais dans la question qu'on t'avait mise, il y a toujours des .gouv.fr en side collectivités + sans départements
