### ISSUE TITLE
Bug accès compte DDT d'aura

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#462]
Hello @UngererFabien 

Est-ce que tu peux valider les accès de ces deux personnes directement depuis la BDD s'il te plait : 

[carine.einkhah@rhone.gouv.fr](mailto:carine.einkhah@rhone.gouv.fr)
[delphine.ducarouge@rhone.gouv.fr](mailto:delphine.ducarouge@rhone.gouv.fr)

Elles ne sont pas vérifiees sur metabase :/ 

Merciii !

**Comment by lerayj** [comment]
Done - tu as une idée de pourquoi ?

**Comment by CeliaVermicelli** [comment]
@lerayj merci ! aucune idée !
