### ISSUE TITLE
QA PAC double-titre : bloquer les titres dans les sections pour forcer l'harmonisation

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#464]
A minima : qu'on ne puisse pas choisir une taille supérieure ou égale au titre de la section dans laquelle on se trouve.

**Comment by CeliaVermicelli** [comment]
@nyko28 c'est pas encore tout à fait ça mais presque ! :) 
demo : https://jam.dev/c/56863f69-20eb-4e52-a48b-5ab81b6827b5

ça décale juste d'un niveau. Hermance disait _"ne puisse pas choisir une taille supérieure **ou égale** au titre de la section dans laquelle on se trouve."_
@HermanceGauth pour vérif

**Comment by nyko28** [comment]
Yes, désolé j'ai pas bien lu. Je vais décaler d'un niveau :)
