### ISSUE TITLE
FRP | Pb sur les règles de déclenchement des évenements suggérés

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#465]
https://jam.dev/c/0076f40d-e407-46f0-ba30-1a84da5eded4

Les events suggérés apparaissent de façon aléatoire et ne prennent pas en compte les events ajoutés exemple sur cette collectivité _(ni les events sudocuh mais ça il y a une autre issue sur ce sujet)_
<img width="1080" alt="Capture d’écran 2024-03-08 à 12 02 08" src="https://github.com/MTES-MCT/Docurba/assets/144041896/21acdd89-d7e3-4ff7-b44f-a309d49e58b4">

**Comment by lerayj** [comment]
En attente du travail de la V2 des évènements suggéré par Francois et @julienzdocurba

**Comment by HermanceGauth** [comment]
Quand on en a parlé hier, je n'avais Github sous les yeux et je pensais que c'était uniquement pour les event issus de Sudocuh et donc je vois que c'est le cas aussi pour les events Docurba. Donc là c'est vraiment la fonctionnalité de base qui ne fonctionne pas, avec juste l'ordre chronologique du tableau. 
Le travail sur la V2 est au début du design et ne remettra a priori pas en cause ce fonctionnement voire le complexifiera (mais ça pose question si une version uniquement basée sur une chronologie linéaire ne fonctionne pas), je redis donc qu'en terme de prio, je ne souhaite pas attendre l'implémentation de la V2 pour résoudre ce bug (qui remets en cause l'intérêt même de la FRP).

**Comment by lerayj** [comment]
ok je regarde ca alors @HermanceGauth

**Comment by lerayj** [comment]
A reverifier et me donner des exemples si ca n'est pas bon, je n'ai pas tester tous les cas. Je ferme en attendant mais le cas présenté est fix

**Comment by CeliaVermicelli** [comment]
**Exemple dans le 81 @lerayj  :** 
[lien FRP](https://docurba.beta.gouv.fr/frise/9c4c16bf-a4e1-4b3e-9b79-0d8678c84a15)

![Capture d’écran 2024-03-13 à 19 02 09](https://github.com/MTES-MCT/Docurba/assets/111045572/631433ab-eaf1-4aec-b862-d5803d2b4fb8)

**Comment by CeliaVermicelli** [comment]
Exemple dans le 08 
[lien FRP](https://docurba.beta.gouv.fr/frise/b8206d65-4bfc-46b0-b345-ca29fb6cdfe9)


![Capture d’écran 2024-03-13 à 19 03 27](https://github.com/MTES-MCT/Docurba/assets/111045572/7dc34618-9fe8-42d3-a2b5-a129e4288c87)

**Comment by CeliaVermicelli** [comment]
Exemple **correct** du 971 : le caractère executoire est renseigné, il n'y a plus d'event suggeré. C'est l'élab du PLU de Bass-terre [lien FRP](https://docurba.beta.gouv.fr/frise/13657620-99af-4b12-a98e-eba79a29bcd9)

**Exemple où ça pose problème** : Modif simplifiée nº1 -[ lien FRP](https://docurba.beta.gouv.fr/frise/b6e8b4a9-b060-4bb3-9957-3e25a7c59520)

![Capture d’écran 2024-03-13 à 19 06 27](https://github.com/MTES-MCT/Docurba/assets/111045572/392efd99-624a-4502-96d7-69c648185450)

**Comment by Octaviedebs** [comment]
Oui j'ai l'impression que c'est assez aléatoire clairement 

<img width="852" alt="Capture d’écran 2024-03-14 à 14 21 05" src="https://github.com/MTES-MCT/Docurba/assets/144041896/b285ae4d-1543-4e63-a54e-7d973fadc20f">
<img width="852" alt="Capture d’écran 2024-03-14 à 14 21 16" src="https://github.com/MTES-MCT/Docurba/assets/144041896/fe6c60b7-5c7f-417d-ae93-13dc5359a691">

**Comment by lerayj** [comment]
> **Exemple dans le 81 @lerayj :** [lien FRP](https://docurba.beta.gouv.fr/frise/9c4c16bf-a4e1-4b3e-9b79-0d8678c84a15)
> 
> ![Capture d’écran 2024-03-13 à 19 02 09](https://private-user-images.githubusercontent.com/111045572/312572230-631433ab-eaf1-4aec-b862-d5803d2b4fb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzgwOTUsIm5iZiI6MTcxMDgzNzc5NSwicGF0aCI6Ii8xMTEwNDU1NzIvMzEyNTcyMjMwLTYzMTQzM2FiLWVhZjEtNGFlYy1iODYyLWQ1ODAzZDJiNGZiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwODQzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mN2IzMGI3NWU1NDlhM2ZjNmIyMTRmMTE4NWE3OWJmYzFkMDY5MGUwNTZmMmI2ZTQ3MzFiZTVjMTE4MWU0Zjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fmD1ZjJHLszeEjv3umE4c34Wa-0ZUWYB_luHhvkYMdU)

Ce cas la va être dur a gérer. En gros voila l'ordre que @HermanceGauth a définie:
![Capture d’écran 2024-03-19 à 09 44 08](https://github.com/MTES-MCT/Docurba/assets/5832419/96b58486-d45b-4609-b7e5-da0f8679df39)
La on est dans un cas pas logique selon cet ordre. Normalement on est pas sensé avoir de Publication du PLU après le caractère executoire. Je ne sais pas si c'est une erreur dans l'ordre d'Hermance, une erreur métier, ou un cas particulier sur cette procédure.

**Comment by lerayj** [comment]
> autre exemple dans le 81 : on nous propose encore le caractere executoire : [lien FRP](https://docurba.beta.gouv.fr/frise/93742394-3437-45ea-bde9-2515d6600634)
> 
> ![Capture d’écran 2024-03-14 à 09 34 19](https://private-user-images.githubusercontent.com/111045572/312761726-23306ff2-3d7a-48ec-a728-5391ea8e387f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzgwOTUsIm5iZiI6MTcxMDgzNzc5NSwicGF0aCI6Ii8xMTEwNDU1NzIvMzEyNzYxNzI2LTIzMzA2ZmYyLTNkN2EtNDhlYy1hNzI4LTUzOTFlYThlMzg3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwODQzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YWMxMThmMDA0YTU0M2I4ZWJiMGMwNWZiYWFjMmNkNmU1Mjk2NDAzOTQ4YmQ4OGYyYjI0YjE0OGQyM2QyZjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tmw9H3JuVI2bGRXf_MvND7nku-koDSWPYV2HsBTINq8)

Même problème. Potentiellement la seule solution que je vois c'est de complexifier l'algo de suggestion pour ne pas resuggérer des events déjà utilisé.

**Comment by lerayj** [comment]
> Oui j'ai l'impression que c'est assez aléatoire clairement
> 
> <img alt="Capture d’écran 2024-03-14 à 14 21 05" width="852" src="https://private-user-images.githubusercontent.com/144041896/312853638-b285ae4d-1543-4e63-a54e-7d973fadc20f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzgwOTUsIm5iZiI6MTcxMDgzNzc5NSwicGF0aCI6Ii8xNDQwNDE4OTYvMzEyODUzNjM4LWIyODVhZTRkLTE1NDMtNGU2My1hNTRlLTdkOTczZmFkYzIwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwODQzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWVjMzE5MmU0M2JkNGQ2ZmI5MmIxNGU5MzAzYjNiZWM5NTNjNDYyYWRmODc0OGQ2ODhlMTQzNGU4YWY1YjIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4xlkbT615aIqBy3eb67mXYMUAGl-bZtSNmrn2VoOWpY"> <img alt="Capture d’écran 2024-03-14 à 14 21 16" width="852" src="https://private-user-images.githubusercontent.com/144041896/312853644-fe6c60b7-5c7f-417d-ae93-13dc5359a691.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzgwOTUsIm5iZiI6MTcxMDgzNzc5NSwicGF0aCI6Ii8xNDQwNDE4OTYvMzEyODUzNjQ0LWZlNmM2MGI3LTVjN2YtNDE3ZC1hZTkzLTEzZGM1MzU5YTY5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwODQzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDM5Y2MwOTQ2MWM2MTI5MDI4ZmJkM2E0MWNhMjk1OWRjMDZlNDAxN2M2NDI0MTFhNzI5YTRjZmI3ZjJkYjIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iUhxRm5FVNfUE_lAHcRX-R5dGuDybJ3FV1YNaZ6M210">

Ca pour le coup je vois pas de problème. A la limite c'est qu'ils ont rentré dans sudocu une prescription avec un type Autre et il on écrit en comment que c'etait une prescription. Mais pour le coup je peux pas faire grand chose. La seule chose a faire a la limite faire du hardfix - en gros changer l'event sudocu directement pour le mettre au bon type en base.

**Comment by Octaviedebs** [comment]
Le deuxième screen est bon oui, c'était pour illustrer que « c'était aléatoire » (1er faux / 2ème juste).

En revanche il y a bien aussi une erreur quand l'event sudocuh est bien renseigné en prescription cf l'exemple donné par Célia pour CC de Aubigny-les-Pothées que je te remets 

<img width="938" alt="Capture d’écran 2024-03-19 à 10 48 43" src="https://github.com/MTES-MCT/Docurba/assets/144041896/cb066d86-3cc2-4520-8c8b-73e5a848f576">


Donc : 
- ne pas suggérer les events de délib de prescription ou d'arrêté de lancement si un event sudocuh contient « prescription» par exemple (peut être affiner pour que ça couvre le maximum de cas mais ça couvrirait donc les cas ou sur sudocuh Autre a été choisi mais aussi les cas où le bon type a été choisi )

- ne pas suggérer d'events déjà utilisés

**Comment by Octaviedebs** [comment]
@lerayj si ça t'aide, divers constats/comportements en vrac =  j'ai testé avec la commune d'Abainville 5501 depuis un accès DDT =

- j'ai essayé d'ajouter une nouvelle procédure secondaire : j'ai alors **une FRP vierge sans events suggérés** mais dans la liste je n'ai plus rien (juste la catégorie Autre) cf cette issue que je viens de [faire](https://github.com/MTES-MCT/Docurba/issues/499)
- j'ai essayé d'ajouter une procédure principale : là j'ai **un event suggéré, mais une fois l'avoir ajouté, je n'ai plus d'event suggéré (c'est vraiment hyper aléatoire)** => **SAUF quand on choisit le type de DU = CC (**mais pour PLU et PLUi c'est bien ça le comportement sauf erreur de ma part)

Autre exemple sur un PLU d'une commune après l'ajout de transmission de PAC : 

![Capture d’écran 2024-03-27 à 13 27 57 (1)](https://github.com/MTES-MCT/Docurba/assets/144041896/42a24783-9e88-4f65-9399-9e5a47be6326)

**Comment by HermanceGauth** [comment]
Jam pour moi-même : https://jam.dev/c/077f4b3f-a597-4001-a16d-b3f72c335fe3

Ce que j'ai constaté sur les procédure principale : 
- pour une carte communale : premiers évènements ok, jusqu'à ce que l'event suggéré tourne en boucle puis au bout d'un moment il n'y en a plus
- pour un PLU : je n'ai que le premier event suggéré et après plus de suggestion
- pour un PLUi : idem PLU

Sur les procédures secondaires : 
- même comportement que pour une carte communale

Donc il y a deux comportements :
- un event suggéré puis plus rien
- un event suggéré qui se met à tourner en boucle puis plus rien

**Comment by lerayj** [comment]
Pour le premier cas - c'est "normal" enfin ca pourrait être amélioré et toujours mettre en dernier celui qui a l'ordre le plus haut en cas d'égalité.

**Comment by lerayj** [comment]
Ok mais j'ai quand même trouvé un bug - en fait vu que l'ordre peut sauter des nombres en fonction de si c'est une pp, une ms, ... le suivant sur la liste n'est pas forcément +1 a l'order, mais le prochain chiffre supérieur a celui en cours. Ca devrait fix tous les pbs hors sudocu !

**Comment by Octaviedebs** [comment]
https://docurba.beta.gouv.fr/frise/55b4635c-1235-4d36-a0e2-c20b27f9e14a
Arradon (56)
Depuis accès employé

Exemple : 
- PLU
- un seul event Délib de prescription existant
- Suite à l'ajout d'un event transmission du PAC = l'event suggéré reste toujours celui de Delib de prescription
![Capture d’écran 2024-04-08 à 15 18 51](https://github.com/MTES-MCT/Docurba/assets/144041896/fc02fad9-6d30-4b72-8fff-cb1b2b687029)

https://jam.dev/c/f56f9a2b-77ba-4a97-ab10-2f817ca29675
