### ISSUE TITLE
QA pre prod double titres : essai sur un nouveau PAC

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#466]
Essai sur un nouveau PAC

https://jam.dev/c/78a7b29a-1109-4785-8c12-bd5ecb3008c2

PAC test : https://dev-dot-docurba.ew.r.appspot.com/trames/projet-a86a9533-a7cc-45ec-ae01-d9125a6a2ba2

**Comment by CeliaVermicelli** [comment]
Même comportement pour un PAC ancien : https://dev-dot-docurba.ew.r.appspot.com/trames/projet-9e9ac7b3-c835-468b-97e2-fb3cd4de673b  (créé en novembre)

Mais ça n'est donc pas un pb de double titres mais plutôt que les nouvelles sections créés au même niveau que les fiches thématique ou doc régionaux apparaissent dans le PDF **que si on les coche deux fois** [voir demo plus complète ](https://jam.dev/c/3dcb45ca-8f65-4661-813c-29562e9b195c) 
-> le pb des doubles titres fonctionne sur ces nouvelles sous-sections. 

@nyko28 as-tu besoin que je fasse une autre issue ? je viens de voir qu'on a aussi ce pb sur la prod.

**Comment by nyko28** [comment]
@CeliaVermicelli merci pour les retours ! Je vais checker ça, pas besoin de créer une autre issue

**Comment by HermanceGauth** [comment]
J'ai l'impression que j'ai le problème uniquement quand la section nouvelle à une sous-section sinon elle s'affiche bien

**Comment by CeliaVermicelli** [comment]
Je viens de faire une verif rapide et ça semble tout bon ! :) on peut close l'issue @nyko28 ?

**Comment by nyko28** [comment]
Oui, je ferme, le problème était lié à une mauvaise synchronisation entre la sélection affichée et celle enregistrée en base.
