### ISSUE TITLE
Ajout d'enregistrements SPF & DKIM à nos DNS sur AlwaysData

### ISSUE THREAD

**Issue by NicolasM92** [MTES-MCT/Docurba#468]
Il faudrait ajouter les deux enregistrements suivants :

- SPF :

Type : TXT
HostName : @
Value : v=spf1 include:_spf.google.com ~all
TTL : 1 hour or 3600 seconds

- DKIM : 

Type : TXT
HostName : google._domainkey
Value : v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmVgt6ZaHupgbYbluyjR84JhL2Y0RHXWF4mXBZNluiZ6FE4jd0wZWS5xhPDDrCIN19yjYHsksju7J3UB/dOxHokjLRa/a6EMum29bu1Cabnrzve3wmf2UerarApoWYgySaMLD9n6KfcZqtVaSV7hl+k1zwdUe8hIWH+DMg4l2ZlNbb0ejrCnuNRhvAAmIsW2NUyham37PJrwD0lC4p0r25g/eyuABTJNo4nv0RhX2dUjxG9Exi74V4FJpmbqslVGkNkk5wW/9lZIDmWX71A6QcKkowM1cTnkU2dFFjp6S9T/rX6SMiwCqF8usJ5O5Plc1LPRUVH8Eilenp71UH0gMbQIDAQAB
TTL : By default

**Comment by UngererFabien** [comment]
Ils sont ajoutés, ça peut prendre 24h pour être à jour.
