### ISSUE TITLE
Sections en double dans les PAC

### ISSUE THREAD

**Issue by UngererFabien** [MTES-MCT/Docurba#47]
Sous section du CJ “qu’est-ce qu’un SCoT” en double dans les Socle de PAC : il y a quelque chose qu’on puisse faire ou c’est aux DDT de choisir quelle section conserver et supprimer l’autre ?

**Comment by UngererFabien** [comment]
Il y a plusieurs solutions à mettre en place sur les doublons de manière générale.

Pour le CJ c'est à nous de prendre une décision. Pour le reste:
- [ ] Ajouter une notification sur les sections en double
- [ ] Permettre de choisir facilement une version ou une autre

**Comment by HermanceGauth** [comment]
Ce qu'il se passe aujourd'hui c'est que lorsque l'on rédige directement dans Docurba il se créé un doublon :
- une section vide
- et une autre où on a toutes les sous-sections présentes. 
(Par exemple : deux sections "Qu'est-ce qu'un SCoT" mais seulement une contient les sous-sections "Contenu" etc)
 Il faudrait que ce doublon vide ne se créé pas. Car en voulant le supprimer on peut se tromper et supprimer la section où les sous-section sont présentes et ainsi perdre tout ce qu'on a fait.

**Comment by UngererFabien** [comment]
Je n'ai pas réussi à reproduire le bug mais j'ai rajouté une notification en cas de doublon. Je veux quand même bien une manière de reproduire le bug.

**Comment by CeliaVermicelli** [comment]
ça fonctionne, j'ai juste noter une erreur d'ortho dans le texte d'aide : confusionS ou perteS

Et je pense que ce texte devrait aussi dire _"notre conseil : conserver la section qui comporte des éléments pré-rédigés"_ car les nouvelles DDT ne verront pas forcément le déroulé des sections à ce stade et pourrait directe supprimer la section rédigée sans se poser la question...

![Capture d’écran 2023-10-12 à 12 22 32](https://github.com/MTES-MCT/Docurba/assets/111045572/2dade821-9462-4521-aa14-6e15c3d012c4)

**Comment by HermanceGauth** [comment]
@UngererFabien j'ai fait une vidéo ou je reproduis le bu ici : https://drive.google.com/drive/folders/1eDWbljNWYh8dPTjQU_gZumb0GfdP193l

**Comment by HermanceGauth** [comment]
@UngererFabien Oui je rejoins le commentaire de Celia le texte de l'aide n'est pas adapté car un doublon est vide et l'autre plein (cf ma vidéo) donc avec ce texte d'aide ils risquent de supprimé le doublon plein qui comporte tout leur travail et de supprimer le vide. Ce bug est vraiment embêtant car c'est comme ça que les DDT perdent leur section.

**Comment by HermanceGauth** [comment]
@UngererFabien j'ai vu que c'était passé en prod, je pense que le texte porte vraiment à confusion, il faudrait a minima dire "Vérifiez quel doublon est complet et supprimez l'autre"
