### ISSUE TITLE
Procédures DU | Des procédures secondaires disparaissent et re apparaissent

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#471]
https://jam.dev/c/fc18179b-3882-4754-adf1-1ab30c1b24d6

Cela m'est arrivé déjà une fois en direct lors d'une démo, le user était en partage d'écran, et tout d'un coup il ne voyait plus une procédure secondaire (ex la procédure modif n°3) alors que moi si, puis au bout de plusieurs longues minutes ça finissait par réappraitre.

Dans la vidéo que j'ai faite, c'est à nouveau un cas, je sais que la modif n°1 existait bien or là elle a disparu (je m'étais même notée ça)

Merci !

**Comment by CeliaVermicelli** [comment]
la modification simplifiée nº6 disparait : https://docurba.beta.gouv.fr/ddt/14/collectivites/14620/commune

**Comment by Octaviedebs** [comment]
Alors que moi je la vois au même moment
![Capture d’écran 2024-03-26 à 18 04 13](https://github.com/MTES-MCT/Docurba/assets/144041896/5e404560-ec40-4f1e-a8b6-fc5065e37579)

**Comment by CeliaVermicelli** [comment]
demo au même moment qu'octavie : https://jam.dev/c/8eadf089-97ca-4eab-a405-275753206b6d

**Comment by CeliaVermicelli** [comment]
Pour suivre, Josiane de la DDT pas encore prévenu de la saisie par la CT du coup.

**Comment by Octaviedebs** [comment]
yes j'ai créé https://github.com/MTES-MCT/Docurba/issues/553

**Comment by Octaviedebs** [comment]
je vois donc bien la modif n°6 pour le cas de la commune 14620
