### ISSUE TITLE
Caractère speciaux dans le PDF du PAC : loi C&R

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#473]
On a toujours ces "?" qui apparaissent dans le PDF d'un PAC, tu as une idée du pourquoi @nyko28 
[Lien de ce PAC test](https://docurba.beta.gouv.fr/trames/projet-9e9ac7b3-c835-468b-97e2-fb3cd4de673b)

FYI @HermanceGauth 

![Capture d’écran 2024-03-13 à 19 20 55](https://github.com/MTES-MCT/Docurba/assets/111045572/37a0ce0d-fbf6-44aa-a0d0-560ba0064d5a)

**Comment by nyko28** [comment]
Doublon de #356 

C'est un caractère d'espacement spécial (celui-ci : https://fr.wikipedia.org/wiki/Espace_fine_insécable) qui s'est peut-être glissé là après un copier-coller à partir d'un logiciel. Dans l'immédiat, on peut remplacer ces "faux" espaces par des vrais. Je vais voir si on peut faire en sorte que ça soit bien interprété par le script de conversion PDF.

**Comment by CeliaVermicelli** [comment]
top ! car ça parait pu mais c'est vraiment bloquant ces caractères pour les ddt ; ça ne passe pas du tout avec le préfet donc des ddt on download le pdf, tout copier coller dans un odt pour améliorer la mise en page pour ensuite l'enregistrer en pdf et l'envoyer au préfet. 
[ce feedback utilisateur peut t'interesser. ](https://www.notion.so/docurba/Retours-d-utilisation-outil-des-PAC-utilisation-du-PDF-du-PAC-avec-le-pr-fet-7698923463e84f5096a7f449b82963db?pvs=4)
