### ISSUE TITLE
Préciser le nom des communes déléguées concernées par les procédures

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#475]
Exemple dans https://docurba.beta.gouv.fr/collectivites/200071868
CC des Vallées du Haut Anjou

Retour utilisateur = dans DU Communaux ; on retrouve beaucoup de documents d’urbanisme pour des communes nouvelles comme Erdre-en-Anjou, Val d’Erdre-Auxence et les Hauts-d’Anjou. Pour les documents de ces communes, il est **difficile de savoir quel document concerne quelle commune déléguée (non précisée dans la liste des communes concernées)**. 
Par exemple, est-il envisageable de rajouter le nom de la commune déléguée concernée à côté de « PLU Les Hauts-d’Anjou (49080) »  pour faciliter la lecture ?

**Je l'ai mis en issue car j'avais un doute : est-ce que c'était déjà prévu ?**
Mais je pourrais le basculer dans le notion si c'était pas du tt le comportement attendu

**Comment by Octaviedebs** [comment]
Concerne les communes fusionnées donc je taggue en prio.

J'avais peut être mal compris, mais il me semblait qu'il était prévu d'indiquer le nom de l'ancienne commune (commune déléguée) dans le titre du DU d'une commune nouvelle 

Exemple dans le 49 : indiquer la commune déléguée concernée à côté de « PLU Les Hauts-d’Anjou (49080) ».

Ce qui a été mis en prod c'est le fait d'indiquer, dans les DU, lorsqu'il s'agit d'un DU d'une ancienne commune c'est bien ça ? 

J'avais peut être mal compris - merci pour les précisions ! 

FYI @HermanceGauth

**Comment by HermanceGauth** [comment]
@Octaviedebs Ce qu'il est prévu c'est d'afficher le nom de la commune déléguée quand le DU concerne l'ancienne commune et le nom de la nouvelle commune lorsque le DU concerne la nouvelle commune.
Je vois ici dans les DU communaux certaines mentions aux COMD.Que ce soit directement ou dans les communes concernées. Est-ce que cela te paraît juste?

**Comment by HermanceGauth** [comment]
Petit Jam : https://jam.dev/c/09436ae4-ea2e-474c-9928-ed9a3d1a09c3

**Comment by Octaviedebs** [comment]
Effectivement, c'est plus logique - sinon il y aurait pleins de noms si on mettait ttes les anciennes communes de la commune nouvelle qui a un DU !

**Comment by Octaviedebs** [comment]
Ah yes je regarde la vidéo - et sinon yes ça me parait bon mais je vais écrire un petit email à l'utilisateur, il y a eu bcp de sujets dans ce département il saura vite si c'est bon ou non

**Comment by Octaviedebs** [comment]
Merci pour le jam, yes c'est plus clair ! je ferme l'issue et si l'utilisateur (il met du temps à répondre) revient sur des éléments j'en rouvrirai une le cas échéant
