### ISSUE TITLE
Pb de statuts dans le Doubs (25) : les auxons, Avanne-Aveney, Chaleze 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#476]
Pour info, et pour base de QA suite à MEP du chantier des statuts : 

> Je m'aperçois qu'il y a des communes pour lesquelles le PLU est approuvé et sont indiquées comme étant en cours : par ex: Les Auxons, Avanne-Aveney, Chaleze et encore d'autres.  

-> to do Célia : vérifier les statuts et prévenir Françoise G. de la DDT.

**Comment by HermanceGauth** [comment]
J'ai l'impression que le problème des statuts est résolus en pre-prod mais par contre des procédures secondaires disparraissent

**Comment by HermanceGauth** [comment]
update : statut maintenant "précédent" au lieu de "opposable"

**Comment by Octaviedebs** [comment]
- Les Auxons : opposable et on voit bien la proc. sec
- Avanne-Aveney. : opposable et on voit bien la proc. sec
- Chaleze : opposable et on voit bien la proc. sec

**Comment by CeliaVermicelli** [comment]
ddt prévenue
