### ISSUE TITLE
Besoin de data Outil des PAC - par user -

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#477]
Hello @UngererFabien,

Comme je te disais ce matin, pour palier le fait que la data obtenue de l’utilisation de PAC n’est pas rétroactive sur Metabase, j’aurais besoin des infos suivantes >> **par user** << : 

- Email de l'utilisateur
- Numéro du département (et si quick win pour toi, le nom de la région)
- Nb de PAC créés 
- Nb de modifications de section (trame et PAC confondus si possible) 
- Date de dernière action (ce qui est le plus « quick win » pour toi) 
- Nb de PAC partagés par email,
- Nb de fois que l’utilisateur à téléchargé un PAC pdf.

**FYI nos besoins in fine pour lancer des actions bizdev :** 
* Identifier les users dit « actifs sur le PAC » (= il a créé un moins 1 PAC, il a fait >10 modifications dans sa trame ou dans un PAC, ces dernières activités ont été réalisées il y a moins de 3 mois)
* Identifier les users dit « inactifs sur le PAC » (= il n’a pas fait de modification de sections créé de PAC depuis les 3 derniers mois)

FYI @Octaviedebs et Nicolas que je n'arrive pas à tagguer mais qui est au courant :)

**Comment by UngererFabien** [comment]
Je t'ai envoyé le fichier par mail. Hésite pas si tu as besoins d'aide.

On a pas de stats sur les PDF téléchargés, je vais rajouter un event.

**Comment by CeliaVermicelli** [comment]
top merci @UngererFabien 

Je regarde ça, pour le moment mon unique question : **le premier "filtrer pour créer cette liste a bien été de prendre tous les users qui se sont inscrits en tant qu'"éditeur de PAC" c'est bien ça ?**
(car je vois des personnes qui n'ont pas de PAC créés, ni d'edit de section, ni de date de dernière action, juste pour mon info)

Et donc ; est-ce que la liste inclus les personnes qui ont eu des actions sur l'outil des PAC mais qui n'auraient pas coché "éditeur de PAC à l'inscription" ?

**Comment by UngererFabien** [comment]
J'ai pris toutes les DDT, je n'ai pas filtré sur leur poste. Je te rajoute cette colonne.
