### ISSUE TITLE
MAJ de l'enregistrement SPF 

### ISSUE THREAD

**Issue by NicolasM92** [MTES-MCT/Docurba#478]
Voici une proposition pour la MAJ de l'enregistrement SPF évoqué ce matin avec Fabien : 

v=spf1 include:spf.sendinblue.com include:_spf.google.com ~all

Les autres paramètres restent identiques.

**Comment by UngererFabien** [comment]
@NicolasM92 Je close vu que la valeur est bonne dans les records, hésite pas à re ouvrir si il faut les changer.
