### ISSUE TITLE
QA PAC options d'édition (mini-détail) : icone pour fixer la première ligne du tableau

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#482]
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/a2dfe769-e989-48d3-8160-8662b570b1aa)
C'est un mini détail mais il me semble que l’icône pour bloquer la première ligne (le 3e) n'est pas le bon

**Comment by CeliaVermicelli** [comment]
je rejoins Hermance. 

Et la dernière icône est pour l'instant "off" c'est ça ? je n'ai pas réussi à savoir comment l'activer pour effectivement moduler la largeur des colonnes

**Comment by nyko28** [comment]
Pour l'instant la largeur des colonnes n'est pas modifiable. La dernière icône permet de fusionner et séparer les cellules sélectionnées. Pour qu'elle s'active il faut sélectionner 2 cellules (avec la souris, comme si tu sélectionnais du texte)

**Comment by CeliaVermicelli** [comment]
ah ok bien sûr ! je n'avais pas interpréter l'icone de la bonne manière, my bad !
