### ISSUE TITLE
Bug FRP : seul l'event "autre" est proposé sur une proc de mise en compatibiltié pour un SCoT

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#491]
Lien FRP : https://docurba.beta.gouv.fr/frise/257c0cbe-def9-48fb-9e65-60cac11a8d3a

Demo jam : https://jam.dev/c/dccc59b6-0cc4-44ba-b6f8-3987e84266d5

(Arnaud - 81)

**Comment by lerayj** [comment]
#499

**Comment by lerayj** [comment]
Un scot qui a une mise en compatibilité ce n'est pas possible.

https://docs.google.com/spreadsheets/d/1zgC0vMOh-VPxUeboYz8gi0Tz5Xs5yxDdno1gUi26C9E/edit#gid=518812151 

On a pas renseigné cette possibilité pour la suggestion d’event. C’est un oubli ou c’est une erreur de la ddt ?
Si c'est une erreur de la ddt on peut changer le type et sinon il faut remplir les events a sugéré dans le spreadsheet pour les mise en compat scot.

**Comment by CeliaVermicelli** [comment]
@HermanceGauth je veux bien ton avis sur le fait qu'une proc de mise en compatibilité ne soit pas possible pour un SCoT, avant d'aller revérifier auprès d'Arnaud qui est normalement toujours juste dans ces retours comme tu le connais :) 


Pour info la page de l'EPCI ne charge pas, et avec le nouveau Dashboard je rentre par le PETR donc je ne verrai pas le SCoT en question de toute façon (si j'ai bien suivi notre problème d'affichage) : 



![Image](https://github.com/MTES-MCT/Docurba/assets/111045572/f432ce2f-7eca-493b-84b6-a8dc9fab6fb7)

**Comment by HermanceGauth** [comment]
Si une mise en compatibilité est bien possible pour un SCoT. Le problème vient du fait que je n'avais pas travaillé les event suggéré pour les SCoT car je pensais qu'on l'implémenterai plus tard, donc les propositions dans la liste et dans les event suggéré ne sont pas bonnes. Je vais faire un travail sur le tableau d'event cette semaine pour implémenter les nouveaux event demandé sans attendre la prochaine version de la FRP. Julien pourra refaire tourner le script pour implémenter les events manquant assez rapidement.

**Comment by CeliaVermicelli** [comment]
ok top @HermanceGauth merci ! je préviens Arnaud que ça sera complété prochainement :)

**Comment by HermanceGauth** [comment]
@lerayj vu :
- que le system d'event suggéré ne fonctionne pas vis-à-vis des event Sudocuh
- qu'il y a peu de nouvelles procédures de SCoT et qu'elles ne peuvent pas être créé depuis Docurba
- que c'est très long pour moi de remplir les colonnes scope-sugg et scope-liste
Est-ce que ce serait possible de remplir que le scope liste pour les SCoT et qu'on ait aucun event suggéré?

**Comment by HermanceGauth** [comment]
Du coup j'ai rajouté quelques event pour les mises en compatibilité dans les event SCoT ici : https://docs.google.com/spreadsheets/d/1zgC0vMOh-VPxUeboYz8gi0Tz5Xs5yxDdno1gUi26C9E/edit?pli=1#gid=518812151
histoire que cela donne moins l'impression d'un bug. Pour aller vite, je me suis basé sur ce qui existe pour les PLU(i) donc on aura sûrement des retours. Reste qu'ils peuvent utiliser "autre" si besoin, et je ferai un truc plus propre lorsque les deux premiers points de mon message précédent auront évolués.

Et j'ai fait une issue en parallèle pour la mise à jour globale des events : https://github.com/MTES-MCT/Docurba/issues/575, donc @CeliaVermicelli je propose de closed celle-ci si tu es ok?

**Comment by CeliaVermicelli** [comment]
yes très clair pour moi. 
Je préviendrai Arnaud que la liste bientôt en prod est une V1
