### ISSUE TITLE
Metabase et filtrer à la région : le champ "région" n'est pas renseigné sur les profiles

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#493]
Hello @UngererFabien, 

Dans la continuité du travail de Nicolas sur le dashboard DREAL je me rends compte que le champs "région" des utilisateurs inscrits après le 12 septembre n'est pas renseigné (voir capture d'écran et [demo jam](https://jam.dev/c/5434a664-867e-4b7a-a787-1d11eb818215) faite à Nicolas pour l'exemple de l'Aura - écouter surtout à partir de 1:02 )

-> toutes nos questions qui utilisent le filtre par région sont faussées. 

Donc est-ce que ça serait possible de renseigner le champ **région** pour tous les users qui on select un département : 
* de manière rétroactive et s'assurer que ça soit bon pour la suite ?
* sur le side etat mais aussi le side collectivité (aujourd'hui seul le agent inscrit en "DREAL" on le champ région renseigné automatiquement). 

FYI @Octaviedebs 

[Question Metabase](https://docurba-metabase.osc-fr1.scalingo.io/question/60-liste-dagents-de-ddt-m-deal-dreal-inscrits)
![Capture d’écran 2024-03-25 à 12 06 41](https://github.com/MTES-MCT/Docurba/assets/111045572/f7e5d4ba-3e96-464d-a42f-8153067fe6f2)

![Capture d’écran 2024-03-25 à 12 19 38](https://github.com/MTES-MCT/Docurba/assets/111045572/b5f6b6f7-f066-4a80-b4fb-64d328dc53a1)

**Comment by Octaviedebs** [comment]
Nicolas M je rejoins célia sur les points soulevés

Le filtre région a peu d'intérêt si ce champ manque sur des profiles.

Par ailleurs j'ai remarqué qu'**il manquait des Code départements sur des Profiles : aucun code département sur des Profiles entre le 10 janvier et mi mars je crois : pourquoi ? https://docurba-metabase.osc-fr1.scalingo.io/question/88-liste-inscrits-ct-be**


Concernant ce champ Région notamment sur le tableau de bord bizdev : pourquoi la liste Région qui apparait ressemble à la liste de départements ?  S'agit-il bien des codes régions ? Est-ce qu'on ne pourrait pas juste afficher les codes régions pour plus de lisibilité ?

**Comment by UngererFabien** [comment]
J'ai mis à jour la BDD avec les départements et les regions. Pas besoins d'attendre la mise en prod.

J'ai remarqué qu'il y avait 72 profiles qui n'ont ni departement, ni region ni colectivite. Je ne sais pas quoi en faire. Une majorité sont des test.

**Comment by Octaviedebs** [comment]
Tu as la liste sous la main ?

**Comment by CeliaVermicelli** [comment]
@Octaviedebs voici la liste des users que je trouve sans département, il y en a une trentaine (sans test) : https://docurba-metabase.osc-fr1.scalingo.io/question/175-user-avec-dpt-vide

on peut les cleaner ensemble via le superadmin si ça te va et on en profite pour relancer ces users qui correspondent aux toutes premières CT/BE

**Comment by Octaviedebs** [comment]
@CeliaVermicelli tqt je m'en occupe  je viens de checker et ils sont aussi dans **la liste que j'avais extraite au séminaire** de user side collectivité sans poste que je dois cleaner justement ( avec comme objectif dans cette liste de supprimer les comptes qui n'iont pas de collectiivté ID ni de poste ET envoyer un email groupé pour qu'ils se créent un nouveau compte )
je checkerai après si la liste sans dpt est bien cleanée du coup !
