### ISSUE TITLE
Bug maj d'une trame dpt avec les éléments de la région au niveau du cadre juridique : crée des doublons dans le CJ

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#494]
Voir demo : https://jam.dev/c/2b317c46-df55-4051-bfc2-16cffcf70162
FYI @HermanceGauth @UngererFabien

**Comment by nyko28** [comment]
Pour repréciser le bug :
Le problème est la création de doublon suite à l'acceptation de section fantôme. Lorsqu'on "accepte" une section fantôme de la trame régionale sur la trame départementale, on copie la section via l'API Github. Un doublon apparait si la section copiée est la sous-section d'une section qui n'a pas d'enfant dans la trame départementale.

Autre point relevé : 
Dans le jam, le problème concerne des sections du Cadre juridique. Les sections fantômes dans le CJ n'auraient pas dû apparaitre étant donné que le script de merge automatique du CJ est censé avoir fait le travail de fusion. C'était dû à un problème de permission de la Github Action du repo France-PAC (ce point est désormais réglé)

**Comment by nyko28** [comment]
Résolu dans la PR #487 : désormais, lors d'un premier ajout de sous-section fantôme, on déplace le fichier de la section parente dans le nouveau dossier en tant que `intro.md` (comportement identique lors de l'ajout classique d'une sous-section quand la section parente n'est pas encore un dossier)
