### ISSUE TITLE
FRP (bug): améliorer la visualisation des event lorsqu'il y a bcp de pièces jointes

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#495]
[FRP concernée ](https://docurba.beta.gouv.fr/frise/3d9a887a-efca-4f97-b997-0aeb672ace66) ddt 81

* Insérer un "voir plus" au niveau de l'event pour pouvoir dérouler les pièces jointes et les télécharger? 
* Insérer un "voir plus" ou menu déroulant dans l'encart des "ressources" à droite ?

![Capture d’écran 2024-03-25 à 23 07 15](https://github.com/MTES-MCT/Docurba/assets/111045572/d2441a73-56e5-440f-ade9-ad180e6a6486)

FYI @Octaviedebs 
(aussi top de voir la CT et la DDT ajouter des event l'un à la suite de l'autre !)

**Comment by julienzdocurba** [comment]
Je pense que le mieux c'est juste de les faire revenir à la ligne:
<img width="797" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/0053942c-5ca5-417f-8e09-0baa4d4a40cb">


Dites moi ce que vous en pensez!

**Comment by CeliaVermicelli** [comment]
QA mep du 29.08 : on a toujours le même problème.

<img width="1254" alt="Capture d’écran 2024-08-29 à 4 28 49 PM" src="https://github.com/user-attachments/assets/e67869f7-96d2-4896-b489-b44b8ea981b8">

**Comment by HermanceGauth** [comment]
@CeliaVermicelli peux-tu regarder en pre-prod car à un moment c'était ok en pre-prod?

**Comment by CeliaVermicelli** [comment]
pas résolu sur dev non plus 
https://dev.docurba.beta.gouv.fr/frise/3d9a887a-efca-4f97-b997-0aeb672ace66

<img width="1163" alt="Capture d’écran 2024-09-03 à 11 17 09 AM" src="https://github.com/user-attachments/assets/47b0b719-03fb-44c2-98d3-0ed9f22869f6">

**Comment by HermanceGauth** [comment]
@lerayj est-ce que c'est passé en prod avec le partage de procédure?
