### ISSUE TITLE
Wording : collectivité connectée "Feuille de route partagée" doit remplacer "Feuille de route publique"

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#498]
Lorsqu'on est connecté en tant que collectivité, on devrait avoir feuille de route partagée (en opposition à ce qu'on voit en mode public)
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/64b155b1-cdcb-478e-80c0-94e1d95d19bd)

**Comment by Octaviedebs** [comment]
@UngererFabien Est-ce que ce serait possible de corriger ça ? J'ai l'impress° que c'est vraiment un quick win

**Comment by UngererFabien** [comment]
J'ai mis feuille de route partoout en attendant de simplifier ce systeme coté code.

**Comment by HermanceGauth** [comment]
Ok pour cette solution de contournement temporaire, je mets un feedback notion pour qu'on n'oublie pas, et si tu as déjà une idée de quand on pourra en reparler?
