### ISSUE TITLE
FRP BUG | Ajout nouvelle procédure secondaire : plus d'évenements disponibles dans la liste (juste AUTRE)

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#499]
Hello ! 

En ajoutant une nouvelle procédure secondaire, je me suis rendue compte qu'ensuite dans la liste des evenements il n'y avait plus de choix a part Autre

https://jam.dev/c/be2a0861-08f8-474f-9983-d2df944a67a6

**Comment by lerayj** [comment]
#491

**Comment by Octaviedebs** [comment]
Résolue je ferme
