### ISSUE TITLE
Banner Flash Info

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#501]
Copy du banner : 

Découvrez les nouveautés de Docurba, rejoignez-nous pour le Flash Info. [Détails et inscriptions ici.](https://app.livestorm.co/mte/flash-info-de-docurba?type=detailed)](https://app.livestorm.co/mte/flash-info-de-docurba?type=detailed)

 **Règles d'apparition :** 
* imposer le banner sur la page d’accueil et en mode connecté jusqu’au 18 avril 13h (je me chargerai de te rappeler de l'enlever :), 
* ne pas le supprimer une fois qu'ils ont cliqué sur le lien,
* supprimer le banner existant "zoom sur les nouveautés" (celui ci disparait une fois qu'on a cliqué dessus une fois mais bcp d'utilisateur l'on encore sur leur espace.

**Comment by Octaviedebs** [comment]
@UngererFabien le banner n'apparait jamais de mon côté

- ni sur mon compte en mode connecté
- ni en me créant un nouveau compte 

@CeliaVermicelli tu le vois toi ?

**Comment by CeliaVermicelli** [comment]
ah effectivement, je le voyais sur mon espace connecté DDT donc je n'ai pas re-vérifié en mode public et CT/BE, mais je ne le vois pas non plus
![Capture d’écran 2024-04-08 à 15 37 13](https://github.com/MTES-MCT/Docurba/assets/111045572/eee0f41e-8e68-46de-8146-1b823f8212d9)
 ! 

![Capture d’écran 2024-04-08 à 15 36 55](https://github.com/MTES-MCT/Docurba/assets/111045572/6b67aac3-699f-4c3a-8fa4-0001a9267fdf)

**Comment by Octaviedebs** [comment]
@CeliaVermicelli je pense pour le coup que par rapport à ta phrase _imposer le banner sur la page d’accueil **et** en mode connecté_  => pour fabien c'était une condition cumulative, donc je pense que c'était le comportement compris par fabien (que en mode connecté)

En revanche je pense @UngererFabien qu'effectivement tu as juste restreint aux services de l'état

Sur l'accès en mode public => perso je suis assez pour
