### ISSUE TITLE
QA PAC : les anciens PAC que l'on a créé ne s'ouvrent pas 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#502]
https://jam.dev/c/06eaf8a4-4d58-4409-b2d3-2db1ac477a45 

Les PAC créés jusqu'à octobre s'ouvrent
Mon PAC créé en aout ne se charge pas 
Les PAC que l'on m'a partagé même en 2022 s'ouvrent bien 

FYI @HermanceGauth

**Comment by CeliaVermicelli** [comment]
Sur mon compte de DDT 08 : 
16 octobre : https://docurba.beta.gouv.fr/trames/projet-0ce0979d-7d20-4a18-a78a-d264e3fd0ecb
novembre : https://docurba.beta.gouv.fr/trames/projet-255ad0a7-5ac9-482c-af64-ab93efab86fa
3 aout : https://docurba.beta.gouv.fr/trames/projet-2884cba0-085d-4a13-8a5b-bbefac2df129 -> NE CHARGE PAS 
janvier 2023 : https://docurba.beta.gouv.fr/trames/projet-cdd3c2f8-6d87-4e9b-86ea-d091e9fa3e6b -> NE CHARGE PAS

mars 2023 : https://docurba.beta.gouv.fr/documents/projet-61947412-831f-4664-90e1-11d291bf40bd/pac -> **ancien** mais créé par ddt 63, le PAC charge correctement

**Comment by UngererFabien** [comment]
Problème réglé en prod. Il y avait 4 projets avec des code collectivité à 4 chiffres au lieu de 5. Aucun impacte pour les utilisateurs je pense.

**Comment by Octaviedebs** [comment]
Hello @UngererFabien je me suis mise sur un accès DDT 08 pour tester, et 3/4 fonctionnent sauf erreur de ma part

En effet janvier 2023 : https://docurba.beta.gouv.fr/trames/projet-cdd3c2f8-6d87-4e9b-86ea-d091e9fa3e6b -> NE CHARGE PAS

cf cette vidéo

Merci  !

https://jam.dev/c/84847ed1-09b5-4c5d-90a7-7fa680fbd019

**Comment by Octaviedebs** [comment]
Tout fonctionne, je close
