### ISSUE TITLE
maj des statut : PLUi Questembert annulé (morbihan)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#503]
> Nous avons un PLUi qui a été annulé par la CAA (Questembert Communauté).
> 
> Dans Docurba, j'ai ajouté l'événement "Annulation TA totale". Mais comment faut-il procéder pour que le PLUi n'apparaisse plus opposable ?
> Tous les documents antérieurs redeviennent d'ailleurs opposables : 12 PLU et 1 carte communale.

juste pour penser à le tester quand sera résolu

**Comment by Octaviedebs** [comment]
ok PLUi annulé + et j'ai bien 12 PLU opposables et 1 CC opposable

**Comment by CeliaVermicelli** [comment]
DDT prévenue.
