### ISSUE TITLE
Bug outil des PAC : impossible de mettre un PAC en cours à jour quand le CJ n'est pas à niveau dans ce PAC

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#505]
Ça n’est pas possible de mettre à jour un PAC en cours quand le CJ a été modifié. 
Je comprends que c'est lié au système des notifications de modifications que va débugué Fabien ces prochaines semaines. 

icone pas active (pj 1) 
dates pas correctes. (pj2)

Exemple PAC d'agen en cours : https://docurba.beta.gouv.fr/documents/projet-9d08fb34-8c44-4114-9714-b82c1f0536d3/pac

![Capture d’écran 2024-03-29 à 02 15 22](https://github.com/MTES-MCT/Docurba/assets/111045572/e37e48f1-98ae-4249-a0f8-b789df820240)
![Capture d’écran 2024-03-29 à 02 15 32](https://github.com/MTES-MCT/Docurba/assets/111045572/36f40a80-3e12-4d07-a87c-1da56cb4e437)

note perso : prévenir Emmanuelle quand c'est résolu

**Comment by CeliaVermicelli** [comment]
Update @UngererFabien 


### Au niveau d'une trame : 
je ne peux pas comparer le contenu de ma section avec la trame régionale, l'icône est 
* trame testée : https://docurba.beta.gouv.fr/trames/dept-1
* demo : https://jam.dev/c/656c7416-0243-48c3-bb36-028eaaf6e730
* MAIS : **ce bug n'apparait pas pour toutes les trames ni pour toutes les sections concernées dans cette trame de l'Ain... je ne trouve pas encore la constante.** 

### Au niveau d'un PAC en cours.
pb évoqué initialement dans cette issue : l'icône de comparaison du contenu depuis une section du PAC en cours est inactive donc je ne peux pas mettre à jour mon PAC en cours aux endroits où on m'indique pourtant qu'il y a des actions à mener. 
* testé sur mon compte associé à la trame 44 https://docurba.beta.gouv.fr/trames/dept-44 (le CJ est bien à jour sur la trame)
* demo : https://jam.dev/c/a6abf1a3-8a41-4468-9594-cde59b8b308d


(il y a pas mal d'autres bug/difficultés liés au système de notifications de mises à jour/comparaison de contenu mais je comprends que pour l'instant on laisse de côté - j'attends votre feu vert pour faire une QA plus poussée quand ce sera pertinent)

**Comment by UngererFabien** [comment]
https://www.loom.com/share/81e9092083fd43228a6bf2de5c8bdebf

J'ai ajouter plus de précision dans la notification de différence. Au lieu d'indiquer seulement "Modification au niveau xxx" j'ai rajouter l'indication "Renommée ou supprimée" pour évité la confusion avec l'icone grisé de modification.

**Comment by CeliaVermicelli** [comment]
Trop top cette modif et ce loom ! Merci pour les explications, c'est très clair. 

Par contre : 

### Pour le cas de l'évaluation environnementale du PAC (de Sèvre et Loire. 
Il s'agit en fait de modifications au niveau national (par @HermanceGauth suite à réorganisation de cette section en en mettant une pour la CC et l'autre pour les PLU/PLUi, si j'ai bien suivi) 
Donc il faudrait afficher "Renommée ou supprimée au niveau **national**" car je pense que ça va perturber la DDT de lui indiquer que c'est elle qui a fait ces modif sur sa trame alors qu'elle va devoir retrouver dans quelle section celles-ci sont éventuellement renommée.

**Comment by HermanceGauth** [comment]
Oui effectivement c'est une réorganisation sur la trame nationale pour l'évaluation environnementale qui a été supprimée de cette sections et remise dans des autres sections

**Comment by CeliaVermicelli** [comment]
on affiche toujours "modif au niveau dpt" alors que c'est le national - donc je ne close pas.

**Comment by HermanceGauth** [comment]
@CeliaVermicelli le fait d'afficher "niveau dpt" quand on est au niveau d'un projet de PAC n'est pas faux en soi car la modif fait le parcours : trame nationale > trame régionale > trame départementale > projet de PAC. On n'est pas capable aujourd'hui dans un projet de PAC de remonter à plus d'un niveau, la comparaison se fait par rapport à la trame départementale, sans savoir si ce changement a été fait dans la trame départementale directement ou est un changement répercuté de la trame régionale ou nationale. On propose donc de laisser comme ça en se disant également qu'en affichant le nom de la personne qui a modifié comme cela est prévu depuis quelques temps ça devrait clarifier (exemple : s'ils voient que c'est moi qui ait fait la modif et pas quelqu'un de leur DDT).

**Comment by CeliaVermicelli** [comment]
ok très clair, ça me va ! 
Et effectivement le nom de l'éditeur apportera déjà pas mal de clarté !

donc je close et passe en testé.
