### ISSUE TITLE
Bug nom procédure DU intercom | CC Isle et Crempse en Périgord | il y a écrit CC au lieu de PLUi

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#506]
https://jam.dev/c/d390e1f4-1442-4e70-9a15-49463e1d4f70

Sur cet EPCI, le titre du document opposable est CC dans l'onglet interco - ça devrait être PLUi

Je me suis mise en pré-prod donc a priori pas de rapport avec ce qui va être passé en prod' sur les statuts vu que le bug existe tjrs

J'aurais besoin de savoir ce qu'il en est (si créa° d'issue ou non) avant que je shoote mon email (j'attendrai du coup probablement)

**User : Céline DOMARCO**

**Comment by UngererFabien** [comment]
Il faut rajouter le nom de la collectivité porteuse dans le cas d'une procédure Interco qui n'a pas de nom.
