### ISSUE TITLE
Bug (prio) | Partage du PAC en mode lecture ne fonctionne pas 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#507]
Exemple pris : partage d'un PAC à la collectivité Abainville dans le 55

- Hermance m'a partagé un PAC 
- impossible d'y accéder en cliquant sur le lien de l'email **Page non trouvée**

Précision : 
- j'ai essayé en étant déjà connectée sur l'accés connectée de cette CT
- j'ai essayé en étant pas connectée sur cet accès

Dans les 2 cas on a accès à rien

Cf cette vidéo
https://jam.dev/c/4fcb025a-c046-4eb9-950e-258853914151

![Capture d’écran 2024-04-02 à 12 01 57](https://github.com/MTES-MCT/Docurba/assets/144041896/ce27e6db-cdba-431c-9c8e-a2f649808607)

**Comment by CeliaVermicelli** [comment]
Fonctionne côté partage à une DDT, il manque juste le champ du département dans l'email : 
![Capture d’écran 2024-04-15 à 19 27 29](https://github.com/MTES-MCT/Docurba/assets/111045572/83255bc9-10f2-47e6-afb6-475314b9f7a0)

**Comment by Octaviedebs** [comment]
3 points côté CT : 

- si j'ouvre le lien (en mode naviga° privée) comme si j'étais pas connectée : j'atteris sur la page d'accueil => il faudrait attérir sur la page de sign in 

- si j'ouvre le lien alors que je suis connectée sur la commune concernée par le PAC : je n'accède pas au PAC, j'atteris que sur le tableau de bord de la CT
<img width="848" alt="Capture d’écran 2024-04-16 à 09 23 32" src="https://github.com/MTES-MCT/Docurba/assets/144041896/753e30fa-0966-42ab-9013-5d564a3983fd">

https://jam.dev/c/6454d44e-a5f9-4cae-85ff-b877930e02f1 

- il manque aussi le département dans l'email de partage

**Comment by Octaviedebs** [comment]
> _lorsque l'user n'a pas de compte on est renvoyé à la page d'accueil, mais sauf erreur de ma part, c'est bien le comportement attendu pour le moment (en attendant la MEP du dashboard où l'on aura une popup d'invitation à créér un compte ?_

Pour moi non ce n'est pas le comportement attendu sauf erreur de ma part = car  le partage d'un PAC ça sera comme le partage sur une FRP on t'invite juste de cette même façon à te créer un compte (mais ce sera pas « partager mon pAC » mais juste « inviter sur ma procédure » donc il faudra bien atterrir sur la page de sign in au clic sur le CTA dans l'email

**Comment by UngererFabien** [comment]
A voir pourquoi la trame ne se charge pas pour un compte CT.

**Comment by UngererFabien** [comment]
- [ ] Ajouter le numéro de dept dans l'email 
- [ ] Changer l'URL de navigation dans le template d'email lecture.
- [ ] Creer une issue sur le search de section de pac qui n'a pas l'air de fonctionner.

**Comment by CeliaVermicelli** [comment]
C'est fonctionnel, je close. 


Note pour info :
Lorsqu'un PAC partagé en mode lecture : 
* à une CT sans compte -> depuis l'email -> redirection vers le PAC en mode lecture. (et non à la page de signup comme initialement prévu) 
* à une CT en mode connectée -> depuis l'email -> redirection vers le PAC en mode lecture. Problème : ce n'est pas possible de retrouver ce PAC depuis le TDB "Ma collectivité", il faut forcément retrouver l'email reçu ou bien conserver l'url. 

FYI @julienzdocurba : j'ajoute ces éléments dans le backlog en vue de l'amélioration du tdb CT/BE : [dans cette carte](https://www.notion.so/docurba/Un-user-CT-BE-ne-peut-pas-retrouver-un-PAC-qu-on-lui-a-partag-par-email-en-mode-lecture-depuis-son--09aa0a1ad0c44293aceef22c42898590?pvs=4)
@Octaviedebs

**Comment by julienzdocurba** [comment]
@CeliaVermicelli Ca devrait être résolu avec les dashboards non?

**Comment by Octaviedebs** [comment]
@julienzdocurba je n'ai pas souvenir qu'il soit prévu dans le dashboard CT qu'il y ait un onglet PAC partagé : on se trompe ?

**Comment by julienzdocurba** [comment]
Non mais tous les PAC se retrouveraient dans les procédures non?

**Comment by CeliaVermicelli** [comment]
ça vous dirait de faire un call rapide à un moment pour mettre à plat ces quelques éléments et ce qui est prévu en terme de temporalité ?

**Comment by julienzdocurba** [comment]
Oui pas de problème, dites moi quand vous êtes dispos.

**Comment by Octaviedebs** [comment]
Fin de matinée à partir de 12h ou à partir de 17h aujourd'hui ?

**Comment by julienzdocurba** [comment]
17h si ca vous va!
