### ISSUE TITLE
Rechcher Corse non fonctionel

### ISSUE THREAD

**Issue by UngererFabien** [MTES-MCT/Docurba#51]
Corse : la recherche par commune ne fonctionne pas, Rien ne se passe au clik sur “rechercher” + cf capture d’écran

**Comment by UngererFabien** [comment]
Devrait être résolu dans le dernier passage en prod. Je n'ai pas réussi à test dans le train.

**Comment by CeliaVermicelli** [comment]
@UngererFabien la recherche par commune ne fonctionne pas à nouveau (Pas de pb pour les EPCI). 
Le click sur "rechercher" n'aboutit pas après avoir sélectionné une commune (dans le 2A ou 2B même problème)

CF PJ

![Capture d’écran 2023-10-09 à 09 47 55](https://github.com/MTES-MCT/Docurba/assets/111045572/4665c1c7-c0df-4d40-aad0-bbcc146deaad)

**Comment by UngererFabien** [comment]
J'ai passer un fix en pre-prod. Cause très improbable sur les validateurs de formulaire.
