### ISSUE TITLE
QA statuts procédure : cas de Taïx dans le 81 : statut en cours au lieu de opposable

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#510]
https://jam.dev/c/16735b25-d49a-4b68-b402-4a447cfd255f

**Comment by HermanceGauth** [comment]
issue initiale https://github.com/MTES-MCT/Docurba/issues/492

**Comment by lerayj** [comment]
Revoir le calcul des status quand ce sont des events Docurba  avec le nouveau modèle

**Comment by UngererFabien** [comment]
@HermanceGauth j'ai laissé un commentaire ici: https://github.com/MTES-MCT/Docurba/issues/492
