### ISSUE TITLE
QA statuts procédure : cas CC Saint Cyr Mère Boitier entre Charolais et Mâconnais - PLUi sectoriels : statut précédent au lieu de oppoable

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#514]
alors que résolu un temps cf l'issue initiale : https://github.com/MTES-MCT/Docurba/issues/438
https://jam.dev/c/018d7231-4831-4221-92ba-7ca2461bf8d2

**Comment by HermanceGauth** [comment]
Pour mémoire un troisième cas similaire : https://jam.dev/c/2b35327b-c864-4c67-b64c-583f0ab59aff
issue initiale : https://github.com/MTES-MCT/Docurba/issues/447

**Comment by Octaviedebs** [comment]
CC Saint Cyr Mère Boitier ok 2 plui sectoriels opposables
