### ISSUE TITLE
QA Doublons procédure | Un doublon sur une procédure secondaire subsiste + je ne peux y accéder

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#516]
Cette issue est en lien avec celle ci qui avait été closed : https://github.com/MTES-MCT/Docurba/issues/467 
EPCI concerné : https://docurba.beta.gouv.fr/collectivites/200067783

La partie sur la maj des statuts est bien correcte ✅

En revanche dans l'issue j'évoquais un doublon sur la procédure secondaire Modification simplifiée du 1er PLUi et il n'y a pas de changements + je n'ai pas eu d'autres précisions de votre part sur ce sujet.

Voici le jam expliquant le souci : https://jam.dev/c/285565ee-3ce6-4732-94d0-8bc7f5d65d75
- il y a 2 modifications simplifiées 
- je peux accéder à la seconde qui semble provenir de sudocu
- je ne peux pas accéder à la première et donc je ne peux pas voir s'il s'agit d'une procédure créé sur docurba // je ne peux pas avoir accès aux events de la FRP et voir s'il y en a qui ont été ajoutés = je ne peux pas comparer les deux pour voir laquelle doit être supprimer 

Pouvez-vous m'aider ?

**Comment by UngererFabien** [comment]
Les deux procédures simplifiées sont des procédures Sudcuh. Je ne sais pas pourquoi la première ne charge pas. Je dois investiguer et je te tiendrais au courrant.

**Comment by Octaviedebs** [comment]
Ok, pour info l'utilisatrice me disait qu'il s'agissait bien d'un doublon du coup (et les communes concernées sont d'ailleurs les même). J'attends ton investigation du coup tu me diras ! merci

**Comment by UngererFabien** [comment]
A voir avec @HermanceGauth pour définir le process dans ce genre de cas qui doit être une erreur DDT. Ici il faut le corrigé dans Sudocuh selon moi. Si on corrige dans Docurba la procédure en double reviendra à chaque mise à jour du dump tant quelle sera dans Sudocuh.

**Comment by HermanceGauth** [comment]
Yes quand l'erreur vient de Sudocuh, il faut la corriger dans Sudocuh donc voir gentiment avec la DDT concernée.

**Comment by CeliaVermicelli** [comment]
ok donc @Octaviedebs ok pour toi que je vois avec la DDT ?

**Comment by Octaviedebs** [comment]
yes bien sûr

**Comment by lerayj** [comment]
Il y avait un problème par rapport à la gestions des pièces jointes lorsque la procédure n'en a aucune. 
Il me semble que pourtant beaucoup de procédures n'ont pas de pièces jointes et fonctionne quand meme - ca serait bien de double check ca.
Sinon c'est fix en local et passera en prod mercredi.

**Comment by CeliaVermicelli** [comment]
ça marche, pour info, j'ai eu le retour de la DDt qui précisait que ces 2 proc. n'étaient pas des doublons mais plutôt liés aux périmètres des EPCI avant leur fusion. -> 

> La communauté de commune de Hanau - La Petite Pierre a élaboré deux PLUI correspondant aux périmètres des EPCI avant leur fusion en application de la loi NOTRE :
> le PLUI du Pays de Hanau
> et le PLUI du Pays de La Petite Pierre.
> 
> Chacun de ces PLUI a fait l'objet d'une modification simplifiée n°1.


donc j'attends la MEP et le dump journalier avant de revenir vers eux pour vérification.

**Comment by CeliaVermicelli** [comment]
@lerayj 
Après vérification avec la DDT sur sudocuh : 

Sur Sudocuh il y a une seule modification simplifié n°1, pour le PLUI du Pays de La Petite Pierre et une seule modification simplifié n°1, pour le PLUI de Pays de Hanau. Donc il n y a rien à supprimer sur Sudocuh.
La procédure "en trop" ne semble visible que sur Docurba :/ 

-> je supprime la proc. depuis Docurba et je verrai ce que ça donne jeudi matin. 

![Capture d’écran 2024-04-30 à 18 51 11](https://github.com/MTES-MCT/Docurba/assets/111045572/29951206-8099-4e24-ac9a-4e635c8f123a)
