### ISSUE TITLE
Bug | Page Breuil Barret (85) et PETR Val de Garonne Guyenne Gascogne tournent en rond et n'aboutissent pas 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#517]
https://jam.dev/c/782f6d5a-e40b-4b17-9052-3b0026e8b690

Hello impossible d'accéder à la page de la CA Gaillac Graulhet - je voulais notamment finir la QA de cette [issue](https://github.com/MTES-MCT/Docurba/issues/447)

Merci !

**Comment by Octaviedebs** [comment]
Note à moi meme = Une fois cette issue résolue, finir la QA de cette [issue](https://github.com/MTES-MCT/Docurba/issues/447) et potentiellement la rouvrir le cas échéant

**Comment by Octaviedebs** [comment]
Pour illustrer il y a aussi le cas du Pôle Territorial Val de Garonne-Guyenne-Gascogne (200097335) dont la page tourne indéfiniment aussi


https://jam.dev/c/a57b1121-bb16-4307-9fdd-2206e9de0d85

**Comment by CeliaVermicelli** [comment]
Suite aux saisies de la DDT sur la FRP de Gaillac Graulhet, je vois que la page de la CT s'ouvre bien que ce soit en mode DDT connecté qu'en mode public @Octaviedebs

**Comment by Octaviedebs** [comment]
je viens de re tester du coup et oui effectivement ça refonctionne aussi de mon côté désormais

**Comment by Octaviedebs** [comment]
Je ne ferme pas mais renomme l'issue - car les deux autres epci mentionnés ici continuent à tourner en rond

**Comment by UngererFabien** [comment]
J'ai corrigé la majorité des problèmes de chargements. Pour ce qui est du PETR 200097335 c'est un groupement de groupement je vais faire une nouvelle issue.
