### ISSUE TITLE
Bug Metabase | Problème relatif aux Collectivites ID dans la table Analytics Event qui font exploser les stats à partir de Mars

### ISSUE THREAD

**Issue by NicolasM92** [MTES-MCT/Docurba#518]
<img width="659" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/60889390/725602be-d597-4ddb-ad23-71f6fdbf5b40">

**Comment by NicolasM92** [comment]
Voici les liens des questions : https://docurba-metabase.osc-fr1.scalingo.io/question/76-evolution-nombre-de-consultation-des-donnees-par-mois

https://docurba-metabase.osc-fr1.scalingo.io/question/113-evolution-nombre-de-consultation-des-donnees-par-semaine

**Comment by NicolasM92** [comment]
Ah mince, c'est à faire de votre côté ou du nôtre ?

**Comment by HermanceGauth** [comment]
@NicolasM92 est-ce que c'est bon, si oui peux-tu close?
