### ISSUE TITLE
QA dasboard | onglet "Mes collectivités" - colonne "Procédures"

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#522]
J'ai l'impression qu'on n'affiche pas la procédure opposable et la/les procédures en cours
https://jam.dev/c/5559aec7-b263-46fd-9287-d648565187cb

**Comment by lerayj** [comment]
note a moi meme - on affiche pour le moment toutes les procédures, même secondaire.
On veux faire remonté les principales opposables d'abord et les principales en cours
