### ISSUE TITLE
QA dashboard | Nom de la FRP

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#525]
https://jam.dev/c/b6c20c8d-4074-4b6f-b081-9026140e1de6

**Comment by HermanceGauth** [comment]
KO pour le nom de la FRP (et vraiment très important avant la mep)

**Comment by HermanceGauth** [comment]
Voir aussi cette issue : https://github.com/MTES-MCT/Docurba/issues/651

**Comment by HermanceGauth** [comment]
Il y a encore quelque bug comme ici : https://dev.docurba.beta.gouv.fr/frise/4c7f0af9-000e-4d14-a9b3-d066b183b01b
et le manque de distinction entre PLU et PLUi pour lequel j'ai fait une issue ici : https://github.com/MTES-MCT/Docurba/issues/653
mais c'est déjà une grosse avancée pour que les DDT puissent mieux s'y retrouver donc je passe en testé

**Comment by Octaviedebs** [comment]
J'ai un autre bug ici moi https://jam.dev/c/04395d94-a4f6-4189-a04a-9b63e41c758c

J'ai l'impression qu'il y a encore des cas où le nom du DU n'est pas la CT concernée par le DU, mais la CT porteuse

@HermanceGauth tu veux que je fasse une autre issue du coup ? 
Est-ce qu'on sait pourquoi parfois c'est ok / parfois non ?

**Comment by HermanceGauth** [comment]
@UngererFabien est-ce possible de passer en prod pour les cas que ça a résolu et de continuer à investiguer et résoudre les autres cas?

**Comment by Octaviedebs** [comment]
Du coup pour les cas non résolus où par exemple le nom du DU n'est pas la CT concernée par le DU, mais la CT porteuse = il y a une autre issue ? 
ou besoin d'en créer une ? 
Exemple parmi d'autres ici : https://docurba.beta.gouv.fr/frise/23624500-68b8-41b9-b803-5090562543f3 c'est pas CA du Pays de Saint Malo Agglomération mais Saint-Père-Marc-en-Poulet

**Comment by HermanceGauth** [comment]
Est-ce qu'on pourrait considéré que ce sera résolu avec cette issue : https://github.com/MTES-MCT/Docurba/issues/651 ou selon toi il en faut une nouvelle?

**Comment by HermanceGauth** [comment]
Et j'ai l'impression que vu qu'on a réussi à être précis ici : https://github.com/MTES-MCT/Docurba/issues/634 on devrait réussir à avoir la même chose pour le nom de la FRP?

**Comment by CeliaVermicelli** [comment]
autre cas pas résolu : pour la [Carte Communale de Montgaillard](https://docurba.beta.gouv.fr/frise/27c70aab-d8c7-475e-9968-9ae6e89fa8f7)
<img width="1254" alt="Capture d’écran 2024-06-20 à 6 42 15 PM" src="https://github.com/MTES-MCT/Docurba/assets/111045572/34235e72-baea-44cb-a241-71a6006c4c72">



<img width="1171" alt="Capture d’écran 2024-06-20 à 6 41 55 PM" src="https://github.com/MTES-MCT/Docurba/assets/111045572/17cb7f70-9132-4293-a55d-f3d7a72e9fda">
