### ISSUE TITLE
QA dasboard | onglet "Mes procédures" - colonne "Périmètre"

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#526]
Moins structurant : 
https://jam.dev/c/ee0f1eae-7bd8-42da-a7f7-b04bf7cae1ee

**Comment by Octaviedebs** [comment]
Je passe en Testé - mais j'ai ajouté cette issue pour une typo https://github.com/MTES-MCT/Docurba/issues/625
