### ISSUE TITLE
QA dasboard | onglet "Mes procédures" - colonne "Prescription"

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#527]
La colonne est vide. L'idée était d'afficher la date de la prescription/lancement de la procédure, pour que l'on puisse trier sur cette date en plus de la date du dernier event. Je ne me souviens pas qu'on l'avait déscopé. Si c'est le cas, je pense qu'il faut faire disparaître la colonne car ça perturbe pas mal les utilisateurs quand on a des champs vides comme ça.

**Comment by Octaviedebs** [comment]
**Commentaires de Test** :

- la colonne Prescription est bien remplie
- en revanche, quand la date est invalide, du coup (logique) elle est vide

Actuellement, lorsqu'on arrive dans l'onglet Mes procédures, le tri **par défaut** fait apparaitre en premier les procédures avec date invalide : il faudrait peut être **inverser l'ordre d'affichage ?** 
**La règle pourrait être tri par date de prescription la plus récente par exemple ?** 

Tri par défaut actuellement ça rend ça quand on arrive dans l'onglet Mes procédures

![Image](https://github.com/MTES-MCT/Docurba/assets/144041896/91c7ec81-09bc-4d8e-aba8-1fcc5e72ec12)

**Comment by Octaviedebs** [comment]
@HermanceGauth je ne l'ai pas passé en Testé du coup mais peut être qu'il vaut mieux que je la passe en Testé et que je crée une autre issue de QA sur ce point ? pour voir si on la fait passer ou non dans cette itération ? Je te laisse me dire.

**Comment by HermanceGauth** [comment]
@lerayj je l'a passe en KO et fait le lien avec l'issue sur les event invalid ici : https://github.com/MTES-MCT/Docurba/issues/563 que je passe de P2 à P0 car effectivement il faut régler ce problème d'event invalide avant la mep du dashboard, sinon on ne va avoir en premier que des procédures avec des events invalide

**Comment by lerayj** [comment]
oki je regarde ca
