### ISSUE TITLE
QA dashboard | onglet "Mes procédures" - bouton "Nouvelle procédure" ne fonctionne pas

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#529]
https://jam.dev/c/53d192e1-782e-47be-b1a7-5af79a249004

**Comment by lerayj** [comment]
Debrifé avec @julienzdocurba qui va faire une proposition, on va surement faire une étape intermédiaire ou les DDT devrons choisir sur quel collectivité il veulent créer la procédure

**Comment by julienzdocurba** [comment]
C'est ici sur Figma: https://www.figma.com/design/4W463mFBKoDzf4mgJAhW9y/Docurba-(V2)?node-id=6188-80513&t=g8Nts5qDFr8YSw9L-0
