### ISSUE TITLE
QA Events suggérés (hors sudocuh)

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#532]
**QA :** en lien avec cette ancienne [issue](https://github.com/MTES-MCT/Docurba/issues/465) closed

- **1er test :** ne fonctionne pas 
https://docurba.beta.gouv.fr/frise/55b4635c-1235-4d36-a0e2-c20b27f9e14a
Arradon (56)
Depuis accès CT: 
-PLU
-un seul event Délib de prescription existant
-Suite à l'ajout d'un event transmission du PAC = l'event suggéré reste toujours celui de Delib de prescription
![Capture d’écran 2024-04-08 à 15 18 51](https://github.com/MTES-MCT/Docurba/assets/144041896/fc02fad9-6d30-4b72-8fff-cb1b2b687029)

https://jam.dev/c/f56f9a2b-77ba-4a97-ab10-2f817ca29675

- **2ème test :** fonctionne
-PLU
-https://docurba.beta.gouv.fr/frise/47cc44d1-65e3-476b-8cb1-c7f36226522c

![Capture d’écran 2024-04-08 à 15 24 02](https://github.com/MTES-MCT/Docurba/assets/144041896/cd092920-95ba-4cdf-bca7-7c794d1087ed)
Le bon event suggéré apparait

**Comment by HermanceGauth** [comment]
On y est presque : https://jam.dev/c/cd5d71f1-6e8d-41e5-85f0-61e616070e19

J'ai l'impression que certains event réinitialisent le compteur de la chronologie

**Comment by Octaviedebs** [comment]
Est-ce que ce ne serait pas en lien avec le fait que si on ajoute un event qui ne suit pas forcément l'ordre défini, ou qui saute un order, alors on retombe au début de la procédure ? 

Cela expliquerait mon cas indiqué tout en haut

**Comment by Octaviedebs** [comment]
ahhhh oui oui exact haha ! peut être que ça dépend des phases où on se trouve - je vais essayer d'enquêter

**Comment by Octaviedebs** [comment]
https://jam.dev/c/b251c15c-63b2-42c4-b5d4-710ae6706825

**Comment by Octaviedebs** [comment]
En tt cas à chaque fois que j'ajoute par exemple : 
- transmission du PAC
- dérogation au pp d'urbanisation limitée => consulktation CDPENAF (délai 3 mois) (...)
- Saisine de la CDNPS pour avis 
=> qui ont tous les 3 bien le **champ « scope_sugg » en vide dans la GSheet**
=> j'ai en event suggéré l'event de délib de prescription comme si c'était réinitialisé

Alors que si j'ajoute Saisine de la CDPENAF qui a bien un **champ « scope_sugg » en non vide dans la GSheet** l'event suggéré est ensuite cohérent

**Comment by lerayj** [comment]
@Octaviedebs bien vu c'étais bien le probleme

**Comment by HermanceGauth** [comment]
Encore presque mais j'ai encore trouvé un cas où ça fonctionne pas : https://jam.dev/c/5827a378-cfd9-44b4-bc2c-1653085ad1a7

**Comment by HermanceGauth** [comment]
J'ai l'impression qu'on est retombé sur le niveau d'avant ou on retombait à zéro pour les event non suggérés : https://jam.dev/c/a7d803a3-f132-40f1-9c6c-53cabd871abb

**Comment by Octaviedebs** [comment]
Concernant le cas que tu évoquais où l'event suggéré post saisine de la CNDPS n'était pas le bon => je me demande si ce n'est pas parce qu'il est considéré comme non structurant (structurant > false dans le tableau ) contrairement à transmission du PAC qui du coup est en true.

Mais je n'ai pas re testé + vous en aviez peut être parlé de vive voix déjà

**Comment by lerayj** [comment]
Non, c'est parceque le fichier n'est pas bon, il n'y a pas de "order" sur l'event "Transmission du porter-à-connaissance". Il faut mettre le fichier a jour.
Exemple ou je met l'event d'apres qui a un order:

![Image](https://github.com/MTES-MCT/Docurba/assets/5832419/71c93ee4-ae8e-4bf1-a068-6491bd10a3e8)



![Image](https://github.com/MTES-MCT/Docurba/assets/5832419/397e8250-d0a9-4070-829e-b4f0353826eb)

**Comment by HermanceGauth** [comment]
Désolé j'ai toujours le même soucis quand j'ajoute transmission du porter-à-connaissance je retombe à zéro


![Image](https://github.com/user-attachments/assets/684be941-f1f6-45db-9670-db255ce84799)

**Comment by HermanceGauth** [comment]
Résolu mais j'ai l'impression qu'il y a eu pour effet de bord de recréer ce problème : https://github.com/MTES-MCT/Docurba/issues/499


![Image](https://github.com/user-attachments/assets/575f22cd-b902-4e7a-a40e-aa6b9e7cbd7d)
