### ISSUE TITLE
QA dashboard: Aligner le contenu des lignes collectivités vers le haut

### ISSUE THREAD

**Issue by julienzdocurba** [MTES-MCT/Docurba#533]
Sur les lignes du tableau "Mes collectivités", le contenu semble être centré verticalement:
<img width="1739" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/ea2e36bf-bfa1-4b87-8d0f-c34377044050">

Idéalement, le contenu devrait être verticalement aligné sur le haut de la ligne:
<img width="1528" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/9eb002d8-ba54-4e3e-80be-823a48ba7995">

**Comment by Octaviedebs** [comment]
Je laisse les yeux aguisés de @julienzdocurba trancher haha mais pour moi c'est bien centré !

**Comment by HermanceGauth** [comment]
@julienzdocurba c'était ok pour toi ou pas?

**Comment by julienzdocurba** [comment]
Oui ca a été fix je ferme l'issue!
