### ISSUE TITLE
QA dashboard: Centrer les noms de procédures et leurs labels

### ISSUE THREAD

**Issue by julienzdocurba** [MTES-MCT/Docurba#534]
Les noms de procédures ne sont pas centrés par rapport à leurs labels:
<img width="370" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/7eb302eb-81c9-4a62-a3c0-616858ec6f37">

**Comment by lerayj** [comment]
Ca me parait bon - j'arrive pas a reproduire

![Image](https://github.com/MTES-MCT/Docurba/assets/5832419/23d8e31e-9e86-4c42-8f93-182d9ce96d7b)

**Comment by julienzdocurba** [comment]
Ca a l'air top sur ta screenshot! Je peux plus tester sur dev mais je pense qu'on peut close et je rouvrirai si l'issue se produit de nouveau en prod. Merci!
