### ISSUE TITLE
Affichage des DU de communes fusionnées : exemple du 85, nouvelle communes de Terval et L'aiguillon la Presqu'ile.

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#537]
> Je viens de m'apercevoir que nous rencontrons une difficulté concernant toutes nos communes rattachées aux communes nouvelles.
> A titre d'exemple :
> Commune nouvelle de Terval (La Tardière / Breuil-Barret / La Chapelle aux Lys)
>     Dans Docurba on ne voit que le PLU de La Tardière mais pas la CC de la commune de Breuil Barret. la Chapelle aux Lys est au RNU.

![Capture d’écran 2024-04-08 à 18 27 20](https://github.com/MTES-MCT/Docurba/assets/111045572/d94b4d82-83db-4aaf-bec2-2d385e39cc64)

pour info, la page de Breuil Barret ne s'ouvre pas : voir demo : https://jam.dev/c/51d2afa3-3c73-4538-9632-8248d996399a (je crée une issue.

> Commune de L'Aiguillon-la-Presqu'île (L'Aiguillon sur Mer et La Faute sur Mer)
>     Dans Docurba on ne voit que le PLU de l'Aiguillon sur Mer mais pas celui de La Faute sur Mer

![Capture d’écran 2024-04-08 à 18 33 43](https://github.com/MTES-MCT/Docurba/assets/111045572/dd809692-f594-4902-ac09-2a484537bdc3)

pour info, la page de La Faute sur Mer ne s'ouvre pas non plus : voir demo : https://jam.dev/c/af703b87-7b9f-422e-8b68-6c48976d672b
(-> je comprends que les DU communaux visibles reprennent le nom de la commune nouvelle car elle partage le même numéro Insee avec une des communes fusionnée)

**Comment by CeliaVermicelli** [comment]
Exemple [Terval](https://dev-dot-docurba.ew.r.appspot.com/ddt/85/collectivites/85289/commune) : ça n'a pas résolu sa remarque, cf demo : https://jam.dev/c/23e5a7bb-4d0d-4819-ac05-97106079e7ee 
Exemple [L'aiguillon la presqu'ile](https://dev-dot-docurba.ew.r.appspot.com/ddt/85/collectivites/85001/commune), ça n'a pas résolu non plu : https://jam.dev/c/eed4519a-841b-42f6-9f88-784af7d4e002

@UngererFabien

**Comment by CeliaVermicelli** [comment]
Exemple [Terval](https://dev-dot-docurba.ew.r.appspot.com/ddt/85/collectivites/85289/commune) : on voit toujours que le PLU de Terval et pas la CC de Breuil Barret dans les DU communaux

Exemple [L'aiguillon la presqu'ile](https://dev-dot-docurba.ew.r.appspot.com/ddt/85/collectivites/85001/commune), non plus : il manque le PLU de Faute sur mer dans les DU communaux 

@UngererFabien

**Comment by CeliaVermicelli** [comment]
Suite à la MEP du dump : 
On ne voit pas les DU des communes fusionnées dans les DU communaux

**Comment by UngererFabien** [comment]
#538

**Comment by UngererFabien** [comment]
@HermanceGauth le nouveau fichier à résolus certain cas mais pas ceux-ci. Dans le fichier Sudocuh je n'ai pas ces communes en approuvés ou en cours.

Les solutions que je vois:
- Si on suspècte une erreur dans l'API de Sudocuh. Améliorer le script pour qu'il utilise la donnée brut plutôt que des extract de l'API.
- On corrige à la main puisque je suis presque sur que les procédures existe mais qu'elle sont juste non afficher. Ca sera bien plus rapide mais si il y a plusieurs cas il faut tous les corriger 1 par 1.

**Comment by HermanceGauth** [comment]
@CeliaVermicelli est-ce qu'on pourrait avoir une copie d'écran de ce qu'il se passe côté Sudocuh pour la DDT voir une vidéo depuis la recherche jusqu'au collectivité pour Terval et Aiguillon presqu'île histoire de s'assurer de ce qu'il y a côté donnée brute est ok avant de taper directment dans la données brute?

**Comment by CeliaVermicelli** [comment]
dde faite à la ddt, je vous tiens au courant @HermanceGauth

**Comment by HermanceGauth** [comment]
Ok bon vraiment bizarre qu'on ait aucune trace de tout cela dans l'API.

Du coup @UngererFabien il faut qu'on fasse un choix entre tes deux propositions de solutions.

Ca prendrait combien de temps d'améliorer le script pour qu'il aille taper la donnée brute plutôt que l'API?

Je me demande si ça vaut le coup d'investir du temps dessus si ça ne concerne que les communes fusionnées qui représentent déjà peu de cas? Peut-être que ce sera plus rapide de corriger à la main?

**Comment by CeliaVermicelli** [comment]
je close l'issue, le retour est bien dans [la doc](https://docs.google.com/spreadsheets/d/1ATNoSmDqaWyygGVwU78hE3Og-E_FYapbc_5WMPbDlxo/edit?usp=sharing), également dispo depuis notion > tech > retour à intégrer.
