### ISSUE TITLE
Des pages ECPI/commune ne s'ouvrent pas : exemple de Breuil Barret notamment (85)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#538]
Liste : 

* ~~[Breuil Barret](https://docurba.beta.gouv.fr/ddt/85/collectivites/85037/commune) (commune fusionnée)~~ 
* ~~[La Faute sur Mer](https://docurba.beta.gouv.fr/ddt/85/collectivites/85307/commune) (commune fusionnée)~~
cf issue #537 -> **pas résolu sur le dev quite à QA du 30.04**

et aussi
* CA Gaillac issue #517

**Comment by UngererFabien** [comment]
Doublon avec: https://github.com/MTES-MCT/Docurba/issues/517

**Comment by Octaviedebs** [comment]
Autre exemple : **CA Montélimar Agglomération (200040459)**

https://jam.dev/c/c2c16a2b-37e6-41cb-a031-0a53e4953427

**Comment by UngererFabien** [comment]
Il y avait 2 bug, le premier était sur une limite dans le nombre de procédures qui empaichait les gros EPCI de charger.

Et un autre dans le cas ou une collectivité n'avait pas de procédures, donc tout ce qui est au RNU ou juste une commue fusionné qui était au RNU.

Je vous laisse regarder après le passage en prod et close les autres issues lié à du chargement ? @CeliaVermicelli @Octaviedebs

**Comment by CeliaVermicelli** [comment]
les 3 pages EPCI/communes chargent correctement, je close.

**Comment by CeliaVermicelli** [comment]
@lerayj C'est normal que je ne puisse plus retrouver les communes fusionnées depuis la barre de recherche ? 

Je ne peux pas revérifier en dev si on a accès aux pages de ces communes du coup, exemple avec la recherche de Breuil Barret et la Faute sur mer : 
![Capture d’écran 2024-04-30 à 10 49 49](https://github.com/MTES-MCT/Docurba/assets/111045572/18007ab9-8273-4b67-b67a-0202647e0b15)
![Capture d’écran 2024-04-30 à 10 50 02](https://github.com/MTES-MCT/Docurba/assets/111045572/9778e9b1-5918-4d8e-b032-6d2d6fe3fdb9)

**Comment by CeliaVermicelli** [comment]
et aussi la page de Montélimar agglo (dpt 26) ne charge plus : 

![Capture d’écran 2024-04-30 à 10 53 09](https://github.com/MTES-MCT/Docurba/assets/111045572/80d0117c-5e3c-40f3-b6aa-e48f8d43163f)

**Comment by lerayj** [comment]
Hum pour Montelimar @CeliaVermicelli c'est un autre probleme, elle a trop de procédure dessus du coup ca passe pas en mode "normal" de la base de donnée, il faut que je fasse un workaround. Pour les soucis de communes fusionnées @UngererFabien si tu peux jetter un oeil a ton retour

**Comment by UngererFabien** [comment]
Pour moi, le click sur une COMD devrait renvoyé sur sa commune nouvelle. Ou bien ne pas être dans la liste.

Le status des documents des COMD peu être complétement incohérent sans le status des documents de sa commune nouvelle.

Pour ce qui est du chargement des procédures. J'ai l'impression qu'il y a un effet de bord avec le dump journalier.

**Comment by UngererFabien** [comment]
Petit loom de plus pour après notre enquête avec Julien.

https://www.loom.com/share/d4e85d7affb44d75afa478b628f00967?sid=8396474c-84e0-40a5-9c0e-634a33f3ae08

**Comment by UngererFabien** [comment]
@HermanceGauth nos scripts utilisaient la version CSV. Est ce que tu pourrais les re sortir en version csv ? Sinon j'adapterais les scripts avec ce format de donnée.

**Comment by HermanceGauth** [comment]
@UngererFabien voici les csv

[API_SUDOCUH_DU_rnu_cf.csv](https://github.com/MTES-MCT/Docurba/files/15385554/API_SUDOCUH_DU_rnu_cf.csv)



[API_SUDOCUH_DU_encours_cf.csv](https://github.com/MTES-MCT/Docurba/files/15385555/API_SUDOCUH_DU_encours_cf.csv)



[API_SUDOCUH_DU_approuve_cf.csv](https://github.com/MTES-MCT/Docurba/files/15385556/API_SUDOCUH_DU_approuve_cf.csv)

**Comment by HermanceGauth** [comment]
@CeliaVermicelli est-ce ok de closed cette issue pour garder uniquement celle-ci https://github.com/MTES-MCT/Docurba/issues/537 ou bien on perdrait des infos?
