### ISSUE TITLE
Bug | FRP DDT connecté : impossible d'ouvrir la FRP d'une procédure secondaire

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#540]
Procédure de modification n°1 sur la commune de Névez (29)
https://jam.dev/c/37d65618-0d1c-4657-a61d-37911e61f678

**Comment by UngererFabien** [comment]
Voir si c'est le même problème qu'ici: https://github.com/MTES-MCT/Docurba/issues/516

**Comment by lerayj** [comment]
Il y avait un problème par rapport à la gestions des pièces jointes lorsque la procédure n'en a aucune. 
Il me semble que pourtant beaucoup de procédures n'ont pas de pièces jointes et fonctionne quand meme - ca serait bien de double check ca. 
Sinon c'est fix en local et passera en prod mercredi.

Pour ce cas en particulier, une fois le bug corrigé je suis un peu embêté parce que je n'ai pas d'info en base sur ce qui a été entré comme info sur les evenements et je ne sais pas comment cet utilisateur a réussi a faire des évenements vide. Quand on voit les dates d'ajouts, cet utilisateur a le même problème depuis Octobre.

Il n'y a meme pas d'utilisateur associé. Est ce possible que ca soit des evenements ajouté par @CeliaVermicelli ou @Octaviedebs  ? Je n'arrive pas a trouvé d'explication. De mon coté quand j'ajoute des évènements a cette meme procédure il n'y a pas de soucis.

![Capture d’écran 2024-04-22 à 15 30 34](https://github.com/MTES-MCT/Docurba/assets/5832419/8983fb84-3e20-4709-8a00-b37645e0fe28)

En tout cas, le problème de cette issue est résolu - je close et il faudrait en re ouvrir une nouvelle avec des infos sur cette derniere pour savoir ce qu'il en est.

**Comment by HermanceGauth** [comment]
J'ai regardé dans Sudocuh, je ne trouve aucun évènement pour cette procédure a priori, je demande confirmation au collègue.

**Comment by HermanceGauth** [comment]
@lerayj les dates des event invalide semble correspondre au date des dates. Donc comme la FRP est vide car pas d'event Sudocuh, on a créé un event invalid à chaque import?

**Comment by Octaviedebs** [comment]
@lerayj  pour te répondre aucun event ajouté de mon côté sur cette procédure

**Comment by CeliaVermicelli** [comment]
La modif nº1 ne charge toujours pas : [lien FRP](https://docurba.beta.gouv.fr/frise/180aeaee-a9ee-433a-98d9-a93c2c501acc)
![Capture d’écran 2024-05-08 à 18 41 15](https://github.com/MTES-MCT/Docurba/assets/111045572/759020a3-6471-4084-81df-cb80e9900848)

**Comment by UngererFabien** [comment]
J'ai corrigé je pense mais je ne vois que des events invalide dans cette frise. Très étrange.

**Comment by HermanceGauth** [comment]
@UngererFabien oui cf les message précédents de cette issue et la nouvelle issue créé pour ça : https://github.com/MTES-MCT/Docurba/issues/563
