### ISSUE TITLE
Outil des PAC : comment gérer les notif de modification lors de suppression de section par les niveaux supérieurs ?

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#543]
https://jam.dev/c/79eba843-acac-4417-a8e3-384451236335

![Capture d’écran 2024-04-09 à 16 08 09](https://github.com/MTES-MCT/Docurba/assets/111045572/2ef3d53c-4548-4430-b6ee-cd416a6e38b5)

**Comment by HermanceGauth** [comment]
@julienzdocurba as-tu un avis sur la question? Veux-tu qu'on bascule cela plutôt sur Notion?

**Comment by julienzdocurba** [comment]
Oui c'est pas un bug donc ca devrait aller dans le backlog (et dans le feedback si on a un retour direct) pour être priorisé.

**Comment by CeliaVermicelli** [comment]
dans le backlog, je close
