### ISSUE TITLE
Retours du 30 sur les statuts : Anduze, Castillon du Gard, Vergèze

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#544]
@UngererFabien 
Le dernier travail sur les statuts à bien résolu le problème sur plusieurs CT mais il reste encore : 

- ~~[Anduze](https://docurba.beta.gouv.fr/ddt/30/collectivites/30010/commune) : la révision nº1 du PLU devrait être en statut opposable car delib d'approbation déposée (erreur statut = en cours)~~ -> résolu au 23 avril - statut opposable. DOUBLON APPROBATION
- ~~[Castillon du Gard](https://docurba.beta.gouv.fr/ddt/30/collectivites/30073/commune) : la révision nº1 du PLU devrait être en statut opposable car delib d'approbation déposée (erreur statut = en cours)~~ -> résolu au 23 avril - statut opposable. DOUBLON APPROBATION
- ~~[Vergèze](https://docurba.beta.gouv.fr/ddt/30/collectivites/30344/commune) : la révision nº1 du PLU devrait être en statut opposable car delib d'approbation déposée (erreur statut = en cours)~~ -> résolu au 23 avril - statut opposable. DOUBLON APPROBATION
- ~~[Jonquières St Vincent](https://docurba.beta.gouv.fr/ddt/30/collectivites/30135/commune)  la révision nº1 du PLU devrait être en statut opposable car delib d'approbation déposée (erreur statut = en cours)~~ -> résolu au 23 avril - statut opposable. DOUBLON APPROBATION

note perso : prévenir Carole C. de la DDT quand c'est ok

**Comment by UngererFabien** [comment]
![Screenshot 2024-04-11 at 09 46 43](https://github.com/MTES-MCT/Docurba/assets/2676385/835cbcdd-fc7c-4172-a553-dcabfd8cda1f)

@lerayj il y a une typo dans la liste, "Délibération d''approbation du municipal ou communautaire" au lieu de "Délibération d''approbation du **conseil** municipal ou communautaire"

**Comment by CeliaVermicelli** [comment]
to do celia : prévenir la ddt que tout est ok sur les statuts + prendre la température au sujet des doublons
