### ISSUE TITLE
QA Dashboard | Le tri sur les Procédures ne fonctionne pas 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#545]
https://jam.dev/c/763cf285-89e4-4319-918d-e8c38af4b412

Quand on clique pour trier par procédures, il ne se passe rien cf vidéo

**Comment by lerayj** [comment]
On s'attendrait a quel comportement de tri ?

**Comment by Octaviedebs** [comment]
Aucune idée, je ne sais pas ce qui était prévu - si pas de tri, il faudrait juste enlever la flèche descendante dans le titre de la colonne qui sous entend qu'un tri est possible. 
@julienzdocurba je ne sais pas ce que tu en penses

**Comment by julienzdocurba** [comment]
Oui c'est un bon point, ca fait pas forcément de sens de permettre de trier par procédure ou SCOT. Même par type de collectivité puisqu'on a un filtre pour ca. Du coup le seul qui est intéressant c'est par nom. On peut conserver le tri seulement sur cette colonne je pense (mais on peut aussi le descoper entièrement si c'est lourd à faire, c'est vraiment pas critique):
![image](https://github.com/MTES-MCT/Docurba/assets/147177148/70f170c7-6ae8-44db-9929-7364f7b8a7c8)

**Comment by Octaviedebs** [comment]
J'ai l'impression qu'il y a toujours le petit bug (cf jam) : **le clic sur Type trie par Nom**
https://jam.dev/c/3894c916-0a42-4c33-96ea-d3144758ec5e

Au 1er clic sur Type : la CA La Roche sur Yon disparait, or c'est une CA donc elle devrait rester dans les premiers (on s'attend à voir afficher avec ce filtre les CA > les CC > les COM) : elle apparait plus bas car effectivement son numéro est plus grand

**Je serais d'avis de faire ce que disait Julien Z : permettre juste le tri par Nom, puisque le trie Par type n'a pas trop de sens (et elles peuvent filtrer en ce sens de tte façon)** et donc si on décide de faire ça enlever la petite flèche descendante sur Tri pour que ce ne soit pas confus

@HermanceGauth tu en penses quoi

**Comment by HermanceGauth** [comment]
oui ok pour cette solution

**Comment by UngererFabien** [comment]
@julienzdocurba j'ai retirer le tri par type. C'est volontaire que le tri par noms soit en faite un tri par code insee/siren ?

**Comment by julienzdocurba** [comment]
Oui c'est ce qu'on s'était dit et c'était pour ca qu'on voulait mettre le code INSEE en 1er. Ca te semble bizarre?
