### ISSUE TITLE
Impossible de changer l'odre des sections d'un PAC

### ISSUE THREAD

**Issue by UngererFabien** [MTES-MCT/Docurba#55]
Impossible de changer l’ordre des sous-section dans “main” “qu’est-ce qu’une carte communale” “contenu”

**Comment by UngererFabien** [comment]
J'ai été incapable de reproduire le bug en prod ou en dev sur la trame de test et main.

J'ai vérifié chaque action en base et je ne vois pas d'anomalie non plus. Prêt à réouvrir si il y a une manière de reproduire ce bug.

**Comment by CeliaVermicelli** [comment]
dans pp du terrioire ça ne fonctionne pas 
dans les dispo de doc supra c'est ok ! 

https://github.com/MTES-MCT/Docurba/assets/111045572/96626d74-9bc9-4162-8eee-0503c2e19023

**Comment by UngererFabien** [comment]
Pas de problème sur tous les PAC testés. A réouvrir avec le lien si tu retrouves le PAC sur lequel tu as le bug @CeliaVermicelli

**Comment by HermanceGauth** [comment]
J'ai de nouveau pas pu changer l'ordre de mes sections, je suis dans la trame "Main"/Qu'est-ce qu'un PLUi?/Contenu et je voulais changer l'ordre des sous-sections dans cette section (Rapport de présentation, PADD...)
