### ISSUE TITLE
Sendgrid : maj email lors de PAC mis à jour

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#551]
Hello @UngererFabien, 

Voici les modifications proposées :

- activer le [nouvel email](https://mc.sendgrid.com/dynamic-templates/d-2b1d871bc04141e69c56e5a89dc20a74/version/dce46502-e7df-423e-8542-60b26ac84258/editor) 
![Capture d’écran 2024-04-15 à 17 22 41](https://github.com/MTES-MCT/Docurba/assets/111045572/1e0db3c0-60e5-4143-bd68-a796c2a91253)

- possible de programmer un envoi à J+1 de la première modification effectuée ? (aujourd'hui on reçoit l'email dans la minute même d'une modif) - mais preneuse si tu as une autre recommandation

**Comment by UngererFabien** [comment]
Aujourd'hui on reçoit la notif direct mais pas d'autre notif avant 24h.

C'est difficile de programmer des envois d'emails, si on a pas eu de retours négatifs à ce sujet je pense qu'on peut garder le système actuel.

**Comment by HermanceGauth** [comment]
Seulement le premier point et la notification à J+1 fera l'objet d'une autre issue

**Comment by UngererFabien** [comment]
A passé en prod direct, impossible à test en preprod.
