### ISSUE TITLE
Bug FRP | FRP Saint Maximin la Sainte Baume n'existe pas 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#553]
Hello : 

https://docurba.beta.gouv.fr/frise/9de4a4c5-c957-44d8-89d3-4725d005834b cette FRP existe bien pour Saint-Maximin-la-Sainte-Baume (83116)

mais impossible de retrouver la procédure dans la liste, il s'agit de la Révision allégée n°2 https://jam.dev/c/0fa1080d-76bc-49fe-b81a-614d1328c87e

On a été regardé dans chaque FRP de chaque procédure secondaire et la FRP est introuvable

Si ça peut vous aider

**Comment by lerayj** [comment]
Done - @UngererFabien Il fallait faire une dedup des perimetres et refaire un upsert avec un uniq index sur collectivite_id & procedure_id. 

Note pour moi meme:  A mettre a jour dans le dump journalier pour la prochaine fois

**Comment by CeliaVermicelli** [comment]
![Capture d’écran 2024-04-21 à 12 56 17](https://github.com/MTES-MCT/Docurba/assets/111045572/2020842e-b9ac-42d1-a20f-daec863a176f)
