### ISSUE TITLE
Metabase : le dpt 52 n'existe pas au sein de la région grand est (code 44)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#554]
je fais référence à [cette remarque dans notre suivi notion](https://www.notion.so/docurba/V1-TdB-Metabase-pour-les-DREAL-bf45b22b45fd47faa1c1208d574bf51a?pvs=4#785eb24e0eaa4424b9437bdd55cd8d45)

-> vérifier en BDD si le dpt 52 est bien dans la région 44 car lorsque l'on filtre sur la région 44 dans [le tdb dreal](https://docurba-metabase.osc-fr1.scalingo.io/dashboard/8-statistiques-dutilisation-de-docurba-des-ddt), le dpt 52 n'apparait pas.

**Comment by UngererFabien** [comment]
Le 52 est bien dans la region 44 mais il n'y a aucun event dans le 52 dans la table analytics events.

Département inactif ?
