### ISSUE TITLE
SD : ils doivent se ranger dans l'onglet SCoT

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#556]
exemple = https://docurba.beta.gouv.fr/collectivites/200041325/?isEpci=false 

Il faudrait modifier le statut car ils sont tous en cours au lieu de caduques

**Comment by UngererFabien** [comment]
A fix dans le code du dump journalier.

**Comment by HermanceGauth** [comment]
Je rouvre l'issue suite à de nouveau retour, par ordre de prio :
- les SD doivent s'afficher dans l'onglet SCoT car se sont les ancêtres des SCoT (et non dans l'onglet DU intercommunaux)
- les SD doivent avoir le statut CADUC (ici abandon par exemple) : https://docurba.beta.gouv.fr/ddt/33/collectivites/33122/commune
![image](https://github.com/user-attachments/assets/9f484b24-affa-417a-b953-626685e08111)

**Comment by HermanceGauth** [comment]
Je supprime la deuxième partie de l'issue car je ne suis pas sûre que l'interprétation de la DDT soit la bonne, la procédure n'a jamais aboutit et il y a un event d'abandon donc pour moi le statut abandon est le bon.

**Comment by rik** [comment]
C'est en production !

**Comment by HermanceGauth** [comment]
@CeliaVermicelli cela peut t'intéresser

**Comment by CeliaVermicelli** [comment]
@HermanceGauth merci ! je l'avais spotté via cette issue : https://github.com/MTES-MCT/Docurba/issues/977#issuecomment-2560755582
Pour info, pour le moment je ne préviens pas les personnes concernées car elles avaient aussi eu des retours négatifs sur l'import et vu que là il en fonctionne pas je me mets un rappel pour récapituler les éléments résolu une fois l'import revenu

**Comment by CeliaVermicelli** [comment]
Je me permets un nouveau commentaire car j'allais prévenir la DDT 33 qui m'avait fait se retour mais je pense qu'il reste une mini incohérence dans la présentation de l'info : 

Ça semblerait pertinent de faire de ranger aussi les SD dans la colonne "SCoT" depuis le tdb DDT et non plus dans les PLU, et donc dans le cas de la capture d'écran ci après : on aurait un "+1 procédure" :

<img width="1223" alt="Capture d’écran 2024-12-26 à 12 15 55 PM" src="https://github.com/user-attachments/assets/2a4ae13d-db30-43d7-b4cc-dc63748a5a03" />

**Comment by rik** [comment]
> Ça semblerait pertinent de faire de ranger aussi les SD dans la colonne "SCoT" depuis le tdb DDT

C'est fait ! https://github.com/MTES-MCT/Docurba/pull/1085
