### ISSUE TITLE
Charger les communes des groupements de groupements.

### ISSUE THREAD

**Issue by UngererFabien** [MTES-MCT/Docurba#558]
Exemple: [200097335](https://docurba.beta.gouv.fr/collectivites/200097335/?isEpci=false)

Dans le référenciel c'est un groupement de CA et CC, du coup urbanisator.js essaye de chargé les périm sur une liste de code siren.

Il faut allez chercher les membres des membres pour les groupements de groupements. Et je pense que ça devrait être fait server side dans le service GEO.

**Comment by Octaviedebs** [comment]
note à moi même : résoudra le fait qu'actuellement du coup on affiche rien pour les PETR

**Comment by Octaviedebs** [comment]
Exemple pour un SM https://docurba.beta.gouv.fr/collectivites/254502669/?isEpci=false

**Comment by Octaviedebs** [comment]
SM du SCot d'Autan et de Cocagne concerné également : https://docurba.beta.gouv.fr/collectivites/200003184/?isEpci=false

**Comment by Octaviedebs** [comment]
Quand en prod, contacter mes SM/PETR suivants

- https://docurba2.pipedrive.com/deal/2013
- https://docurba2.pipedrive.com/deal/139
- https://docurba2.pipedrive.com/deal/1497 sur la partie SM SCoT
- https://docurba2.pipedrive.com/deal/1479 
- https://docurba2.pipedrive.com/deal/1931 / https://docurba2.pipedrive.com/deal/1501
- https://docurba2.pipedrive.com/deal/1964
- https://docurba2.pipedrive.com/deal/1499
- https://docurba2.pipedrive.com/deal/989
- https://docurba2.pipedrive.com/deal/1502
- https://docurba2.pipedrive.com/deal/139 (et les communes )

**Comment by Octaviedebs** [comment]
Hello ! En fait j'ai l'impress° qu'il y a un effet de bord - par exemple là je suis sur une CC du Cordais et du Causse, et on affiche aussi le PLUi de la CA Gaillac-Graulhet

https://jam.dev/c/cda6dedb-e501-46a6-8325-46311247f2cb

@UngererFabien je fais en + une issue de QA du coup ? ou je laisse ça comme ça

**Comment by Octaviedebs** [comment]
https://github.com/MTES-MCT/Docurba/issues/610 lien. ?

**Comment by Octaviedebs** [comment]
je la closerai quand j'aurais contacté les groupements que je dois prévenir
