### ISSUE TITLE
Modif du banner suite au Flash Info ! 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#559]
@UngererFabien  Peux-tu modifier le banner présent actuellement stp ?

* Lien à insérer : https://pad.incubateur.net/s/A_BpJ3_NH
* Copy : Regardez le replay du Flash info du 18 avril :[ zoom sur les nouveautés et amélioration à venir.](https://pad.incubateur.net/s/A_BpJ3_NH)

Mercii ! 
FYI @Octaviedebs

**Comment by UngererFabien** [comment]
Ca passe en prod !
