### ISSUE TITLE
Banner dump sudocuh : supprimer le banner dès que le dump journalier sera effectif ?

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#560]
ou bien ce serait possible de mettre à jour la date automatiquement tous les jours @lerayj ?

Si possible de le mettre à jour tous les jours, je trouverai utile que dans cette phase transitoire on précise la date de dernière bascule (on verrait donc la date de la veille tous les jours)
Si pas "quick win", on pourrait mettre ce copy à la place : _L'extract de données Sudocuh vers Docurba est désormais journalier, les données sur Docurba sont donc à jour._ 

@HermanceGauth tu as un avis là dessus ?
Je parle de ça : 
![Capture d’écran 2024-04-18 à 14 42 38](https://github.com/MTES-MCT/Docurba/assets/111045572/ad77fcbf-d949-4cf7-8b63-bd4173826091)

**Comment by HermanceGauth** [comment]
Je crois que ce n'était pas facile de le mettre à jour automatiquement. Donc je serai pour garder effectivement pendant la transition un banner avec la phrase sur l'import journalier

**Comment by HermanceGauth** [comment]
à passer en prod indépendemment dèque possible
