### ISSUE TITLE
QA communes fusionnées | affichage : ex champigné, CC vallées haut anjou

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#561]
Pour que ce soit bien claire, il faudrait afficher uniquement la communes déléguées lorsque c'est elle qui est concernées car on pourrait aussi avoir un PLU en cours sur la nouvelle commune. Exemple ici il faudrait afficher Guipronvel (COMD)

**Comment by HermanceGauth** [comment]
https://docurba.beta.gouv.fr/ddt/29/collectivites/29076/commune

**Comment by HermanceGauth** [comment]
@UngererFabien je l'a mets en testé mais un petit commentaire vis--à-vis de ce que je te disais oralement, il y a une autre issue à ce sujet il me semble : https://jam.dev/c/c82e7fb4-57ef-4dbb-9ea7-d18271547c45

**Comment by HermanceGauth** [comment]
@UngererFabien finalement je m'aperçois d'un soucis, je ne sais pas si c'est lié à ça mais ce n'est pas présent en prod, dis-moi si je dois faire une issue spécifique : https://jam.dev/c/7195b3dc-1b53-4b3f-839c-6b35467d6335

**Comment by HermanceGauth** [comment]
+ deux cas similaires n'ont pas été résolus : https://github.com/MTES-MCT/Docurba/issues/581, https://github.com/MTES-MCT/Docurba/issues/580 alors que celui de Milizac-Guipronvel l'est bien

**Comment by HermanceGauth** [comment]
@UngererFabien j'investigue sur le cas "PLU - CC des Vallées du Haut-Anjou" de mon JAM, je pense que c'est bien un PLU donc à ranger dans l'onglet document communaux (comme c'est bien le cas en prod) mais qu'il y a une erreur dans le nom, je le retrouve bien sur la commune des Hauts d'Anjou sur Sudocuh. Donc ça devrait être "PLU - Les Hauts-d'Anjou" ranger dans les DU communaux. Je ne sais pas si cette erreur est liée au boulot sur les communes fusionnées.

**Comment by UngererFabien** [comment]
@HermanceGauth pour moi ce perimettre est une erreur ou une volonté de gardé un historique. Mais si c'est pour l'hitorique ça ne fait pas de sens d'un point de vu perimetre. Je t'ai fais une explication plus détaillé.

https://www.loom.com/share/8412643f6c8a47d2bedb0aa712dbcdc6?sid=0228c985-d713-4d13-90bf-b0e14061b339

**Comment by HermanceGauth** [comment]
@UngererFabien effectivement je ne pas sûr de comprendre ce que Champigné vient faire là. D'après le site internet de la commune : https://leshautsdanjou.fr/vie-municipale/les-communes-deleguees/ Querré et Champigné ont existé en même temps et ont toutes les deux étaient absorbées par Les Hauts-D'Anjou.
Si c'est une erreur, elle vient de Sudocuh cf mon jam : https://jam.dev/c/93253801-a9ff-4f78-a9ea-931d659a91be
@CeliaVermicelli pourrait-on demander à la DDT ce qu'il en est? Cette procédure concerne-t-elle Champigné et Querré ou que Champigné?

**Comment by HermanceGauth** [comment]
@UngererFabien en fait non l'erreur ne vient pas de Sudocuh après retour de Claire, ça vient de chez nous car dans Sudocuh il n'y a pas trace de Champigné pour cette procédure : https://jam.dev/c/4a390206-1994-48ae-a556-c8677414c3d8

**Comment by UngererFabien** [comment]
Pour info, l'erreur est partagé dans les API Sudocuh. Donc les exports API que tu as fais on retrouve ça:

![Image](https://github.com/MTES-MCT/Docurba/assets/2676385/87a1ef4f-c03b-4e0b-bbb5-528d308b9f71)

![Image](https://github.com/MTES-MCT/Docurba/assets/2676385/856ebf62-aec7-4b15-bdaa-4cf2c76337be)

C'est bien 2x le même numéro de procédure Sudocuh pour les 2 communes fusionnées. C'est une correction à faire manuellement du coup.

**Comment by HermanceGauth** [comment]
Ok ça marche! S'il y a une erreur dans l'API de Sudocuh on peut peut-être aussi le signaler (en plus de le corriger à la main), parce que c'est peut-être pas un cas isolé https://github.com/MTES-MCT/Docurba/issues/604

**Comment by CeliaVermicelli** [comment]
@HermanceGauth @UngererFabien réponse de la DDT 49 : 

Tout d'abord la procédure que tu me présentes sur DocUrba est celle prise en charge par l'EPCI de la CC des Vallées du Haut-Anjou, et non celle de encadrée par les Hauts d'Anjou entre 2006 et 2010 issue de la capture PJ3 de ton mail. Les deux procédures sont différentes mais elles présentent la même particularité sur SuDoCuh concernant les communes concernées :
![image](https://github.com/MTES-MCT/Docurba/assets/111045572/0416f014-edd6-48cf-92b4-11a010209152)

En observant dans le détail pour les communes (2), voilà ce qu'on obtient pour les deux procédures !
![image](https://github.com/MTES-MCT/Docurba/assets/111045572/2d4c7ebb-34e1-4d5f-b9a9-c2f6266b059c)


Donc, je ne vois pas d'où provient la mention de Champigné sur DocUrba car cela concerne uniquement Querré dont la procédure doit bientôt se conclure. La procédure est clairement particulière pour les Hauts d'Anjou et ses communes déléguées mais j'ai plus l'impression que c'est un soucis de périmètre. Sur SuDoCuh, je n'arrive pas à intégrer moi-même cette subtilité de l'infracommunale pour repréciser la commune déléguée dans la procédure. Peut-être est-ce une manipulation que Madame Chaine...

**Comment by UngererFabien** [comment]
J'ai corrigé manuelement. @HermanceGauth le fait que l'erreur soit présente dans l'export me conforte dans l'idée que les API sur les communes fusionnées ne sont pas fiable à 100%. https://github.com/MTES-MCT/Docurba/issues/537

**Comment by CeliaVermicelli** [comment]
FYI j'ai demandé à la DDT si ça lui semblait correct.

**Comment by CeliaVermicelli** [comment]
C'est bon pour la DDT.

**Comment by HermanceGauth** [comment]
@CeliaVermicelli est-ce qu'on peut close cette issue?
