### ISSUE TITLE
Afficher une FRP vide lorsqu'il n'y a pas d'event Sudocuh (cas de la modification n°1 du PLU de Nevez) + attention aux event invalid Docurba

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#563]
Comme dis ici : https://github.com/MTES-MCT/Docurba/issues/540 j'ouvre une nouvelle issue.
Pour cette procédure, il n'y a pas d'event Sudocuh ce qui est potentiellement la raison pour laquelle l'ouverture de la procédure a buggé. Comportement attendu : que la feuille de route s'ouvre quand même sur du vide pour que l'on puisse voir cet historique et non penser à un bug.
Par ailleurs il y a des event invalide Docurba qui semblent provenir des dump, il ne faudrait pas les afficher non plus.

**Comment by HermanceGauth** [comment]
Note pour moi-même : prévenir Gérald quand c'est bon

**Comment by lerayj** [comment]
sur branche preprod

**Comment by HermanceGauth** [comment]
Gerald prévenu
