### ISSUE TITLE
Statut de SCoT "caduc" : SCoT Pays D'Autan (81)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#565]
> Le SCoT est caduc. Son statut ne doit pas être opposable mais précédent.

Lien vers la FRP : https://docurba.beta.gouv.fr/frise/29316f46-369e-4f23-b28b-9f3ab1eab025
Il faudrait manuellement changer le statut de ce SCoT et le passer en "caduc". 
Il s'agit de ce SCOT : 

![Capture d’écran 2024-04-24 à 12 08 40](https://github.com/MTES-MCT/Docurba/assets/111045572/14201d66-b9ec-4d06-a3f2-a2de691acec4)

to do célia : prévenir Arnaud quand c'est good

**Comment by CeliaVermicelli** [comment]
@Octaviedebs

**Comment by HermanceGauth** [comment]
@lerayj @UngererFabien en fait il y a l'évènement "caducité" dans Sudocuh et dans Docurba qui permet de le savoir donc il faudrait je pense dire au moment du dump que l'orsqu'il y a un event "Caducité" on passe en statut caduc pour l'historique.
Pour les procédure Docurba je fais la modif dans le tableau des event pour que cet évènement devienne impactant.
On définira plus tard les système d'alerte à mettre en place, ça fera partie de la prochaine version de la FRP.

**Comment by Octaviedebs** [comment]
tt bon même en prod @CeliaVermicelli je te laisse prendre connaissance et prévenir arnaud :) 

<img width="1408" alt="Capture d’écran 2024-05-08 à 20 00 23" src="https://github.com/MTES-MCT/Docurba/assets/144041896/b13912b9-6e1e-4346-b4d5-e70ad51da369">

**Comment by CeliaVermicelli** [comment]
Mercii @Octaviedebs DDT prévenue, je close
