### ISSUE TITLE
Bug Stats : Metabase & Matomo

### ISSUE THREAD

**Issue by NicolasM92** [MTES-MCT/Docurba#567]
Les événements semblent enregistrer moins de conversion sur l'ensemble des metriques que l'on utilise pour le calcul du score :

<img width="557" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/60889390/98e1b983-11c4-4f61-9576-90f98c07e2be">

**Comment by NicolasM92** [comment]
Est-ce que ce ne serait pas lié aux bots également qui auraient pu faire grossir les stats pendant les précédentes périodes ?

**Comment by UngererFabien** [comment]
@HermanceGauth pas grand chose a faire ici je pense. D'un coté il faut corrigé le spam des bots et de l'autre il faut ré ouvrir les sections d'intro sur les pages de socle de PAC.

**Comment by HermanceGauth** [comment]
L'issue sur l'ouverture d'intro du socle date d'octobre donc je ne pense pas que ce soit lié à ce problème qui est apparu en avril

**Comment by HermanceGauth** [comment]
@NicolasM92 est-ce que c'est bon, si oui peux-tu close?
