### ISSUE TITLE
Page commune - Probléme d'affichage PLUi - on ne sait pas de quel PLUi on parle car on affiche le nom de la commune au lieu de l'EPCI

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#568]
C'est pour cela que Claire n'a pas compris notre démo la semaine dernière et c'est vraiment pas claire d'afficher comme ça.
https://jam.dev/c/bc3e39eb-f03c-4728-b749-9831db3c7a9c

**Comment by HermanceGauth** [comment]
Il faudrait avoir : PLUi - nom de l'EPCI et non PLUi- nom de la commune
Certainement lié à la mep sur les périmètres

**Comment by HermanceGauth** [comment]
Je constate un soucis pour les PLUi sectoriels que je relis à cette évolution
https://jam.dev/c/98bb9fb0-6052-43eb-890f-44b966ca9009

**Comment by HermanceGauth** [comment]
Rectification en fait le problème est dès qu'on est sur une page collectivité - EPCI pas seulement pour les PLUi sectoriel. Donc on n'a plus rien d'afficher pour tous les PLUi dès qu'on est sur une page d'un EPCI.

**Comment by UngererFabien** [comment]
@HermanceGauth qu'est ce qu'on affiche si la collectivité porteuse n'existe plus dans le référenciel ?

**Comment by HermanceGauth** [comment]
@UngererFabien pour le cas montré c'est un vieux POS, en plus on a la liste des communes concernées je pense que c'est limite plus important que le nom pour l'historique donc ça me va de rester comme ça

**Comment by Octaviedebs** [comment]
J'ai créé une autre issue qui me semble en lien avec celle-ci https://github.com/MTES-MCT/Docurba/issues/590

**Comment by CeliaVermicelli** [comment]
**le nom de l'EPCI apparait bien en face du PLUI :** 
![Capture d’écran 2024-05-08 à 18 43 57](https://github.com/MTES-MCT/Docurba/assets/111045572/0a09934a-e66f-4e42-81df-4cf777d9abb4)
![Capture d’écran 2024-05-08 à 18 45 06](https://github.com/MTES-MCT/Docurba/assets/111045572/ff806a72-b57a-4054-9682-5a6ac65452c0)

**Exemple de St Cyr blablabla dans le 71 : c'est ok pour les 2 plui sectoriels** : 
![Capture d’écran 2024-05-08 à 18 47 47](https://github.com/MTES-MCT/Docurba/assets/111045572/ba265c7b-4dda-4001-bb3a-d0938c4773c2)

Aussi résolu pour le cas de la CC Sidobre Vals et Plateaux 

@HermanceGauth je me permets de close
