### ISSUE TITLE
Impossible de supprimer une section de PAC

### ISSUE THREAD

**Issue by UngererFabien** [MTES-MCT/Docurba#57]
Pb à la suppression de sections ? “Hier lorsque j'ai ouvert ma trame de pac, j'ai eu des éléments en double [et j'en ai encore ce matin (alors que je les avaient supprimés hier matin) voir capture d'écran]”

**Comment by UngererFabien** [comment]
Tester en prod et en dev, je n'ai pas réussi à reproduire sur les trames test et test-main. Est-ce qu'on a un moyen de reproduire ?

**Comment by CeliaVermicelli** [comment]
Cela semble fonctionner : 
J'ai supprimé des sections de la trame, je recharge la page, les sections ont bien disparues. Je créé un nouveau PAC et les sections en questions ne sont pas présentes -> ok !
