### ISSUE TITLE
Modification manuelle des statuts : cas de Livarot-Pays d'Auge (14)

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#570]
Lié à cette issue : https://github.com/MTES-MCT/Docurba/issues/137
Dernier message de Fabien : Pour la commune 14371, je ne vois pas d'autre moyen de corriger ce cas que de corriger manuellement le périmètre de la procédure avec les COMD.

@lerayj il faudra qu'on adapte le process des dump journalier pour qu'il n'écrase pas les corrections manuelles sur les COMD. Aujourd'hui le script repart de 0 comme il n'y a que 1003 cas à insert.

Il faut que le PLUi en cours reste en cours et que les trois autres deviennent opposables.

**Comment by HermanceGauth** [comment]
Sera réglé après les corrections sur le reste (communes fusionnées)

**Comment by CeliaVermicelli** [comment]
Je close l'issue, le retour est bien saisi dans [la doc](https://docs.google.com/spreadsheets/d/1ATNoSmDqaWyygGVwU78hE3Og-E_FYapbc_5WMPbDlxo/edit?usp=sharing)
(lien également dispo depuis Notion > tech > "retours/bug")
