### ISSUE TITLE
bug ajout de proc. principale : CA Morlaix (29) 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#573]
@lerayj 
Demo : https://jam.dev/c/7c0a3197-cc6b-48cc-a1b8-d5f77fbefe9f

Morlaix : https://docurba.beta.gouv.fr/ddt/29/collectivites/242900835/epci

**La procédure principale de révision ajoutée mais n'apparait pas dans la liste, même après actualisation de la page.** 
Pour info, j'ai testé l'ajout de procédure principale sur un autre dpt et elle a été ajoutée sans problème.

FYI @HermanceGauth suite à appel de Gérald.

**Comment by lerayj** [comment]
C'est fix. C'était un probleme a cause de communes fusionnées qui avait le meme Insee au niveau du perimetre.

**Comment by Octaviedebs** [comment]
Je confirme tout semble ok en pré prod et en prod

![Image](https://github.com/MTES-MCT/Docurba/assets/144041896/abc8bcd5-0580-4d8c-bd32-4d93e96b21d0)
![Image](https://github.com/MTES-MCT/Docurba/assets/144041896/0de4afab-3a7e-4b99-ad46-23a3879d3d19)

Je te laisse checker et voir avec ton user @CeliaVermicelli  :)

**Comment by CeliaVermicelli** [comment]
Mercii ! DDT prévenue, je close
