### ISSUE TITLE
Erreur dans le dump ? Numéro de proc. mal reportées de Sudocuh : Cavalaire (83) 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#577]
@lerayj 
Page de Cavalaire : https://docurba.beta.gouv.fr/ddt/83/collectivites/83036/commune

* la proc de révision nº1 sur Sudocuh, est notée nº2 sur Docurba
* la proc de révision (approuvée en 2013) n'a pas de numéro sur Sudocuh, elle est notée numéro 1 sur Docurba, 

Cf capture d'écran : 
![image (5)](https://github.com/MTES-MCT/Docurba/assets/111045572/25e8d517-27b4-4a59-89d6-95f28fe3a0d8)

![Capture d’écran 2024-04-30 à 16 48 38](https://github.com/MTES-MCT/Docurba/assets/111045572/b3b7a064-c6f7-4c34-9b95-163ecf1986d5)

**Comment by UngererFabien** [comment]
Sizé assez large parce qu'il faut sans doute remonté à la donnée Sudocuh pour comprendre ce qu'il s'est passé.

**Comment by lerayj** [comment]
cas 2 correct manual waiting for script

**Comment by HermanceGauth** [comment]
@CeliaVermicelli ça m'a l'air ok, je te laisse prévenir et closed?
