### ISSUE TITLE
Communes fusionnées - cas de Piré-Chancé (35)

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#580]
Exemple d'une commune nouvelle (piré-chancé), pour cette commune nouvelle il existe 2 PLU en vigueur : un pour la commune déléguée de piré-sur-seiche et un pour la commune déléguée de chancé. Or Docurba affiche des informations incomplètes faisant penser qu'il n'existe qu'un seul PLU opposable qui couvre toute la commune nouvelle.
https://jam.dev/c/6417b14a-91d6-456b-86ea-5b537bcd7ef7
Historique : https://github.com/MTES-MCT/Docurba/issues/303

**Comment by HermanceGauth** [comment]
C'est moi qui avait fait cette issue pour plus de clarté mais @CeliaVermicelli je la laisse pour que tu puisse prévenir Clément.
Pour info, les DDT vont peut-être tiquer sur l'historique où les POS sont présentés comme étant sur la commune fusionnée et pas les anciennes communes. On pourra se le mettre en feedback mais insister sur le fait que l'important c'est le présent et pas l'historique (et du coup qu'on va pas forcément investir du temps dessus)

**Comment by CeliaVermicelli** [comment]
Merci @HermanceGauth ! La DDT est prévenue, je close.
