### ISSUE TITLE
Communes fusionnées - cas de Cambremer (14)

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#582]
La commune nouvelle de Cambremer réunit deux communes, Cambremer et Saint-Laurent-du-Mont, qui ne partagent pas le même document d'urbanisme. Il faut donc pouvoir assigner un document d'urbanisme à chacune des deux entités ;
https://jam.dev/c/41386b01-8f4a-4ef9-b1f4-677416696fea
Historique : https://github.com/MTES-MCT/Docurba/issues/137

**Comment by HermanceGauth** [comment]
@CeliaVermicelli est-ce que tu pourrais demander à la DDT s'ils sauraient pourquoi Saint-Laurent-du-Mont n'apparaît pas dans le référentiel de l'INSEE comme commune déléguée? Et si l’appellation COMD pour Saint-Laurent-du-Mont leur paraîtrait erronée? Et si oui comment le représenter selon eux? Je ne sais pas si tu avais fait un update sur les autres points de l'issue initiale, le premier semblait résolu et le dernier c'est Livarot Pays-d'Auge qu'on va modifier à la main dans la base de données normalement cette semaine cf https://github.com/MTES-MCT/Docurba/issues/570

**Comment by CeliaVermicelli** [comment]
FYI je la relance cette aprem. @HermanceGauth

**Comment by CeliaVermicelli** [comment]
Retour de la DDT : 

_Effectivement, Saint-Laurent-du-Mont n'est pas une commune déléguée : c'est une fusion simple qui a été opéré en 2019, et SLdM a été absorbée par Cambremer sans établissement de commune déléguée.
Pour autant, le code de l'urba, en son article L153-4 ("En cas de création d'une commune nouvelle, les dispositions des plans locaux d'urbanisme applicables aux anciennes communes restent applicables."), permet bien de conserver l'ancien PLU sur le territoire de l'ancienne commune.
**Même si officiellement ce n'est pas une commune déléguée, nous pensons que le plus simple est quand même de conserver l’appellation de commune déléguée ;-)**_

**Comment by CeliaVermicelli** [comment]
je close car bien saisi dans [la doc ](https://docs.google.com/spreadsheets/d/1ATNoSmDqaWyygGVwU78hE3Og-E_FYapbc_5WMPbDlxo/edit?usp=sharing)
Lien dispo depuis notion > Tech > Retours/bug
