### ISSUE TITLE
Erreur de statut | CC de Etrappe - statut précédent au lieu de opposable

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#583]
https://docurba.beta.gouv.fr/frise/4bdbf4ac-4289-4cad-b048-9cc7f28a17d0

Précédent au lieu de opposable 

https://jam.dev/c/688d3fce-a822-4a27-80f9-befbe7c80887

**Comment by HermanceGauth** [comment]
voir ici : https://github.com/MTES-MCT/Docurba/issues/143

**Comment by Octaviedebs** [comment]
Résolu - même commentaire : peut être en lien avec la 143 mais elle est tjrs open pourtant donc je ne sais pas si elle avait été mep
