### ISSUE TITLE
CRM V2 P1 : Assurer la mise en place du parcours DDT/DREAL

### ISSUE THREAD

**Issue by NicolasM92** [MTES-MCT/Docurba#584]
Besoin de mettre en place les éléments de cette [carte notion](https://www.notion.so/docurba/CRM-V2-P1-Assurer-la-mise-en-place-du-parcours-DDT-DREAL-37ee64baca1a4d56b970719b87e0aea1) pour démarrer le chantier CRM.

**Comment by Octaviedebs** [comment]
J'ai peut être mal compris mais il me semble que l'idée était quand même de remettre le contenu de la carte Notion du coup non ? pour que ce soit plus lisible/facile à dérouler sans lien externe - mais peut être que comme ça ça suffit aussi

**Comment by Octaviedebs** [comment]
C'est précisé en commentaire dans le doc Notion mais au cas où, il s'agit donc d'
- assurer la mise à jour automatique (dynamique) de ces nouveaux champs **à chaque fois qu’un utilisateur créé un compte (nouvel email du user)** 
- rétroactivité :  il faudrait que ces champs soient également mis à jour sur les fiches Personnes déjà existantes :  cela correspondrait à faire matcher les Email des fiches Personnes avec les emails users des profiles ? comment tu voyais les choses ? (lancer un script ?) Nh'ésite pas si besoin de précisions !

**Comment by UngererFabien** [comment]
https://github.com/MTES-MCT/Docurba/issues/401

**Comment by Octaviedebs** [comment]
Note à moi même : quand en prod, finaliser la documenta° sur cette partie

**Comment by Octaviedebs** [comment]
@UngererFabien suite à ta vidéo (merci !) : 

**- écrasement données :** en pp on a justement renommé les anciens champs « anciens champs » et seuls ceux ci peuvent avoir été modifiés manuellement donc ne devrait pas y avoir de risque d’écrasement de données mais à préciser

- **statut invité** :  oui tu as complètement raison, j'avais pas pensé à ce point 
@NicolasM92 il faudrait donc  : 
- enlever cette valeur
- créer un autre champ à part : Invité.e - du coup pour les valeurs possibles on a plusieurs choix mais je propose la même logique adoptée pour d'autres champs à savoir : si pas invité champ vide / sinon date du dernier partage ? (étant précisé qu'on a déjà acté qu'il n'est pas recommandé de remonter l'info° si c'est invita° via FRP ou via PAC) - tu en penses quoi @UngererFabien  ?

**Comment by Octaviedebs** [comment]
@NicolasM92 pourras tu du coup aussi procéder au test pour chaque ajout du coup pour vérifier et l'indiquer sur la carte notion quand c'est testé ?

**Comment by Octaviedebs** [comment]
@UngererFabien On est d'accord que du coup pour tester on peut tester en condition réelle en fait c'est ça ?

**Comment by Octaviedebs** [comment]
J'ai commencé les test et on en fera d'autres tests avec @CeliaVermicelli  

En revanche **je ne peux pas tester si les champs fonctionnent côté Side Collectivités car il n'y a pas d'accès pré prod. pour le side collectivité = @UngererFabien comment procéder ?** 

**Side Etat :** 
- champ validation : ne semble pas se mettre à jour exemple [ici](https://docurba2.pipedrive.com/person/2456) accès dreal que j'ai validé au bout de 5 minutes - ici compte DDT que j'ai validé tt de suite, le champ est à [jour](https://docurba2.pipedrive.com/person/2455)  
- champ statut : ne se met pas à [jour](https://docurba2.pipedrive.com/person/2455) : exemple ici : je me suis déconnecté puis reconnecté et champ ne se met pas à jour 
- rôle état : semble [fonctionner](https://docurba2.pipedrive.com/person/2455) mais pas sur l'accès [dreal](https://docurba2.pipedrive.com/person/2456)

On va retester avec Célia poru que ça couvre ttes les [possibilités](https://www.notion.so/docurba/CRM-V2-P1-Assurer-la-mise-en-place-du-parcours-DDT-DREAL-37ee64baca1a4d56b970719b87e0aea1)

**Comment by Octaviedebs** [comment]
Du coup pour s'y retrouver, résumer de la carte P1 CRM P2 : 

- [ ] Mettre à jour le **champ Validation** = faire remonter le champ table Profiles
         
- prend la valeur non par défaut ❌
         Note : exemple [ici](https://docurba2.pipedrive.com/person/2456) (précision : il s'agit d'un compte DREAL, est-ce que ça viendrait de ça ? ) 

- prend la valeur oui dès que le champ verified de la BDD est coché - 💬
        Note : [ici](https://docurba2.pipedrive.com/person/2455) cela fonctionne mais pas [ici](https://docurba2.pipedrive.com/person/2456) alors que j'ai validé :
 
 - avec rétroactivité 




- [ ] Mettre à jour le champ **“Rôles Etat”** (**avec rétroactivité si possible**) = remonter les valeurs du champ **Autres Postes de la BDD** uniquement du side état _(rappel : il n’y a pas encore de rôle depuis l’accès side collectivité (mais à venir)_
 
- prend les valeurs ci-dessous en multichoix
          Chef d'unité/de bureau/de service et adjoint
          Rédacteur(ice) de PAC
          Chargé(e) de l'accompagnement des collectivités
          Référent(e) Sudocuh

- assurer la rétroactivité sur les utilisateurs déjà sur Pipedrive 




- [ ] Mettre à jour le champ **Poste** (**avec rétroactivité si possible**) = Faire remonter tous les champs **Poste** de de la BDD *(remplies à l’inscription sur Docurba) dans le champ Poste de pipedrive (et pas poste ancien champ) : 

- prend les valeurs ci-dessous côté side collectivité : 
     - bureau d'étude
     - elu(e)
     - technicien(ne) ou employé(e)
     - agence d'urbanisme
     - autre

 - prend les valeurs ci-dessous côté side état : 
    
     - DDT/DEAL
     - DREAL 


- assurer la rétroactivité pour les utilsiateurs déjà sur pipedrive 




- [ ] Mettre à jour le champ **« Autres informations »** = informations indiquées lors du choix du poste Autre

    -  remonter dans ce champ les informations indiquées lors du choix du Poste Autre
    - Historique à faire remonter (script)



- [ ]  Mettre à jour le champ « **Statut** » qui pourrait prendre 4 valeurs : 
= suivre le parcours d’inscription sur docurba

- **Non inscrit.e** 
→ par défaut lors de la création d’une personne



- **Non connecté.e** = sign in once* false de Profiles
*→* une personne s’est inscrite *sign up* mais ne s’est jamais connectée *(ni directement via le 1er email post inscription, ni plus tard via la page connexion)* 
 *Infos : actuellement, le champ existant est Tentative d’inscription et correspond à une Etape sur Pipedrive et non un champ sur une fiche Personne*
   
- **Connecté.e** **P1** =  *sign in once* true dans Profiles
→ une personne s’est inscrite et s’est connecté au moins une fois
→  la valeur change automatiquement
    

- [ ] Ajouter un champ **Invité.e** sur pipedrive
- [ ] Faire remonter la valeur = *Project Sharing* qui est lié à un email 
→ lorsqu’une personne est invitée à rejoindre une procédure/un PAC


    
    **NB :** 
    ⚠️ Pipedrive crée une valeur “Aucun” pour les champs à option qui correspond à la valeur par défaut du champ lorsqu’un contact est créé. Attention du coup pour les cas où on veut que cette valeur par défaut soit ≠

**Comment by Octaviedebs** [comment]
@UngererFabien du coup je te remets ici le GSheet https://docs.google.com/spreadsheets/d/10V-4tp3GW7JdpCBstnf-KiyFcstXgJ8pQEPk1ma0Mq8/edit#gid=0

**Comment by Octaviedebs** [comment]
⚠️ La raison pour laquelle ça a pas marché c'est que le serveur avait time out
Pourquoi ? en très gros, le serveur de prod a mis du temps à se réveiller car c'est le serveur de pré prod qui met à jour Pipedrive = donc en faisant des test en prod', ça a certes permis de lui dire de se réveiller, mais avec un gros laps de temps = c'est pq seuls les derniers tests qu'on a fait ont fonctionné (avec 2min de maj), car il était réveillé

Utilie de le savoir pour les prochaines fois

**POUR RESUMER** 

- a priori tt fonction mais @UngererFabien doit tester pour la DREAL

**@NicolasM92 en revanche, il manque la valeur Autre dans le champ Poste = peux tu l'ajouter ?** + pour le champs Invité cf ci-dessus

Cf Notion : 
![Capture d’écran 2024-06-10 à 17 43 46](https://github.com/MTES-MCT/Docurba/assets/144041896/8c19e57e-452b-4144-94f5-fc4fd962d4ef)

Cf Pipedrive actuel : 
<img width="394" alt="Capture d’écran 2024-06-10 à 17 45 10" src="https://github.com/MTES-MCT/Docurba/assets/144041896/7f61ce2d-a633-4d24-a1d3-f1ed6a527261">

**Comment by UngererFabien** [comment]
J'ai refais une série de test sur les DREAL et trouvé la source du problème. Les DREAL ont le champ "Autre poste" vide dans la BDD et ce qui  fait planté le code.

C'est corrigé en pre-prod. Pour le reste, vous devriez pouvoir test en prod ou pre-prod. Faite juste attention à ce que le server de pre-prod soit réveiller en navigant dessus un peu avant de faire vos test.

Pour ce qui est des valeur par default de verified. En y re réfléchissant dans les test je me dis que c'est peut être bien de garder la valeur initial à null/aucun. Ca permet de distingué les gens refusé des gens pour qui on a pas encore pris de décision.

Si ça ne vous convient pas je peux toujours forcé un update des profiles après chaque signup et ça mettra à jour le champs avec OUI/NON.

**Comment by CeliaVermicelli** [comment]
* DREAL testé en pre-prod -> c'est tout bon !

**Comment by Octaviedebs** [comment]
@UngererFabien Du coup il reste le point sur la rétroactivité, comment tu vois les choses ?

**Comment by Octaviedebs** [comment]
@NicolasM92 du coup je me suis occupée d'ajouter la valeur Autre
Il reste de ton côté pour le champs Invité.e
A dispo si besoin

**Comment by Octaviedebs** [comment]
ok merci @NicolasM92 du coup l'idée c'était de supprimer la valeur invité dans le champ Statut aussi du coup - vu que maintenant il y a un champ dédié - je peux te laisser le faire ? merci à toi 
+ de l'ajouter dans la carte P2 sur laquelle je t'ai mis des commentaires car il manquait des trucs, autant qu'on se fasse un point ce sera plus rapide !

**Comment by Octaviedebs** [comment]
suite et finalisation dans d'autres issues
