### ISSUE TITLE
Envoyer la descritption des champs de l'API à Claire

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#585]

**Comment by HermanceGauth** [comment]
- rajouter le type si c’est un entier, un bouléen
- Un endpoint sur tous les départements : rajouter dans la doc
Est-ce que c’est possible d’avoir au niveau national? Oui mais ça met du temps à sortir
Est-ce que c’est possible d’avoir au niveau régionale? Oui c’est possible : on le rajoute soit avec le nom soit avec le code
Est-ce qu’il serait possible de rajouter le COG? 
Est-ce qu’on peut rajouter un exemple de filtre multiple dans les intercommunalités? + écrire la marche à suivre
Est-ce qu’on peut intégrer les populations et les superficies? Pas le cas encore.
PA_sectoriel renvoie uniquement false
Retirer les données sur le volet qualitatif et rajouter les infos lors de la création de procédure champ "Objet" (trajectoire ZAN, feu de forêt,...)
Ajouter les SCoT et notamment zones blanches et SCoT modernisés

**Comment by UngererFabien** [comment]
@HermanceGauth j'ai rajouté les type. Par contre le reste je propose de le divisé en plusieurs issues.

**Comment by HermanceGauth** [comment]
Ok il faudra aussi rajouter un point sur les event ajouté dans Docurba. Je te laisse faire les issues correspondantes?

**Comment by HermanceGauth** [comment]
Je pense que ce sera à mettre dans le prochain sprint du coup plutôt. Surtout qu'ils doivent aussi revenir vers nous avec leur tableau finalisé.

**Comment by HermanceGauth** [comment]
Tableau d'Andy : 

[Export CSV Docurba - 20240523.xlsx](https://github.com/MTES-MCT/Docurba/files/15453945/Export.CSV.Docurba.-.20240523.xlsx)

**Comment by HermanceGauth** [comment]
Fabien découpe cette issue en plusieurs issues.
