### ISSUE TITLE
Retours communes fusionnées du 76 : procédure de COMD de Caudebec-en-caux ?

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#587]
"je n'ai pas trouvé trace dans doc urba pour la commune de Caudebec en Caux (commune déléguée de Rives en Seine) du PLU prescrit le 16/12/2011 et approuvé le 19/12/2017."
demo https://jam.dev/c/3e4e551e-683a-48c0-8dc9-f0a21844af6e je ne vois pas le PLU effectivement. 

![Capture d’écran 2024-05-06 à 15 25 30](https://github.com/MTES-MCT/Docurba/assets/111045572/44ebc292-93c5-4555-b24f-3955ad7e4ac1)

@UngererFabien @HermanceGauth

**Comment by CeliaVermicelli** [comment]
ah autant pour moi ! je n'ai pas eu le réflexe de vérifier sur le lien dev ! 
Je laisse l'issue ouverte pour mon suivi au cas où

**Comment by HermanceGauth** [comment]
bien présent en prod ce jour @CeliaVermicelli je te laisse prévenir et closed?

**Comment by CeliaVermicelli** [comment]
mercii c'est fait ! je close
