### ISSUE TITLE
Communes fusionnées du 76 | Pb d'affichage des DU des communes déléguées de Petit Caux (EPCI CC Falaises du Talou)

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#589]
Il y a plusieurs éléments qui ne correspondent pas concernant l'affichage des DU encore opposables des communes déléguées de Petit Caux, après enquête de ma part + des retours du chargé urba de la CC Falaises du Talou - j'ai numéroté les points pour faciliter vos réponses éventuelles à chaque d'eux _(en mettant juste le numéro des points du coup)_- : 

**1. Biville-sur-Mer :** 

- 1a = j'ai remarqué qu'aucun DU n'est affiché sur la page de la commune : https://docurba.beta.gouv.fr/collectivites/76098/?isEpci=false
![Capture d’écran 2024-05-06 à 19 28 08](https://github.com/MTES-MCT/Docurba/assets/144041896/b0365779-9de8-469b-947f-b99dc6e47ed0)
OR on voit bien le DU opposable depuis la page de l'EPCI https://docurba.beta.gouv.fr/collectivites/247600729/?isEpci=false
![Capture d’écran 2024-05-06 à 19 29 04](https://github.com/MTES-MCT/Docurba/assets/144041896/5541fc87-e6c1-41e6-b9ce-901eaa1df701) = c'est normal ?
- 1b note à moi même : il manque des procédures secondaires - ajouter ces procédures via moi quand rep EPCI acte prescription_

**2. Saint-Martin-en-Campagne (commune déléguée de Petit Caux)** : 
- 2a = aucun DU opposable n'est remonté **OR il y a une procédure secondaire de  modification simplifiée N° 1 du PLU de Saint-Martin-en-Campagne : _mise à disposition du public prévue entre le 25 mai et le 25 juin 2024.** d'après le user
- ni en prod ni en dev
- 2b = la recherche de cette comd via la barre de recherche renvoie sur la page de la nouvelle commune https://docurba.beta.gouv.fr/collectivites/76618/?isEpci=false (et donc aucun DU dans l'onglet DU n'apparait concernant cette comd) => je l'indique là mais j'imagine que c'est un comportement attendu ?

**3. Berneval-le-Grand (commune déléguée de Petit Caux)**
- 3a : apparait depuis la page de l'EPCI
![Capture d’écran 2024-05-06 à 19 35 57](https://github.com/MTES-MCT/Docurba/assets/144041896/df04acb8-6358-40c3-a976-47a0374a21b2)
 OR aucune procédure de DU n'apparait depuis la page de la comd
![Capture d’écran 2024-05-06 à 19 36 13](https://github.com/MTES-MCT/Docurba/assets/144041896/0c9194b9-0ade-4ee8-b7a5-bbe967bab339) : c'est normal ? 
- 3b = par ailleurs le titre des FRP ont comme titre le nom de la nouvelle commune et pas de la COMD ce qui est un peu confusant (mais pas important) => je note ça ici mais je pourrait mettre ça dans le backlog si plus pertinent ?

**Comment by CeliaVermicelli** [comment]
FYI je viens de rajouter cette issue suite au retour de la DDT: https://github.com/MTES-MCT/Docurba/issues/591

**Comment by HermanceGauth** [comment]
J'ai l'impression que c'est ok en allant voir sur Petit-Caux https://docurba.beta.gouv.fr/ddt/76/collectivites/76618/commune
@Octaviedebs peux-tu closed si c'est ok?

**Comment by HermanceGauth** [comment]
le comportement attendu était de renvoyer vers la communes nouvelles quand on est sur la page de la COMD @UngererFabien comme tu l'avais écrit dans cette issue : https://github.com/MTES-MCT/Docurba/issues/579
J'ai l'impression que le comportement a changé avec la mep du dashboard, par exemple les COMD ne sont plus trouvables dans le TDB DDT alors qu'on peut les trouver dans la recherche publique. Je vais refaire une issue sur le comportement attendu et la mettre sur un prochain sprint. En attendant @Octaviedebs la reco c'est de passer par la nouvelle commune.

**Comment by HermanceGauth** [comment]
Issue pour le comportement COMD créée ici : https://github.com/MTES-MCT/Docurba/issues/652
Et pour le titre de la FRP il y a déjà énormément d'issues donc je propose de ne pas en refaire et de close celle là.
