### ISSUE TITLE
Le titre du DU Interco est n'est pas celui de l'interco mais d'une commune

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#590]
Sauf erreur de ma part, dans l'EPCI CC Falaises du Talou on a bien un PLUi
<img width="1314" alt="Capture d’écran 2024-05-06 à 20 31 05" src="https://github.com/MTES-MCT/Docurba/assets/144041896/c357b785-18ac-4fbb-911b-3fef4868e25a">

ET Petit Caux et Saint Martin le Gaillard par exemple sont bien des communes de cet EPCI.
DONC sur la page de ces communes on devrait voir dans l'onglet DU Interco : PLUi CC Falaises du Talou et pas PLUI Nom commune

OR cf ces deux exemples : 

![Capture d’écran 2024-05-06 à 20 25 15](https://github.com/MTES-MCT/Docurba/assets/144041896/28f6644f-d96a-4620-9001-2a0c5c537d55)
![Capture d’écran 2024-05-06 à 20 25 59](https://github.com/MTES-MCT/Docurba/assets/144041896/c753cd44-e45f-4e6f-b3d4-d02aeb71b2d2)

**Comment by CeliaVermicelli** [comment]
@Octaviedebs tu veux vérifier ces cas que tu as cité suite à la resolution de l'issue 568 ?

**Comment by Octaviedebs** [comment]
C'est tt bon, je close

<img width="1408" alt="Capture d’écran 2024-05-08 à 19 25 23" src="https://github.com/MTES-MCT/Docurba/assets/144041896/a455a6ba-c34e-4356-8169-9cca749330a4">
<img width="1408" alt="Capture d’écran 2024-05-08 à 19 26 22" src="https://github.com/MTES-MCT/Docurba/assets/144041896/7a6f0fae-1c73-4b5b-8840-ff75e33b275b">
