### ISSUE TITLE
Com fusionnées DDT 76 : cas de fauville-en-caux, St martin en campagne, Buchy et Penly

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#591]
> J'ai regardé toutes les communes déléguées de Seine-Maritime.
> Il n'y a des erreurs sur les documents opposables que sur 4 communes déléguées:
(l'affichage est le même que ce soit en dev ou en prod)

- Fauville-en-Caux  (commune nouvelle = Terres-de-Caux) statut du PLU devrait être opposable au lieu de précédent comme c'est le cas actuellement. --> **ok en preprod au 22.05**
- Saint Martin en campagne (commune nouvelle = Petit-Caux) statut du PLU devrait être opposable au lieu de précédent comme c'est le cas actuellement.--> **ok en preprod au 22.05**
- Buchy  (commune nouvelle = Buchy) statut du PLU devrait être opposable au lieu de précédent --> **ok en preprod au 22.05**

- le statut d'une des cartes communales de la commune déléguée de Penly (commune nouvelle = Petit-Caux) doit être passé en précédent (2 cartes communales opposables actuellement) : il s'agit de la CC qui a le commentaire _"----- procédure sectorielle concernant l'ancien périmètre de la commune PENLY"_ --> **ok en preprod au 22.05**
![Capture d’écran 2024-05-07 à 11 53 16](https://github.com/MTES-MCT/Docurba/assets/111045572/3f279cb5-e3d8-40a8-93ea-d640022e415a)

**Comment by Octaviedebs** [comment]
en lien avec https://github.com/MTES-MCT/Docurba/issues/589

**Comment by Octaviedebs** [comment]
Question : pourquoi on a décidé de ne pas appliquer pas la même règle pour les procédure precedent / abandon etc en affichant aussi la COMD dans le titre du DU ?

**Comment by UngererFabien** [comment]
@CeliaVermicelli @Octaviedebs je vous fais des liens pour que ça soit plus simple de test:

https://dev.docurba.beta.gouv.fr/collectivites/76258/?isEpci=false Fauville-en-Caux le PLU est bien opposable
https://dev.docurba.beta.gouv.fr/collectivites/76618/?isEpci=false Saint-Martin-en-Campagne le PLU est bien opposable
https://dev.docurba.beta.gouv.fr/collectivites/76146/?isEpci=false Buchy le PLU est bien opposable et concerne bien uniquement la COMD

https://dev.docurba.beta.gouv.fr/ddt/76/collectivites/76618/commune Celle-ci devrait se corrigé avec une mise à jour des fichiers de dump des communes fusionnés.

**Comment by HermanceGauth** [comment]
@Octaviedebs je laisse @UngererFabien complété pour l'historique mais il me semble que ça rajoutait une difficulté supplémentaire et donc on s'est concentré sur le "présent" cf mon commentaire ici : https://github.com/MTES-MCT/Docurba/issues/580

**Comment by CeliaVermicelli** [comment]
Note à moi même : prévenir Noel Evain quand tout est ok 

Aujourd'hui tout semble bon, même en prod. 
Sauf : 
* pour Buchy, on retrouve la comd et la FRP de la com nouvelle de Buchy ne charge pas (à retester)
* Les CC de Penly, les deux statuts sont encore opposables.

**Comment by CeliaVermicelli** [comment]
Les 4 points évoqués dans le premier com sont résolus en preprod

**Comment by CeliaVermicelli** [comment]
FYI retour de la DDT : 

> Toutes les communes déléguées de Seine-Maritime affichent le bon document opposable.

💪
