### ISSUE TITLE
⚙️ Implémentation form Tally > suppression form Stonly

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#594]
Il faudrait mettre en ligne [ce formulaire d'acquisition Tally ](https://tally.so/forms/n9d42K/edit) en embed format Standard : 
- sur la landing page en mode non connecté 
- le faire apparaitre 2 fois maximum si le user ne répond pas
- ne plus le faire apparaitre une fois que le user a répondu 

Si je ne me trompe pas le code est : 
<iframe data-tally-src="https://tally.so/embed/n9d42K?alignLeft=1&hideTitle=1&transparentBackground=1&dynamicHeight=1" loading="lazy" width="100%" height="703" frameborder="0" marginheight="0" marginwidth="0" title="Découvrez Docurba en quelques étapes 👇🏻"></iframe><script>var d=document,w="https://tally.so/widgets/embed.js",v=function(){"undefined"!=typeof Tally?Tally.loadEmbeds():d.querySelectorAll("iframe[data-tally-src]:not([src])").forEach((function(e){e.src=e.dataset.tallySrc}))};if("undefined"!=typeof Tally)v();else if(d.querySelector('script[src="'+w+'"]')==null){var s=d.createElement("script");s.src=w,s.onload=v,s.onerror=v,d.body.appendChild(s);}</script>

Mes questions : est-ce qu'une fois en ligne, si je modifie des petites choses sur ce formulaire les mises à jour seront automatiques et ne nécessiteront pas une modification de ta part ? 

** 🚩 Pré requis : supprimer l'accès au formulaire d'acquisition stonly dès que ce formulaire Tally est testé / validé / en prod**

@UngererFabien surtout hésite pas si questions

FYI @CeliaVermicelli et si tu souhaites ajouter des choses - d'ailleurs, concernant les formulaires Stonly autres que celui d'acquisi° (DREAL/PAC) : que souhaites-tu en faire ?

**Comment by CeliaVermicelli** [comment]
C'est top ! 

Pour les guides stonly DREAL et DDT/PAC on s'était dit que la suppression du compte Stonly arriverait en même temps (ou presque) que la MEP du parcours emailing DDT/DREAL sur Pipedrive. 
Il me semble qu'on estimait la suppression de Stonyl autour du 1er juin ou 15 juin. 
On peut s'en reparler suite aux retours de Fabien au prochain point ops :)

**Comment by Octaviedebs** [comment]
Effectivement si du coup ça arrive avant le 15 juin c'est good ! Avant le 15 mai ça me parait short - mais yes on s'en reparle

**Comment by Octaviedebs** [comment]
Ca me parait bon sauf pour la condition : **_le faire apparaitre 2 fois maximum si le user ne répond pas_**
Je n'ai pas l'impress° que cette condition fonctionne mais je n'ai peut être pas bien réussi à reproduire ce test (en dev, j'ai fermé l'onglet où la pop up était apparu une première fois, puis l'ai rouvert => rien ne re-apparait mais j'avais déjà cliqué sur une réponse du formulaire, sans aller jusqu'au bout ///// et j'ai fait pareil en navig privée mais du coup ça me parait pas les bonnes cond° de test pour le coup)

Au pire, je trouve que ce n'est pas grave @CeliaVermicelli tu en penses quoi ? 

Autre point : je dois cliquer **deux** fois sur la petit croix pour que la pop up disparaisse (mais ça vient peut être de tally) 

J'attends que célia teste aussi avant de la passer en Testé

**Comment by CeliaVermicelli** [comment]
Effectivement @Octaviedebs : 
* j'ai vu la popup hier qu'une seule fois (je n'y ai pas rep)
* j'avais noté que pour tester/que la popup réapparaisse il fallait supprimer tout les tally depuis la console -> local storage, mais je ne trouve pas où : @UngererFabien tu pourrais nous redire ?

Sinon c'est effectivement pas la fin du monde :) 

![Capture d’écran 2024-06-04 à 11 17 55 AM](https://github.com/MTES-MCT/Docurba/assets/111045572/233ed961-051d-4e6c-ad64-ce53763aa646)

**Comment by Octaviedebs** [comment]
Ah yes effectivement ! Voir si Fabien répond sinon on lui demandera demain

**Comment by Octaviedebs** [comment]
@UngererFabien petit up ici pour qu'on puisse retester ?

**Comment by Octaviedebs** [comment]
- clique droit n'importe où sur docurba (en étant sur le bon espace, prod ou dev)
- Inspecter > aller Application > à gauche cliquer sur local storage > aller sur le nom de domaine docurba > cliquer sur ts les trucs tally > clique droit delete = ça remet nos compteurs à 0

**Comment by Octaviedebs** [comment]
Re testé : 
- quand on remplit le form, il re apparait une 2ème fois ❌
- quand on remlplit pas, il apparait bien une 2ème fois ✅
