### ISSUE TITLE
Ajout de deux procédures secondaires manquantes (76) : impossible de distinguer le DU opposable pour l'ajouter sur le bon DU 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#595]
J'ai besoin que vous ajoutiez deux nouvelles procédures secondaires qui sont manquantes sur Docurba sur 2 communes fusionnées.

**Pourquoi je ne suis pas autonome pour le faire** 👉🏻 car lors de l'ajout d'une nouvelle procédure depuis l'accès DDT, la liste des DU porteurs ne permet pas de reconnaitre de quelle commune il s'agit

https://jam.dev/c/0dc27faf-bc4d-44ba-9801-6215cb755699

J'aurais donc besoin que vous ajoutiez : 
- PLU de Biville-sur-Mer : ajouter une Modification simplifiée N° 4 du PLU 
Objet : Autre > écrire ce qu'il y a cf PJ
<img width="774" alt="Capture d’écran 2024-05-09 à 12 05 35" src="https://github.com/MTES-MCT/Docurba/assets/144041896/02bec04c-81cf-49c1-83fb-66e9daf77a16">

- Carte communale de Belleville-sur-Mer opposable = ajouter une révision simplifiée 
Objet : Aménagements | Chantier EPR

Note à moi même : ajouter les 2 events de prescript° avec les PJ que Martin Weyland m'a envoyées + lui écrire pour l'informer

**Comment by Octaviedebs** [comment]
Hello ! Est-ce qu'il serait possible de gérer cette issue indépendamment des 574 & 634 pour qu'éventuellement cela soit réglé un petit peu plus rapidement si possible ? 

**En gros ici j'ai besoin pour mon utilisateur que ces procédures soient ajoutées car je ne pouvais pas le faire**
Le règlement des autres permettra un règlement du pb long terme effectivement. 

Note à moi même : quand résolue, prévenir falaise du talou (weyland) cf spark snoozé

**Comment by HermanceGauth** [comment]
Je vais voir pour faire sizer l'issue mais je me dis que c'est plus rentable d'investir du temps pour régler tous les cas que pour régler un cas particulier.

**Comment by Octaviedebs** [comment]
Je comprends - c'est juste dommage car en attendant l'utilisateur ne peut pas ajouter d'événements, donc assez bloquant !
Mais effectivement là je vois que tu l'as mise pour entre le 17 & 30 juin donc top !

**Comment by UngererFabien** [comment]
Je l'ai sizé un peu large au cas ou je vois la possibilité de faire remonté tous les doublons pendants mes test.

**Comment by HermanceGauth** [comment]
@Octaviedebs est-ce que la résolution de cette issue a réglé ton pb : https://github.com/MTES-MCT/Docurba/issues/634

**Comment by Octaviedebs** [comment]
J'ai un nouveau souci les deux communes fusionnées sur lesquelles j'avais donc besoin d'ajouter 2 nouvelles procédures secondaires ne sont pas accessibles depuis le TBD DDT car elles sont catégorisées maintenant comme « n'ayant pas de compétence » https://jam.dev/c/da136608-a9e0-4892-a5e7-93a34d0da4e5

**Comment by HermanceGauth** [comment]
Voir aussi : https://github.com/MTES-MCT/Docurba/issues/652

**Comment by HermanceGauth** [comment]
@Octaviedebs il me semble que les procédures sur laquelle tu veux ajouter une procédure est bien visible et tu peux y accéder en passant pas la nouvelle commune Petit-Caux
![image](https://github.com/user-attachments/assets/abbecf66-5a11-4f05-beb7-4b69edd10e8c)
![image](https://github.com/user-attachments/assets/86970e50-65e9-4727-a874-163716152e64)

**Comment by Octaviedebs** [comment]
Ajout Modification simplifiée n°4 PLU de Biville-sur-Mer ✅
Ajout Révision simplifiée CC Belleville-sur-Mer ✅ 

user prévenu - je close 

@HermanceGauth Je pense que ça peut être intéressant de garder en tête pour une prochaine amélioration : actuellement quand on est connecté sur le territoire d'un EPCI porteur, dans l'ajout d'une nouvelle procédure, on ne prend en compte que les procédures opposables du territoire concerné, et pas les DU opposables des territoires « du niveau en dessous » - ici, depuis son accès CC Falaises biduel, je ne peux pas ajouter de PS sur une commune du périmètre => je dois passer par la page commune pour pouvoir le faire, ce n'est pas forcément très intuitif. Je le mets dans le backlog


<img width="1196" alt="Capture d’écran 2024-09-26 à 16 28 06" src="https://github.com/user-attachments/assets/107e4881-5dab-49a6-bcf7-a3b2a15d7892">
