### ISSUE TITLE
La page d'édition des PAC ne prend pas en compte le role de l'utilisateur

### ISSUE THREAD

**Issue by UngererFabien** [MTES-MCT/Docurba#596]
Un partage en mode lecture donne accès au droit d'écriture sur la page d'edition des PAC.

**Comment by CeliaVermicelli** [comment]
> Un partage en mode lecture donne accès au droit d'écriture sur la page d'edition des PAC.

ça semble ok @UngererFabien(et je suppose que le titre de l'issue veut dire la même chose ?) : 

Mon user agent ddt 44 (email = @docurba.beta) a partagé un pac à mon email perso @gmail.com : 

Même en étant reconnu par Docurba j'ai accédé au PAC qu'en mode lecture.
Et depuis mon accès DDT de mon email perso gmail : j'ai bien retrouvé le PAC dans ma liste avec le seul droit de lecture + téléchargement de PDF. 

<img width="1289" alt="Capture d’écran 2024-06-11 à 12 27 14 PM" src="https://github.com/MTES-MCT/Docurba/assets/111045572/8817c114-fcef-4b1b-b4da-5c2b14656f69">

**Comment by UngererFabien** [comment]
@CeliaVermicelli oui j'avais fais un fix mais ce n'était que visuel. Les utilisateurs avait encore accès si ils allaient sur la bonne url.

J'ai rajouter un middleware. C'est à dire une redirection. Si un utilisateur arrive sur une trame qu'il n'a pas le droit d'édité il est redirigé sur la page public de cette trame.

Et de la même manière. Si un utilisateur arrive sur une trame qu'il n'a pas le droit de voir il est redirigé sur la page d'acceuil.

**Comment by UngererFabien** [comment]
@HermanceGauth au passage avec ce middleware les DDT/Dreal n'ont plus accès en edition au trames des autres départements/region. Seulement en lecture.

**Comment by CeliaVermicelli** [comment]
je peux passer d'une trame à l'autre sans pb en changeant l'url; https://jam.dev/c/dfe1a5f7-e26f-4a29-9034-36e152f20973

donc je n'ai p-e pas compris ce que vous vouliez dire
