### ISSUE TITLE
56  Theix-Noyalo : un PLU de commune nouvelle apparait dans l'onglet DU intercommunaux

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#604]
Lien [commune nouvelle Theix-Noyalo](https://docurba.beta.gouv.fr/ddt/56/collectivites/56251/commune)
(les communes de Theix et de Noyalo ont fusionnées) 

Le DU de Theix-Noyalo devrait apparaitre dans les DU communaux et non intercommunaux. 
La liste des communes concernées fait référence à une COMD **sans nom** et le lien n'aboutit pas. (cf demo si besoin : https://jam.dev/c/53422203-2d47-4496-87ba-8578632a2c0d)
![Capture d’écran 2024-05-14 à 10 35 17](https://github.com/MTES-MCT/Docurba/assets/111045572/162b68c1-9c8a-4ad1-a247-b4c0237612a9)
![Capture d’écran 2024-05-14 à 10 36 25](https://github.com/MTES-MCT/Docurba/assets/111045572/3f82095a-e40c-4fb1-af0f-505d70932e70)

FYI @HermanceGauth 
Fait écho à l'issue https://github.com/MTES-MCT/Docurba/issues/561 et l'exemple de la CC les Vallées du Haut Anjou (49) et les communes de Champigné et Querré

**Comment by HermanceGauth** [comment]
A priori à reprendre à la main comme la https://github.com/MTES-MCT/Docurba/issues/561

**Comment by UngererFabien** [comment]
Problème de la commune nouvelle de Theix qui n'existe pas selon l'INSEE

https://www.loom.com/share/403a64a24c334c64a74ff4295b7e7bfa

**Comment by CeliaVermicelli** [comment]
je vois toujours le même affichage : 

- [ ] le PLU de la nouvelle commune apparait dans du intercommunaux au lieu de du communaux
- [ ] le nom de la  COMD depuis les communes concernées est incomplet. 
- [ ] le click n'aboutit à rien (page header docurba et reste blanc) sur la comd mentionnée précédemment

![Image](https://github.com/MTES-MCT/Docurba/assets/111045572/7d0314b6-de66-4b70-aa61-055c315a6b14)

**Comment by HermanceGauth** [comment]
@CeliaVermicelli je propose de transférer ce cas et celui de Cambremer dans le tableau?

**Comment by Octaviedebs** [comment]
Dsl je n'avais pas vu cette issue du coup je viens d'en faire 2 pour Theix

https://github.com/MTES-MCT/Docurba/issues/661
https://github.com/MTES-MCT/Docurba/issues/660

Donc si je comprends bien **à intégralement basculer dans le tableau c'est ça ? 
je closerai les issues**

**Comment by HermanceGauth** [comment]
Oui ça vient du fait qu'une des anciennes communes n'existe plus dans l'INSEE et donc on doit le traiter à la main. Je pense que le mieux effectivement est de répertorier tous les cas non encore traités (même s'ils avaient fait l'objet d'une issue) dans le tableau et après on traitera par groupe tous les cas d'un coup, à définit ensemble la fréquence en fonction des cas rencontrés
