### ISSUE TITLE
Incohérence des noms des FRP : on indique le nom de l'EPCI et non celui de la commune (exemple Le Palais56, Dambenois 25, Parisot 81)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#605]
Le nom de la CT affichée dans la FRP de cette procédure secondaire est le nom de l'EPCI au lieu du nom de la commune, mais la procédure secondaire apparait bien sous la procédures principale/DU de cette commune. Je ne comprends pas pourquoi.
demo : https://jam.dev/c/87ac0fc9-30ae-4fbc-b08e-967d08a104a3
[lien EPCI](https://docurba.beta.gouv.fr/ddt/56/collectivites/245600465/epci)

Pour info, les autres procédures secondaires de ce même DU indique bien le nom de la commune dans le titre. 
J'ai pas l'impression que c'est dû au choix de la procédure parente au moment de la création de procédure secondaire, et si c'est ça je ne comprends pas à 100% comment le nom de l'EPCI se retrouve à ce niveau mais la proc secondaire bien au bon endroit dans la page de l'EPCI. 

@HermanceGauth je veux bien tes lumières :)

**Comment by Octaviedebs** [comment]
pour suivi

**Comment by Octaviedebs** [comment]
J'ai potentiellement l'impression que ça fait ça QUE quand la procédure a été créé sur Docurba - pas quand elle vient de sudocuh (mais j'ai pas tout testé )

**Comment by Octaviedebs** [comment]
En tout cas, pour illustrer le fait que le titre de la FRP peut vraiment nous aider - j'ai le sentiment que pour plus de clareté il faudrait : 
- nom du la collectivité **concernée** (et pas que porteuse)
- nom du type de procédure

Mais peut être que c'est déjà prévu ?

**Comment by CeliaVermicelli** [comment]
yes dans le nouveau dashboard (onglet Mes procédures) on aura bien le nom de la procédure sous cette forme : 
type de proc. - nº si existant - type de du -  CT concernée 
(Ex : modification nº2 du PLU de Sarzeau)

Je l'avais ré-évoqué avec @lerayj au séminaire et JulienZ car ça n'apparaît pas dans les maquettes effectivement, mais c'est normalement bien pris en compte.

**Comment by CeliaVermicelli** [comment]
### Nouvel exemple suite à ajout d'event par la DDT 68 : CA Colmar agglo

![Capture d’écran 2024-06-04 à 10 40 07 AM](https://github.com/MTES-MCT/Docurba/assets/111045572/8f0142d7-71d9-4359-8858-29672e4ef3d7)
![Capture d’écran 2024-06-04 à 10 40 19 AM](https://github.com/MTES-MCT/Docurba/assets/111045572/a67536ec-966f-45ec-b46b-072e6d30b0e0)

**Comment by CeliaVermicelli** [comment]
Autre cas : Locmaria Plouzané/CC Pays d'Iroise : 

FRP : https://docurba.beta.gouv.fr/frise/a23251c7-ec6e-4c97-943a-a0670c85ebb1
<img width="1071" alt="Capture d’écran 2024-06-21 à 5 03 36 PM" src="https://github.com/MTES-MCT/Docurba/assets/111045572/88c5c687-4433-40ac-ae09-93429e7ec323">

**Comment by CeliaVermicelli** [comment]
Autre cas remonté de Bastien (à prévenir quand résolu) 
voir son email : https://app.sparkmailapp.com/web-share/pKdfwKtv9AlnYF5IiIW2hteNslP3z8LiPzXLPmyF

Exemple du PLU de Gâvres 56062 // CA Lorient Agglo

**Comment by CeliaVermicelli** [comment]
Autre cas remonté par Pierre DDT 67 (à prévenir quand résolu) + Olivia 

Commune : Cosswiller

> En cliquant sur le DU communal, nous voyons une procédure secondaire. En cliquant sur la feuille de route, le titre indique "Modification 1 PLU CC de la Mossig et du Vignoble " ce qui est trompeur puisque la CC n'a pas de compétence PLU...

**Comment by CeliaVermicelli** [comment]
Testé pour : 
* Parisot 81 
* Le palais 56 
* gavres 56 
* Cosswiller 67
* Locmaria plouzané 29
-> tout est ok, on a bien le nom de la commune - périmètre du DU et non le nom de l'EPCI porteuse

**Comment by Octaviedebs** [comment]
Cela fonctionne en prod' uniquement pour les procédures principales et pas secondaires - mais j'ai l'impress° que la version dev actuelle corrige ce problème pour les procédures secondaires 

Exemple pour Dambenois (25) en prod : [modif n°2 ](https://docurba.beta.gouv.fr/frise/df76f786-735f-4308-a82d-25cdf1cf71bc)

<img width="901" alt="Capture d’écran 2024-08-29 à 15 26 39" src="https://github.com/user-attachments/assets/837fc39c-f273-42b0-bc83-4e5e68191fb5">


en dev : 

<img width="901" alt="Capture d’écran 2024-08-29 à 15 25 21" src="https://github.com/user-attachments/assets/24233ef3-6034-4d52-866e-390b8bd797d2">


ou autre cas sur lql je suis tombée : Plouhinec (56) :

**Comment by CeliaVermicelli** [comment]
**De mon Côté ça fonctionne bien** pour les PS aussi (en side etat)
Bon aussi pour les PS de : 
* Le Palais (56)
* gâvres (56)
* Parisot (81)
* Locmaria-Plouzané (29)

<img width="1056" alt="Capture d’écran 2024-08-29 à 4 34 08 PM" src="https://github.com/user-attachments/assets/261642e2-eead-40d6-afc0-48c6d5dcc0a2">

**Comment by Octaviedebs** [comment]
Yes en dev c'était bon donc ça m'étonne pas que ce soit bon en prod' !
