### ISSUE TITLE
Nouveau PDF à héberger (suite au changement de QV4 par "UP4")

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#606]
Hello Fabien! 

Voici le lien du nouveau PDF à héberger : https://drive.google.com/file/d/1F0L-wyIjTOnIp2FYKBXgDtl9qsbtCvNo/view?usp=sharing

l'url devrait rester : https://docurba.beta.gouv.fr/pdf/kitdecom/DDT/pourquoiutiliserdocurba.pdf si possible

merci !

**Comment by Octaviedebs** [comment]
@CeliaVermicelli c'est tt bon je close et l'url est bien la même
