### ISSUE TITLE
Erreur affichage d'un PLUiH dans la mauvaise EPCI - CC des 100 étangs (70)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#608]
demo : https://jam.dev/c/b5e4669c-97e3-49fa-bd23-d1fc0a2419e4

EPCI où se trouve l'erreur : https://docurba.beta.gouv.fr/ddt/70/collectivites/247000854/epci

![Capture d’écran 2024-05-16 à 08 54 53](https://github.com/MTES-MCT/Docurba/assets/111045572/95196de3-157f-4e2b-b1f4-3bdacc9fb76d)

La ddt précise que les onglets DU communaux et scot sont correct.

to do célia : prévenir Nicole quand résolu

**Comment by lerayj** [comment]
Duplicate #610 
Même idée que l'issue, ici c'est Malbouhans (70328) qui est dans le PLUi du Pays de Lure alors qu'il appartient au CC des 1000 étangs

**Comment by HermanceGauth** [comment]
@CeliaVermicelli je pense que la chose à faire est d'expliquer d'où provient cet affichage à la DDT et voir si elle a des préconisations? Parce qu'en gros on ne peut pas dire on affiche que les PLUi avec le même périmètre que l'EPCI car sinon on n'afficherait pas les PLUi sectoriels. Peut-être y a-t-il une erreur dans les périmètres sur Sudocuh comme dans l'issue https://github.com/MTES-MCT/Docurba/issues/610 ?

**Comment by CeliaVermicelli** [comment]
DDT prévenue, je close et réouvrirai une issue ou feedback utilisateur si jamais elle a des préconisations ou commentaire sur les périmètres. 
Merci !
