### ISSUE TITLE
Bug dump - ex du 81 et 56

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#609]
* 81 : Event "autre" ajouté sur Sudocuh le 15.05, avec en description/commentaire le fait qu'il s'agit bien d'une delib de prescription
Au 16.05 9h, il n'est pas remonté sur Docurba : 
https://docurba.beta.gouv.fr/frise/40c05a6b-f74e-45dd-b5c7-e10d598d4f79

* 56 :  https://jam.dev/c/960b970d-2fa1-459d-9ccd-4fafeed2d4e0
il manque la modif simplifié du soct de lorient, ajouté par claire le 29 mars sur Sudocuh. 

@HermanceGauth @lerayj @UngererFabien

**Comment by CeliaVermicelli** [comment]
Autres exemples d'ajouts sur Sudocuh par la DDT 56 qui ne sont pas encore visibles sur Docurba : 

* La révision du SCoT du Pays d’Auray,
* la modification simplifiée nº2 du ScoT opposable d'Auray

Lien page EPCI : https://docurba.beta.gouv.fr/ddt/56/collectivites/200050219/epci

**Comment by CeliaVermicelli** [comment]
FYI retour de la DDT 49 cet aprem : les éléments ajoutés sur Sudocuh se sont bien retrouvés le lendemain sur Docurba de son côté. Il ne m'a pas donné de détails car on devait parler de bcp d'autres choses mais si besoin je peux lui demander.

**Comment by Octaviedebs** [comment]
Note à moi même : CC Auray Quiberon Terre Atlantique (56) à prévenir quand issue résolue 
MS n°2 prescrite fin 2023 présente sur docurba pas sur sudocuh rattachée au SCOT opposable AURAY

**Comment by CeliaVermicelli** [comment]
81 : event manquant du 4.12 - prescription ✅ visible en dev et en prod

56 : sont bien présents ✅ : 
* la PS de modif simplifiée du SCoT de Lorient 
* La révision du SCoT du Pays d’Auray,

**Il manque par contre :** 
* [demo](https://jam.dev/c/c4c04b8d-5a65-43d7-91eb-ccd66e23de11). la modif simplifiée nº2 du scot opposable d'Auray, prescription du 20.11.2023 (cf capture sudocuh) ❌
<img width="838" alt="Capture d’écran 2024-09-26 à 4 23 50 PM" src="https://github.com/user-attachments/assets/af9f21b5-9d2b-44e6-9f92-89e8a741cd02">

**Comment by HermanceGauth** [comment]
@lerayj à vérifier

**Comment by HermanceGauth** [comment]
@CeliaVermicelli ça m'a l'air ok : https://docurba.beta.gouv.fr/frise/677780aa-0fd1-4fe1-9d58-413ece6035ce je te laisse prévenir si besoin et closed
