### ISSUE TITLE
Comment faire un export .pdf du PAC

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#61]
problématique à l'issue "comment partager le PAC" : 

Les users, au moment de créer le PAC, veulent comprendre comment il vont pouvoir s'en saisir effectivement pour partage à la CT : est-ce qu'on peut avoir une solution fonctionnelle pour éviter cette régression ? :/

**Comment by HermanceGauth** [comment]
Oui c'est typiquement le genre de régression dont je parlais pendant le séminaire. Il n'est plus possible de consulter, télécharger ou partager un PAC. A mon avis, on n'aurait pas dû changer l'interface tant que ces fonctionnalités essentielles n'étaient pas préservées.

**Comment by UngererFabien** [comment]
- [ ] Remettre la fonctionnalité de partage sur les projets
- [ ] Remettre le bouton de téléchargement de PDF
- [ ] Avoir du feedback/progression sur le telechargement de PDF
- [ ] Save les PDF générés dans le storage
- [ ] Utiliser le sha de la branche git pour ne pas re générer le PDF si le PAC n'a pas changé.

**Comment by HermanceGauth** [comment]
Et aussi le mode "consultation" pour voir ce que la collectivité verrait

**Comment by CeliaVermicelli** [comment]
@UngererFabien tu as closed cette issue car tu ajoutes ça à ta roadmap ? 
J'ai une session de prise en main le 5 octobre et ça m'aiderait d'avoir de la visibilité sur le retour des fonctionnalités prio : 
- export pdf 
- Partage par email
- push automatique des modifications du cadre juridique sur toutes les trames
pour savoir ce que je peux leur promettre

**Comment by CeliaVermicelli** [comment]
Test pre preprod : 

- Le PAC ne charge pas sur un PAC créé il y a quelques mois. (+5min d'attente)
![Capture d’écran 2023-10-12 à 11 31 28](https://github.com/MTES-MCT/Docurba/assets/111045572/5ff6662e-c796-441a-9c5d-05bd93732550)
- Test sur un PAC créé le 10.10 et un créé à l'instant : plus de 5min d'attente, je considère que ça ne fonctionne pas.

Si chargement de plus de 30s : tu parlais d'une barre de progression du chargement, ce serait possible à rajouter ? ou au moins un message qui prévienne du temps moyen de chargement.

**Comment by CeliaVermicelli** [comment]
@UngererFabien ça a fonctionné pour un PAC sur une commune (Pac créé le 6 juin). 

Le problème est sur les EPCI : 
![Capture d’écran 2023-10-12 à 11 49 12](https://github.com/MTES-MCT/Docurba/assets/111045572/3b185a23-8e73-41fb-a047-7050af5600b9)

**Comment by CeliaVermicelli** [comment]
Retour un un PDF téléchargé : 

Le sommaire comporte bien les liens des différentes sections mais ils ne sont pas en bleus et surlignés ; je pense que les DDt vont croire que ça ne fonctionne pas, pas sûr qu'ils testent d'eux mêmes....
![Capture d’écran 2023-10-12 à 11 52 18](https://github.com/MTES-MCT/Docurba/assets/111045572/d8e559d8-5878-4162-9c4e-0c90f2ab3d39)

**Comment by CeliaVermicelli** [comment]
Incohérences entre le sommaire et le contenu du PAC en PDF : 

Le sommaire contient une seule loi sur la planif : loi climat et résilience (CF pj1), alors qu'en allant consulter le texte, je retrouve les lois ALUR, ENE, etc,(cf PJ2) -> j'ai vérifié et toutes mes sections de lois sont cochées dans le PAC (cf PJ3) donc c'est un pb de sommaire?
![Capture d’écran 2023-10-12 à 11 59 04](https://github.com/MTES-MCT/Docurba/assets/111045572/b1f0c41b-fb78-4bd3-9471-bd68c230a2a7)

![Capture d’écran 2023-10-12 à 11 59 13](https://github.com/MTES-MCT/Docurba/assets/111045572/87f93aec-27c8-4a79-a8b8-dae698b044d6)
![Capture d’écran 2023-10-12 à 12 02 35](https://github.com/MTES-MCT/Docurba/assets/111045572/3c418604-4ab5-41f0-861b-d67b18ecb919)

**Comment by CeliaVermicelli** [comment]
`Nom du fichier téléchargé et message de confirmation`

Je pense que les DDT ne sont pas toute à mêem de retrouver les fichiers teléchargés sur leur ordinateur.. je pense qu'un message/popoup de confirmation "Pdf du APC téléchargé correctement" permettrait d'éviter des frustration 

Aussi, j'imagine qu'en cherchant le fichier, elles vont le chercher avec le nom du PAC choisi ou le nom de la CT ; ce serait possible de donner un nom au "file" - le nom du PAC qu'elles ont déterminé.

**Comment by CeliaVermicelli** [comment]
Retour de Cécilia Bellay (DDT22) sur le téléchargement de son PAC (créé le premier trimestre 2023 j'estime) : 

> J'ai essayé d'obtenir un pdf mais en cliquant sur 'pdf' à côté de 'modifier le PAC', ça 'tourne' puis rien ne se passe... je n'ai rien dans mes téléchargements.

Dans ce genre de cas, @UngererFabien de quoi as-tu besoin? du lien du PAC ? date exacte de création ? 
C'est un PAC qu'elle a normalement créé pour la commune de Trédaniel, si jamais ça peut aider.

**Comment by UngererFabien** [comment]
Je close cette issue, Laurence nous a fait des retours, je vais créer une nouvelle issue avec tous ses retours.

> Dans ce genre de cas, @UngererFabien de quoi as-tu besoin? du lien du PAC ? date exacte de création ? C'est un PAC qu'elle a normalement créé pour la commune de Trédaniel, si jamais ça peut aider.

Oui juste le lien du PAC c'est suffisant. Je devrait bientôt avoir ces informations avec le travail d'analytics.

**Comment by CeliaVermicelli** [comment]
Hello @UngererFabien 


Bug sur l'export PDF : le fichier téléchargé ne comporte que la page de garde. 
J'ai testé sur un PAC PLUi et PLU du 08, et la DDT40 sur un PLUi : on obtient que la page de garde. CF PJ

[file (5).pdf](https://github.com/MTES-MCT/Docurba/files/13029883/file.5.pdf)

**Comment by UngererFabien** [comment]
Il faut re fetch les sections séléctionnés dans le module de création de PDF au cas ou un utilisateur fait sa selection dans un onglet de navigateur et le téléchargement dans l'autre.

**Comment by CeliaVermicelli** [comment]
> Je close cette issue, Laurence nous a fait des retours, je vais créer une nouvelle issue avec tous ses retours.

Hello @UngererFabien, je ne trouve pas la nouvelle issue, désolée ! 
donc voici le lien du PAC du 22 qui ne se télécharge pas sur son ordinateur _"je clique sur "PDF", ça tourne et rien ne se passe"_ : https://docurba.beta.gouv.fr/trames/projet-47e7dad0-9f7b-4cfb-b92d-50b64348cfc9
