### ISSUE TITLE
(Erreur affichage ) | Le PLUi d'une nouvelle commune remonte sur le mauvais EPCI 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#610]
Là je suis sur une CC du Cordais et du Causse, et on affiche aussi le PLUi de la CA Gaillac-Graulhet

https://jam.dev/c/cda6dedb-e501-46a6-8325-46311247f2cb

**Comment by Octaviedebs** [comment]
[#558](https://github.com/MTES-MCT/Docurba/issues/558) en lien ?

**Comment by lerayj** [comment]
Après investigation:

https://www.loom.com/share/e5ba54aaf9fe4c039620b40e33d06d70?sid=6e91e390-3fee-4e63-b3e8-73eb6a89d98d

**Comment by Octaviedebs** [comment]
Alors, il se trouve que j'ai eu l'EPCI au tel ce matin, qui m'a donné plus de précisions = 

CA Gaillac Graulhet = apparemment c'est une nouvelle commune issue de la fusion de : 
- CC Vére gresigne (mais juste une partie des communes car l'autre partie des communes sont allées dans la CC Cordais et du Causse = Noailles et Loubers + Frausseilles Amarens et Donnazac ) 
- CA Rabastinois - Tarn et Dadou - et Pays Salvagnacois 

Par ailleurs sur le PLUi en cours d'élaboration sur la CC Cordais et du Causse : **les communes de Frausseilles, Amarens et Donnazac ne sont pas comprises il faudrait les supprimer du périmètre de ce PLUi** (elles ont rejoint trop tard l'interco de ce que j'ai compris)

**Comment by lerayj** [comment]
On peut difficilement modifier des périmètres définis dans Sudocu avec le dump journalier.
En soit on est donc plutot sur une issue de "Pouvoir modifier les périmetres de DU originaire de Sudocuh"
Mais la logique actuel est donc bonne.
Sinon oui c'est ca c'est juste un PLUi qui a des communes de plusieurs epcis. 

Pour changer l'ordre ca me va, c'est juste qu'il faudrait en faire une issue et que ca soit clair pour tous le monde, cad par exemple que l'on sors de l'ordre les status abrogé, annulé, ... pour les mettre a la fin ou ailleurs ? @julienzdocurba ?

**Comment by julienzdocurba** [comment]
Juste pour être sûr de comprendre: Le problème c'est qu'il y a un Du abandonné (c'est un status sur Docurba?) et l'utilisateur le confond avec une autre procédure?

**Comment by HermanceGauth** [comment]
@julienzdocurba pour moi il y a deux choses ici :
1) il y a une commune (ou plusieurs communes) qui était anciennement dans le périmètre d'un DU qui a été abandonné (oui c'est le statut Docurba, il n'y avait pas ce concept de statut dans Sudocuh) et qui est maintenant dans le périmètre du DU en cours. Sur la page de la collectivité qui porte le DU en cours, on voit le DU abandonné parce que certaines communes de cet EPCI faisaient parties du périmètre du DU abandonné. Donc c'est normal qu'on affiche cela mais un quick win serait sûrement comme le dit Octavie de faire apparaître en premier le DU en cours et en second le DU abandonné.
2) en réalité ces communes Frausseilles Amarens et Donnazac font partie du périmètre de l'EPCI mais pas du périmètre du DU car elles ont rejoint l'EPCI trop tard, alors que la procédure était trop avancé. Hors dans le périmètre du nouveaux DU on voit bien ces communes là. C'est une erreur qui provient de Sudocuh, et donc on ne peut rien y faire à part demander à la DDT de le modifier si elle peut. Ca rejoint notre débat sur le fait de laisser la main aux utilisateurs pour modifier les périmètres et éviter d'avoir à traiter chacun de ces cas.

**Comment by julienzdocurba** [comment]
Ok je comprends mieux merci. Je parlais surtout du problème que ca cause (qu'est-ce qui à causé le fait qu'on pense à changer quelque chose?): Est-ce que l'utilisateur en question a essayé de retrouver son DU et s'est retrouvé sur le DU abandonné par erreur? Est-ce que c'est autre chose? Parce que ça pourrait impacter énormément la solution (par exemple peut être qu'en fait il faut mettre le statut plus en avant). Changer l'ordre d'affichage des DU c'est une solution possible mais elle aura ses inconvénients comme par exemple devoir définir de nouvelles règles d'affichage, changer le pattern du tableau du nouveau dashboard qui est ordonné par date etc. Du coup je préfère qu'on soit certain du problème qu'on souhaite résoudre pour nous aider à choisir la solution la plus adaptée.

**Comment by julienzdocurba** [comment]
Super merci, je vais ajouter ca au feedback utilisateur dans l'aprem du coup!

**Comment by HermanceGauth** [comment]
@Octaviedebs j'ai l'impression qu'il n'y a plus trop d'action de dev ici, plutôt informer collectivité pour le point 1 et DDT pour le point 2?

**Comment by Octaviedebs** [comment]
Yes complètement 

- CT prévenue ✅
- @CeliaVermicelli peux tu voir avec la DDT 81 pour qu'ils puissent modifier le périmètre du PLUi en cours d'élaboration sur la CC Cordais et du Causse https://docurba.beta.gouv.fr/collectivites/200034064/?isEpci=false sur sudocuh : il faut enlever les communes de Frausseilles, Amarens et Donnazac qui ne sont pas comprises dans ce DU (elles ont rejoint trop tard l'EPCI) - tu pourras close quand good !

**Comment by CeliaVermicelli** [comment]
Modifications faites par la DDT sur Sudocuh : 

- Retrait des communes du PLUI Cordais Causse,
- Ajout des mêmes communes dans le PLUI Vère Grésigne.

Je vérifie demain matin si les modif sont bien visibles sur Docurba.

**Comment by CeliaVermicelli** [comment]
Les changements n'ont pas été pris en compte apparemment :/ 

### 1. On a toujours les communes Frausseilles, Amarens et Donnazac dans le périmètre du PLUi en cours :/

<img width="1246" alt="Capture d’écran 2024-06-05 à 10 28 22 AM" src="https://github.com/MTES-MCT/Docurba/assets/111045572/adc60413-6b86-4f36-9463-b592e15d6064">

### 2. Le PLUi opposable par contre les a bien dans son périmètre


<img width="1294" alt="Capture d’écran 2024-06-05 à 10 28 33 AM" src="https://github.com/MTES-MCT/Docurba/assets/111045572/0e207812-fa13-4bfa-8f5f-2cffd14a1e6c">

**Comment by HermanceGauth** [comment]
Ok je pense que c'est quelque chose qui n'est potentiellement pas pris en compte dans le dump, je vais faire une issue spécifique sur ce sujet
