### ISSUE TITLE
Permettre aux collectivités de créer une procédure

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#612]
Harmonisation du parcours DDT et CT : https://www.figma.com/design/4W463mFBKoDzf4mgJAhW9y/Docurba-(V2)?node-id=3605-16156&t=yuS66aGuvEQGFkcY-0

Bien prévoir l'ajout de procédure SCoT pour tous les utilisateurs

**Comment by HermanceGauth** [comment]
Fonctionnalité disponible uniquement en mode connecté.

**Comment by lerayj** [comment]
https://github.com/MTES-MCT/Docurba/tree/harmonisation

**Comment by Octaviedebs** [comment]
**Note à moi même : entre dev & prod** 

- créer la pop up d'annonce (vidéo & co)
- issue tally pour mep

**Comment by Octaviedebs** [comment]
FYI @CeliaVermicelli

**Comment by Octaviedebs** [comment]
Hello @HermanceGauth - comme le soulignait @CeliaVermicelli [ici](https://github.com/MTES-MCT/Docurba/issues/259) : est-il prévu de moduler les droits d'accès pour la création d'une nouvelle procédure ?
Qu'est-il prévu dans le parcours lorsqu'il y a création d'une nouvelle procédure depuis un accès non connecté ?

Avec la suppression à venir du dépôt d'un lien URL sur le GPU : peut être juste empêcher la création d'une nouvelle procédure en mode non connecté > rediriger juste vers la page de sign up avec un message informant que pour créer une nouvelle procédure il faut d'abord se créer un compte

**Comment by HermanceGauth** [comment]
Voici ce qui est prévu dans les maquettes : 
![image](https://github.com/user-attachments/assets/c0315d75-afab-4868-bc49-ea53c036d654)

**Comment by Octaviedebs** [comment]
Hello @UngererFabien - j'ai retesté (on avait probablement testé avant les vacances) mais cela ne semble plus fonctionner

https://jam.dev/c/4dd89ffd-ac0d-4913-a8e3-b0c42be8e788

FYI @HermanceGauth

**Comment by HermanceGauth** [comment]
Ce qu'on en disait avant les vacances, je vais retester
![image](https://github.com/user-attachments/assets/2455a3d5-769f-4aa3-8687-7307409fc723)

**Comment by HermanceGauth** [comment]
- Accès non connecté : 
comportement en dev : j'ai accès au formulaire de création de procédure mais je ne peux pas réaliser l'action / comportement attendu : être redirigé vers la page de création de compte au clic sur nouvelle procédure
- Accès non validé : idem mais redirection vers "en attente de validation"
- Accès connecté DDT :
comportement en dev : j'ai pu créer une procédure pour une collectivité qui n'est pas dans mon département /
comportement attendu : je ne dois pas pouvoir créer une procédure pour une collectivité qui n'est pas dans mon département
- Accès connecté CT/BE : voir jam d'Octavie, la collectivité devrait pouvoir créer, modifier, supprimer une procédure sur son périmètre (et ne pas pouvoir le faire en dehors sauf si invité sur la procédure)

**Comment by Octaviedebs** [comment]
Je ne pense pas que la solution court terme soit optimale car « conserver l'email avec le lien GPU lors du dépôt d'acte via un événement » = un email sera donc envoyé à chaque ajout d'événement si je ne dis pas de bêtises @lerayj @julienzdocurba 
**=> cela risque de faire bcp bcp d'emails envoyés aux DDT/CT (à tous les users utilisant la FRP) ce qui n'est pas optimal**

On avait évoqué @julienzdocurba le fait d'ajouter ce lien URL ailleurs, soit sur l'event concerné, soit une option au niveau du forme d'ajout d'event pour générer ou non le lien (il me semble) : quelle serait la solu° la moins coûteuse pour ne pas retarder la mep ? 

Pour rappel sur le besoin : cela permet aux communes  de plus simplement partager leurs documents/actes

Si c'est trop coûteux on peut peut être supprimer le lien URL à court terme / mais prévoir une intégration de ce lien dans une prochaine itération ? 

Qu'en pensez vous ? 

Je suis dispo pour en parler de vive voix si besoin

**Comment by HermanceGauth** [comment]
Pour ne pas retarder la mep, je propose de supprimer tout envoi d'URL et de réfléchir dans un second temps à l'intégration dans la FRP car l'URL n'est pas un besoin prégnant VS l'ajout de procédure par les collectivités qui est une feature très structurante dont on a besoin rapidement.

**Comment by julienzdocurba** [comment]
Je suis pas certain de tout comprendre des derniers échanges. Vous voulez qu'on se fasse un call pour en parler ou c'est bon pour vous?

**Comment by Octaviedebs** [comment]
Je peux me rendre disponible pour en discuter pour que ce soit clair pour toi ! je te MP :)

**Comment by UngererFabien** [comment]
La creation de procedure bug.

**Comment by HermanceGauth** [comment]
Effectivement, quid de :
- la possibilité de supprimer une procédure par une CT (valider ensemble pendant notre point et le but était d'harmoniser le parcours DDT et CT donc la suppression doit être possible des deux côtés)
- la possibilité de créer une procédure pour un SCoT (cf début de l'issue)

**Comment by Octaviedebs** [comment]
Autre point qui n'a pas été harmonisé - à la création d'une nouvelle procédure, quand une CT choisit en objet Autre > puis renseigne des éléments = rien n'apparait depuis l'accès collectivité (cela n'apparait que depuis l'accès DDT cf PJ)

<img width="1406" alt="Capture d’écran 2024-09-03 à 16 05 44" src="https://github.com/user-attachments/assets/9ecc7497-c7c5-4ecb-9147-1987d66bdd06">
<img width="1406" alt="Capture d’écran 2024-09-03 à 16 06 31" src="https://github.com/user-attachments/assets/dfd8efcc-9c0b-49ed-8485-4cade7020e3c">

**Comment by Octaviedebs** [comment]
https://github.com/MTES-MCT/Docurba/issues/798

**Comment by Octaviedebs** [comment]
Les points restant sont dans les 3 issues mentionnées ci-dessus https://github.com/MTES-MCT/Docurba/issues/796 https://github.com/MTES-MCT/Docurba/issues/797 https://github.com/MTES-MCT/Docurba/issues/798
