### ISSUE TITLE
Permettre le partage d'une procédure

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#615]
https://www.figma.com/design/4W463mFBKoDzf4mgJAhW9y/Docurba-(V2)?node-id=5027-39835&t=yuS66aGuvEQGFkcY-0

même règle de suggestion = les personnes de mon périmètre
- possibilité de retirer un collab = rentre dans le scope (JulienL ok)
- feature d’ajout de collab dispo aussi pour les procédures historiques
- email pour prévenir qu’il ont été invité sur une procédure et renvoi vers la création de compte si la personne n'a pas de compte
- les personnes invitées peuvent ensuite ajouter des events

**Comment by lerayj** [comment]
https://github.com/MTES-MCT/Docurba/tree/collabprocedure

**Comment by Octaviedebs** [comment]
**Pré requis après passage en DEV > Mise En Prod** | TO DO @Octaviedebs @CeliaVermicelli 

- [ ] Pop up Tally à faire (vidéo & visuels)
- [ ] Mise en prod du Tally concomitante à la mep de cette issue

**Comment by Octaviedebs** [comment]
@lerayj @HermanceGauth Peut être que ce point a déjà été évoqué mais quelles sont exactement les conditions d'affichage des collaborateurs à la fois sur la liste sur la FRP & dans les collab suggérées ? 

Mon point est le suivant : j'ai l'impression que ceux sont uniquement les users inscrits sur le périmètre concerné => je pense qu' il faudrait juste ajouter : **et qui ont été validés** - en effet, même s'il y en a pas bcp, il ne faudrait pas qu'on se retrouve avec les gens random qui se sont inscrits sur un territoire mais que je n'ai pas validé du coup car rien à voir avec la collectivité

Lien aussi avec [cette issue/réflexion](https://github.com/MTES-MCT/Docurba/issues/682) juste pour info

**Comment by Octaviedebs** [comment]
Issues de QA (en cours): 

- https://github.com/MTES-MCT/Docurba/issues/825
- https://github.com/MTES-MCT/Docurba/issues/826
- https://github.com/MTES-MCT/Docurba/issues/827 
-

**Comment by HermanceGauth** [comment]
@CeliaVermicelli @Octaviedebs je close mais vous aviez une todo liste ici.
