### ISSUE TITLE
Afficher les collaborateurs sur la FRP et les events

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#616]
https://www.figma.com/design/4W463mFBKoDzf4mgJAhW9y/Docurba-(V2)?node-id=5034-44139&t=yuS66aGuvEQGFkcY-0

- Sur la FRP : afficher la liste des collaborateurs sur l’encart de droite, quand +3 collaborateurs mettre un “voir plus” pour dérouler l’ensemble.
- dans l’`encart de l’event` : précision de l’auteur de l’ajout d’évent = rentre dans le scope (JulienL ok)

**Comment by Octaviedebs** [comment]
**Note à moi même : entre dev & prod** 

- créer la pop up d'annonce (vidéo & co)
- issue tally pour mep
