### ISSUE TITLE
Règles sur les event en fonction des rôles

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#617]
- n'importe qui peut créer n'importe quel type d'event
- les ddt peuvent éditer n’importe quel event et les CT/BE seulement les leurs

**Comment by Octaviedebs** [comment]
1er souci (j'ai l'impression qu'il est nouveau et en lien avec la https://github.com/MTES-MCT/Docurba/issues/637

https://jam.dev/c/7425ace6-17da-4500-9798-c3febddc90e2

- Une CT peut ajouter un event sur une FRP d'une autre CT (sur laquelle elle n'est donc pas connecté) mais qui fait partie du même EPCI - je ne suis pas sûre qu'on veuille ce comportement

**Comment by Octaviedebs** [comment]
@HermanceGauth Désolée j'ai besoin de précision sur le comportement attendu, cf ton premier commentaire

Sur une FRP, j'ai testé le comportement suivant = 

- je suis CT : je ne peux QUE modifier celui que j'ai ajouté 
- je suis DDT : je peux modifier tous les events même ceux des CT / autres users DDT mais pas sudocuh de **mon département**

- je suis DDT :je peux modifier tous les events même ceux des CT / autres users DDT mais pas sudocuh  HORS MON DEPARTEMENT cf ce jam https://jam.dev/c/3d5417da-f06d-488f-92ff-a843067121ad
👉🏻 pas sûre que ce soit le comportement voulu justement ?

Sur la création d'event, as tu des cas à tester ? des cas où certains events ne pouvaient pas être créés en fonction d'un rôle ?

**Comment by HermanceGauth** [comment]
Oui effectivement je n'avais pas précisé, car cela me semblait assez évident, que l'on ne doit pas pouvoir modifier les évènements des autres.

> je suis CT : je peux ajouter un event sur une FRP d'une autre CT (sur laquelle elle n'est donc pas connecté) mais qui fait partie du même EPCI - je ne suis pas sûre qu'on veuille ce comportement ?

> je suis CT : je peux ajouter un event sur une FRP d'une autre CT en dehors de mon EPCI : je ne suis pas sûre qu'on veuille ce comportement ?

Non il ne faut pas effectivement qu'une collectivité puisse contribuer à une procédure qui n'est pas la sienne.

> je suis DDT :je peux modifier tous les events même ceux des CT / autres users DDT mais pas sudocuh HORS MON DEPARTEMENT

> je suis DDT : je peux ajouter un event HORS MON DEPARTEMENT

Pour ce qui concerne les DDT cf cette issue : https://github.com/MTES-MCT/Docurba/issues/146

**Comment by HermanceGauth** [comment]
Tant qu'on est pas invité on est cantonné à son périmètre initial

**Comment by HermanceGauth** [comment]
A priori effet de bord de passage en prod de celle-ci ? https://github.com/orgs/MTES-MCT/projects/37?pane=issue&itemId=65093201

**Comment by Octaviedebs** [comment]
Retour d'une utilisatrice pour illustrer  : _je me suis créé un compte pour la commune de Waldhambach que j’accompagne pour l’élaboration de son PLU et je suis surprise de constater que j’ai accès à toutes la communes de la CC d’Alsace Bossue dont la commune est membre._

La résolution de ce bug est prévue pour cet été @HermanceGauth @lerayj ?

Cela risque d'être assez bloquant

**A prévenir post résolution : Léa Dentz**

**Comment by UngererFabien** [comment]
Mis a part le partage de procédure j'ai l'impression que le comportement est bon maintenant.

**Comment by Octaviedebs** [comment]
Update : tout ok 
- je suis connectée en side collectivité sur un territoire X : je ne peux pas ajouter d'event ni sur un territoire Y ni sur un territoire qui fait partie de l'EPCI de X donc tout est ok

**Comment by Octaviedebs** [comment]
User contactée
