### ISSUE TITLE
Permettre la consultation et le remplissage de l'onglet DGD

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#619]

**Comment by HermanceGauth** [comment]
https://www.figma.com/design/4W463mFBKoDzf4mgJAhW9y/Docurba-(V2)?node-id=6280-52864&t=VCBi7W4i8voDReVW-0

**Comment by HermanceGauth** [comment]
écrans 274, 275, 276 et 273

**Comment by lerayj** [comment]
Pour garder tous le monde up to date sur le sujet:
- L'interface fini a 90% (différents etat et forms). La partie validation des champs et auto calcul des montant globaux au niveau des versement est manquant.
Ce qu'il manque:
- Déplacer et transformer la data d'un format JSON (hierarchie) vers un format relationnel. La gestion de info general + versements + step de versement deviens trop compliqué a géré maintenant que l'on va dans ce niveau de details.
- Il faudra donc reformatter également la donnée historique la dessus et le rajouter au daily dump pour que le niveau de détails / donnée de docurba fonctionne avec la donnée historique.
- Mettre des gardes fou sur la donnée historique pour empeche l'édition et la manipulation de step rentré précédament, un peu a la manière des evenements historique

**Comment by CeliaVermicelli** [comment]
Je crois que le lien d'Hermance n'est pas le bon, en tous cas il ne cible pas les écrans que j'imaginais trouver sur la dgd. 
Je crois que le lien est [celui -ci](https://www.figma.com/design/4W463mFBKoDzf4mgJAhW9y/Docurba-(V2)?node-id=6440-157715&node-type=FRAME&t=PLevpX22RXCn8o1G-0) et c'est le frame 184 

Comportement attendu : petit doute par ce que vous entendez par "collaborateurs" de la proc. et les "editeurs DDT" de la proc. 
-> un _collaborateur_ peut éditer la proc. 
-> hier on nommait _l'editeur_ celui qui a créé la procédure initialement, donc cela peut être une CT. Problème : quand la DDT n'a pas créé la proc., est-ce qu'elle peut récupérer les droits d'éditeur (que j'aurai tendance à appeler "admin" pour ne pas confondre entre nous avec _collaborateur_)

**QA onglet DGD :** 

**ACCES DDT**

[demo](https://jam.dev/c/b7c0a92e-7698-4397-a82a-e7d3ab441422). 
Problèmes soulevés : 
* il **manque le bouton "ajouter une étape dans le versement**" donc je comprends que je ne peux pas tester le reste du parcours et la validation des versement. 
* **l'ajout de commentaire este possible mais n'est pas sauvegardé** 

ACCES CT : pas testable.

Et sinon : 

* **traduire le "Type & press" :** 
<img width="951" alt="Capture d’écran 2024-09-06 à 3 37 18 PM" src="https://github.com/user-attachments/assets/b2ac50ab-9486-4252-81d8-718ad7dd1b78">

**Comment by HermanceGauth** [comment]
Effectivement le lien du figma n'est pas le bon, peut-être dû au ménage fait dans le fichier?

Pour les droits : 
- lecture : tous les collaborateurs de la FRP
- édition : collaborateurs DDT de la FRP

Sur la fonctionnalité :
- je ne vois pas l'historique, je ne sais pas si c'est dû au département dans lequel je me trouve : https://jam.dev/c/2050fb85-f351-4a0d-ad64-880796bd1a57
- étape de versement : si c'est déscopé il faut permettre de changer à la main le "versement terminé" et ne plus distinguer "montant total" de "montant versé" :https://jam.dev/c/ead0f3d9-6909-43cb-a58b-c51803fef3b6

**Comment by julienzdocurba** [comment]
Désolé pour le lien, je le remets ici: https://www.figma.com/design/4W463mFBKoDzf4mgJAhW9y/Docurba-(V2)?node-id=6966-208689&node-type=FRAME&t=vuBkxAbEF1Xhq8zn-0

**Comment by HermanceGauth** [comment]
En attendant le redesign complet de la page collectivité, il faudrait a mimnima enlevé le lien vers DGD et infos général pour pas créer trop de confusion
![Image](https://github.com/user-attachments/assets/f5544e95-a4b6-4c03-a353-2aee8c81de76)

**Comment by julienzdocurba** [comment]
Oui bon point!

**Comment by HermanceGauth** [comment]
Désactiver le lien uniquement en production en attente de l'historique non éditable.

**Comment by HermanceGauth** [comment]
Comportement constaté ce jour : pas d'accès en lecture pour les CT : ok dans un premier temps, issue sera faite et priorisée selon besoin.
