### ISSUE TITLE
Remettre le guide utilisateur PAC

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#62]
Ce serait possible de remettre https://docurba.beta.gouv.fr/guide côté DDT connecté ? 

Je l'imagine éventuellement (et pour l'instant) derrière le click des 3 points en haut à droite, au dessus de "déconnexion". 

(Car si on faisait un onglet "Guide utilisateur" au mettre titre que les onglets "trame de PAC", "Mes collec", etc. Il faudrait aujourd'hui que l'on fusionne tout le contenu des guides outil des PAC + guide FRP et ce serait un enfer à lire. 
On va prochainement évaluer les options disponibles pour mieux transmettre ces tips.)

![Capture d’écran 2023-09-21 à 19 06 40](https://github.com/MTES-MCT/Docurba/assets/111045572/fdec9885-6b70-4a06-b7ed-85df7eadbbe8)

**Comment by lerayj** [comment]
Done.
