### ISSUE TITLE
QA Dashboard | Les liens SCoT ne sont pas cliquables

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#624]
Hello ! Les liens SCoT ne sont pas cliquables dans le tbd - j'image que le comportement attendu est qu'ils apparaissent comme pour les autres DU.

https://jam.dev/c/9b180275-f288-4b42-8e5c-9a0dd31e0357

<img width="945" alt="Capture d’écran 2024-05-22 à 08 57 36" src="https://github.com/MTES-MCT/Docurba/assets/144041896/ddf0240c-c425-4d75-b04d-65940a9e3b6d">

**Comment by HermanceGauth** [comment]
Le plus important n'est pas le cliquable mais surtout d'avoir le nom et de savoir s'il est opposable ou non. Les DDT ont besoin de cela car le déroulé de la procédure n'est pas exactement le même s'il y a un ScoT opposable sur le périmètre de la procédure ou non.

**Comment by HermanceGauth** [comment]
cf maquette : https://www.figma.com/design/4W463mFBKoDzf4mgJAhW9y/Docurba-(V2)?node-id=5092-48217&t=sToEc8mH9fm2qPAr-0

Je la met dans cette itération pour rassembler toute la QA

**Comment by Octaviedebs** [comment]
oui oui complètement j'allais préciser et screen la maquette 👌🏻
