### ISSUE TITLE
BUG Metabase | La colonne "Région" ne semble plus être mise à jour 

### ISSUE THREAD

**Issue by NicolasM92** [MTES-MCT/Docurba#629]
La colonne "Région" de la table "Profiles" n'est plus mise à jour depuis début Avril :

<img width="857" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/60889390/3cd9a048-70d1-4132-b86a-45ab0c2643c3">

**Comment by UngererFabien** [comment]
Il manque aussi les project ID sur les events PAC.

**Comment by HermanceGauth** [comment]
1. Regarder où la région ne remonte pas et pourquoi?
2. Revenir en arrière pour réparer la donnée qui a été impactée

**Comment by UngererFabien** [comment]
Pull request envoyé pour les futures inscriptions. Et j'ai fixe en BDD les regions manquantes à partir du code département.
