### ISSUE TITLE
DDT : commencer un PAC : accès à "ajouter un DU" VS "démarrer une procédure"

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#63]
Confusion et bug?, pour trouver comment initier un PAC : 
[https://docurba.beta.gouv.fr/ddt/13/collectivites](https://docurba.beta.gouv.fr/ddt/13/collectivites)

Un agent de DDT connecté -> click sur `mes collectivités` -> recherche la commune `Arles` -> au click sur le lien de l'interco (cf PJ1) -> il se retrouve sur le `TdB parcours collectivité` avec le CTA `démarrer une procédure` (cf PJ2) -> donc il ne comprenait pas car le CTA indique qu'il faut être d'une collectivité ou d'un BE. 
Je l'ai redirigé vers son TdB à nouveau puis le bouton `consulter` et c'était ok mais ça me parait important de le signaler.

![Capture d’écran 2023-09-21 à 19 15 09](https://github.com/MTES-MCT/Docurba/assets/111045572/6ce4d3a9-f751-42d2-a93b-72383d05f92d)
![adrien porcher](https://github.com/MTES-MCT/Docurba/assets/111045572/2f81c8cb-aae4-48a4-a3a2-396ee95396ec)

**Comment by CeliaVermicelli** [comment]
FYI : je n'ai pas réussi à reproduire ce bug d'accès au tdb collectivité alors que je suis sur un accès DDT. 
J'ai bien le "ajouter un DU" cf pj 

J'ai aussi essayé sur le tdb du 44 et ok aussi.

![Capture d’écran 2023-09-21 à 19 29 20](https://github.com/MTES-MCT/Docurba/assets/111045572/c07a3563-6664-427d-bc54-b9d388dfec5c)

**Comment by UngererFabien** [comment]
Je comprend la confusion, mais je n'arrive pas à reproduire non plus. Donc je pense à une confusion.
