### ISSUE TITLE
Ajout de procédure secondaire : afficher le nom de la procédure principale avec le nom de la collectivité lors de la sélection de la procédure parente

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#634]
Historique : https://github.com/MTES-MCT/Docurba/issues/574

Pour les procédures issues de Sudocuh : avec la date dans le nom cf issue ci-dessus

Pour les procédures de Docurba : avec le nom complet comme il a été donné au moment de la création de procédure

**Comment by HermanceGauth** [comment]
Hello @UngererFabien comme pour le nom de la FRP, des avancées mais tous les cas ne sont pas traités :
- lorsque la collectivité porteuse est un EPCI pour un DU communal : on ne peut pas différencier, il faudrait que le nom de la procédure soit complet ( ex : Révision du PLU de commune X - collectivité porteuse EPCI Y) et on devrait pouvoir avoir la distinction entre COMD dans l'idéal
- lorsqu'une collectivité à plusieurs DU opposable (soit PLUi sectoriel soit un premier qui a été opposable puis des révisions) dans ce cas c'est l'issue https://github.com/MTES-MCT/Docurba/issues/574 et s'appliquera.
Du coup je mets en KO même si une partie est déjà réalisée.

**Comment by UngererFabien** [comment]
Ha yes no problem !
