### ISSUE TITLE
Dump pour une COMD du 76, CC Peny : Modifications effectuées dans Sudocuh non reprises dans docurba 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#636]
### Retour de la DDT (Noel-Evain) : 

l'extraction des données de Sudocuh dans Docurba ne semble pas supprimer ou modifier les lignes d'évènements lorsqu'elles ont été corrigées.
Voici ce qu'il y a dans Sudocuh pour la CC de Penly approuvée le 18/04/2024
<img width="1116" alt="Capture d’écran 2024-05-27 à 12 45 22 PM" src="https://github.com/MTES-MCT/Docurba/assets/111045572/dd096321-013e-4506-98fc-dd53bff82db8">

et ce qui apparait dans Docurba (4042e045-2bf9-433b-85f4-9d5de7245521 - (sudocu: 189424) )
<img width="982" alt="Capture d’écran 2024-05-27 à 12 46 41 PM" src="https://github.com/MTES-MCT/Docurba/assets/111045572/1429c728-8bbd-4faa-bfd4-d7fbac3007b0">

### les modifications effectuées dans Sudocuh le 19 avril 2024 n'ont pas été prise en compte. 
Les différences que j'identifie (celia) :
-> la prescription du 1.01 à été supprimée 
-> la prescription définitive du 26.06 n'est plus "invalide" + le champ commentaire de l'event est vide

### De la même façon le commentaire de Docurba n'a pas été mis à jour ->

**Commentaire actuel dans Docurba :** Date réelle de prescription 29/06/2023 - modifiée temporairement pour être antérieure à la prescription du PLUi (pb sudocuh) a corriger à l'approbation de la révision de la CC ----- procédure sectorielle concernant l'ancien périmètre de la commune PENLY 

**Commentaire dans Sudocuh (modifié le 19.04) :**  ----- procédure sectorielle concernant l'ancien périmètre de la commune PENLY

**Comment by UngererFabien** [comment]
@lerayj Est ce qu'on les supprime de la BDD ? On peu revoir ensemble ce qu'il faudrait faire quand il y a des suppression dans Sudocuh.

**Comment by HermanceGauth** [comment]
@CeliaVermicelli comme pour les communes fusionnées, il faudrait répertorier les cas où le dump ne fonctionnent pas dans le tableau et les traiter d'un coup.

**Comment by CeliaVermicelli** [comment]
@HermanceGauth j'ai créé ce doc du coup : https://docs.google.com/spreadsheets/d/1ATNoSmDqaWyygGVwU78hE3Og-E_FYapbc_5WMPbDlxo/edit?usp=sharing

Je l'ajoute[ au notion dans la partie tech](https://www.notion.so/docurba/Tech-70b9d2eed415432c867fc608feefc342), à côté des retours sur les COMD

**Comment by lerayj** [comment]
manual fix cas 2

**Comment by CeliaVermicelli** [comment]
Testé 

- ✅ contenu de la FRP : ok 
- ❌ le commentaire "----- procédure sectorielle concernant l'ancien périmètre de la commune PENLY" à mettre à jour était au niveau du champ commentaire (de la proc) et non de l'event de prescription. 


Voici le commentaire actuel (copy que je mettais plus haut dans l'issue)
<img width="1211" alt="Capture d’écran 2024-09-16 à 11 26 32 AM" src="https://github.com/user-attachments/assets/3a3db3ff-a0fa-479d-bc50-aeb8d6241ece">

**Comment by CeliaVermicelli** [comment]
@lerayj est-ce que c'est plus clair avec cette [demo](https://jam.dev/c/b51cf1a2-2cf9-4bd8-9055-51deade57759) ?

**Comment by HermanceGauth** [comment]
@CeliaVermicelli je passe dans testé car ça m'a l'air ok, n'hésite pas à revenir en arrière si j'ai mal compris
https://dev.docurba.beta.gouv.fr/ddt/76/collectivites/76618/commune
![image](https://github.com/user-attachments/assets/168733f8-5a1d-4666-9e99-f02578c748d0)

**Comment by CeliaVermicelli** [comment]
yes c'est tout bon merci ! 
également sur la prod, donc je close l'issue er préviens la DDT.
