### ISSUE TITLE
Bug (PAC) les copier/coller d'un odt dans Docurba ne fonctionnent pas.

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#638]
demo : https://jam.dev/c/3a28abad-5aae-4c05-bc5f-8bc09db26176
(remarque : je n'ai pas la suite office sur mon PC donc je ne suis pas 100% sûre de pouvoir dans tous les cas faire ces tests -> je suppose que même si je ne peux pas modifier les doc. je peux faire des copier/coller du contenu).

J'ai eu des retours de DDT qui affirment que le copier/coller ne fonctionne pas d'un fichier docx/odt à Docurba dans les cas suivant : 
- texte jaune, 
- schéma, 
- tableau. 

On m'a aussi remonté que le texte copié/coller d'un doc ne conserve pas la taille de texte (mais je n'arrive pas à testé ça désolée !

note perso : prévenir isabelle de la drome, Cécilia du 22

**Comment by HermanceGauth** [comment]
A mon avis c'est normal? Au moins pour les tableaux et schéma, je pense que la bonne pratique c'est de l'enregistrer en image et de l'insérer ou de le refaire dans Docurba pour les tableaux. 
Pour le surlignage peut-être qu'on pourra faire quelque chose mais je pense que globalement on ne copie pas la mise en forme dans Docurba, je ne sais pas si c'est faisable @UngererFabien ?

**Comment by CeliaVermicelli** [comment]
Retour de la DDT : ses copier/coller fonctionnent à nouveaux.. Elle ne m'a pas transmis plus de détails.

Concernant l'impossibilité de copier/coller des images je trouve que c'est assez bloquant dans le cas des DDT qui migrent leur PAC type sur Docurba ; car il contient probablement des images dont ils n'ont plus le fichier source. 
Si jamais c'est faisable de permettre ce genre de copier/coller.

**Comment by HermanceGauth** [comment]
@CeliaVermicelli je propose de closed et de mettre une ligne dans notion spécifiquement pour le copier/coller d'image?

**Comment by CeliaVermicelli** [comment]
Oups j'avais raté ton dernier commentaire. Je rajoute une ligne dans le notion et close l'issue comme tu proposais. 

Juste au passage : nouveau retour de Laurence ddt 01 : 

> A un même endroit, j'ai voulu mettre 2 images à la suite provenant d'un même document en faisant un copier/coller : impossible !! J'avais réussi sans problème peu de temps avant et après non ?? J'ai réussi à mettre une image au bout de 4 ou 5 essai mais je ne comprends pas ce qui bloque.

-> Dans la plupart des outils c'est possible de faire des copier/coller d'image d'un doc à un autre - j'insiste sur le fait que je trouve important de remettre cette possibilité.
