### ISSUE TITLE
Un user du 13 ne peut plus se connecter (Faidix)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#639]
user : karine.faidix@bouches-du-rhone.gouv.fr 

-> elle affirme que le processus de mdp oublié de lui fonctionne pas (de mon côté RAS donc je lui ai rappelé la démarche mais elle insiste)
-> elle ne peut pas se créer un nouveau compte car on reconnait son adresse email (cf capture)
-> alors que je ne retrouve pas son user dans la BDD (cf capture)

<img width="1453" alt="Capture d’écran 2024-05-28 à 3 39 28 PM" src="https://github.com/MTES-MCT/Docurba/assets/111045572/b36c2189-988e-4293-8161-6f5e9e2f5542">

<img width="1430" alt="Capture d’écran 2024-05-28 à 3 39 10 PM" src="https://github.com/MTES-MCT/Docurba/assets/111045572/b43b18ad-9b4f-4585-b568-85fdbe1600fb">

<img width="870" alt="Capture d’écran 2024-05-28 à 3 42 17 PM" src="https://github.com/MTES-MCT/Docurba/assets/111045572/e132faf7-1e7d-4d14-8bd0-990f6e0f981a">

**Comment by UngererFabien** [comment]
Créer un profile en BDD pour cet email.

**Comment by UngererFabien** [comment]
@CeliaVermicelli je lui ai créer un profile. Il faut s'assurer qu'elle arrive bien à se connecter.

**Comment by CeliaVermicelli** [comment]
ddt prévenue, j'attends sa confirmation avant de close
