### ISSUE TITLE
UX parcours connecté DDT : arrivée dans leur espace DDT VS cliquer sur le bouton "TdB"

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#64]
juste FYI c'est la 3eme personne qui se retrouve "bloquée" dès la page d'accueil : 
 -> ne comprennent pas qu'il faut cliquer sur "TdB" pour accéder à leur espace DDT -> peut-être que le CTA de la barre de recherche publique est la seule chose qu'ils imaginaient de Docurba. 

-> mettre plus en valeur le bouton tableau de bord en haut à droite en attendant de faire mieux en terme d'UX ? 

![Capture d’écran 2023-09-21 à 19 24 53](https://github.com/MTES-MCT/Docurba/assets/111045572/f14edfea-616b-4872-a5c0-5548e4d82415)

**Comment by lerayj** [comment]
La landing page quand on est connecté en tant que DDT renvoie maintenant automatiquement au tableau de bord.

**Comment by CeliaVermicelli** [comment]
Nouveau retour de Cécile Rolant-Guyot (DDT 38) : 

Elle ne s'est pas rendue compte qu'elle était déjà connectée - et malgré la mise en valeur du bouton TdB, depuis la page d'accueil elle s'est rendue direct sur le bandeau d'invitation à se connecter ou s'inscrire pour les agents de l'État (ils n'ont pas l'habiture que leur navigateur se souvienne d'eux autant de temps) cf PJ

![gkhgpnhcfjcpemek](https://github.com/MTES-MCT/Docurba/assets/111045572/f6e65ade-7f06-4552-b16c-66a8ed48a3d5)

Aussi, quand elle a cliquer sur "se connecter", on ne lui a pas prévenue qu'elle l'était déjà (et n'a pas remarqué le "deconnexion" derrière les 3 petits points) donc s'est retrouvée sur cette page, sans message d'erreur, sans page qui mouline, etc.  cf PJ

![elffoafdiifhimnn](https://github.com/MTES-MCT/Docurba/assets/111045572/49d0ed51-23de-4fed-8d0f-971b48b12c2c)
