### ISSUE TITLE
New tdb : temps de chargement long pour l'onglet "Mes procédures"

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#642]
demo 1 : temps entre "mes proc." et "mes CT" : https://jam.dev/c/29169b98-f8bf-471e-8cb1-198fe454f99f
demo 2 : temps long entre "mes proc" et une FRP : https://jam.dev/c/335eecb3-1a70-4bcf-9287-6cb31d01989c

j'ai eu a plusieurs reprise cet écran (apparu à chaque fois au passage sur l'onglet mes proc. quand j'étais en train de faire une capture video de mon écran, et apparu 1 fois sur les 5 essais alors que je n'utilisais rien d'autre que Docurba)

<img width="1159" alt="Capture d’écran 2024-05-30 à 1 09 49 PM" src="https://github.com/MTES-MCT/Docurba/assets/111045572/76052d2e-edd7-4097-9f12-e89a2b5a3268">

**Comment by Octaviedebs** [comment]
Autre exemple jam Temps de chargement : https://jam.dev/c/a2a70424-2af8-4935-a6f1-83b77bbe532c

**Comment by HermanceGauth** [comment]
De mon côté je suis à 5sec max pour celui du 55

**Comment by CeliaVermicelli** [comment]
pour le 54 : je suis à 11s de chargement de l'onglet mes proc. 

(pour une fois que c'est plus rapide en DDT Hermance, je me réjouis !)

**Comment by CeliaVermicelli** [comment]
je close, c'est beaucoup mieux !
