### ISSUE TITLE
QA TBD | Typo dans l'onglet Mes procédures & Mes collectivités

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#647]
**ONGLET MES PROCEDURES**

**Tous type de procédure** à remplacer par :
Tout type ( = tou**t** + singulier)
**OU** Tous les types  (= tou**s** + pluriel)

**Tous types de documents** à remplacer par : 
Tout type de document ( = tou**t** + singulier)
OU Tous les types de documents (= tou**s** + pluriel)

**Tous les status** à remplacer par : 
Tous les statu**t**s
<img width="1405" alt="Capture d’écran 2024-05-30 à 16 46 17" src="https://github.com/MTES-MCT/Docurba/assets/144041896/a45ceb0d-dd37-4560-b9d2-faa66d69ef4f">

Périmetre à remplacer par Périm**è**tre
<img width="955" alt="Capture d’écran 2024-05-30 à 17 23 32" src="https://github.com/MTES-MCT/Docurba/assets/144041896/53c88866-ed06-49e6-9e72-cee15d0abc9b">

**ONGLET MES COLLECTIVITES** :  
**Tous types de collectivité** à remplacer par : 
Tout type de collectivité ( = tou**t** + singulier)
OU Tous les types de collectivités (= tou**s** + pluriel) 

<img width="584" alt="Capture d’écran 2024-05-30 à 16 52 24" src="https://github.com/MTES-MCT/Docurba/assets/144041896/b430fd89-a8a6-4a8a-b4eb-23311622d514">

 Colonne SCoT : si 1 commune alors remplacer 1 commune**s** PAS 1 commune (sans s)

<img width="444" alt="Capture d’écran 2024-05-30 à 16 56 50" src="https://github.com/MTES-MCT/Docurba/assets/144041896/e6561292-6df4-48c1-bdb3-cb366557e0b7">

**Comment by UngererFabien** [comment]
Pour la dernière typo je n'ai pas trouvé le problèmes sur les communes. Mais j'ai corrigé les +1 procédures en procédure au singulier.

**Comment by Octaviedebs** [comment]
Nope, il en reste encore  : 

**ONGLET MES COLLECTIVITES :**
Tous types de collectivité à remplacer par :
Tout type de collectivité ( = tout + singulier)
OU Tous les types de collectivités (= tous + pluriel)

=> tu as mis Tout type**s** cf image



![Image](https://github.com/MTES-MCT/Docurba/assets/144041896/c2b36eb8-60f8-4651-a854-eaeaf44ded81)



**ONGLET MES PROCEDURES**

_Tous type de procédure à remplacer par :
Tout type ( = tout + singulier)
OU Tous les types (= tous + pluriel)_
=> **c'est ok**

_Tous types de documents à remplacer par :
Tout type de document ( = tout + singulier)
OU Tous les types de documents (= tous + pluriel)_
=> tu as mis Tout type**s** cf image - du coup c'est sans s



![Image](https://github.com/MTES-MCT/Docurba/assets/144041896/dc824762-b243-4cc8-8f85-04d3b4125949)



_Tous les status à remplacer par :
Tous les statuts_
=> c'est ok

**Comment by Octaviedebs** [comment]
tt ok

<img width="1276" alt="Capture d’écran 2024-06-10 à 19 05 48" src="https://github.com/MTES-MCT/Docurba/assets/144041896/801504ef-19f1-49ef-9c95-004caa3857ff">
<img width="1276" alt="Capture d’écran 2024-06-10 à 19 05 56" src="https://github.com/MTES-MCT/Docurba/assets/144041896/3ec0740c-7fc5-4367-90dd-9c32934c0402">
