### ISSUE TITLE
PJ Sudocuh pas consultables (34- Corneilhan)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#650]
juste pour mon suivi auprès de la ddt 34 fabien C.

> Bonjour, Dans la révision PLU de la commune de Corneilhan l'extraction des PJ de SUDOCUH à DOCURBA ne s'ouvre pas. Est ce normal ? doit-on les réenregistrer ? si oui comment faire. Cordialement

https://docurba.beta.gouv.fr/frise/57288453-3da8-405f-8ef2-16977eff637a

**Comment by HermanceGauth** [comment]
@CeliaVermicelli normalement c'est bon maintenant
