### ISSUE TITLE
Erreur de libellé PLU communal

### ISSUE THREAD

**Issue by lmagreault** [MTES-MCT/Docurba#651]
En tant qu'EPCI (CA ECLA), j'ai accès aux DU communaux dont le PLU de l'Étoile :
![image](https://github.com/MTES-MCT/Docurba/assets/677071/de0a27b2-1408-44d8-bf14-5d1ea6e4cb72)
Or dans la feuille de route, le libellé n'est pas le bon (PLU de CA ECLA au lieu de PLU de L'Étoile) :
![image](https://github.com/MTES-MCT/Docurba/assets/677071/ba11257a-ea8a-4c2a-a74c-59d3bb5df5d2)

**Comment by HermanceGauth** [comment]
non résolu suite au passage en pre-prod de l'issue 525

**Comment by HermanceGauth** [comment]
Voir autres cas ici : https://github.com/MTES-MCT/Docurba/issues/525

**Comment by HermanceGauth** [comment]
C'est le nom de la collectivités porteuse qui s'affiche au lieu du nom de la commune concernée. On souhaite affichée le nom de la commune concernée en priorité.

Similaire à ce qu'on a fait sur les procédures parents : https://github.com/MTES-MCT/Docurba/issues/634

**Comment by HermanceGauth** [comment]
Autre cas : https://github.com/MTES-MCT/Docurba/issues/633

**Comment by HermanceGauth** [comment]
Autre cas : https://github.com/MTES-MCT/Docurba/issues/605

**Comment by HermanceGauth** [comment]
En pre prod ce jour :
- ok pour L'Etoile (39)
- ok pour Montgaillard (81)
- pas résolu pour SCoT du Vaurais (81)
- ok pour Dambenois (25)
- ok pour Herrlisheim-près-Colmar (68)

@CeliaVermicelli @Octaviedebs je n'ai pas testé tous les cas mais je pense que c'est résolu pour tous les cas communaux. Je passe donc en testé et on gardera open l'issue 633 sur les SCoT

**Comment by Octaviedebs** [comment]
Ok super je préviendrai l'utilisateur dès la mise en prod

**Comment by CeliaVermicelli** [comment]
Parfait, testé aussi pour les autres cas communaux remontés en DDT et tout est bon.
