### ISSUE TITLE
Doublon procédure de révision CC Bretagne Porte de Loire à masquer/supprimer  📆 25 juin 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#659]
https://docurba.beta.gouv.fr/frise/760d88f0-008d-4505-98f6-a7a9a2ebaf61

**Comment by Octaviedebs** [comment]
@HermanceGauth @UngererFabien du coup juste pour être sûre qu'elle ne se perde pas dans les limbes j'avais slacké fabien mais je vous re mentionne ici pour le mettre dans l'itération prochaine

**Comment by Octaviedebs** [comment]
J'ai besoin de faire une vidéo back up d'ici le 25 donc l'idéal ce serait effectivement que cela soit masqué d'ici là - merci !

**Comment by UngererFabien** [comment]
Pareille, sizé un peu large au cas ou je vois une opportunité de faire remonté plus de doublons.
