### ISSUE TITLE
Ajout de PAC PLUi : charge à l'infini

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#66]
https://docurba.beta.gouv.fr/trames/projet-2bbe869a-10e3-458c-9505-776f88de3364
Depuis mon compte/trame du 08
La création du DU a fonctionné, c'est au click sur `modifier le PAC` que le Le chargement du nouveau PAC Plui n'aboutit pas CF PJ (ma connexion est bonne et j'ai attendu plus d'une minute mais rien ne charge)

Nom du PAC : PAC du Pays Rethélois. 5 septembre 2023

![Capture d’écran 2023-09-22 à 12 26 19](https://github.com/MTES-MCT/Docurba/assets/111045572/bb313f02-ded3-43c3-974f-f297aa77015c)

**Comment by UngererFabien** [comment]
Je n'arrive pas à reproduire dans un projet du 01 donc probablement pas de problème sur les codes de départements mais il y a une erreur dans la console qui n'a pas l'air relié à l'accès en auth.

<img width="1680" alt="Screenshot 2023-09-25 at 14 36 17" src="https://github.com/MTES-MCT/Docurba/assets/2676385/04a96ba3-ce2c-4566-b804-507c43108900">
