### ISSUE TITLE
Sendgrid | Activer l'email automatique post validation de compte side collectivités | 📆 25 juillet 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#662]
Il faut mettre en ligne l'email de validation de compte afin que cet email ne soit plus envoyé manuellement. 
La date limite du 25 juillet c'est parce qu'ensuite je serai en vacances.

**Email** : https://mc.sendgrid.com/dynamic-templates/d-0143010573f6497b86abbd4e4c96f46e/version/4f9ccf62-6628-4d7f-88c7-92754ac160e3/editor

**Conditions** : 
- à la validation du compte depuis le bot_admin
- uniquement à l'inscription sur le side Collectivités

**Comment by CeliaVermicelli** [comment]
Email bien reçu ! 

Du coup @Octaviedebs on reçoit l'email de "lien magique" + compte validé  (je sais pas si ça peut poser pb dans le cas où tu valides les comptes assez vite)



![Image](https://github.com/user-attachments/assets/1e0b7ae4-8446-48d5-9f21-f9af499a52f7)
![Image](https://github.com/user-attachments/assets/22619211-4669-428c-8869-c0ad2699d608)

**Comment by Octaviedebs** [comment]
Yes c'est pour ça qu'initialement j'avais mis 5min de délai dans le titre je crois 🤔

@UngererFabien tu penses qu'on pourrait mettre un délai de 5 min suite à la validation ? 
Comme ça si compte validé vite/quasi concommitamment à la créa° du compte, il y aura du coup un petit délai pour être sûr qu'ils le voient.

Célia hésite pas à donner ton avis sur ça !

![Image](https://github.com/user-attachments/assets/d0adc8ca-fcb5-477d-8646-e33183000c2c)

**Comment by CeliaVermicelli** [comment]
ah yes je n'avais pas vu le délais (pas retournée sur Sendgrid)

Si pas de délais possible il y a peut-être juste à modifier les objets des deux emails pour mieux orienter sur le fait qu'il y a une action à réaliser ?

**Comment by UngererFabien** [comment]
L'API de sendgrid me permet de définir un horaire d'envoi. Je vais test ça :)
