### ISSUE TITLE
Bug PAC : le téléchargement de la trame régionale en PDF (accès DRIEAT) n'aboutit pas

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#666]
demo sur accès DREAL Ile de France (=DRIEAT) : https://jam.dev/c/bcc22ae4-5613-4a44-aa16-31ba64ffc00e

Alors que sur un accès DDT tout est ok : https://jam.dev/c/b484eb28-87e0-488e-8cf1-9e2f077ac8c3

- [x] prévenir christelle

**Comment by UngererFabien** [comment]
Hello ! C'est parce que la trame contient des gif qui ne sont pas suportés par le format PDF. Je regarde ce que je peux faire.

**Comment by UngererFabien** [comment]
Pour le moment je passe un hotfix qui ignore les gif pour que le téléchargement du PDF aboutisse. Mais du coup il n'y aura pas ces images.

C'est probablement possible de convertir ces gif en png on jpeg de notre coté mais ca demande plus de test.

J'ai rajouter dans la console une alerte sur les images non compatibles. Pour pouvoir prévenir les utilisateurs.

Dans le cas du 11:
https://ixxbyuandbmplfnqtxyw.supabase.co/storage/v1/object/public/text-images/public/19829d80-3bd7-419e-9374-08b8ae4e7511.gif
https://ixxbyuandbmplfnqtxyw.supabase.co/storage/v1/object/public/text-images/public/6fe890b4-46bd-4c31-9c0f-dfbe6864552e.gif
https://ixxbyuandbmplfnqtxyw.supabase.co/storage/v1/object/public/text-images/public/f555b51a-95ff-4534-adb0-d8f055115943.gif

**Comment by CeliaVermicelli** [comment]
Hello @UngererFabien 

je ne comprends pas pourquoi tu dis "Dans le cas du 11:" ? 
tu parles de la trame du dpt 11 qui contenait ces gif ? 
Dans l'issue je ne parlais que de la trame DRIEAT où il y avait le pb
