### ISSUE TITLE
TBD DDT | Onglet Mes Collectivités > le tri par défaut est inversé sur Firefox

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#668]
Quand j'arrive sur "Mes collectivités" sur Firefox elles sont rangées à l'envers et quand je vais sur Chrome pour faire un jam elles sont dans le bon ordre, je pensais que c'était peut-être que moi mais je viens de voir un retour DDT similaire 

![image (4)](https://github.com/MTES-MCT/Docurba/assets/144041896/b799f2be-55a7-4857-96c2-b01ce4ccd9fb)

@HermanceGauth FYI

**Comment by rik** [comment]
Corrigé et en production.
