### ISSUE TITLE
BDD > Pipedrive | Remonter la valeur dans le champ « Invité » & création une Personne sur Pipedrive lors du partage

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#670]
Cela doit être concomitant à la mep de la https://github.com/MTES-MCT/Docurba/issues/615

**1er point**  : synchronisation de la BDD avec le champ Invité
Dans Pipedrive, il y a un nouveau champ Invité qui doit : 
- si l'email a été partagé lors d'un partage de procédure ou de PAC : la valeur est la date du dernier partage
- si aucun partage : la valeur est vide

Pour rappel, il a été arbitré qu'on était ok avec le fait qu'on ne pouvait pas distinguer selon que le partage est un partage frp ou un partage pac sur pipedrive car cela aurait eu pour csq de « dissocier» les valeurs BDD > Pipedrive ce qui n'est pas recommandé.

**2ème point** : création d'une nouvelle Personne sur Pipedrive

Il faut créer une Personne dans Pipedrive dès qu'il y a un partage (PAC ou FRP) donc shared email  :
**SI ET SEULEMENT** SI email du user ≠ email existant sur Pipedrive 
**SINON** mettre à jour le champ Invité de la fiche Personne existante

Attention : Vérifier le pb lié au fait que actuellement aucune Personne ne se créée si un email existe déjà sur pipedrive qui _contient_ un bout de l’email du nouveau user ⇒ @UngererFabien  au courant et doit faire la modif suite échange support pipedrive

**Comment by Octaviedebs** [comment]
> _Pour rappel, il a été arbitré qu'on était ok avec le fait qu'on ne pouvait pas distinguer selon que le partage est un partage frp ou un partage pac sur pipedrive car cela aurait eu pour csq de « dissocier» les valeurs BDD > Pipedrive ce qui n'est pas recommandé_

Est-ce qu'on est vraiment sûr de ça ? Est-ce que cela a évolué depuis la discussion qui aurait pr csq qu'on pourrait quand même envisager de dissocier PAC / FRP

Avis de fabien recommandé

**Comment by UngererFabien** [comment]
Verifier si on a la distinction entre lecture et lecture frise seule.

**Comment by UngererFabien** [comment]
C'est bien passé en test sur mon profile pipedrive fabien@quantedsquare.com

Comme c'est un webhook lié à la BDD ce n'est testable qu'en prod. @lerayj il faudra enclenché le web hook au passage en prod.

**Comment by Octaviedebs** [comment]
@UngererFabien comme évoqué ce matin, voici le détail des champs à remplir : je pense que les titres sont suffisamment clairs mais n'hésite pas ! Evidemment ne fais pas attention au  champ Invité FRP (lecture) qui n'existe pas dans la BDD pour l'instant

<img width="230" alt="Capture d’écran 2024-09-26 à 10 35 14" src="https://github.com/user-attachments/assets/e433a81b-80f5-4f15-bc9f-231f097f6a1f">

**Comment by HermanceGauth** [comment]
@Octaviedebs est-ce ok pour toi avec le passage en prod?

**Comment by Octaviedebs** [comment]
On en avait parlé de vive voix avec @UngererFabienlors du point ops et cela n'était pas encore testable donc on attendait le go - c'est pour cela que j'ai laissé - Fabien tu nous diras ! 
(j'ai du coup revérifier et cela n'est pas le cas mais je peux le passer en KO si vous préférez)

**Comment by UngererFabien** [comment]
A traiter en même temps que la #711

**Comment by UngererFabien** [comment]
> [@UngererFabien](https://github.com/UngererFabien) comme évoqué ce matin, voici le détail des champs à remplir : je pense que les titres sont suffisamment clairs mais n'hésite pas ! Evidemment ne fais pas attention au champ Invité FRP (lecture) qui n'existe pas dans la BDD pour l'instant
> 
> <img alt="Capture d’écran 2024-09-26 à 10 35 14" width="230" src="https://private-user-images.githubusercontent.com/144041896/371054455-e433a81b-80f5-4f15-bc9f-231f097f6a1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDY5MDIsIm5iZiI6MTczMjU0NjYwMiwicGF0aCI6Ii8xNDQwNDE4OTYvMzcxMDU0NDU1LWU0MzNhODFiLTgwZjUtNGYxNS1iYzlmLTIzMWYwOTdmNmExZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxNDU2NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTJmZTgzNGI3YjQwZDgxNGZiMTBjNmMxMTA1MWVkYmMzMzUyYzI4Mjk1MTdiYmJjZTJmMThhOTIzMDU2YTgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fGc2Rj9OzlTOsf6INtKKDqKJz_WjhuSqKlpDa62bYfU">

J'ai mis a jour le mapping pipedrive et test sur mon profile sans problème. @rik il faut test le webhook en prod ou preprod.

**Comment by Octaviedebs** [comment]
**SUITE TEST au 28.11**

Aucune fiche contact n'est créé si l'email user à qui on partage n'existe pas déjà sur Pipedrive.
Ensuite quand la fiche contact existe déjà sur Pipedrive =
- Si je partage un PAC en mode lecture = c'est le champ Invité FRP (lecture) qui se met à jour 
- Si je partage un PAC en mode écriture = c'est le champ Invité PAC (lecture) qui se met à jour 
- SI je partage une FRP en mode écriture = c'est bien le champ Invité FRP (édition) qui se met à jour 

Je ne comprends pas pourquoi le champ Date d'édition de la FRP est rempli également.
Il n'était pas mentionné, c'est un champ qui n'avait pas été supprimé depuis nos échanges sur ce sujet je pense = pour éviter la confusion, je peux le supprimer tout de suite mais j'attends peut être que le code soit modifié.

**Comment by Octaviedebs** [comment]
On a dissocié l'issue pour la partie Création de contact voir cette [issue](https://github.com/MTES-MCT/Docurba/issues/1008)

**Comment by HermanceGauth** [comment]
Pouvez-vous vérifier si cette issue est fini ou si ce qu'il reste est reporté dans une autre issue et fermer?

**Comment by Octaviedebs** [comment]
C'était l'objet du dernier commentaire : cette issue n'est pas finie car il reste le ramasse miettes à mettre en place.
Le reste est basculé dans une autre issue https://github.com/MTES-MCT/Docurba/issues/1008

**Comment by HermanceGauth** [comment]
On créé une issue pour le ramasse miette

**Comment by rik** [comment]
On suivra le reste à faire sur https://github.com/MTES-MCT/Docurba/issues/1036
