### ISSUE TITLE
Statuts des proc. incorrects CC du Pays de la Châtaigneraie (85)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#677]
demo : https://jam.dev/c/a374d955-705a-42ac-9044-367881100901

page EPCI : https://docurba.beta.gouv.fr/ddt/85/collectivites/248500415/epci

Le problème : 
* Le PLUi est précédent alors qu'il devrait être opposable (approbation et caract. executoire renseignés en juin 24)
* Les DU communaux sont opposables alors qu'ils devraient être précédents (approbation et caract. executoire renseignés en 2019)

**Comment by CeliaVermicelli** [comment]
Cas similaire dans le 29 et la [CC Communauté Lesneven Côte des Légendes](https://docurba.beta.gouv.fr/frise/b514b048-c269-4468-8b27-ab52d2d44729) : 

Le statut du PLUiH est devenu "précédent" suite à l'ajout de l'approbation, (et les DU communaux opposables)

FYI @HermanceGauth , Gérald risque de nous rappeler.

**Comment by Octaviedebs** [comment]
Pour suivi quand mep contacter https://docurba.slack.com/archives/C06EUA1E96D/p1719392070455029

**Comment by HermanceGauth** [comment]
@UngererFabien étrange car l'évent d'approbation semble bien venir de Docurba et non de Sudocuh donc à mon sens pas lié au dump

**Comment by HermanceGauth** [comment]
Non en fait Claire a aussi rajouté l'event d'approbation dans Sudocuh pour ces deux procédures et ça a donc été corrigé au dump effectivement

**Comment by CeliaVermicelli** [comment]
Le PLUi est bien opposable sur la prod (et les PLU en précédent), je close

<img width="1222" alt="Capture d’écran 2024-09-12 à 10 12 35 AM" src="https://github.com/user-attachments/assets/3876fa17-bcc0-4da6-bda8-acf16f4b1d2c">

Prévenir
- [ ] Emmanuel du 85 
- [ ] Gérald du 29
