### ISSUE TITLE
Séparer la révision à modif simplifiée de la révision allégée dans le menu déroulant des PS ?

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#679]
https://jam.dev/c/feaa67c7-3f12-4cc3-b6ff-7341bb3e26c6

-> on ne peut pas enlever l'un ou l'autre dans le titre de la procédure proposé automatiquement, je ne sais pas si c'est un bug. 
@HermanceGauth peut-être que c'était intentionnel ?

**Comment by HermanceGauth** [comment]
En fait les deux désignent le même type de procédure. Le problème c'est que le code ne nomme pas explicitement cette procédure et que certains l'appellent simplifiée et d'autres allégée.

**Comment by CeliaVermicelli** [comment]
ok, je close et bascule le retour en feedback pour l'instant. 
Peut-être que le sujet reviendra
