### ISSUE TITLE
Accès github et edit Master

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#68]
- msg peut-être relié à la question d'Octavie -

Que ce soit pour éditer le guide utilisation ou pour ajouter des images dans assets, avant je pouvais les commit directement sur la master, maintenant je fais des PR. C'est normal ? - C'est ce qui devait arriver suite au commentaire du FAST sur la branch master ?
CF deux PJ :  

![Capture d’écran 2023-09-22 à 11 52 37](https://github.com/MTES-MCT/Docurba/assets/111045572/3d532e35-a6ed-4a24-a23e-65cbb5984c47)
![Capture d’écran 2023-09-22 à 12 46 32](https://github.com/MTES-MCT/Docurba/assets/111045572/777a5fc4-a695-4703-a14d-5eb968faf79f)

**Comment by UngererFabien** [comment]
Yes c'est normal. On nous a conseillé de protéger la branche master donc je managerais les pull request.
