### ISSUE TITLE
NPS PAC & FRP | Limiter l'affichage des pop up 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#681]
Il faudrait que la pop up NPS FRP & PAC n'apparaissent pour la première fois QUE au bout d'un certain temps depuis leur 1ère connexion car actuellement, dès leur création de compte ces pop up sont affichées = du coup ils ne les remplissent pas donc on perd des éléments c'est dommage. 

**Condition à ajouter :** n'afficher chacune des pop up QUE au bout d'1 mois depuis leur 1ère connexion (et avec les mêmes conditions qu'initialement paramétrées) 

@CeliaVermicelli pour avis / modification du délai ?
Je pense que c'est important de les laisser un peu utiliser l'app pour récolter des feedbacls intéressants - d'autant que côté PAC il y a un temps d'onboarding dessus donc moins d'un mois me semble pas forcément pertinent, mais tu me dis !

**Comment by CeliaVermicelli** [comment]
yes c'est très bien, et le NPS qui sera envoyé par email est bien à J+90 donc bien espacé.

**Comment by Octaviedebs** [comment]
côté FRP c'est ok , quand on créé un compte on ne voit pas la pop up tt de suite en tt cas > je checkerai à mon retour du coup si la pop up apparait bien sur ce même compte

@CeliaVermicelli je te laisse vérif sur la ddt ?

**Comment by CeliaVermicelli** [comment]
C'est bon côté DDT : aucune pop-up n'apparait (FRP &PAC)

**Comment by CeliaVermicelli** [comment]
**Vérification côté DDT à J+34 :** 

Depuis une FRP ou un PAC : **la popup n'apparait pas**. ❌


-> à vérifier côté CT - je note cette issue pour le prochain point dev/ops.

**Comment by UngererFabien** [comment]
https://www.loom.com/share/4fd6fbb2ab054734935e5ad0c8e99c5c?sid=fd105a65-f113-4f22-9a33-336f674d294b

**Comment by CeliaVermicelli** [comment]
demo https://jam.dev/c/d2271aa1-7357-45fa-b0a8-c36751694119

Côté DDT : 
* Sur un PAC : la popup NPS apparait mais le temps de chargement du PAC est très long (15s)
* sur une FRP : la popup NPS apparait mais également la popup d'annonce du nouveau tdb (j'ai buggué dans la vidéo la personne qui aura vu la popup NPS à J+30 de son inscription aura fermé la popup TDB depuis bien longtemps - là je l'ai vu car j'avais supprimé tous les Tally de la console)

**Comment by Octaviedebs** [comment]
Côté CT : 
- je ne peux pas tester le fait que quand je créé un compte tout nouveau, je ne vois pas la pop up NPS : le lien de connexion reçu ne redirige pas sur dev
- et du coup je ne peux pas tester le delay des 30 jours

@UngererFabien c'est plus clair ? Mais il me semble que tu disais que si côté DDT c'était tt ok = alors side CT aussi - c'est ça ?

**Comment by UngererFabien** [comment]
Je la passe en dev, tout semble normal et du coup elle sera testable en CT @Octaviedebs
