### ISSUE TITLE
Amélioration de l'affichage des DU

### ISSUE THREAD

**Issue by UngererFabien** [MTES-MCT/Docurba#69]
<img width="1680" alt="Screenshot 2023-09-25 at 15 07 54" src="https://github.com/MTES-MCT/Docurba/assets/2676385/341ad7cc-d62c-4232-9459-a366076077ab">

- [ ] Améliorer l'affichage dans le cas ou il n'y a pas de DU dans une tab
- [ ] Changer le texte pour clarifier qu'on parle des DU sur les quels la collectivité à la compétence
- [ ] Ajouter le nom de la collectivité dans ce texte.
- [ ] Ajouter un texte explicatif pour dire "Si vous ne voyez pas votre DU c'est qu'il est présent au niveau commune/EPCI"

**Comment by lerayj** [comment]
Done.
