### ISSUE TITLE
{ Bug ] Impossible de créer une procédure secondaire sur Ploufragan (pas de procédure parente) (22)

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#695]
**1) Impossible de créer une PS sur Ploufragan ALORS qu'il y a bien une procédure principale opposable** 
- depuis la page de la commune onglet communaux  : impossible de trouver une procédure parente
- depuis la page de la commune onglet intercommunaux  : impossible de trouver une procédure parente
- depuis la page de l'EPCI : l'onglet PS tourne en rond donc impossible de tester en sélectionnant que la commune concernée
Pour info : j'ai par ailleurs testé ce « chemin » sur un autre EPCI pour une autre commune, et on ne permet pas d'ajouter une procédure sur une commune sélectionnée depuis la page EPCI (cf point 3) mais c'est donc peut être comportement voulue

https://jam.dev/c/0d365ba9-e967-4968-a75a-24e08d67bc99

2)En revanche cela fonctionne lorsque je veux ajouter une PS sur une autre commune exemple avec Tréguier : 
https://jam.dev/c/1dfb1687-1bd3-4c9e-a854-f424f7a0e3d4

3)MAIS cf ce même jam 👆🏻 à noter (mais c'est peut être un comportement attendu) : on ne permet pas d'ajouter une procédure depuis la page EPCI, en cochant uniquement la commune concernée mais c'est donc peut être comportement voulu

User à prévenir : Cécilia BELLAY @CeliaVermicelli

**Comment by CeliaVermicelli** [comment]
Merci pour ces explorations. Je complète avec un autre chemin : 

* ajout de la procédure secondaire **depuis la FRP de la procédure principale** concernée : https://jam.dev/c/318c92d6-f6d4-499d-b4e7-de103570a8fd
pour info, c'est un "chemin" qui permettait effectivement de contourner le bug cité par Octavie dans le cas de Milizac-Guipronvel, cf [cette issue.](https://github.com/MTES-MCT/Docurba/issues/631) mais ici cela ne fonctionne pas non plus.

**Comment by Octaviedebs** [comment]
TT clair pour moi je close
