### ISSUE TITLE
On est redirigé sur la page collectivité après la création de procédure

### ISSUE THREAD

**Issue by julienzdocurba** [MTES-MCT/Docurba#699]
Lorsque l'on créé une procédure, on est actuellement redirigé sur la page collectivité: https://jam.dev/c/0f2e4c5a-efcb-4cea-9c43-fb0ce5139e8e

On devrait plutôt rediriger sur la page de la procédure nouvellement créée.

Feedback remonté par 2 utilisateurs qui du coup avaient du mal à retrouver leur procédure.

**Comment by CeliaVermicelli** [comment]
@julienzdocurba tu pourrais préciser les prénoms - numéro de dpt des deux DDT qui t'ont fait ces retours, pour que je les préviennent quand résolu. 
Merci !

**Comment by julienzdocurba** [comment]
C'est Léa Dantz mais elle travaille en BE je crois. L'autre utilisateur il me semble que c'était toi @CeliaVermicelli qui en avait parlé sur Slack ou Github (mais j'arrive plus à le retrouver). Ca te dit rien?

**Comment by CeliaVermicelli** [comment]
ok si si 
alors ping @Octaviedebs pour prévenir Léa 
et de mon côté : Eliane 971

**Comment by CeliaVermicelli** [comment]
note à moi-même : 
- prévenir Lamanguib + Anne-Sophie du Loiret

**Comment by HermanceGauth** [comment]
@CeliaVermicelli @Octaviedebs j'ai l'impression que c'est ok maintenant?

**Comment by CeliaVermicelli** [comment]
Oui tout à fait - on arrive bien sur la FRP que ce soit suite à la création d'un PP ou d'une PS- je close.
