### ISSUE TITLE
Bug | Pb synchronisation champ pipedrive  > champs BDD 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#711]
**BDD :** 
<img width="1123" alt="Capture d’écran 2024-07-04 à 15 56 46" src="https://github.com/MTES-MCT/Docurba/assets/144041896/f2073d12-56c1-44e6-ac91-7bf1f8aab776">

**Pipedrive :**
https://docurba2.pipedrive.com/person/2804

Champs de la fiche Personne : 
<img width="334" alt="Capture d’écran 2024-07-04 à 15 59 51" src="https://github.com/MTES-MCT/Docurba/assets/144041896/59da59f7-ca65-4194-8d6b-b19bba1d99d2">

Pour ce contact, on voit bien qu' il s'est sign up en : 
-  Poste = Autre
-  qu'il a précisé Responsable urbanisme dans le champs Autres informations 
OR : 
- sur Pipedrive : Poste reste vide
- sur BDD : rien n'apparait dans le champ Autres infos (moins prio au moins ça remonte sur le CRM mais c'est pour comprendre)

**Comment by Octaviedebs** [comment]
TO DO Octa quand issue mep : 
- modifier dans la BDD le poste pour la mettre Employé de mairie pour qu'elle reçoive les bons parcours utilisateurs à la rentrée
 https://docurba2.pipedrive.com/deal/2565

**Comment by Octaviedebs** [comment]
**UPDATE** : le champs Autres informations s'est mis à la jour

**Comment by CeliaVermicelli** [comment]
### Infoº pas mise à jour : le statut connecté/non connecté

https://docurba2.pipedrive.com/person/1548 
Elodie THEVENARD est en statut "non connecté" alors qu'elle a ajouté plusieurs event dans des FRP.

**Comment by Octaviedebs** [comment]
https://docurba2.pipedrive.com/deal/2690 
 https://docurba2.pipedrive.com/deal/2264

**Comment by UngererFabien** [comment]
J'ai mis à jour la fonction de recherche des user pipedrive pour qu'elle match uniquement les email spécifique et pas similaire.

Il faudra test en prod d'update un profile user et de voir si il se met bien à jour avec les bon champs.

**Comment by Octaviedebs** [comment]
Autre souci : cette fiche personne ne se met pas à jour https://docurba2.pipedrive.com/person/2958

**Comment by Octaviedebs** [comment]
@UngererFabien la dernière fois tu m'indiquais que les webhooks ne fonctionnent que lorsque le user se connecte à Docurba ? Et donc si j'ai bien compris, tant que le user ne se connecte pas, nos contacts Pipedrive ne sont pas forcément à jour.

Est-ce que le fait de faire tourner un script quotidiennement ne pourrait pas être plus efficace ? Sûr ?

**Comment by Octaviedebs** [comment]
Autre cas : ce compte s'est créé tout à l'heure =>[ sa fiche personne n'est pas à jour](https://docurba2.pipedrive.com/person/3680)

**Comment by UngererFabien** [comment]
> **BDD :** <img alt="Capture d’écran 2024-07-04 à 15 56 46" width="1123" src="https://private-user-images.githubusercontent.com/144041896/345857272-f2073d12-56c1-44e6-ac91-7bf1f8aab776.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDQ2MjAsIm5iZiI6MTczMjU0NDMyMCwicGF0aCI6Ii8xNDQwNDE4OTYvMzQ1ODU3MjcyLWYyMDczZDEyLTU2YzEtNDRlNi1hYzkxLTdiZjFmOGFhYjc3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxNDE4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2FlNjU1OTY3OGEzOTljMWFlZjMyNzg3ZDQ2YzkyZGM2MjY1ZmRmNmQ4NWU1NjBmNzk0YWIxNDUyMGIxYTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h70agg0t5UT8msuIc8gtPCGfGcG9oVTpvZXKaq1ps3I">
> 
> **Pipedrive :** https://docurba2.pipedrive.com/person/2804
> 
> Champs de la fiche Personne : <img alt="Capture d’écran 2024-07-04 à 15 59 51" width="334" src="https://private-user-images.githubusercontent.com/144041896/345857971-59da59f7-ca65-4194-8d6b-b19bba1d99d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDQ2MjAsIm5iZiI6MTczMjU0NDMyMCwicGF0aCI6Ii8xNDQwNDE4OTYvMzQ1ODU3OTcxLTU5ZGE1OWY3LWNhNjUtNDE5NC04ZDZiLWIxOWJiYTFkOTlkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxNDE4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2JjMTJmZDU1NTc2ZTYxNGVkMjQ0ZTVmYzFhMDE5ZGFkMGFmNjA3MjUxMjI4YzM4ODY0Y2FmZDgwOWRjYTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4fc-1XDnmrpd-Yaqc-WoQZCwxifDBj5Wi_LAnVHmmKM">
> 
> Pour ce contact, on voit bien qu' il s'est sign up en :
> 
> * Poste = Autre
> * qu'il a précisé Responsable urbanisme dans le champs Autres informations
>   OR :
> * sur Pipedrive : Poste reste vide
> * sur BDD : rien n'apparait dans le champ Autres infos (moins prio au moins ça remonte sur le CRM mais c'est pour comprendre)

On ne remontai juste rien pour l'option autre dans Pipedrive. Je l'ai rajouter dans la liste des options.

**Comment by UngererFabien** [comment]
> ### Autre pb lié à la mise à jour des champs pipedrive : le champ statut (connecté/non connecté) ne semble pas se mettre à jour non plus
> Quelques exemples de personnes ayant le statut "non connecté" alors qu'elles ont ajouté plusieurs event dans des FRP. :
> 
> * https://docurba2.pipedrive.com/person/1548
>   Elodie THEVENARD
> * https://docurba2.pipedrive.com/person/69
>   Isabelle Girardet

J'ai deplacé le code qui met à jour cet etat. @rik j'ai aussi du rajouter une RLS en BDD pour laisser un user update son propre profile.

**Comment by UngererFabien** [comment]
> Autre souci :
> 
> * cette fiche personne, créé avant la création du compte, ne se met pas à jour https://docurba2.pipedrive.com/person/2958 : à la place cette [fiche](https://docurba2.pipedrive.com/person/3301) a été créée alors que c'est strictement le même email  (parfois cela fonctionne très bien, mais pas sur ce cas) - je cleanerai une fois résolu

Quand j'update en BDD j'ai la première fiche qui se met à jour. Je n'ai aucune idée de comment Pipedrive gère les doublons. Comme c'est lui qui choisie l'ordre dans le quel il renvoit les fiche persone pour un même email ça pourrait être aléatoire.

Je conseille de suprimer les doublons dans pipedrive. Le reste des updtes bdd devrait suivre.

**Comment by Octaviedebs** [comment]
Suite à ma question du 16 octobre du coup quand cette issue & la gestion de la synchro seront ok : est-ce que les webhooks continueront de ne fontionner que lorsque le user se connecte à Docurba ? ou allez-vous du coup implanter un autre fonctionnement en les faisant tourner quotidiennement/régulièrement ?

**Comment by Octaviedebs** [comment]
_> C'est mieux d'avoir un déclencheur unique à chaque changement_
C'est pas très clair pour moi. Tu me disais que du coup en faisant ça, tant que le user ne se connecte pas, les champs ne seront pas mis à jour - ça pourrait être problématique non ?

_> En revanche on peu faire tourner les scripts d'updates pour récupérer l'historique de partage. Il faut juste que ça ne déclanche pas des envoit d'email pour les partage un peu vieux._
Tu parles de cette [issue](https://github.com/MTES-MCT/Docurba/issues/670) dans cette phrase, non ? 

Les envois d'email sont déclenchés par un changement dans la BDD et non par un changement d'un champ Pipedrive.
Je ne comprends pas le risque que tu évoques 

On peut s'en parler de vive voix jeudi

**Comment by UngererFabien** [comment]
> C'est pas très clair pour moi. Tu me disais que du coup en faisant ça, tant que le user ne se connecte pas, les champs ne seront pas mis à jour - ça pourrait être problématique non ?

Pour les partage c'est au moment du partage. Pas besoins que les users à qui on fait le partage se connectent.
Et pour l'historique ça sera un script qui rattrape un coup.

**Comment by Octaviedebs** [comment]
**Résumé :** 
-  la synchro fonctionne / est déclenchée soit quand le site authentifie la personne _(via inscrip° ou si tu reviens sur le site)_ & quand qln invite une personne sur une FRP (cf [670](https://github.com/MTES-MCT/Docurba/issues/670))
- pour régler le souci de synchro et éviter les trous dans la raquette, on va faire tourner un script pour forcer le webhook ( (il faut qu'il soit en prod pour que le script fonctionne et le tester : prochaine étape)
- tests à faire lors de la mise en place du script = une personne qui créé un compte / une personne qui existe déjà et dont on met à jour les infos / une personne qui partage une procédure
- concernant le champ  _successfully logged once_  qui ne fonctionne pas (=> champ Non connecté sur Pipedrive) ne sera pas rétroactivement mis à jour - à garder en tête - (sauf à mettre en place un système pour aller identifier ceux qui ont fait des activités et donc qui ont été connecté )

**Comment by HermanceGauth** [comment]
Pouvez-vous vérifier si cette issue est fini ou si ce qu'il reste est reporté dans une autre issue et fermé?

**Comment by Octaviedebs** [comment]
Pareil vu avec Anthony il reste le ramasse miettes pour que cette issue puisse être fermée.

**Comment by rik** [comment]
On suivra le reste à faire sur https://github.com/MTES-MCT/Docurba/issues/1036
