### ISSUE TITLE
Changer le titre de page "Invitez des collaborateurs"

### ISSUE THREAD

**Issue by julienzdocurba** [MTES-MCT/Docurba#714]
Actuellement, la page "Invitez des collaborateurs" (qu'on montre lors de la création de procédures) a le nom de la collectivité en titre:
<img width="2672" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/fe6da4f6-d0ad-49f1-b22a-e29e4cda4fd5">

On voudrait plutôt garder le titre "Nouvelle procédure" pour clarifier le fait qu'on est toujours en train de créer une nouvelle procédure:
![image](https://github.com/MTES-MCT/Docurba/assets/147177148/7a3654aa-f3a3-4484-b591-d900332904a0)

**Comment by Octaviedebs** [comment]
![Image](https://github.com/user-attachments/assets/adef8872-8b6b-43da-a02a-f00b7e641110)
résolu

**Comment by julienzdocurba** [comment]
Je clos l'issue!
