### ISSUE TITLE
Il manque le bouton "Fermer" sur la fenêtre de partage de procédure

### ISSUE THREAD

**Issue by julienzdocurba** [MTES-MCT/Docurba#720]
Le bouton "Fermer" n'est pas présent:
<img width="1010" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/0cba17d9-a84f-4975-942e-7e403bd7eef7">

Il devrait être en haut à droite:
<img width="799" alt="image" src="https://github.com/MTES-MCT/Docurba/assets/147177148/eaad2152-46de-478b-901b-d70e6bef63f8">

**Comment by Octaviedebs** [comment]
c'est bon 
<img width="748" alt="Capture d’écran 2024-09-16 à 11 09 30" src="https://github.com/user-attachments/assets/3dbfcc9c-86f0-4bd3-96c9-a35bf4762df7">

**Comment by julienzdocurba** [comment]
Top je clos l'issue merci!

**Comment by Octaviedebs** [comment]
On s'est pas dit qu'on close l'issue quand c'est mep ?

**Comment by julienzdocurba** [comment]
Je pensais que tu disais que c'était bon parce que c'était en prod.
