### ISSUE TITLE
Le bouton "Partager" dans la fenêtre de partage de procédure ne fonctionne pas

### ISSUE THREAD

**Issue by julienzdocurba** [MTES-MCT/Docurba#722]
CF: https://jam.dev/c/88bcc16f-3ca9-4beb-9dd7-617b6a8fb6c6

**Comment by lerayj** [comment]
https://jam.dev/c/9c4342e3-2d8f-4b74-9665-57de74bef916

**Comment by julienzdocurba** [comment]
Ok top donc en gros la solution que tu proposes c'est que quand je clique sur "Partager", ca "transforme" l'email en bloc email et partage c'est ca? Si c'est le cas ca me semble bien oui.

**Comment by HermanceGauth** [comment]
On a le même système dans le partage du PAC et ça fonctionne bien, je pense qu'il faut reprendre le même système par uniformité
