### ISSUE TITLE
Les DDT et CT du périmètre de la procédure sont suggérées alors qu'elles devraient être pré-ajoutées

### ISSUE THREAD

**Issue by julienzdocurba** [MTES-MCT/Docurba#727]
Sur l'écran "Invitez des collaborateurs" lors de la création de procédure, il semblerait qu'on ait 3 problèmes:
1. Les DDT et CT du périmètre de la procédure sont suggérées alors qu'elles devraient être ajoutées (c'est à dire qu'elle devraient apparaitre dans cette liste dans l'état "invité" avec le bouton "Retirer" pour que l'utilisateur puisse les retirer manuellement de la procédure).
2. Les CT du département mais qui ne sont pas dans le périmètre de la procédure sont suggérées alors qu'elles ne devraient pas apparaître dans cette liste.
3. On suggère des comptes tests et idéalement il ne faudrait pas les montrer.
![image (23)](https://github.com/MTES-MCT/Docurba/assets/147177148/f2682ce0-af1e-49ce-864b-457eb60476e0)

**Comment by HermanceGauth** [comment]
Je focus l'issue sur le point 1 car les deux autres points ont été repris dans des autres issues.

**Comment by HermanceGauth** [comment]
il faut vraiment par contre que cette issue : https://github.com/MTES-MCT/Docurba/issues/830 et la suppression des comptes test fonctionne sinon on va pré-invité beaucoup de fausse chose

**Comment by HermanceGauth** [comment]
Ce n'est pas bloquant mais on prend le risque que les CT créé des procédures snas inviter les DDT et que les DDT n'est plus accès à rien
