### ISSUE TITLE
Update de l'export CSV des data Sudocuh

### ISSUE THREAD

**Issue by UngererFabien** [MTES-MCT/Docurba#73]
- [ ] Changer les noms de colonnes qui mentionnes interco ou commune pour ne parler que de collectivité
- [ ] Faire des fichiers différents pour communes et interco
- [ ] Rendre le fichier téléchargeable direct dans les APIs

**Comment by lerayj** [comment]
Nouveau endpoints:

https://docurba.beta.gouv.fr/api/urba/sido_csv
=> Renvoie le CSV communes + epcis

https://docurba.beta.gouv.fr/api/urba/sido_csv?epcis=true
=> Renvoie le CSV epcis uniquement

https://docurba.beta.gouv.fr/api/urba/sido_csv?communes=true
=> Renvoie le CSV communes uniquement
