### ISSUE TITLE
Dde de modification de statut du PLU de Le conquet (29)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#732]
lien de la commune : https://docurba.beta.gouv.fr/ddt/29/collectivites/29040/commune

### Peut-on passer le PLU précédent en opposable ? (cf capture)
👉 **Les deux PLU devraient avoir le statut opposable** dû à une particularité terrain : ils sont sur deux périmètres distincts au sein de la commune. 

Merci ! 

<img width="1206" alt="Capture d’écran 2024-07-10 à 3 31 02 PM" src="https://github.com/MTES-MCT/Docurba/assets/111045572/7d96c38b-c5b0-468b-b160-19fa538e1a1f">

To do Célia : prévenir Gérald et Nathalie quand c'est good

> Dans ce cas précis, ne serait-il pas opportun de transformer le statut PLU "précédent" en statut PLU "opposable", car les deux sont opposables, aussi bien celui actuellement intitulé "précédent" que celui intitulé "opposable"?
> 
>  En effet, le jugement rendu ne portait que sur l'annulation partielle du PLU , un secteur restreint du PLU opposable originel. La nouvelle révision, intervenue suite au dit jugement, porte, par conséquent, uniquement sur ce secteur restreint. Le PLU "précédent" a toujours été, et est toujours opposable (excepté le secteur restreint précité).
> 
> Cette situation n'apparaît pas très claire visuellement, dans DOCURBA. Nous pensons qu'elle le sera encore moins pour le "grand public".

**Comment by HermanceGauth** [comment]
Même issue que celle-ci : https://github.com/MTES-MCT/Docurba/issues/361

**Comment by HermanceGauth** [comment]
je close car dans le tableau de correction
