### ISSUE TITLE
Ajouter une notif slack sur le channel bot_admin quand il y a un partage qlqu'il soit - lien de la frise cliquable

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#733]
Il faudrait : 
- ajouter  une **notif slack sur le channel bot_admin** quand il y a un **partage** qlqu'il soit : PAC ou FRP
- contenu de la notif parfaite : 

[ **_**Nom** du user qui a partagé ]_**, **_[ **poste** du user qui a partagé ]_** a partagé un(e) **_[ PAC ou FRP ]_** à  email du user à qui on a partagé ] : 
Lien (PAC ou FRP) : [ _lien  ]

**Nice to have** : avoir le titre de la FRP ou du titre du PAC si possible (en plus du _**type**_ de contenu partagé)

Ex : Bastien Ruamps, ddt,  a partagé une(e) FRP Modifcation simplifiée PLU Castelnau à célia@ blabla

**Comment by UngererFabien** [comment]
A faire en même temps que la https://github.com/MTES-MCT/Docurba/issues/669

**Comment by Octaviedebs** [comment]
**Précision point du 05.09** : 
1 seul notif° avec ts les emails (cas multi partage )

**Comment by Octaviedebs** [comment]
@lerayj Fabien nous disait que tu devais nous faire un loom ou une rapide visio sur ça justement - peut être attendre avant de la passer en tester ? avec @CeliaVermicelli on se rend dispo quand tu le souhaites

**Comment by Octaviedebs** [comment]
j'ai l'impress° que pour l'instant à chaque fois le rôle est inconnu - il faut afficher le Poste du user pour rappel

Par ailleurs (cf image 2), le lien de la frise est le lien de la page d'invita° des collaborateurs en lien avec cette [issue](https://github.com/MTES-MCT/Docurba/issues/832) à mon avis  

**Image 1**
<img width="604" alt="Capture d’écran 2024-09-25 à 14 23 58" src="https://github.com/user-attachments/assets/f4ad425a-3bb5-4112-93db-bc40ddc2af1a">

**Image 2**
<img width="604" alt="Capture d’écran 2024-09-25 à 14 23 12" src="https://github.com/user-attachments/assets/41e2c9b2-4aa2-48b9-8451-8226023f17e1">

**Comment by HermanceGauth** [comment]
@Octaviedebs est-ce ok pour toi à présent?

**Comment by Octaviedebs** [comment]
Il reste juste le lien de la frise qui n'est pas cliquable 
<img width="1022" alt="Capture d’écran 2024-10-21 à 09 03 00" src="https://github.com/user-attachments/assets/b2277afb-11b4-4b83-85e5-ddd5306af96b">

Je n'avais pas vu qu'elle était repassée de KO -> en prod' donc je n'avais pas rechecké.
Mais à part ça en principe cela me semble conforme à ce qu'on s'était dit

**Comment by Octaviedebs** [comment]
A priori tout ok à closer mais attendre qu'une nouvelle frp soit partagée pour check une dernière fois (si je me partage à mon email docurba je ne reçois pas non plus la notif

**Comment by Octaviedebs** [comment]
Je clos, une autre issue d'améliorations de cette notif est ici https://github.com/MTES-MCT/Docurba/issues/945
