### ISSUE TITLE
Rediriger l'ancien lien de la FAQ vers le nouveau du Centre aide Crisp

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#734]
Il faudrait redirigé l'ancien lien de la FAQ : https://docurba.beta.gouv.fr/faq vers l'actuel : https://docurba.crisp.help/fr/

----

**Problème** : les nouvelles personnes arrivent sur le navigateur et peuvent tomber sur la FAQ mais etre redirigé sur l'[ancien lien](https://docurba.beta.gouv.fr/faq) -> pas top. 

<img width="952" alt="Capture d’écran 2024-07-11 à 10 23 33 AM" src="https://github.com/MTES-MCT/Docurba/assets/111045572/48217a07-419e-41b8-a4e2-f92558d3f317">

**Comment by UngererFabien** [comment]
J'ai fais une redirection globale. Même si les gens click sur le lien de Google ils seront renvoyé sur crisp.

**Comment by CeliaVermicelli** [comment]
c'est good je close
