### ISSUE TITLE
New Proc. | Side Collectivité - lors de la création de procédure j'atterris ensuite sur la page d'accueil 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#745]
https://jam.dev/c/964848cb-e16e-43c5-9feb-971b44175796

Lorsque je créée une procédure depuis un accès CT j'atterris sur la page d'accueil au lieu d'atterrir sur la FRP pour pouvoir la compléter

**Comment by HermanceGauth** [comment]
Est-ce toujours le cas, il me semble que ça avait été résolu côté DDT mais j'ai un doute côté CT?
