### ISSUE TITLE
Tdb - onglet mes collectivités - 58 : erreur d'affichage, pas de SM alors qu'il existe le SM du SCoT du Grand Nevers

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#751]
https://jam.dev/c/bf600a04-c87c-4e4c-9a87-ca387b7bfa7a

**Comment by HermanceGauth** [comment]
@UngererFabien pas résolu en prod avec maj du référentiel

**Comment by UngererFabien** [comment]
Ha c'est fun, c'est parce que c'est un SMF et pas un SM je pense. Et donc il est filtré par les type de collectivités. Donc pas lié au référentiel mais à la fonctionnalité

![Screenshot 2024-11-05 at 15 17 16](https://github.com/user-attachments/assets/d1f7e294-f549-421a-be61-40f3668e26ec)
 de filtre.

**Comment by UngererFabien** [comment]
Je passe le hotfix en prod direct c'est juste un rapide fix sur les filtres.

**Comment by HermanceGauth** [comment]
Pour moi-même prévenir Claire
