### ISSUE TITLE
Pb statut Forcalquiert - 83 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#756]
[Lien commune](https://docurba.beta.gouv.fr/ddt/83/collectivites/83059/commune)

![Capture d’écran 2024-07-23 à 9 27 16 AM](https://github.com/user-attachments/assets/21c3207e-6832-468b-b8cb-d8896a50fe50)

Commentaire de la ddt concernant l'approbation invalide du PLU de 2013 : 

> la délibération d'approbation est considérée comme invalide alors que dans SuDocUH elle est juste indiquée comme étant annulée partiellement.

(et donc le POS devrait être en précédent et non opposable comme c'est le cas auj.)

To do Célia : Prévenir Josiane

**Comment by HermanceGauth** [comment]
voir https://github.com/MTES-MCT/Docurba/issues/143

**Comment by CeliaVermicelli** [comment]
Partiellement résolu - ddt prévenue. 

Le problème qui persiste : le PLU qui reste en "en cours" car l'approbation est annulée partiellement sur Sudocuh.
