### ISSUE TITLE
Dump : les modifications et suppressions d'event ne sont pas prises en compte 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#758]
On le savait déjà mais si jamais on prévoit d'inclure ces éléments dans le dump - modification qui peuvent être structures comme le besoin de modifier le périmètre d'une proc. https://github.com/MTES-MCT/Docurba/issues/658 

Marie Etch. du 34 : 

[Commune de Maraussan, 034](https://docurba.beta.gouv.fr/frise/70086048-dc44-44e1-a299-8f9dd41f038b) - procédure en cours de révision d'un PLU.

3e évènement : La nature d'un évènement était mal choisie : apparaissait comme un arrêt alors qu'il s'agissait d'une délibération objectifs poursuivis et modalités de concertation.
4e évènement : Doublon - à nouveau la délibération objectifs poursuivis et modalités de concertation - était indiqué à une mauvaise date.

- J'ai rectifié le 3e évènement sur SUDOCUH et j'ai supprimé le 4e - en date du 16 juillet.
- Ces deux rectifications n'ont pas été prises en compte sur Docurba - en date du 26 juillet.

![Capture d’écran 2024-07-29 à 11 44 25 AM](https://github.com/user-attachments/assets/a0cb1e06-4dcc-4be2-81a4-3562f755acba)

**Comment by lerayj** [comment]
Fixed manuellement - la modif est plus dur a faire dans le dump

**Comment by CeliaVermicelli** [comment]
QA en dev : ✅
- un seul event est conservé 
- la date conservée est le 12.07.2022 - correspond à la PJ


<img width="1030" alt="Capture d’écran 2024-09-16 à 1 07 22 PM" src="https://github.com/user-attachments/assets/5dd6e67b-b6e6-4082-aded-0bda2efeaa59">

**Comment by HermanceGauth** [comment]
@CeliaVermicelli je te laisse vérifier si c'est tout bon, prévenir et closed si ok
