### ISSUE TITLE
Page blanche sur l'email dans le depot de procedure

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#76]
![Uploading Capture d’écran 2023-09-26 à 12.40.19.png…]()

**Comment by Octaviedebs** [comment]
<img width="1437" alt="Capture d’écran 2023-09-26 à 12 40 19" src="https://github.com/MTES-MCT/Docurba/assets/144041896/14882229-1585-4b43-ad9a-d891678deeea">

**Comment by lerayj** [comment]
Fix sur dev, va bientot être mis sur prod pour le re rendre accessible
