### ISSUE TITLE
bug dump - la procédure secondaire de Adrets de l'Esterel (83) n'est pas remontée

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#760]
https://docurba.beta.gouv.fr/ddt/83/collectivites/83001/commune -> le 06/05/2024, la DDT avait ajouté une prescription de modification simplifiée n°1 du 25/04/2024, elle n'apparait pas sur Docurba. 
-> QA 16.09 en dev : pas de PS modif simplifiée ❌

Même cas pour [Bargemon](https://docurba.beta.gouv.fr/ddt/83/collectivites/83011/commune) : modification approuvée le 24/06/2024, notée dans SuDocUH depuis le 09/07/2024, n'apparait pas dans Docurba
-> QA 16.09 en dev : pas de PS de modif  ❌

pour rappel : Julien avait débugué le dump le 24 juillet au soir. 

Célia : 

- [ ] prévenir josiane

**Comment by lerayj** [comment]
@CeliaVermicelli possible d'avoir l'identifiant de la procédure principale sur laquelle elle a été ajouté ? (ou le lien de la FRP de sa principale)

**Comment by CeliaVermicelli** [comment]
@lerayj yes ! voici la [FRP de la proc principale de les Adrets de L'esterel ](https://docurba.beta.gouv.fr/frise/e5f64e66-63cd-4118-9f08-9b84740b6d8f)

**Comment by HermanceGauth** [comment]
@CeliaVermicelli je passe en testé car les deux me semblent ok

**Comment by HermanceGauth** [comment]
@CeliaVermicelli ça m'a l'air bon en prod je te laisse closed et prévenir Josiane si bien le cas
