### ISSUE TITLE
bug statut - cas de la CC du Pays Morcenais (40)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#762]
Sur la FRP de[ ce PLUiH ](https://docurba.beta.gouv.fr/ddt/40/collectivites/244000691/epci)il y avait : 
* une prescription (**saisie par erreur de la DDT sur docurba**) 
* Approbation saisie sur Sudocuh 
* Prescription saisie sur Sudocuh (la bon event) 

-> en l'état, le PLUiH était "en cours". J'ai donc demandé à la DDT de rectifier sa saisie et basculer la prescription renseignée par erreur dans la[ procédure secondaire de MS nº1](https://docurba.beta.gouv.fr/frise/2c90fffd-ac9f-418f-99c2-83ab4f002d26) de ce même PLUiH.

Résultat : 
### Le PLUiH de cette CC est passé du statut "en cours" à "précédent" alors qu'il aurait dû redevenir "opposable" puisque le dernier event structurant renseigné dans la FRP est l'approbation. 

![Capture d’écran 2024-07-30 à 3 38 32 PM](https://github.com/user-attachments/assets/d543f1f5-4bc9-4bea-9ed5-8ae732d796b3)

- [x]  to do célia : prévenir Guy et Christelle de la DDT

**Comment by HermanceGauth** [comment]
@CeliaVermicelli j'ai l'impression que c'est ok maintenant?

**Comment by CeliaVermicelli** [comment]
ouiii merci bcp @HermanceGauth je n'avais plus vu cette issue dans la liste
