### ISSUE TITLE
Copy incorrect sur les actions rapides - Socle de PAC 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#763]
Il faut enlever le mot "modifiez" - car personne ne peut modifier le socle dans ce parcours (recherche publique >> tdb CT) 
@HermanceGauth est-ce qu'on en profiterait pas pour mettre le copy suivant "Consultez les éléments génériques de niveau national et régional de votre futur PAC" ?

![Capture d’écran 2024-08-01 à 1 12 16 PM](https://github.com/user-attachments/assets/97676651-cd98-4d1c-8b49-951f2e68dc22)

**Comment by HermanceGauth** [comment]
Oui!
