### ISSUE TITLE
Bug Csv : il manque la date d'approbation du DU pourtant renseigné par la DDT dans la FRP (ex Lesneven - 29)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#765]
### Event bien renseigné dans Docurba  - approbation du 19.06.2024.

![Capture d’écran 2024-08-01 à 2 03 48 PM](https://github.com/user-attachments/assets/cae93748-81c8-4ff6-9ddd-c5dacc4c9e7d)

### alors que sur le .csv la date d'appro manque donc fausse la carte obtenue : 

<img width="991" alt="Capture d’écran 2024-08-01 à 2 03 36 PM" src="https://github.com/user-attachments/assets/4ef7d348-be67-45c0-ae35-e592bfda9e4f">

To do Célia : en conv. avec Ronan de la ddtm, lui envoyer le dictionnaire des champs. et me fait d'autres retours.

- [x] prévenir Ronan de la date d'appro de Lesneven

**Comment by UngererFabien** [comment]
Je me demande si je n'ai pas résolu ce bug suite à un retour de Claire sur le même sujet. J'irais faire un test.

**Comment by CeliaVermicelli** [comment]
@UngererFabien j'ai fais un nouvel export des procédures et on ne voit pas la date d'appro de Lesneven du 19.06.2024, donc à priori pas résolu suite au fix du retour de Claire

**Comment by UngererFabien** [comment]
C'est corrigé en prod de mes derniers test.
