### ISSUE TITLE
Bug lors de la connexion et de la récupération du mot de passe

### ISSUE THREAD

**Issue by julienzdocurba** [MTES-MCT/Docurba#767]
Un utilisateur ne peut plus se connecter car lorsqu'il essaie de récupérer son mot de passe, le bouton "Connectez-vous" dans l'email le redirige vers une page qui montre cette erreur:
<img width="942" alt="image" src="https://github.com/user-attachments/assets/7d903754-9cc3-434d-ba04-3d4d41112834">

N'hésitez pas si vous avez besoin de plus de détails, je peux lui poser des questions.

**Comment by julienzdocurba** [comment]
Un autre utilisateur a eu le même problème aujourd'hui.

**Comment by julienzdocurba** [comment]
Pas sûr que ce soit lié mais on vient de recevoir un feedback d'une utilisatrice qui dit qu'elle ne peut plus se connecter et qu'une réinitialisation de son mot de passe a été effectuée sans qu'elle ne le demande:
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/be9abd31-aab7-444e-a1d5-6c25c83b9840">

**Comment by julienzdocurba** [comment]
Un autre utilisateur qui a un problème sans avoir fait de demande de changement de mot de passe initialement:
<img width="657" alt="image" src="https://github.com/user-attachments/assets/de5958a6-5ca4-4bab-9085-d91509b9be4a">

**Comment by julienzdocurba** [comment]
Une utilisatrice mentionnée ci-dessus dit qu'elle ne reçoit même pas les emails d'oubli de mot de passe (mais il semblerait que les autres utilisateurs les reçoivent). Elle a vérifié ses spams et l'email n'est pas là non plus.

**Comment by julienzdocurba** [comment]
Je continue d'ajouter les messages qu'on reçoit:
<img width="1765" alt="image" src="https://github.com/user-attachments/assets/0ddcacb1-3217-44a2-8561-94b25b4e9ba7">

**Comment by julienzdocurba** [comment]
<img width="769" alt="image" src="https://github.com/user-attachments/assets/b131860e-9a3d-4b90-a1d0-4ac02bfe645c">

**Comment by julienzdocurba** [comment]
<img width="973" alt="image" src="https://github.com/user-attachments/assets/280f9561-fb94-4921-bc18-bf6171f5a08c">

**Comment by HermanceGauth** [comment]
Ce que j'obtiens : 
![image](https://github.com/user-attachments/assets/c1e71bb7-c5dd-4725-b0a0-e3d77550e3f2)

**Comment by HermanceGauth** [comment]
https://jam.dev/c/59c05d29-f6e2-4c62-9db0-0e2e8101679e
