### ISSUE TITLE
Formulaire inscription à la Newsletter

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#77]
Terminer ce qu'on avait commencé avec Fabien pour le formulaire de la page d'accueil et Brevo

**Comment by CeliaVermicelli** [comment]
Hello @UngererFabien, est-ce que l'on pourrait finaliser la mise en route du formulaire d'inscription à la newsletter et le rendre fonctionnel depuis le site ? 

Le formulaire prévoit la sélection de la cible (BE, CT et DDT) cf PJ1 - cela les ajoute dans 3 listes de contacts différentes dans Brevo (cf Pj2), le but est de réussir à leur envoyer du contenu plus qualifié.

Idéalement on voudrait aussi : 
- tracker les emails que l'on ne connait pas du tout au sein de ces listes (faire le lien avec nos BDD sur docurba/pipedrive?) -> pour identifier les leads à activer
- relier les automatisations pipedrive, via les actions sur Docurba pour faire évoluer ces listes de contacts dans Brevo -> un contact inscrit à la NL qui a fait 3 PAC recevra un NL avec du contenu orienté "rétention" et non "acquisition

-> est-ce que ce serait plus simple de faire un rapide call à ce sujet quand tu auras un moment ? 

FYI @Octaviedebs 
![Capture d’écran 2023-10-11 à 16 34 07](https://github.com/MTES-MCT/Docurba/assets/111045572/c36ea9e7-f79c-4aef-bff3-6d66b23fc4f1)
![Capture d’écran 2023-10-11 à 16 34 35](https://github.com/MTES-MCT/Docurba/assets/111045572/a5f9c2bb-b3a2-46bc-a550-0eb16558c9a2)

**Comment by Octaviedebs** [comment]
Hello @UngererFabien ! Je me permets une petite relance sur cette issue 

Si tu préfères on peut la splitter en deux issues : 

- **must have = PRIO** que le champs d'inscription à la NL soit fonctionnel (premier point de Célia) pour qu'on puisse récupérer ces emails et les activer : là actuellement et depuis plusieurs mois, on passe à côté de leads et c'est dommage :/ 
- **nice to have =** tracking et automatisations

Merci par avance 🙏🏻

**Comment by CeliaVermicelli** [comment]
Hello @UngererFabien, pour faire suite à ce que l'on s'est dit hier ; 

- voici la [prévisualisation du form d'inscription à la newsletter](https://64935080.sibforms.com/serve/MUIFAH46VtU6BZvdDJo3BIETnbhUYVx1mWd6R4uVHT_1IHWFdrNTB78-i3jbruWG-Or-8E-BWBuir1NDZ_YWEysT2T49GWKi4WH8gLGg2_NKjmRclqmrg_JreVKTP6l3LvESU8HjdlUqG9Wcbkp0YeAcy6jtkoOxDtYS9JGAmRhLAmGHuVsgJ1Cbaaje68G_xC94JXCSySJ_5o0Y) - à intégrer à la homepage de Docurba
- **et voici le code si on souhaite l'intégrer en iframe** : <iframe width="540" height="305" src="https://64935080.sibforms.com/serve/MUIFAH46VtU6BZvdDJo3BIETnbhUYVx1mWd6R4uVHT_1IHWFdrNTB78-i3jbruWG-Or-8E-BWBuir1NDZ_YWEysT2T49GWKi4WH8gLGg2_NKjmRclqmrg_JreVKTP6l3LvESU8HjdlUqG9Wcbkp0YeAcy6jtkoOxDtYS9JGAmRhLAmGHuVsgJ1Cbaaje68G_xC94JXCSySJ_5o0Y" frameborder="0" scrolling="auto" allowfullscreen style="display: block;margin-left: auto;margin-right: auto;max-width: 100%;"></iframe>
-> si c'est ok pour toi @julienzdocurba  ?

FYI @Octaviedebs
