### ISSUE TITLE
Erreur remontée procédure Sudocuh > Docurba - Neuviller (54)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#781]
> je ne retrouve pas la carte communale prescrite 27 juillet 2024 pour la commune de Neuviller-les-Badonviller. Je l'avais enregistré dans Sudocuh, le 07 août 2024.

[Lien commune](https://docurba.beta.gouv.fr/ddt/54/collectivites/54398/commune)

To do célia : 

- [ ]  Prévenir Valérie de la ddt

**Comment by lerayj** [comment]
@CeliaVermicelli tu peux me confirmer que c'est bon ?
Le contenu me parait quand meme étrange, il y a que un seul event dans l'elaboration et c' une Approbation du préfet
![Image](https://github.com/user-attachments/assets/e9e14238-9ef7-4f0e-85f6-8de13d682d51)

**Comment by CeliaVermicelli** [comment]
@lerayj yes c'est tout bon merci (cf PJ1.) 


![Image](https://github.com/user-attachments/assets/0bf590f1-aa3e-4c8d-aa04-151049aa4b09)



Et pour ta remarque, je crois que tu t'es fais avoir avec l'accès limité DDT (qui date de peu), tu ne devais pas être connecté sur le 54, il y a bien d'autres event privé qui rendent un peu plus cohérente la proc. eheh 



![Image](https://github.com/user-attachments/assets/64fd6de6-dae9-457d-8137-aed73def9726)
