### ISSUE TITLE
bug PAC : téléchargement du pdf impossible (PAC en cours de relecture - ddt 37)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#782]
PAC en question : https://docurba.beta.gouv.fr/documents/projet-6957055a-2359-4954-9b45-c5fb1118889a/pac
demo : https://jam.dev/c/76beb567-7493-4967-94ee-b0c8cb78ebca

Si jamais ça peut aider : 
* l'agent de la DDT avait bien réussi à télécharger ce PAC courant juillet. 
* on avait eu un problème isolé comme celui-ci en fin d'année - [cf résolution de Nico](https://github.com/MTES-MCT/Docurba/issues/172#issuecomment-1813117675). C'était dû à des blocages de téléchargement d'une image de sante.gouv.fr

Pour info le téléchargement fonctionne sur un PAC créé par moi-même en janvier et un autre début aout. 

To do : 

- [x] prévenir benoit

**Comment by UngererFabien** [comment]
Corrigé, c'était les image en base64 qui n'étaient pas bien traitées.
