### ISSUE TITLE
Tally Pop-up | Communica° Nvlle procédure

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#788]
Hello @UngererFabien !

Voici la pop up d'information pour annoncer la nouvelle fonctionnalité de nvlle proc. (je t'en parle en pt d'équipe tt à l'heure): 

Tu peux y accéder sur Tally https://tally.so/forms/wQdZvX/share : j'ai l'impress° que la dernière fois c'était plus simple que tu y récupères toi même le code pour les moduler en fonction de ce qu'on s'est dit.

Conditions : 
- format standard
- side collectivité
- accès connecté
- 2 fois maximum par connexion + la pop up n'apparait plus du tout dans 30 jours

FYI @CeliaVermicelli

**Comment by UngererFabien** [comment]
Comme pour le tableau de bord dans une modal au centre de l'écran.

**Comment by UngererFabien** [comment]
Popup a retirer completement.

**Comment by Octaviedebs** [comment]
testé tt ok
