### ISSUE TITLE
bug téléchargement trame de PAC en PDF dans le 81

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#789]
Retour de la ddt : 

> Pour les PAC, je n'ai pas réussi à le télécharger. Cela ne fonctionne ni sur les ordinateurs de mes collègues, ni sur un autre navigateur.

-> je n'ai pas eu de problème de mon côté, que ce soit pour la trame ou pour un PAC tout juste créé, j'ai réussi à télécharger le PDF.
Mais il m'a confirmé à deux reprises de son côté la semaine dernière que ça ne fonctionnait pas pour lui. 
Est-ce qu'il y a moyen de vérifier que tout fonctionne normalement ? Pour info, c'est une personne qui est familière à Docurba.

To do celia : 

- [x] prévenir Arnaud.

**Comment by UngererFabien** [comment]
Pareille pour cette trame. Je n'arrive pas a reproduire. Je rajoute le PDF en pièce jointe et je continu de chercher une manière de reproduire.
[Trame départementale.pdf](https://github.com/user-attachments/files/16995030/Trame.departementale.pdf)

**Comment by CeliaVermicelli** [comment]
ça marche merci !

**Comment by CeliaVermicelli** [comment]
La DDT m'informe que ça fonctionne à nouveau, ils n'ont rien changé depuis la dernière fois "A ma connaissance pas de mise à jour particulière, je n'avais pas alerté non plus le service informatique."
