### ISSUE TITLE
bug dump ? il manque la RA nº2 de Saint Maximim (83) initialement ajoutée depuis Sudocuh

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#794]
[Lien page CT
](https://docurba.beta.gouv.fr/ddt/83/collectivites/83116/commune)

### Sur Docurba on a une procédure de RA nº2 (ajoutée depuis Docurba) : 
![Capture d’écran 2024-09-03 à 4 45 39 PM](https://github.com/user-attachments/assets/9c4b2613-578c-4f3b-a2cf-12be6dda3870)

### Mais on devrait en avoir une 2eme, celle ajoutée initialement depuis Sudocuh par la DDT (qui n'utilise pas encore Docurba) 
![st_maximin_2](https://github.com/user-attachments/assets/89ea1cbe-766d-4f86-b80c-cb8b6ce4037b)
![st_maximin_1](https://github.com/user-attachments/assets/3725a0c2-6fff-4eed-9092-42453e16d67e)

-> le dump n'aurait pas remonté cette procédure, 
-> la CT, voulant ajouter ses event, a créé (via les bizdev) la procédure et ajouté ses events

Pour info, cette CT a fait l'objet de plusieurs issues/bug : [471](https://github.com/MTES-MCT/Docurba/issues/471) [553](https://github.com/MTES-MCT/Docurba/issues/553) [621](https://github.com/MTES-MCT/Docurba/issues/621)

Célia : 
- [x] prévenir Josiane quand procédure remontée depuis Sudocuh 
- [ ] voir pour supprimer la procédure ajoutée depuis Docurba qui serait donc en doublon

**Comment by HermanceGauth** [comment]
@CeliaVermicelli la procédure apparaît à présent il me semble

**Comment by CeliaVermicelli** [comment]
yes c'est bon merci ! je ne close pas tant que l'on n'a pas supprimé la proc en doublon avec la CT -

**Comment by CeliaVermicelli** [comment]
doublon supprimé et PJ rajouté dans la bonne proc. 

Josiane prévenue, CT aussi du coup.
