### ISSUE TITLE
Permettre la création d'une procédure de SCoT

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#797]
Il faut permettre la création d'une procédure de SCoT pour tous les accès depuis le formulaire de créa° de nouvelle procédure.

Voir https://github.com/MTES-MCT/Docurba/issues/612 si besoin 
FYI @HermanceGauth : y a til besoin de remettre les liens des maquettes Figma ? 

Avant passage en prod pinguer Octavie pour que je prévienne Paola OCAÑA-SEGUIN 💬 + Antoine hersent ✅(email du 11.12) qui avait remonté cette demande + surveiller Nathalie SEMENT ✅qui va bientôt créer un compte pour créer sa procédure de révision du SCoT

QA :
- #935

**Comment by HermanceGauth** [comment]
cf maquette ici : https://www.figma.com/design/4W463mFBKoDzf4mgJAhW9y/Docurba-(V2)?node-id=3605-16156&node-type=CANVAS&t=HuT4zBvgOtno0HoC-0

**Comment by HermanceGauth** [comment]
Le référentiel fait buguer l'import du dump, pré-requis de débuguer le référentiel

**Comment by HermanceGauth** [comment]
En termes métier possibilité de dissocier :
- création de procédure SCoT lorsque le périmètre est déjà dans notre référentiel
- création de procédure SCoT lorsque le périmètre est un groupement que l'on n'a pas dans notre référentiel

**Comment by UngererFabien** [comment]
https://github.com/MTES-MCT/Docurba/pull/984

**Comment by HermanceGauth** [comment]
@rik @UngererFabien le tableau de bord s'est mis à m'afficher des groupements qui n'ont pas la compétence urbanisme et 543 collectivités au lieu de 514 : https://dev.docurba.beta.gouv.fr/ddt/55/collectivites
![Image](https://github.com/user-attachments/assets/0729cba0-672a-464d-923a-61edd0263cc3)
![Image](https://github.com/user-attachments/assets/5e64abc8-abbe-4672-8a3a-58ecad5fd5a3)

**Comment by HermanceGauth** [comment]
Et en revanche là où cela pourrait avoir du sens de retrouver ces EPCI n'ayant pas la compétence dans Banatic pour ne pas bloquer l'utilisateur si le référentiel Banatic n'est pas à jour - c'est à dire à la création de procédure depuis l'onglet "Mes procédures" bouton "Nouvelle procédure" - les EPCI qui n'ont pas la compétence dans Banatic ne s'affichent pas et j'ai cette phrase à la place. Cela ne me dérange pas en soi puisqu'on pense qu'il y a peu de cas où l'EPCI n'est pas dans notre référentiel, mais je ne me souviens pas qu'on en ait parlé.
![Image](https://github.com/user-attachments/assets/23c45560-ca9e-4370-ba9d-6cdb09fbd089)

![Image](https://github.com/user-attachments/assets/da94d88b-ec36-4eed-b67b-9c4317fbdfca)

**Comment by rik** [comment]
On va traiter le problème remonté par Hermance dans https://github.com/MTES-MCT/Docurba/issues/1067.

**Comment by rik** [comment]
C'est en prod.

@Octaviedebs Désolé, je ne vois que maintenant le ping que tu demandais **avant** de mettre en prod.

@CeliaVermicelli @Octaviedebs Comme c'est une grosse fonctionnalité, je vous assigne le ticket pour vous servir de rappel pour vos communications. Vous pouvez fermer quand vous le souhaiter.

**Comment by Octaviedebs** [comment]
@CeliaVermicelli on est maintenant tout bon sur nos to do respectives en dehors d'ici post cette issue donc je la close ?
