### ISSUE TITLE
Bug téléchargement du PAC en PDF (971 - Guadeloupe) 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#805]
voici le lien du PAC qui ne peut pas être téléchargé : 
https://docurba.beta.gouv.fr/trames/projet-d4eaaba1-e355-478c-a600-1d2f0bfb1618

- [x] prévenir Ana quand résolu

**Comment by UngererFabien** [comment]
Je n'ai pas réussi à reproduire, je rajoute en pièce jointe le PDF.
[PLU - PAC.pdf](https://github.com/user-attachments/files/16994913/PLU.-.PAC.pdf)
