### ISSUE TITLE
Erreurs statuts procédures principales (remarques de Claire faites en août)

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#814]
-> Evenement 'délib approbation' avec statut 'annulation partielle' doit être considéré comme 'Valide' RNU dans docurba alors que DU  opposable
94016, 77006, 76158, 64322, 33540, 34238, 34039, 26145,38120,2A269
_C'est bien la règle que nous avons implémentée (cf extrait de code ligne 9, un event avec annulation partielle ('AP') reste valide). Nous sommes en train de regarder pourquoi cela ne s'applique pas comme nous le prévoyons : peut-être réglé avec le travail de Fabien sur les statuts?_

-> Evenement 'Annulation TA' : le DU n'est pas opposable
ne sont pas au RNU dans docurba , alors que pas de DU opposable
ex 18178,  21069, 02645, 88348, 55185, 52231, 40092, 11256,63326, 2A275, 2A163, 2A092
_Ce problème concernait uniquement les cartes communales annulées, nous avons identifié d'où provenait le problème dans le code et allons corriger._

-> Approbation PLUi
Quand il y a des procédures individuelles en cours simultanément à un PLUi, lorsque le PLUi est approuvé, les proc individuelles ne doivent plus être en cours puisque le PLUi s'oppose. Dans SudocUH elles sont 'abandonnées' via un évenement d'abandon, dans docurba elles restent 'en cours' 
https://jam.dev/c/bb81ad30-e46e-40a2-953c-aa733e13eac7

-> Autre constat non lié au RNU, mais au process metier docurba :
Certaines évenements devant générer une nouvelle procédure de révision ont été inclus dans la procédure opposable, cela va être compliqué d'identifier ces cas...
-> Presc/app/presc dans la même procédure 
ex 68188 , 35061
_Effectivement c'est assez étrange, le 68 nous a envoyé cette copie d'écran, on voit que tu avais fait des modifications mais on ne comprends pas pourquoi c'est traduit comme cela dans Docurba, si jamais tu as une idée? De notre côté, on continue d'investiguer._
image.png
voir l'issue https://github.com/MTES-MCT/Docurba/issues/780

**Comment by HermanceGauth** [comment]
updtae sur remarque 1 : le travail sur les statuts gère de la bonne manière les annulations partielles pour les nouvelles procédures sur Docurba avec ajout d'un event annulation partielle à part entière. Toutefois, le problème persiste pour les évènement d'approbation issus de Sudocuh avec statut "annulation partielle" qui sont considérés comme "invalide" au lieu de "valide".

**Comment by UngererFabien** [comment]
_-> Evenement 'délib approbation' avec statut 'annulation partielle' doit être considéré comme 'Valide' RNU dans docurba alors que DU opposable_
J'ai vérifié toutes les communes en exemple, elles sont toutes au RNU. Cependant, je n'ai pas l'impression que cela soit 100 % correct. Beaucoup d'entre elles mentionnent en commentaire la notion d'annulation/abrogation partielle. Les documents ne devraient-ils pas être opposables lorsqu'ils sont seulement partiellement invalidés ?

_-> Evenement 'Annulation TA' : le DU n'est pas opposable_
 Le problème devrait être réglé au prochain DUMP.

_-> Approbation PLUi :_ 
J'ai essayé de mettre en place une solution. Mais en testant, je me rends compte que cela rend l'abandon irréversible. Si nous ajoutons un événement d'abandon automatiquement, les procédures ne pourront plus repasser à "en cours" si jamais le PLUi est annulé, s'il s'agit d'une erreur de saisie, ou même d'un simple test. Du coup, je pense qu'il faudrait que le statut d'abandon suite à l'approbation du PLUi soit déduit logiquement plutôt que déclenché par un événement. Qu'en penses-tu, @HermanceGauth ?

**Comment by UngererFabien** [comment]
Les event AP (annulation partiel) sont classé invalide alors qu'ils devraient être valident.

**Comment by HermanceGauth** [comment]
+vérification des PS non remontées : 
![image](https://github.com/user-attachments/assets/2c109265-34ad-43bc-b43c-4fed96280dfe)

**Comment by HermanceGauth** [comment]
+vérification statuts :
- https://github.com/MTES-MCT/Docurba/issues/911
- https://github.com/MTES-MCT/Docurba/issues/656

**Comment by HermanceGauth** [comment]
Pour les PS, @lerayj a fait une première passe qui semble avoir résolu plusieurs cas, mais le cas de Claire semble encore poser problème car je compte 16 PS sur PLU pour cette commune contre 24 dans Sudocuh.

**Comment by HermanceGauth** [comment]
Complément du 25 octobre :
        1.2 **L’évenement d’approbation avec statut ‘annulation partielle’ vaut approbation**
Le POS est en cours
 Pas de DU opposable, tous les statuts sont à PRECEDENT, le premier approuvé en 2017 est bien l’opposable 
![Image](https://github.com/user-attachments/assets/d6cca60f-0e1b-4520-a702-f994e1edb391)
![Image](https://github.com/user-attachments/assets/65eb22f4-b00f-4447-ab79-820790dc358f)

Autres exemples ou le DU est bien opposable : 13041, 13040

A de l'influence sur les statuts des procédures principales

1.3  **PLU individuel codifié en PLUi certains apparaissant dans les DU intercommunaux d'autres communaux**
![Image](https://github.com/user-attachments/assets/db031b44-3764-4997-97f0-35cd970fd82d)
![Image](https://github.com/user-attachments/assets/78661a18-abcb-4116-bac2-c0cd65a9423a)

2.1 **Evenement abandon, laisse le statut en cours**
![Image](https://github.com/user-attachments/assets/c058992e-2432-4e66-b32b-37691c8f7e96)
![Image](https://github.com/user-attachments/assets/1b224bc0-8684-4194-bb39-efffb36bc531)

2.2 **Export non prise en compte de la dernière procédure en cours**
![Image](https://github.com/user-attachments/assets/f46447ed-cadb-475e-a628-aa3651aca356)

3.1 **Saisie de prescription à la suite de DU opposable**
![Image](https://github.com/user-attachments/assets/3a5319b9-b444-4d2c-9672-f5d1a5fe4fba)

**Comment by HermanceGauth** [comment]
+ sa remarque sur les COG : https://github.com/MTES-MCT/Docurba/issues/919

**Comment by HermanceGauth** [comment]
On fini ce qui est structurant (vis-à-vis de la quantité) ici puis fonctionnalité spécifique de l'enquête et on revient sur le reste.

**Comment by HermanceGauth** [comment]
PR aujourd'hui et point pour expliquer ce qui est couvert.

**Comment by UngererFabien** [comment]
https://www.loom.com/share/1683e7bdb93142269e5fce819cc8c40a?sid=990001a6-89ce-4537-99f2-f4a36fc08ac7

**Comment by HermanceGauth** [comment]
Je comprends qu'avec le nouveau fonctionnement par PR, je ne peux pour l'instant pas aller vérifier sur dev? En tout cas, en attendant que j'ai pu faire les vérifications tu peux repasser sur la création de procédure SCoT oui.

**Comment by rik** [comment]
@HermanceGauth Le code améliorant le comportement pour les communes déléguées est sur `dev`. Mais tu veux sans doute attendre demain matin, après l'exécution de la nouvelle version du script d'import, pour tester.

**Comment by UngererFabien** [comment]
> Est-ce que tu pourrais me rééxpliquer pourquoi on n'a pas le nombre de communes du COG dans les exports au cas où la question soit posée demain? exemple ici : https://dev.docurba.beta.gouv.fr/ddt/85/collectivites/248500415/epci 14 communes dans l'EPCI, 14 communes au COG, 16 communes dans le périmètre de la procédure

Il y a bien 14 communes dans le référentiel suite à la dernière mise a jour. Les 2 communes en trop sont des communes qui sont devenu COMD (Cezais 85041 et Saint-Sulpice-en-Pareds 85271).

On ne gère pas la mise a jour des perimettre suite aux fusions. Donc soit la DDT le met à jour, soit c'est à nous de faire la correction en BDD.

Les corrections possibles sont:
1. On retirre les COMD des perimettres PLUi quand on met à jour les reférenciels --> Perte de l'historique
2. On rajoute une notion d'archivage de perim pour indiquer que la ligne n'est plus valable suite à un changement
3. Uniquement pour les COMD on décide de ne pas les inclure dans les perim à l'affichage.

**Comment by UngererFabien** [comment]
> @UngererFabien @rik Vérification en dev : 1.2 ok pour Erdeven mais n'a pas résolu les pb évoqués en août sur 77006, 94016, 76158 au début de l'issue, ou les autres remontés en octobre 13040 et 13041 même après que le dump ait eu lieu, sauf si je loupe quelque chose, j'ai essayé avec la mise à jour manuel qu'on a sur super admin, ça ne fonctionne pas non plus, ils sont tous en cours au lieu de opposable.

Je n'ai pas résolu le problème sur les anulations partiels. C'est des choses qu'on foit prendre en compte de manière spécifique. Un peu comme les POS qu'on doit mettre en caduc/abandonné sistématiquement.
