### ISSUE TITLE
Permettre la validation des procédures pour l'ensemble des DDT

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#817]
Avec statuts cohérents avec les autres onglets.

- https://github.com/MTES-MCT/Docurba/issues/653
- https://github.com/MTES-MCT/Docurba/issues/323

Attention à l'affichage des communes fusionnées.

À faire dans https://github.com/MTES-MCT/Docurba/pull/980:
- [x] Feature flag
- [x] Tooltip au survol de la checkbox pour indiquer qu'on valide une collectivité et pas une procédure

Dans une autre PR :
- [x] Filtre EPCI

**Comment by HermanceGauth** [comment]
L'onglet de validation des procédures est redondant avec l'onglet "mes collectivités", est-ce qu'on garde deux onglets? @julienzdocurba

**Comment by HermanceGauth** [comment]
Atelier du 09/10 : on choisit d'utiliser l'onglet "Mes collectivités"

**Comment by julienzdocurba** [comment]
Le design est expliqué en détails ici: https://www.figma.com/design/4W463mFBKoDzf4mgJAhW9y/Docurba-(V2)?node-id=7995-46411&node-type=frame&t=3zmVKfB9oMvLgnXy-0

On peut se faire un call pour en parler quand vous commencez à bosser dessus!

**Comment by rik** [comment]
Lien Slack avec des retours sur la hiérarchie de l'information : https://docurba.slack.com/archives/C03MEER8S06/p1731429236397519

**Comment by HermanceGauth** [comment]
On va déployer une preview sur dev puis travailler sur feature flag

**Comment by rik** [comment]
PR contenant le travail en cours :
- https://github.com/MTES-MCT/Docurba/pull/980

Par rapport au Figma, dans la branche, je ne vois pas :
- le tooltip au survol de la checkbox pour indiquer qu'on valide une collectivité et pas une procédure
- le tooltip au hover sur les labels des statuts
- le filtre EPCI
- la colonne type est toujours là

Je le note pour que l'on puisse décider ce qu'on fait ou pas.

Une validation n'est annulable que par la personne qui a fait la validation (ou l'équipe admin Docurba). Donc pas par n'importe quelle personne de la DDT. Est-ce le fonctionnement souhaité ? (je n'ai pas trouvé d'indication dans Figma)

**Comment by rik** [comment]
Discussion avec @lerayj :
- le tooltip au survol de la checkbox pour indiquer qu'on valide une collectivité et pas une procédure : faisable dans la PR existante.
- le tooltip au hover sur les labels des statuts opposables : petit doute sur la facilité de remonter l'information de la date d'opposabilité. Faisons le dans une autre PR car c'est peut-être une fonctionnalité à garder après l'enquête.
- le filtre EPCI : Faisons le dans une autre car c'est peut-être une fonctionnalité à garder après l'enquête.
- la colonne type est toujours là : travail effectué dans #653.

Questions pour @julienzdocurba :
- Est-ce que l'on doit mettre un tooltip sur les labels des status "en cours" ? Si oui, quelle info serait utile d'afficher dedans ?
- Est-ce que le filtre EPCI est voué à rester une fois l'enquête terminée ?
- Est-ce que le tooltip sur les statuts opposables est voué à rester une fois l'enquête terminée ?

**Comment by HermanceGauth** [comment]
Je me permets juste de répondre sur le premier point des questions à Julien. Pour le "en cours" c'est comme le opposable "Depuis le..." avec la date de prescription cette fois.

**Comment by julienzdocurba** [comment]
Oui exactement ce que décrivait @HermanceGauth pour la 1ère question.

Et sinon pour les 2 autres, oui le filtre EPCI comme le tooltip sur les statuts sont voués à rester après l'enquête.

**Comment by rik** [comment]
On fera le tooltip des dates dans https://github.com/MTES-MCT/Docurba/issues/1037

**Comment by rik** [comment]
L'interface de validation et le filtre EPCI sont disponibles en dev. À vos tests !

Pour rappel, cela n'inclut pas le [Tooltip de dates d'opposabilité et prescription](https://github.com/MTES-MCT/Docurba/issues/1037) ou le [formattage des titres de procédures](https://github.com/MTES-MCT/Docurba/issues/653).

**Comment by rik** [comment]
- J'ai envoyé le filtre EPCI en production.
- Les bugs Firefox ont été résolus.
- On se parle lundi de la validation d'une collectivité sans PLU ou SCoT. Je me demande si ça a du sens niveau métier.

**Comment by rik** [comment]
La validation d'une collectivité sans procédures fonctionne maintenant.

Je passe Célia et Hermance en assigned. Si vous ne voyez plus de soucis, vous pouvez fermer cette issue.

**Comment by CeliaVermicelli** [comment]
C'est tout bon pour moi !

**Comment by HermanceGauth** [comment]
C'est tout bon, je ferme l'issue. Il faudra reset les communes validées là où on a fait nos tests.
