### ISSUE TITLE
Banner informatif Flash info + partage de proc. 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#821]
Hello @UngererFabien comme on en parlais en point ops: 

**Visibilité du banner sur le site :**

en mode : 

- non connecté sur la page d'accueil
- connecte DDT
- connecté DREAL
- connecté CT/BE

Faire deux temporalités :

### Copy 1 : 
Flash Info le jeudi 7 novembre, [Plus d'informations et inscriptions via ce lien](https://app.livestorm.co/mte/flash-info-de-docurba?type=detailed).

**Quand** : dès que possible et jusqu'au 7 novembre 13h30 si possible.

### Copy 2 :
NOUVEAUTÉ 🥳 Invitez désormais les parties prenantes de votre procédure sur Docurba. 
[En savoir plus.](https://docurba.crisp.help/fr/article/plusieurs-personnes-travaillent-sur-votre-procedure-invitez-les-7w4vd5/?bust=1728470032756)

**Quand** : dès le 7 novembre 13h30 et jusqu'au 21.novembre. 

FYI @Octaviedebs

**Comment by CeliaVermicelli** [comment]
@UngererFabien toutes les informations sont dispo pour mettre le banner en ligne, si besoin on en reparle demain en point ops :)

**Comment by CeliaVermicelli** [comment]
Hello @UngererFabien 

On voit que le banner prévu n'est pas apparu suite au Flash info de ce midi. 

Pour rappel, voici le copy : 

NOUVEAUTÉ 🥳 Invitez désormais les parties prenantes de votre procédure.
[En savoir plus.](https://docurba.crisp.help/fr/article/plusieurs-personnes-travaillent-sur-votre-procedure-invitez-les-7w4vd5/?bust=1728470032756)

### jusqu'au 21 novembre max, 

Merci !

**Comment by Octaviedebs** [comment]
En fait c'est tout bon depuis ce matin - je close
