### ISSUE TITLE
Mise a jour du référenciel des collectivitées porteuse de SCoT

### ISSUE THREAD

**Issue by UngererFabien** [MTES-MCT/Docurba#823]
Il faut ajouter dans le référenciel les groupement qui sont porteurs de SCoT dans Sudocuh mais qui n'ont pas la compétence SCoT dans Banatic.

Sinon ces SCoT ne sont pas présent dans les export et créer des bugs dans les dashboards.

https://github.com/MTES-MCT/Docurba/issues/641

**Comment by rik** [comment]
A-t-on de la documentation sur comment ces référentiels sont mis à jour ?

**Comment by HermanceGauth** [comment]
Corrige bien les SCoT manquant API SCoT, mais ne résout pas les interdépartementaux dans l'affichage DOcurba

**Comment by HermanceGauth** [comment]
En plus des cas interdépartementaux dans l'onglet mes procédures, certains SCoT sont encore absent en pre-prod de l'onglet mes collectivités :
- https://github.com/MTES-MCT/Docurba/issues/751
- https://github.com/MTES-MCT/Docurba/issues/633

**Comment by HermanceGauth** [comment]
Passage en prod dés que le debug est fait.
