### ISSUE TITLE
QA Partage de proc. | Les users test apparaissent en tant que collaborateurs

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#825]
Exclure dans les collaborateurs (suggestion + barre latérale droite) dont les emails users contiennent : 

- docurba
- yopmail
- celia.vermicelli@gmail.com 
- okie09@hotmail.fr
- vos emails à vous que vous avez déjà utilisé

A discuter pour les solutions si besoin !

**Comment by HermanceGauth** [comment]
et hermance.gauthier@developpement-durable.gouv.fr
en lien avec cette issue j'imagine ? https://github.com/MTES-MCT/Docurba/issues/812

**Comment by HermanceGauth** [comment]
et cette issue aussi https://github.com/MTES-MCT/Docurba/issues/728
