### ISSUE TITLE
QA Partage de proc. | On ne peut pas retirer un collaborateur

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#826]
https://jam.dev/c/d6b7f614-123f-4e7e-8a11-d06de77f2f07

Quand je clique sur Partager > trois petits points impossible de retirer un collaborateur 

OR il s'agit d'une procédure from Docurba.

Il faudrait qu'à la suppression on ait le message de suppression + que la page se mette à jour tout de suite (et pas qu'i faille cliquer à côté puis recharger pour que constater la suppress°) - je pense que c'était dans les maquettes

**Comment by HermanceGauth** [comment]
Je ne parle pas parce que je suis dans le train mais de mon côté je n'ai pas rencontré ce pb : https://jam.dev/c/459f871a-1f2c-459a-b3ff-039630200084

**Comment by Octaviedebs** [comment]
https://dev.docurba.beta.gouv.fr/frise/c571c674-7016-4781-b134-10394637311d

Est-ce que tu peux essayer sur cette proc. ? https://jam.dev/c/f5e107b6-3346-4945-9f4b-28c1e77f0e76

**Comment by Octaviedebs** [comment]
(je vais plutôt essayer sur la tienne)

**Comment by Octaviedebs** [comment]
@HermanceGauth peux tu m'inviter sur cette procédure pour que je teste ? [octavie+3.dbs@docurba.beta.gouv.fr](mailto:octavie+3.dbs@docurba.beta.gouv.fr)

Je suis bien connectée sur dev avec cet email > sur cette collectivité 55 Willeroncourt
<img width="1393" alt="Capture d’écran 2024-09-25 à 12 51 24" src="https://github.com/user-attachments/assets/5ba08d31-9d2d-4f84-962d-101dcdcef500">

Mais comme il s'agit d'une nouvelle procédure je ne suis pas considérée par défaut comme collaboratrice

**Comment by Octaviedebs** [comment]
@HermanceGauth j'ai bien reçu ton email de partage de procédure mais il semblerait que mes droits ne se soient pas mis à jour. J'ai rechargé plusieurs fois. https://jam.dev/c/9e35b239-e52b-4196-bfed-fe05cb64fd3c

**Cet email :** 
<img width="958" alt="Capture d’écran 2024-09-25 à 13 18 02" src="https://github.com/user-attachments/assets/79118500-aebd-47eb-8dec-aa5f6914d878">


**Cette FRP** https://dev.docurba.beta.gouv.fr/frise/adf542fb-23b7-4dac-b232-3afd8144fabb

**Je suis bien connecté en dev avec cet email :** 
<img width="1416" alt="Capture d’écran 2024-09-25 à 13 18 49" src="https://github.com/user-attachments/assets/5f4854e3-653d-4810-98ba-df3d29403115">

**Pourtant toujours pas d'accès :** cf jam

**Comment by HermanceGauth** [comment]
J'ai l'impression que c'est deux choses différentes, dans un premier temps tu avais accès aux droits mais l'action de retirer ne donne rien. Dans un second temps le problème c'est que tu n'as pas les droits

**Comment by Octaviedebs** [comment]
Oui complètement, c'est pour ça que je t'avais demandé en parallèle qu'on fasse les tests sur le partage de la FRP du 35, car je ne pouvais plus tester le retrait d'un collab' suite à ton commentaire indiquant que tu le pouvais. 

Je propose qu'on supprime nos derniers commentaires pour plus de clareté _(j'ai demandé à julien L dans le thread sur slack s'il voulait qu'on fasse des issues dédiées pour cette q° de droits, j'attends sa rep)_ 

Pour cette histoire de retrait il faudrait donc juste comprendre pourquoi toi tu y arrivais > moi je n'y arrivais pas cf mon commentaire d'il y a trois heures 
<img width="955" alt="Capture d’écran 2024-09-25 à 15 40 17" src="https://github.com/user-attachments/assets/1b93288f-24d2-4202-a2d0-91bec44959a1">

Ca te va ?

**Comment by HermanceGauth** [comment]
Yes supprimons nos commentaire ici sur les questions de droits et je pense que tu peux refaire une issue spécifique du coup dans cette milestone pour les droits

**Comment by Octaviedebs** [comment]
Done de mon côté pour la suppress° des commentaires - tu peux supp les tiens
