### ISSUE TITLE
QA Partage de proc. | L'ajout d'un collaborateur inconnu ne suit pas le comportement attendu

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#827]
Lors de l'ajout d'un email inconnu (= qui n'est pas un user) en principe : 
- une fois ajouté, l'email doit apparaitre dans les liste  => ce n'est pas le cas 
- un bandeau vert indiquant que le collaborateur a été ajouté doit apparaitre => ce n'est pas le cas

Maquettes figma à prendre en compte =  écran 129 notamment 

@julienzdocurba pour précision / ajout de commentaires

Par ailleurs, lors de l'ajout de l'email, il faut cliquer sur Entrer > puis Partager = ce qui n'est pas intuitif - il faudrait pouvoir ajouter l'email > cliquer sur Partager pour procéder à l'ajout = quel comportement était prévu ?

**Comment by julienzdocurba** [comment]
> une fois ajouté, l'email doit apparaitre dans les liste des suggestions

On avait descopé cette partie. Les suggestions ne montrent que les comptes du périmètre pour l'instant, pas les comptes avec lesquels j'ai déjà collaboré (c'est expliqué ici sur Figma: https://www.figma.com/design/4W463mFBKoDzf4mgJAhW9y/Docurba-(V2)?node-id=5027-41250&node-type=frame&t=Gc04WE9jf0ME3vUM-0).

> un bandeau vert indiquant que le collaborateur a été ajouté doit apparaitre

Oui pour toute invitation on doit montrer cette alerte: https://www.figma.com/design/4W463mFBKoDzf4mgJAhW9y/Docurba-(V2)?node-id=5046-46704&node-type=frame&t=Gc04WE9jf0ME3vUM-0

> Par ailleurs, lors de l'ajout de l'email, il faut cliquer sur Entrer > puis Partager = ce qui n'est pas intuitif - il faudrait pouvoir ajouter l'email > cliquer sur Partager pour procéder à l'ajout = quel comportement était prévu ?

Il me semble qu'on a du changer ça récemment à cause d'un bug et qu'on s'était justement mis d'accords pour que l'on puisse cliquer directement sur "Partager".

**Comment by Octaviedebs** [comment]
>Les suggestions ne montrent que les comptes du périmètre pour l'instant, pas les comptes avec lesquels j'ai déjà collaboré (
Ce n'est aps ce que je dis - je dis que lorsqu'on ajoute un email inconnu, qu'on clique sur partager, cet email / personne qu'on a invité doit apparaitre alors dans la liste, non ?

**Comment by julienzdocurba** [comment]
> Ce n'est pas ce que je dis - je dis que lorsqu'on ajoute un email inconnu, qu'on clique sur partager, cet email / personne qu'on a invité doit apparaitre alors dans la liste, non ?

Ah tu parles de la liste des personnes avec qui la procédure a été partagée ("Partagé avec:"), pas des suggestions? Si c'est le cas, oui le compte devrait apparaître dans la liste "Partagé avec:", mais pas encore dans les suggestions car on ne l'a pas priorisé.

**Comment by HermanceGauth** [comment]
Pour compléter le premier point d'Octavie il y a deux manières d'ajouter un user inconnu : 

1) Une fois la procédure créée: https://jam.dev/c/e541ad1e-327d-4cf4-8cbe-7206d895502f
On reçoit bien une notification slack mais je n'ai pas reçu d'email de partage et le collaborateur n'apparaît pas.

2) Ou à la création de procédure : https://jam.dev/c/5eaa8c3f-03dd-40dc-9950-6c6085a848f9
La ça semble fonctionner, je reçois bien le mail et j'apparait dans les collaborateurs

**Comment by UngererFabien** [comment]
J'ai rajouter l'alerte à l'ajout de collaborateur. Mais par default je n'ai pas le bon design. Est ce que quelqu'un se souvient si ce design d'alertes à été intégrer ailleur ?

**Comment by julienzdocurba** [comment]
Je suis pas 100% sûr mais on était sensés l'avoir sur la suppression de versement DGD aussi il me semble:
![image](https://github.com/user-attachments/assets/cc2972e6-caba-4ac1-8719-b1748c05018a)


Sinon tu as quoi comme design? On peut regarder ensemble si c'est plus simple.

**Comment by Octaviedebs** [comment]
Et @julienzdocurba est-ce qu'il était prévu de l'avoir aussi lors du Retrait du collaborateur ? 
SI non vous nous direz comment l'indiquer (issue / feedback) pour une prochaine itéra°.

FYI @CeliaVermicelli

**Comment by julienzdocurba** [comment]
Oui également sur le retrait de collaborateur:
![image](https://github.com/user-attachments/assets/29384232-6cb2-49de-8438-0176c99d6b48)
