### ISSUE TITLE
QA Partage de proc | Doublon dans les collaborateurs

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#828]
A plusieurs reprises on a constaté des doublons dans les collaboborateurs alors qu'ils ont qu'UN seul compte sans alias du tout.

<img width="678" alt="Capture d’écran 2024-09-25 à 10 16 08" src="https://github.com/user-attachments/assets/55238597-2614-4039-b0bb-bf73456a5232">

<img width="1394" alt="Capture d’écran 2024-09-25 à 10 17 42" src="https://github.com/user-attachments/assets/d3969554-b07f-425d-a776-7533e9c788e8">

**Lien frise** : https://dev.docurba.beta.gouv.fr/frise/c571c674-7016-4781-b134-10394637311d
Tu peux aussi constater un doublon sur Clément Bébin aussi

**Comment by lerayj** [comment]
done local
