### ISSUE TITLE
QA Partage de proc. | Je ne dois pas pouvoir retirer un collaborateur d'une procédure from sudocuh (pour éviter effets de bord du dump)

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#829]
Comportement attendu suite échange d'il y a 15 jours sur le comportement de retrait d'un collaborateur sur une proc. from sudocuh : voir la bible produit https://www.notion.so/docurba/Bible-FRP-21fe54962130453f887129a52f2264ff?pvs=4

![Capture d’écran 2024-09-25 à 10 26 05 AM](https://github.com/user-attachments/assets/dbc75658-a8c5-4836-8ab3-9a893fc5eb58)

OR actuellement, on voit le bouton Retirer un collaborateur (qui ne marche pas de tte façon cf autre [issue](https://github.com/MTES-MCT/Docurba/issues/826)

**Comment by lerayj** [comment]
done local
