### ISSUE TITLE
QA Partage de proc. | Les collaborateurs suggérés lors de la nouvelle proc. doivent être ceux inscrits s/ le périmètre

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#830]
Lors de l'ajout d'une nouvelle procédure, il faut que les collaborateurs suggérés lors de la nouvelle proc. soient ceux inscrits s/ le périmètre OR ce n'est pas le cas cf ce jam 

https://jam.dev/c/23d5a60a-55e4-497a-8a48-0433babdf189

OR FLorian LERAT est un user sur la commune de Augan de l'EPCI CC Oust à brocéliande
<img width="1426" alt="Capture d’écran 2024-09-25 à 10 33 32" src="https://github.com/user-attachments/assets/5006a241-6166-40f8-8d08-d1e63d235bfd">

Pour une procédure existante ET from sudocuh c'est ok

**Comment by HermanceGauth** [comment]
Comme indiqué lors du point qu'on avait fait ensemble, la règle pour les CT semble être la même que celle pour les DDT : on voit toutes les personnes de CT du département alors que pour le CT on ne devrait voir que celle du périmètre de la CT.

**Comment by lerayj** [comment]
done local
