### ISSUE TITLE
QA Partage de Proc. | Le créateur de la proc. n'est pas dans la liste des collaborateurs et ne peut pas finaliser l'ajout

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#831]
**Contexte** : je suis connectée sur le dpt 56 _(on peut voir qu'on a bien les droits d'ajout d'event etc)_ donc je devrais pouvoir aller au bout de la créa° de proc. 

https://jam.dev/c/0920d878-026b-403a-8bf2-655ce468da3a 

OR à la création d'une nouvelle proc, on a pu la créer mais on était pas ajouté d'office dans la liste des collaborateurs ce qui a empêché de finaliser la procédure.

**Comment by HermanceGauth** [comment]
Oui a fixe avant mep : le créateur de la procédure devrait être automatiquement collaborateur et pouvoir éditer la procédure.
Déjà signalé ici : https://github.com/MTES-MCT/Docurba/issues/715

**Comment by HermanceGauth** [comment]
Le problème semble avoir lieu uniquement lorsqu'on invite personne et qu'on clique sur "passer l'étape". Si j'invite quelqu'un je serais bien ajouter comme collaborateur automatiquement.

**Comment by lerayj** [comment]
done local
