### ISSUE TITLE
QA partage de proc. | Lien dans le mail de notification pour personne sans compte Docurba "Ouvrir la procédure" renvoie vers le partage de procédure

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#832]
https://dev.docurba.beta.gouv.fr/frise/adf542fb-23b7-4dac-b232-3afd8144fabb/invite
![image](https://github.com/user-attachments/assets/8003d2a0-a1d7-4cbc-b8ba-cbddbb9febd3)

**Comment by julienzdocurba** [comment]
Testé et c'est bon pour moi.
