### ISSUE TITLE
Pb de dump & de synchronisation des données sudocuh | CC de l'Aillantais en Bourgogne 

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#844]
Les dates de prescription des procédures secondaires du PLUi ne sont pas les bonnes donc la DDT a supprimé ces event (la CT a ajouté les bons depuis donc c'est son event qui fait foi) :

- modif simplifiée https://docurba.beta.gouv.fr/frise/3424a8b8-2e8b-4504-a59e-752da3f58e9d 
- révision allégée 1 https://docurba.beta.gouv.fr/frise/41525665-0291-4c58-9257-51ebf35a8d4d
- révision allégée 2 https://docurba.beta.gouv.fr/frise/8d553224-ace5-4922-ad0f-265ba22627cc

TO DO quand corrigé : prévenir & relancer Leslie TISSIER

**Comment by HermanceGauth** [comment]
@Octaviedebs ce qu'il faut faire c'est supprimer les prescriptions from Sudocuh pour ces trois procédures?
@CeliaVermicelli à mettre dans le tableau de correction manuelle suite à modification/suppression dans Sudocuh je pense.

**Comment by Octaviedebs** [comment]
Yes ce n'était effectivement pas clair du tout - tout à fait, il faudrait que ces events supprimées sur sudocuh puissent également disparaitre sur Docurba mais ce qui implique effectivement un changement de gestion de l'import / dump (prise en compte également des modications). 

Je peux l'ajouter moi même dans le tableau, je ne l'ai plus sous le coude mais si vous l'avez n'hésitez pas, sinon je rechercherai ça ! Et dès ajout, je close l'issue du coup ?

**Comment by CeliaVermicelli** [comment]
L'info était déjà dans le tableau ! (mais je n'avais linké la bonne issue 🤔 - c'est chose faite) 
![Capture d’écran 2024-11-20 à 3 09 55 PM](https://github.com/user-attachments/assets/167047a6-55e1-4605-8f93-a697c498f373)

Et personnellement je trouve toujours pertinent d'utiliser les issues pour donner plus de détails si besoin - closed ou pas, c'est top de garder une trace pour plus de précisions. 


### Pour rappel : 

[Voici le lien du tableau](https://docs.google.com/spreadsheets/d/1ATNoSmDqaWyygGVwU78hE3Og-E_FYapbc_5WMPbDlxo/edit?usp=sharing)
Et dans notion il se trouve en bas de la page "Tech"
<img width="1202" alt="Capture d’écran 2024-11-20 à 3 09 07 PM" src="https://github.com/user-attachments/assets/a39df9e1-fe28-4dc7-afe1-2196f7e87fe8">
