### ISSUE TITLE
Dialog share procedure: Order la liste des partage par dernier ajouté

### ISSUE THREAD

**Issue by lerayj** [MTES-MCT/Docurba#859]

**Comment by HermanceGauth** [comment]
@CeliaVermicelli @Octaviedebs il me semble issue issue (:)) de votre QA, est-ce tout bon en prod?

**Comment by CeliaVermicelli** [comment]
yes c'est ok en prod, le dernier ajouté apparait en haut de la liste dans la fenetre de partage. 
Je close.
