### ISSUE TITLE
Désactiver l'onglet "validation des procédures" utilisé pour l'enquête 2023 et toujours visible pour les ddt pilotes

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#873]
L'onglet est à désactiver sur les accès ddt des dpt suivants : 

25
29
35
56
58
81
89

<img width="1424" alt="Capture d’écran 2024-10-09 à 12 18 23 PM" src="https://github.com/user-attachments/assets/b38176d2-8723-422a-a94e-1204c322ebaa">

**Comment by HermanceGauth** [comment]
Nettoyer le code

**Comment by rik** [comment]
La suppression du code n'est pas indispensable pour le lancement de l'enquête, alors que la désactivation l'est.
La quantité de travail n'étant pas la même, je préfère séparer en deux tâches distinctes. J'ai ouvert #923 pour suivre la suppression.

**Comment by rik** [comment]
C'est en ligne!
