### ISSUE TITLE
REX fonctionnalité de partage des procédures 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#879]
Hello @julienzdocurba 

J'ai eu les premiers retours d'un agent sur la fenêtre de partage, j'explique tout dans la [demo](https://jam.dev/c/255c3c3e-95b4-437b-a2b7-237342ee1fb7)
en quelques mots : 
* il n'avait pas compris que l'encart de droite sur la FRP listait les collaborateurs effectifs
* dans la fenêtre de partage, il pensait que le "partagé avec" + liste" correspondait aux suggestions 
* dans la fenêtre de partage, il pensait qu'en cliquant sur "partager" il partageait la proc à l'ensemble de la liste et que cette fenêtre l'invitait à faire ça

Qu'en penses-tu ? Est-ce que tu vois des quick win pour clarifier ?
Bien sûr c'est la première personne, je verrai dans les prochains jours si d'autres agents ont les mÊmes difficultés, on peut attendre pour s'en reparler. 

**Remarque sur la notif de partage reçue sur le bot_admin** : c'est top de conserver les notif dès qu'un agent clique sur "partager" justement pour identifier ces incompréhensions

FYI @HermanceGauth & @Octaviedebs

**Comment by julienzdocurba** [comment]
Top merci beaucoup! Je pense qu'on peut mettre ca dans le feedback sur Notion et pas dans une issue. Je vais le faire. Il y a quand même un bug clairement identifié dans la vidéo et qui mérite une issue: Le bouton "Partager" devrait être désactivé tant qu'il n'y a pas d'email valide de saisi. Je vais ouvrir une issue pour ça.
Sinon plus globalement je suis d'accord avec toi et je pense qu'on peut garder un oeil là-dessus et voir si on a d'autres retours, notamment une fois que le bug ci-dessus sera résolu.

**Comment by julienzdocurba** [comment]
Je vais clore cette issue une fois que j'aurais ajouté le feedback à Notion au fait.

**Comment by CeliaVermicelli** [comment]
top merci ! et du coup tu cree aussi l'issue sur le bug du bouton à désactiver ?

**Comment by julienzdocurba** [comment]
Oui c'est fait ici: https://github.com/MTES-MCT/Docurba/issues/880

**Comment by julienzdocurba** [comment]
Et c'est ajouté au feedback ici: https://www.notion.so/docurba/7ed7389e9d9446b4aa3f696a476b5b62?v=23e53c0c33354264884261c914ab5c0e&p=11bbe4d354c080d1b5e5dd4f11ca0201&pm=s
Et ici: https://www.notion.so/docurba/7ed7389e9d9446b4aa3f696a476b5b62?v=23e53c0c33354264884261c914ab5c0e&p=11bbe4d354c080b9bb75fb120acce994&pm=s

N'hésite pas à compléter si il manque des éléments.
