### ISSUE TITLE
Mise à jour des liens hébergés sur Docurba (kit de com')

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#881]
Hello Fabien, suite à la MEP du partage de proc. il faudrait remplacer le contenu hébergé dans les liens suivant par les pdf que je te link à la suite. 
On en reparle au point ops.

**CT** 
remplacer https://docurba.beta.gouv.fr/pdf/kitdecom/CT/pourquoiutiliserdocurba.pdf par -> [le pdf suivant ](https://drive.google.com/file/d/1cq2jQVX8WA7tuPdjuMimF4TecjJOG2-M/view?usp=sharing)
remplacer https://docurba.beta.gouv.fr/pdf/kitdecom/CT/pasapas.pdf par -> [le pdf suivant ](https://drive.google.com/file/d/1bfqlysLVxWUnL_8Q3JT4tchvZiHSN0Rv/view?usp=sharing)

**BE** 

remplacer https://docurba.beta.gouv.fr/pdf/kitdecom/BE/pourquoiutiliserdocurba.pdf  -> [le pdf suivant](https://drive.google.com/file/d/1QieGEuElJISe2UqOWfecvvOJ1OysIQpa/view?usp=sharing) 
remplacer https://docurba.beta.gouv.fr/pdf/kitdecom/BE/pasapas.pdf -> [le pdf suivant ](https://drive.google.com/file/d/14caZrBKTDsIoMFpkfoQx510dI4AusuAG/view?usp=sharing)

**DDT** 

remplacer https://docurba.beta.gouv.fr/pdf/kitdecom/DDT/pourquoiutiliserdocurba.pdf -> le [pdf suivant ](https://drive.google.com/file/d/1nlLafmjCG40m-qLmsfAGgD23_YPIAfHj/view?usp=sharing)
remplacer https://docurba.beta.gouv.fr/pdf/kitdecom/DDT/pasapas.pdf -> le [pdf suivant](https://drive.google.com/file/d/14lfuYVid3mREPyRPAhwwS_KpER15G_Q1/view?usp=sharing)

**Comment by rik** [comment]
C'est en production !
