### ISSUE TITLE
Déploiement au push

### ISSUE THREAD

**Issue by lerayj** [MTES-MCT/Docurba#888]
Avoir des branche 1:1 avec la prod et le dev.

Scalingo ayant le déploiement au push prêt à l'emploi, plutôt que de le configurer sur les hébergeurs existants, déplaçons tout sur Scalingo. Cela simplifiera aussi les notes de frais et accélérera l'utilisation de fournisseurs français.

- [x] Déployer `docurba-nuxt3` sur Scalingo
  - [x] Brancher `docurba-nuxt3` sur Scalingo
  - [x] [Optimisation pour ne pas dépasser le timeout de 60s](https://github.com/betagouv/docurba-nuxt3/commit/0760692a6b859321faae567099ab2fad69fe2d8f)
  - [x] Changer les DNS pour pointer sur Scalingo
- [x] Déployer `docurba` sur Scalingo
  - [x] Réduire la taille du code pour passer sour 300Mo https://github.com/MTES-MCT/Docurba/pull/1051
  - [x] Brancher `docurba` sur Scalingo https://github.com/MTES-MCT/Docurba/pull/1052
  - [x] Changer les DNS de dev pour pointer sur Scalingo
  - [x] Changer les DNS de prod pour pointer sur Scalingo

**Comment by rik** [comment]
Travail terminé. Nous n'avons qu'une seule branche `main` désormais qui est déployée sur deux hébergements Scalingo qui ne diffèrent que par les variables d'environnement.
