### ISSUE TITLE
[ Bug ] Une procédure from sudocuh apparait avec un statut « gris » et la frp est inaccessible

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#910]
Hello, une procédure from sudocuh apparait avec un statut « gris » - 
<img width="1431" alt="Capture d’écran 2024-10-21 à 18 19 46" src="https://github.com/user-attachments/assets/2ffa5b21-1470-4409-a697-90b4a65ffc9b">

La FRP n'est pas accessible.

Lien page CT : https://docurba.beta.gouv.fr/collectivites/200067882/?isEpci=false

Le jam =
https://jam.dev/c/03609fc0-ac05-4bfe-b708-1914bddae6ec

**Comment by CeliaVermicelli** [comment]
autre cas : 
https://docurba.beta.gouv.fr/ddt/35/collectivites/200039022/epci

de mon côté j'accède quand même à la FRP de la CC de la capture suivante :

<img width="1352" alt="Capture d’écran 2024-10-22 à 12 02 10 PM" src="https://github.com/user-attachments/assets/4e817846-012b-4c50-9648-2a88d3e3c278">

**Comment by HermanceGauth** [comment]
Cas remonté par Claire :
![image](https://github.com/user-attachments/assets/442af933-4da2-4143-98d9-92d3635a42f1)

**Comment by CeliaVermicelli** [comment]
### Autre cas dans le 32 : Gers. 

[PLUi en cours d'elaboration](https://docurba.beta.gouv.fr/frise/4dbd4081-e984-4980-8cb1-731b68102784) et statut "gris" depuis la page de l'EPCI - affiché "archivé" depuis l'onglet "mes collectivités"


<img width="981" alt="Capture d’écran 2024-11-13 à 10 34 45 PM" src="https://github.com/user-attachments/assets/5d793868-1bb5-42f9-b1ee-209de01b1651">
<img width="904" alt="Capture d’écran 2024-11-13 à 10 34 34 PM" src="https://github.com/user-attachments/assets/c8c1acaa-31a0-4531-bc31-3d4f15bfeca7">


- [ ] Olivier C. si résolu dans moins de 3 mois, sinon : Remi T.

**Comment by HermanceGauth** [comment]
Statuts gris corrigé voir ce loom vers 3min : https://www.loom.com/share/1683e7bdb93142269e5fce819cc8c40a?sid=990001a6-89ce-4537-99f2-f4a36fc08ac7

**Comment by Octaviedebs** [comment]
Cette issue est tout ok pour moi - de mon côté il me reste juste cette [FRP](https://docurba.beta.gouv.fr/frise/7ac5e1db-67a1-43ca-b5f7-0a43c0cfa883) qui continue de tourner en rond : peut être créer une autre issue pour ça du coup non @HermanceGauth ça te va ?
 
Célia je te laisse faire ta TO DO et close l'issue.
