### ISSUE TITLE
[ Bug ] Erreur de statut  | Statut precedent sur une procédure alors qu'il n'y a aucune autre procédure opposable ou en cours

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#911]
https://docurba.beta.gouv.fr/collectivites/200069698 

<img width="1417" alt="Capture d’écran 2024-10-22 à 10 37 32" src="https://github.com/user-attachments/assets/f7588f64-4498-4ed5-9bec-a8605bb3bb13">

Statut precedent sur la procédure de PLUi alors qu'il n'y a aucune autre procédure opposable ou en cours

**Comment by Octaviedebs** [comment]
Même souci ici https://docurba.beta.gouv.fr/collectivites/200071538/?isEpci=false
<img width="1417" alt="Capture d’écran 2024-10-22 à 11 08 48" src="https://github.com/user-attachments/assets/bf5041df-b773-4161-99dd-f1f2beeafcf4">

**Comment by Octaviedebs** [comment]
Même souci ici https://docurba.beta.gouv.fr/collectivites/200071645/?isEpci=false

<img width="1417" alt="Capture d’écran 2024-10-22 à 11 24 08" src="https://github.com/user-attachments/assets/772df4c4-644e-409d-a54f-0bb629e37133">

**Comment by Octaviedebs** [comment]
https://docurba.beta.gouv.fr/collectivites/247100290/?isEpci=false

<img width="1417" alt="Capture d’écran 2024-10-22 à 11 29 52" src="https://github.com/user-attachments/assets/cae8ff93-df89-4ad2-8506-5e37e2a52853">

**Comment by Octaviedebs** [comment]
https://docurba.beta.gouv.fr/collectivites/247100589/?isEpci=false

<img width="1417" alt="Capture d’écran 2024-10-22 à 11 42 14" src="https://github.com/user-attachments/assets/b1caed22-4a0f-43a6-affb-823c2385c3f0">

**Comment by Octaviedebs** [comment]
https://docurba.beta.gouv.fr/collectivites/247103765/?isEpci=false
<img width="1417" alt="Capture d’écran 2024-10-22 à 11 52 23" src="https://github.com/user-attachments/assets/b3c02a1a-ae30-486b-941e-3f6370ad230a">

**Comment by Octaviedebs** [comment]
https://docurba.beta.gouv.fr/collectivites/247103864/?isEpci=false

<img width="1417" alt="Capture d’écran 2024-10-22 à 11 57 16" src="https://github.com/user-attachments/assets/78eaf2c4-0dd1-44bd-8829-eb2814c6fe52">

**Comment by Octaviedebs** [comment]
Note Octa dès mep : finir déploiement R1 EPCI 71

**Comment by Octaviedebs** [comment]
Je ne les référence pas tous mais à nouveau ici dans un autre département (67)
 https://docurba.beta.gouv.fr/collectivites/200041325/?isEpci=false

**Comment by Octaviedebs** [comment]
https://docurba.beta.gouv.fr/collectivites/200067783/?isEpci=false : et je sais qu'ils étaient en opposables avant j'ai retrouvé un message en ce sens qui date d'avril

**Comment by CeliaVermicelli** [comment]
autre cas dans le 46 : 

https://docurba.beta.gouv.fr/ddt/46/collectivites/244600573/epci
![Capture d’écran 2024-10-22 à 5 41 38 PM](https://github.com/user-attachments/assets/90ec1fc1-7b04-4cf9-afb8-fa00272309ed)

**Comment by HermanceGauth** [comment]
@CeliaVermicelli @Octaviedebs ça a l'air revenu à la normal, je vous laisse prévenir et closed si c'est bon?

**Comment by CeliaVermicelli** [comment]
yes c'est bon de mon côté

**Comment by Octaviedebs** [comment]
yes j'ai tt vérif tt ok merci !
