### ISSUE TITLE
Perte de contenu suite à la suppression de fiches dupliquées

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#92]
DDT 13 
user adrien.porcher@bouches-du-rhone.gouv.fr 
projet de pac concerné : [https://docurba.beta.gouv.fr/trames/projet-4122fdf3-19c5-4a66-ac78-0b78d489cf23](https://docurba.beta.gouv.fr/trames/projet-4122fdf3-19c5-4a66-ac78-0b78d489cf23)

La fiche thématique "s'adapter et lutter contre le changement climatique" apparaissait en double : il a récupérer le contenu et en a ajouté dans une des deux fiches pour enfin supprimer celle qui était vide -> cela a supprimer les deux fiches thématique dont celle où il y avait tout son travail de rédaction. 

-> je n'ai pas réussi à répliquer ce bug sur un projet où j'avais aussi une fiche dupliquée 
-> est-ce que c'est possible de retrouver son contenu et de le repusher dans son projet ?

**Comment by UngererFabien** [comment]
Je vais regarder pour le content perdu dans l'historique des commits.

**Comment by CeliaVermicelli** [comment]
email du concerné avec PJ : 

Bonjour,

Suite à notre discussion je voulais vous dire que la fiche thématique en objet a bien été réintégrée à mon PAC-ScoT du pays d'Arles effectué sur la ville sur Arles

Ce qui est bien c'est qu'il n'y a désormais qu'une fiche intitulée "s'adapter et lutter contre le réchauffement climatique"

Ce qui ne va pas c'est que je n'ai récupéré qu'une toute petite partie de mon travail qui portait sur le PCET de la période précédente

Or, j'avais effectué un gros travail sur cette fiche de plusieurs pages avec des illustrations des projets et des PJ

S'il vous plait récupérez ce travail très important pour moi

merci d'avance

![Sans titre](https://github.com/MTES-MCT/Docurba/assets/111045572/0314e03c-59dd-4a44-874f-8a77fabaac87)

**Comment by UngererFabien** [comment]
Sorry pour le delay sur cette issue. J'ai récupéré son travail et je l'ai remis direct dans sa trame de projet.

Le texte de l'introduction avait été rechangé. Je ne savais pas lequel garder donc je n'ai pas toucher à l'intro mais je peux lui remettre ce qu'il avait s’il veut.

**Comment by CeliaVermicelli** [comment]
Top merci ! écoute je pense que tu peux tout lui remettre (quitte à faire 2 sections intro) et ensuite il se débrouille, je vais le prévenir, 
Et oui je les rassure toujours en disant que c'est jamais perdu grace à github. Mais j'avais un doute là dessus : c'est quand mêem perdu s'ils n'ont pas enregistré les modifs sur une section, non ?

**Comment by UngererFabien** [comment]
Oui si ils n'ont jamais enregistré et qu'ils quitent la page c'est perdu. Mais quand ils suppriment une section elle reste dans l'historique. Toutes les modifications reste dans l'historique.

![Screenshot 2023-10-12 at 14 13 28](https://github.com/MTES-MCT/Docurba/assets/2676385/82fb7bef-a483-4af9-8fa8-94b64b3f6720)

**Comment by CeliaVermicelli** [comment]
@UngererFabien voici le retour de Mr porcher au sujet de son contenu : 

Bonjour madame Vermicelli,

J'ai put regarder

Malgré votre demande il n'y a qu'une seule rubrique qui a été récupérée, malheureusement pas celle qui m'intéresse le plus et qui contenait les éléments contextualisés avec les projets sur le territoire.

Seuls les textes élaborés par docurba sur les GES, le cadre juridique et les dispositions à prendre dans les PLU (ainsi qu'un court texte que j'ai rédigé sur le PCET existant) apparaissent

En revanche, si les éléments Scot arrivent effectivement pour lundi ce sera à temps pour que je puisse les reprendre

cordialement

-> tu vois d'autres choses qui pourraient être récupées, apparemment il ne retrouve pas son contenu.

**Comment by CeliaVermicelli** [comment]
(seulement pour centraliser les infos) 

Dernier retour de Mr Porcher : 

> En ce qui concerne l'enregistrement de mon travail je l'ai bien enregistré même si je ne suis pas sur pour la toute dernière version. Quand j'ai effacé, c'était l'une des deux fiches "s'adapter et lutter contre le réchauffement climatique" qui étaient en doublon.
> 
> Merci pour l'export pdf mais les difficultés rencontrées nous ont conduit à faire finalement ce pac du ScoT sous format papier et j'ai déjà rapatrié toutes mes fiches sous format .odt
> 
> En conclusion je suis encore intéressé :
> à récupérer mes travaux effacés par erreur sur la fiche "s'adapter et lutter contre le réchauffement climatique" jusqu'en fin de semaine prochaine au plus tard. Passé ce délai vous pouvez abandonner les recherches.
> Et bien sur, par les éléments généraux sur le ScoT si ils arrivent aussi la semaine prochaine :  je les récupérerais pour les intégrer à notre version papier.
