### ISSUE TITLE
Partage de procédure avec Lea Dentz ne fonctionne pas

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#929]
Hello ! 

Rien ne semble fonctionner sur la fonctionnalité de partage de procédure :
- ni le retrait
- ni le partage : on a fait ça en direct live avec partage d'écran avec une user et elle ne reçoit ni email ni n'a de droits sur les procédures que je lui partage

Voir ce jam clair j'espère :  https://jam.dev/c/c41e4aa8-2325-4473-8875-3867e3a6f0d5

Lien de la frise : https://docurba.beta.gouv.fr/frise/79d0b4fb-7586-4df2-a174-b8a367ef5d60
Email de connexion : je suis toujours connectée avec mon compte superadmin octavie.dbs+test@docurba.beta.gouv.fr

**Comment by rik** [comment]
Merci pour le jam.

Deux informations supplémentaires toujours utiles pour débugguer :
- L'URL de cette procédure ?
- L'email du compte avec lequel tu es connectée.

**Comment by Octaviedebs** [comment]
Ah yes, désolée ! 

Lien de la frise : https://docurba.beta.gouv.fr/frise/79d0b4fb-7586-4df2-a174-b8a367ef5d60
Email de connexion : je suis toujours connectée avec mon compte superadmin octavie.dbs+test@docurba.beta.gouv.fr

**Comment by rik** [comment]
@lerayj Peux-tu donner des explications sur la cause du problème ?

**Comment by lerayj** [comment]
Il y a eu 2 problèmes: 
Pour le delete il y a eu un problème de droit des RLS qui avait été mis a jour - le check_permissions avait mal été ajouté dans la condition:
<img width="553" alt="Capture d’écran 2024-11-13 à 18 55 12" src="https://github.com/user-attachments/assets/f9ff6743-5edb-4329-bc9b-d74005b32a67">

Et pour le add c'est suite a l'ajout de l'analytics de suivi des partages de procédures qui avait son module du plugin Nuxt mal importé et qui faisait fail en silence.

**Comment by rik** [comment]
Merci pour les précisions. Comme il n'y avait rien de spécifique à Lea Dentz et que l'ajout et la suppression de collaborateurs était cassé pour tout le monde, je change le titre pour refléter l'ampleur du problème.

**Comment by rik** [comment]
Début des soucis d'ajout :
- Commit https://github.com/MTES-MCT/Docurba/commit/8fb5366287b8af75dfd57d2da7cd71450cbe8cc7 le 31 octobre à 17h49.
- En production à partir du 31 octobre 2024 à 17:55

Correction de l'ajout :
- Commit: https://github.com/MTES-MCT/Docurba/commit/24a4a68cd8d5fec8d32b72cef9dc774b2909d675 le 5 novembre à 17h12.
- En production à partir du 5 novembre 2024 à 17:20:39

**Comment by rik** [comment]
Dans la base de données :
- le dernier partage avant bug était le 31 octobre 2024 à 16:15.
- le premier partage après correction était le 5 novembre à 17h25.
