### ISSUE TITLE
Cacher les collaborateurs non actifs de la liste des collaborateurs et de la modale de partage

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#939]
Lors de la mise en place de cette [issue](https://github.com/MTES-MCT/Docurba/issues/682) il faudrait concomitamment ajouter une condition pour ne plus afficher ces collaborateurs non actifs du coup dans la liste des collaborateurs et dans la modale de partage.

Cependant : 
-  il faudrait pouvoir continuer à voir le Nom / Prénom de ces users non actifs qui avaient précédemment ajoutés des événements
- il faudrait peut être ajouter une mention pour que ce soit plus clair (ancien ou inactif ou autre)

J'ai ajouté cette issue pour bien la dissocier de l'issue ops mais il y a peut être d'autres points à préciser sur ce qu'on veut.
FYI @julienzdocurba @CeliaVermicelli

**Comment by julienzdocurba** [comment]
Je pense qu'on devrait ajouter ca au backlog et pas dans une issue car c'est pas un bug c'est une nouvelle fonctionnalité. Je serais super prudent avec ce genre de feature parce qu'à vouloir trop automatiser on risque de se retrouve avec un système incompréhensible + le problème de comptes inactifs n'est pas propre à Docurba et c'est très rare qu'il soit automatisé comme ca. Mais en tout cas on peut le lister dans le backlog et en discuter.

**Comment by julienzdocurba** [comment]
Oui à priori si l'issue 682 ne concerne que Pipedrive ca ne devrait pas avoir d'impact sur le produit donc c'est bien ca je pense!

**Comment by Octaviedebs** [comment]
Ajouté dans le backlog - je close
