### ISSUE TITLE
Pouvoir accèder à l'édition de PAC depuis l'encadré de la procédure principale

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#94]
![image](https://github.com/MTES-MCT/Docurba/assets/91552054/060c694d-91fb-4020-b45a-f21ab0606fb0)

**Comment by HermanceGauth** [comment]
Pour les DDT uniquement

**Comment by UngererFabien** [comment]
Cette issue n'est plus d'actu. Il faudra match le design des nouvelles procedures et faire un lien sur les projets avec une distinction des procedure exporter de Sudocuh.
