### ISSUE TITLE
Pop-up NPS : retours sur le Partage de procédure

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#941]
[Lien du Form](https://tally.so/r/wzQkQk)

### Format : 
pop-up en bas à droite

### Conditions d'apparition : 
* sur les accès connectés
* Quelque soit le side 
* sur toutes les pages de FRP (exemple : https://docurba.beta.gouv.fr/frise/f447175a-df39-4e36-bf10-c86fdc576b47)
* récurrence : 
-> **2 fois max**. 
Exemple : si je ferme la pop-up **sans répondre**, elle ne réapparaîtra qu'une seconde fois - idéalement à la connexion suivante. 
Dans le cas où je réponds, la pop-up n'apparait plus.

@Octaviedebs

**Comment by Octaviedebs** [comment]
@CeliaVermicelli 
Comme il y a la pop up NPS FRP aussi - je propose de la mettre en pause jusqu'au 31.12 et de la remplacer par celle-ci de partage.

Qu'en penses tu ?

**Comment by Octaviedebs** [comment]
Merci pour la question - j'ai tendance à penser qu'on peut l'afficher tout de suite sans condition : en effet, je me dis qu'avec le partage de procédure, un user invité va atterrir directement sur une FRP > donc rapidement interagir / voir le bouton Partager > et potentiellement l'utiliser _(si lui même souhaite ajouter un collaborateur)._

On avait mis cette condition pour l'autre NPS FRP en se disant que lorsqu'un user se créé un compte de lui même il n'allait pas forcément tout de suite avoir à utiliser la FRP. 

J'espère que c'est clair - @CeliaVermicelli qu'en penses tu ?

**Comment by rik** [comment]
Si je puis donner mon avis, je pense qu'il faut quand même un petit buffer, peut-être pas 30 jours comme les autres mais 7 jours ?

En mettant 0 jours d'ancienneté, Roger reçoit une invitation pour une procédure, crée son compte, atterrit sur une FRP, boum on lui demande son avis sur le partage alors qu'il n'a même pas encore lu la FRP. Bah Roger, s'il a mon caractère, va être ronchon parce qu'il était venir pour faire son travail et qu'il n'a pas pu lire sa FRP avant qu'on l'enquiquine. En plus, Roger n'a même pas utilisé la fonctionnalité, il en a juste bénéficié parce que Denis l'a invité.

**Comment by Octaviedebs** [comment]
Yes je suis alignée - mon seul point c'est que côté collectivités, le risque dans l'usage est le suivant : 

_Roger reçoit une invitation pour une procédure, crée son compte, atterrit sur une FRP, ajoute un événement , partage à son BE, quitte l'outil. Peu de chance qu'il se reconnecte 7 jours plus tard car les prochaines étapes seront plus tôt dans 1 ou 2 mois._ 

Mais on récupèrera des verbatims grâce au volume plus nombreux de procédures gérées par les DDT

**Comment by Octaviedebs** [comment]
> si le délais d'appararition était de quelques minutes passées sur une FRP ça m'irait aussi.)

Oui je suis assez d'accord. On pourrait partir sur 7 minutes au lieu de 7 jours par exemple ça laisse le temps d'arriver sur la FRP etc.

**Comment by rik** [comment]
Pour ne pas complexifier les choses et garder le code existant, on va rester sur la règle "compte créé depuis N jours". Du coup, vous voulez un compte vieux de 1 jour ? 2 jours ? 7 jours ?

**Comment by Octaviedebs** [comment]
1 jour parfait - yes tu as raison

**Comment by rik** [comment]
C'est déployé. Je me suis permis de sauter la phase QA car je suis sûr de ce qui était souhaité et de ce que j'ai réalisé.
