### ISSUE TITLE
Bug dump ? Nouvelles saisies depuis Sudocuh non remontées sur Docurba (exemple Gourhel 56 - Linas 91 - plusieurs 83)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#942]
### Gourhel 56 
[Lien commune ](https://docurba.beta.gouv.fr/ddt/56/collectivites/56065/commune)
**Problème** : la ddt a renseigné sur Sudocuh une nouvelle procédure (avec prescription) pour une élaboration de PLU au 17 octobre et sur Docurba on ne la voit toujours pas. 
On ne retrouve que la CC opposable. 

<img width="865" alt="Capture d’écran 2024-11-08 à 11 38 49 AM" src="https://github.com/user-attachments/assets/8da93faa-5162-4db1-99a2-65d7b69047e5">
<img width="1423" alt="Capture d’écran 2024-11-08 à 11 37 27 AM" src="https://github.com/user-attachments/assets/93ccfb55-26b3-40c9-a71a-0ea730d14744">

- [x] emmanuel et bastien

### QA en prod 12.11 à 12h30 
on retrouve bien la nouvelle proc. - élab de PLU (+ sa prescription) - mais le statut est "gris" en lien avec cette issue https://github.com/MTES-MCT/Docurba/issues/910
![Capture d’écran 2024-11-12 à 12 19 30 PM](https://github.com/user-attachments/assets/0d2e28c1-64d6-45d7-89a8-15a149f617e7)

**Comment by CeliaVermicelli** [comment]
### Linas 91

[Lien FRP](https://docurba.beta.gouv.fr/frise/f3a49dd8-3ba6-458f-a322-89aae5ecfe04)

La ddt a enseigné l'approbation sur Sudocuh et l'info n'était pas remontée sur Docurba donc la ddt l'a remise sur Docurba : si c'est effectivement un bug, il y aura 2 approbations sur cette FRP. 

- [ ] Severine LP et Imed

**Comment by CeliaVermicelli** [comment]
### ddtm 83

Sur l'intégralité des documents vérifiés ce matin, toutes les dates saisies dans SuDocUH depuis mon retour vers le 21 octobre et novembre 2024 n'apparaissent pas dans Docurba,

[AUPS](https://docurba.beta.gouv.fr/ddt/83/collectivites/83007/commune)
J'ai saisi la date exécutoire de la modification n°2 dans SuDocUH depuis le 31/10/2024 (date exécutoire le 02/11/2024), elle n'apparait toujours pas dans Docurba.

[CALLIAN](https://docurba.beta.gouv.fr/ddt/83/collectivites/83029/commune)
la révision du PLU de Callian a été approuvée le 23/09/2024, là les dates apparaissent bien (y compris la date exécutoire du 01/10/2024 donc le problème a dû arriver plus tard en octobre pour la non remontée des dates) mais la procédure apparait comme étant EN COURS ?
Toujours plus bizarre, les dates apparaissent bien jusqu'au caractère exécutoire et l'évènement suggéré est la prescription du conseil municipal ?

[FREJUS](https://docurba.beta.gouv.fr/ddt/83/collectivites/83061/commune)
La plupart des dates de la modification n°2 approuvée le 19/09/2024

[LA ROQUE ESCLAPON](https://docurba.beta.gouv.fr/ddt/83/collectivites/83109/commune)
dates concernant la modification n°1 approuvée le 15/10/2024 toutes absentes

LA [SEYNE](https://docurba.beta.gouv.fr/ddt/83/collectivites/83126/commune)
Mise à jour du 08/10/2024 : n'apparait pas du tout

[LE LAVANDOU
](https://docurba.beta.gouv.fr/ddt/83/collectivites/83070/commune)J'ai créé le 06/11/2024 une mise à jour du 22/10/2024 exécutoire le 24/10/2024, elle n'apparait pas dans Docurba

[LE MUY](https://docurba.beta.gouv.fr/ddt/83/collectivites/83086/commune)
dates concernant la mise en compatibilité du PLU approuvée le 23/09/2024 touts absentes

[SAINT RAPHAEL](https://docurba.beta.gouv.fr/ddt/83/collectivites/83118/commune)
J'ai noté des diverses dates pour la modification simplifiée n°1 le 24/10/2024, elles n'apparaissent pas dans Docurba (dates début et fin mise à disposition du public, approbation, transmission au contrôle de légalité, publication, exécutoire).
J'ai aussi créé une mise à jour du 21/10/2024, elle n'apparait pas du tout.

[SAINT TROPEZ](https://docurba.beta.gouv.fr/ddt/83/collectivites/83119/commune)
Une révision n°2 du PLU a été prescrite en 2022, les dates sont bien remontées dans Docurba.
Par contre, cette même révision apparait dans les procédures secondaires de la révision actuellement opposable, je ne pensais même pas qu'il était possible de saisir une révision en procédure secondaire ?

[LE THORONET
](https://docurba.beta.gouv.fr/ddt/83/collectivites/83136/commune)prescription de la modification n°2 par arrêté du 08/10/2024 absente de Docurba

[TOULON](https://docurba.beta.gouv.fr/ddt/83/collectivites/83137/commune)
prescription de la modification n°6 le 30/09/2024 : absente de Docurba

[VIDAUBAN](https://docurba.beta.gouv.fr/ddt/83/collectivites/83148/commune)
Notification de la modification n°2 par courrier du 03/10/2024 : absente de Docurba

**Comment by lerayj** [comment]
Il y a eu un problème sur le dump avec la modification pour rattacher les procédures secondaires. Je ne sais pas pourquoi mais la base de donnée c'est mis a refuser les appels a la base de donnée si on ne lui explicitait pas les droits d'usage.

La seyne, lavandou, saint raphael, le thoronet, toulon et Vidauban, potentiellement le muy -> procedure secondaire mal rattaché suite a ce problème.

Saint Tropez, effectivement ce n'est pas normal que la révision soit une secondaire, j'essaye de comprendre ce qui a pu la rattacher. J'ai vérifié et fait un script qui check ca pensant que potentiellement il y en aurait plusieurs avec cette erreur,mais St tropez semble être la seule. Je vais manuellement supprimer et voir si ca reviens par le dump, ou si c'est une modif manuelle qui a été faite par erreur. (id: 74c39ee8-3c7d-448d-b5d9-22da5c6bc97f)

**Comment by CeliaVermicelli** [comment]
> [Saint Tropez](https://docurba.beta.gouv.fr/ddt/83/collectivites/83119/commune), effectivement ce n'est pas normal que la révision soit une secondaire, j'essaye de comprendre ce qui a pu la rattacher. J'ai vérifié et fait un script qui check ca pensant que potentiellement il y en aurait plusieurs avec cette erreur,mais St tropez semble être la seule. Je vais manuellement supprimer et voir si ca reviens par le dump, ou si c'est une modif manuelle qui a été faite par erreur. (id: 74c39ee8-3c7d-448d-b5d9-22da5c6bc97f)


@lerayj je ne vois plus la révision nº2 dans la liste des PS donc a priori on est bon !

**Comment by rik** [comment]
> Il y a eu un problème sur le dump avec la modification pour rattacher les procédures secondaires. Je ne sais pas pourquoi mais la base de donnée c'est mis a refuser les appels a la base de donnée si on ne lui explicitait pas les droits d'usage.

@lerayj Est-ce que cela signifie qu'entre le moment où tu as ajouté les modifications pour rattacher les procédures secondaires (e420a1ef le 28 octobre) et le 12 novembre, aucun import journalier n'a été effectué ?
