### ISSUE TITLE
Bug Statut : le statut n'est pas mis à jour suite à l'ajout de l'approbation pour la révision du PLU de Callian (83)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#949]
[CALLIAN](https://docurba.beta.gouv.fr/ddt/83/collectivites/83029/commune)
la révision du PLU de Callian a été approuvée le 23/09/2024, là les dates apparaissent bien (y compris la date exécutoire du 01/10/2024  mais la procédure apparait comme étant EN COURS ?

<img width="953" alt="Capture d’écran 2024-11-12 à 2 37 09 PM" src="https://github.com/user-attachments/assets/18e6c38f-2ee0-486c-b870-bb2a58bd10ba">

<img width="875" alt="Capture d’écran 2024-11-12 à 2 37 34 PM" src="https://github.com/user-attachments/assets/1039646a-fc16-4fde-a2b8-067129a3e3c4">

**Comment by HermanceGauth** [comment]
@CeliaVermicelli ça m'a l'air OK

**Comment by CeliaVermicelli** [comment]
c'est good
Josiane prévenue, je close.
