### ISSUE TITLE
Problème statut gris : la procédure qui était manquante s'affiche maintenant avec un statut "gris" (Saballian)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#957]
[lien FRP concernée](https://docurba.beta.gouv.fr/frise/7c8257c2-f70b-4bff-adcb-93a6a1b9a577)

Pour rappel, le 12.11, julien a fix un pb sur l'import Sudocuh - cf [cette issue](https://github.com/MTES-MCT/Docurba/issues/942). 

Quelques jours avant, la ddt m'informait de cette procédure de révision manquante. -> elle est bien présente auj. et charge correctement mais sont statut est buggué, apparait juste en "gris" 

<img width="1074" alt="Capture d’écran 2024-11-13 à 10 26 55 PM" src="https://github.com/user-attachments/assets/dfe1466d-12fd-423e-b2f8-632b2cc7be55">

- [x] Olivier C. si résolu dans moins de 3 mois, sinon : Remi T.

**Comment by HermanceGauth** [comment]
corrigé voir ce loom vers 3 min : https://www.loom.com/share/1683e7bdb93142269e5fce819cc8c40a?sid=990001a6-89ce-4537-99f2-f4a36fc08ac7
