### ISSUE TITLE
le 01 ne retrouve pas deux PAC créés en juillet 

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#96]
Laurence : "les PAC réalisés en juillet : Abergement de Varey et Bourg-en-Bresse n'apparaissent pas".
CF PJ. et "et pour Bourg-en-Bresse, la nouveauté du matin : c'est que je n'ai plus de document!" CF PJ2

![ckdakikdemoaojig](https://github.com/MTES-MCT/Docurba/assets/111045572/abf804d9-b955-4950-ba98-3199ce210630)
![dgippphibnmeldhg](https://github.com/MTES-MCT/Docurba/assets/111045572/36f2a572-e158-481e-a4a5-1551a81d187d)

**Comment by CeliaVermicelli** [comment]
update de Laurence en fin de journée @lerayj : 
elle a bien retrouvé la liste des DU/historique mais pas son PAC en cours pour Bourge en Bresse. 
![gpcmbgfbmigneich](https://github.com/MTES-MCT/Docurba/assets/111045572/d7aaef93-7ff0-40ff-819c-4720a6a9e0dd)

**Comment by UngererFabien** [comment]
Correctif en prod à cette date. J'attend la confirmation de Laurence pour close l'issue.
