### ISSUE TITLE
Attention il manque des groupements dans la pre-prod par rapport à la prod (a priori les SMO et SMF qui ont été rajoutés récemment)

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#960]
Quand je suis en prod : https://docurba.beta.gouv.fr/ddt/36/collectivites 19 lignes
Quand je suis en pre-prod : https://dev.docurba.beta.gouv.fr/ddt/36/collectivites 15 lignes, il manque les SMO et SMF

**Comment by rik** [comment]
@UngererFabien Il me semble que c'est parce que https://github.com/MTES-MCT/Docurba/commit/42269847 n'est dans la branche dev.

**Comment by rik** [comment]
Comme j'ai du faire un déploiement de `dev`, je me suis permis de synchroniser les branches.

@HermanceGauth Je passe en QA

**Comment by HermanceGauth** [comment]
Ok pour moi, je close puisque c'était déjà bon en prod
