### ISSUE TITLE
L'évènement d'approbation du SCoT n'est pas le bon, cela devrait être "Délibération d'approbation"

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#961]
cf ligne 54 du tableau, onglet SCoT :https://docs.google.com/spreadsheets/d/1NEcWazdx7LvpnydcyP4pBdFWl9fI_Iu9zy9AQcDtll0/edit?gid=518812151#gid=518812151
![image](https://github.com/user-attachments/assets/047fe77d-1d55-463b-826c-6fbef9a1659f)
Dans la liste des évènements des procédures SCoT il faut mettre le libellé qui est indiqué dans le tableau qui sert de base, car sinon le libellé n'est pas exact en termes métier.
Actuel : "Délibération d'approbation du conseil municipal ou communautaire" 
Attendu : "Délibération d'approbation"

**Comment by rik** [comment]
En dev

**Comment by rik** [comment]
En prod, j'ai vérifié et je ferme.
