### ISSUE TITLE
Périmètre d'un SM porteur de SCoT faux

### ISSUE THREAD

**Issue by HermanceGauth** [MTES-MCT/Docurba#963]
Il n'y a pas 666 communes dans cet EPCI
![image](https://github.com/user-attachments/assets/579574c6-b356-4d58-bb44-bcf5b3b24ead)
https://docurba.beta.gouv.fr/ddt/36/collectivites/253602650/epci
Actuel : montre un nombre de membres erroné
Attendu : monter le bon nombre de membres (et les bons membres)

**Comment by HermanceGauth** [comment]
autres exemples, où le chiffre augmente à chaque fois que je rafraîchis la page : https://jam.dev/c/6609a8f6-f264-4c3a-aba3-73a6e44f11f1

**Comment by HermanceGauth** [comment]
Résolu sur dev

**Comment by rik** [comment]
En prod, j'ai vérifié et je ferme.
