### ISSUE TITLE
Bug : des procédures from Sudocuh ne s'ouvrent pas (Clairac et Lafitte sur lot - 47)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#972]
Procédures concernées : 

### [Clairac](https://docurba.beta.gouv.fr/ddt/47/collectivites/47065/commune)

La procédure qui ne s'ouvre pas (from sudocuh) : https://docurba.beta.gouv.fr/frise/15c4f099-bc70-4092-8bdf-f1edfc5a76c9 

### [Lafitte sur Lot](https://docurba.beta.gouv.fr/ddt/47/collectivites/47127/commune)
La procédure qui ne s'ouvre pas (from Sudocuh) : https://docurba.beta.gouv.fr/frise/f5375be5-5f4b-42b4-bc73-219174b20775

### [Varès](https://docurba.beta.gouv.fr/ddt/47/collectivites/47316/commune) 
La procédure fom sudocuh ne s'ouvre pas : https://docurba.beta.gouv.fr/frise/20fedbc3-cab1-4989-b56a-b0c237643eb3

### [Grateloup saint Gayrand](https://docurba.beta.gouv.fr/ddt/47/collectivites/47112/commune)
La proc qui ne s'ouvre pas (from sudocuh) : https://docurba.beta.gouv.fr/frise/f23cd769-a8cd-42da-ad58-3b83436d2e4e

to do bizdev : 
- [ ] décider la suppression ou non de ces proc sudocuh, si oui, s'assurer que l'autre proc en doublon est bien partagée aux be et ct 
- [ ] dder à la ddt de basculer ses event dans l'une ou l'autre des procédures (Desplat et Gaudino)

@Octaviedebs

**Comment by Octaviedebs** [comment]
Exemple de cette [FRP](https://docurba.beta.gouv.fr/frise/7ac5e1db-67a1-43ca-b5f7-0a43c0cfa883) de Bazois Loire Morvan qui ne s'ouvrent pas

**Comment by CeliaVermicelli** [comment]
Pour info et rappel - Cette issue est liée directement à la #872 car ce sont des procédures qui à priori seront amenées à être cachées, donc possiblement clore cette issue en même temps que les doublons éliminée lors de la 872. 

### Liste des actions proposées à la DDT auj par email pour la gestion de ces doublons (et donc ces procédures qui ne s'ouvrent pas) :

**1. Le Mas Agenais :** on a 2 révision du PLU : une de Sudocuh et une de Docurba
Celle issue de sudocuh (https://docurba.beta.gouv.fr/frise/15bbb0f5-78d5-499c-bd40-db41f53e6327) a moins de saisies, 
Proposition : 
cacher la procédure issue de Sudocuh 
Si ok pour vous : il faudra ressaisir l’événement existant dans la procédure qui sera conservée (créée sur docurba : https://docurba.beta.gouv.fr/frise/cd9090ea-013b-4226-9d40-d56c05df3e20 ) 

**2. Caumont sur Garonne** : problème similaire : 
Celle issue de sudocuh (https://docurba.beta.gouv.fr/frise/bc41cd01-6dc4-42cc-9821-d543ca0d210c) a moins de saisies, 
Proposition : 
cacher la procédure issue de Sudocuh 
Si ok pour vous : il faudra ressaisir l’événement existant dans la procédure qui sera conservée (créée sur docurba : https://docurba.beta.gouv.fr/frise/f0f27795-e78a-479b-b84b-c4683b440bef ) 

**3. Clairac** : problème similaire + la procédure issue de Sudocuh ne s’ouvre pas correctement
Celle issue de sudocuh (https://docurba.beta.gouv.fr/frise/1fcb41d2-db00-4c81-ad76-cd57abfc62b4) ne s’ouvre pas. J’ai de la visibilité sur les saisies historiques des 3 derniers mois et vous ne semblez pas y avoir ajouté d’événements. 
Proposition : 
cacher la procédure issue de Sudocuh 
Conserver celle créée sur docurba : https://docurba.beta.gouv.fr/frise/55eb9e08-5a59-4e95-85d4-4a56ac060fa7 

**4. Varès :** Mêmes problèmes que Clairac

Proposition : 
Cacher la procédure issue de Sudocuh qui ne s’ouvre pas : https://docurba.beta.gouv.fr/frise/20fedbc3-cab1-4989-b56a-b0c237643eb3
Conserver la procédure créer sur Docurba : https://docurba.beta.gouv.fr/frise/75308490-4f7b-4043-8e81-4f9631f2589b
Idem, d’après mon historique des 3 derniers mois, pas d’événement ajoutés dans cette feuille de route que je propose de cacher donc semble ok. 

**5. Lafitte sur Lot** : même pb que précédemment : 
Proposition : 
Cacher la procédure issue de Sudocuh qui ne s’ouvre pas : https://docurba.beta.gouv.fr/frise/39394644-3fe9-4572-ad81-4e1bd080011d
Conserver celle que vous avez été plusieurs à déjà alimenter 100% depuis Docurba : https://docurba.beta.gouv.fr/frise/f2694b19-7dea-4f85-a78a-5973b66f2982

**6. Grateloup saint Gayrand :** même problème.

Proposition :
Issue de sudocuh à cacher : https://docurba.beta.gouv.fr/frise/46c605c7-6c32-4a0c-9747-ae8d3ccb7b66 -> je n’y vois pas non plus d’événement renseignés les 3 derniers mois. 
100% docurba à conserver : https://docurba.beta.gouv.fr/frise/f95fd038-d1db-4837-b35d-408cb803cb46

**7. Lagruère :** 
Proposition : 
Cacher la procédure issue de sudocuh : https://docurba.beta.gouv.fr/frise/72e7bdc6-3f48-4018-9483-d0a1bd94772b qui ne comporte qu’un seul événement en plus de la prescription (et qui peut rester là)
Conserver la procédure 100% Docurba : https://docurba.beta.gouv.fr/frise/79ec7a2e-06aa-414d-8f33-ff12b52f306a

**8. Tonneins :** 

Je ne vois qu’une seule révision avec le statut en cours où la commune et BE ont ajouté effectivement plusieurs événement : https://docurba.beta.gouv.fr/frise/8926645a-6b9a-47d8-97e9-00b099fb8660 (procédure issue de Sudocuh)
Mais je ne vois pas de doublon, est-ce que je rate quelque chose ? Ou bien vous avez déjà supprimé le doublon qui était moins fourni en événement depuis notre appel de ce matin ?

**9. Marcellus :** 

Il y a deux modification nº1 du PLU opposable : je vous laisse basculer les événements d’une procédure dans l’autre et supprimer le doublon souhaité.
Sur les deux révision n1 en cours : 
Celle issue de sudocuh est à cacher : https://docurba.beta.gouv.fr/frise/05868595-0ce4-4f20-9b5e-7c44c404a21a
Et on conserve celle de Docurba : https://docurba.beta.gouv.fr/frise/80669533-8295-47e8-9b6e-01001dda2be0

**Comment by Octaviedebs** [comment]
**Vu de vive voix mais note pour moi même &  pour l'historique** : de mon côté j'ai prévenu le bureau d'études pour **s'assurer qu'ils ne continuent pas d'ajouter des événements sur les mauvaises procédures.**ll y a beaucoup de procédures (c'est le même bureau d'études pour toutes ces procédures) donc ce serait vraiment super que cela puisse être géré rapidement.

**TO DO Octa :**
prévenir [contact@urbadocbadiane.fr](mailto:contact@urbadocbadiane.fr) quand c'est résolu

**Comment by CeliaVermicelli** [comment]
Cas traités via l'issue #1034 et le [doc excel](https://docs.google.com/spreadsheets/d/189sgPJHEoLHqR0aoizgd2YzS6DumSbAPPSH_-iGZ3SI/edit?gid=1995940740#gid=1995940740) de gestion des doublons et procédures introuvables. 
DDT et BE prévenus, je ferme
