### ISSUE TITLE
On devrait afficher les Métropoles et les CU dans le tableau de bord ddt

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#977]
### Problème : Metz Métropôle n'est pas trouvable depuis l'onglet "mes collectivités".
Alors que [la page de l'EPCI](https://docurba.beta.gouv.fr/ddt/57/collectivites/200039865/epci) existe bien. 
Il faut par contre **passer par la page de la commune de Metz pour accéder à l'EPCI.** 

[Demo Metz](https://jam.dev/c/6d71bda1-90af-4d18-8591-70b88b9dce39)

- [x] Huguette DDT

**Comment by HermanceGauth** [comment]
@UngererFabien j'ai l'impression que globalement on n'affiche pas (plus?) les métropoles dans le dashboard.

**Comment by CeliaVermicelli** [comment]
On ne les affiche "plus" alors, car il n'y a pas si longtemps je me souviens retrouver la métropole d'aix-marseille !

**Comment by HermanceGauth** [comment]
Les métropoles et les CU sont bien dans le référentiel.

**Comment by rik** [comment]
@lerayj On pense qu'il faut juste ajouter des checkbox en plus dans le dropdown "Type de collectivité" pour ajouter CU et METRO. Si c'est le cas, on le fait. Sinon, donne nous des infos pour qu'on décide quand on travaille dessus.

**Comment by rik** [comment]
C'est en production, je te passe la main @CeliaVermicelli.
