### ISSUE TITLE
Erreur sur les statuts de deux procédures SCoT (57) suite à annulation TA (from Sudocuh)

### ISSUE THREAD

**Issue by CeliaVermicelli** [MTES-MCT/Docurba#979]
[CF page EPCI ](https://docurba.beta.gouv.fr/ddt/57/collectivites/200067486/epci)

Lien vers les deux SCOT qui devraient avoir le statut "annulé" car la DDT avait ajouté (sur Sudocuh) l'event "annulation TA"  : 

[ Révision SCOT SM SCOT agglomération thionvilloise
](https://docurba.beta.gouv.fr/frise/7fc7cced-adb0-4841-8b57-8a33a1b3e904)
[Elaboration SCOT SM SCOT agglomération thionvilloise
](https://docurba.beta.gouv.fr/frise/408f1ad7-1739-42b7-9122-c414dce45397)

<img width="988" alt="Capture d’écran 2024-11-19 à 5 52 59 PM" src="https://github.com/user-attachments/assets/63e50aa7-c43b-4b38-bd81-21793e7986e8">

- [x] Mme Gritti - ddt

**Comment by UngererFabien** [comment]
Corrigé pour ces deux la. Si il y a d'autre cas ils seront régler par les prochains dump. Je fais la pull request dans l'aprem.

**Comment by rik** [comment]
En prod, je te transmets @CeliaVermicelli pour ta todo list.

**Comment by CeliaVermicelli** [comment]
@rik euh je vois toujours les mêmes statuts et donc la non prise en compte de l'événement d'annulation TA : 

<img width="1052" alt="Capture d’écran 2024-12-18 à 1 55 30 PM" src="https://github.com/user-attachments/assets/9dfe84f7-af89-4ad8-aeae-5efdef562aee" />

**Comment by rik** [comment]
Vu ensemble : les statuts sont maintenant bons.
