### ISSUE TITLE
BUG | Cette procédure from sudocuh charge indéfiniment

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#982]
La frise suivante tourne en boucle et ne charge jamais : https://docurba.beta.gouv.fr/frise/18d32493-bb03-436f-ac11-f8f57ed35e7e
Je suis connectée comme d'habitude avec mon email octavie.dbs+test@docurba.beta.gouv.fr 

@CeliaVermicelli a eu le même souci.
@HermanceGauth je ne sais pas exactement à quelle milestone le rattacher : Problème avec les procédures ? Import ? 

Il s'agit d'une procedure from sudocuh.
La conséquence c'est que du coup ils en ont créé une autre (donc à nouveau des doublons).

Merci par avance !

**Comment by rik** [comment]
Avec le boulot de https://github.com/MTES-MCT/Docurba/pull/1023, on voit maintenant que c'est une procédure inexistante.

Par contre, je n'ai pas d'infos sur comment elle a été supprimée.

**Comment by rik** [comment]
(je t'assigne l'issue pour montrer que la balle est dans ton camp pour la suite à donner à cette issue)

**Comment by Octaviedebs** [comment]
Merci ! J'aurais dû préciser de quelle collectivité il s'agissait
Je ne l'ai pas fait parce qu'on a généralement sur l'URL de la frise, la flèche de « retour » vers la collectivité concernée
Avec ce nouveau message d'erreur (qui est top du coup) impossible pour moi de savoir quelle collectivité cela concerne

@rik Y a t il une information dans l'URL de cette frise qui m'aiderait à le savoir ? 
Ou as tu la possibilité de le savoir en base ? 

Merci !

**Comment by Octaviedebs** [comment]
Ok mince - parce que j'ai besoin de la supprimer sur Docurba maintenant mais c'est de ma faute ! 
Bon à savoir en tout cas, je vais close l'issue

**Comment by rik** [comment]
> j'ai besoin de la supprimer sur Docurba

Elle est supprimée sur Docurba donc je ne comprends pas ce message. Voulais-tu dire "j'ai besoin de la supprimer sur Sudocuh" ?

**Comment by Octaviedebs** [comment]
> Elle est supprimée sur Docurba donc je ne comprends pas ce message
Elle est supprimée dans la base de donnée Docurba, mais elle est affichée sur le tableau de bord ou la collectivité du coup non ? D'où l'intérêt de faire atterrir l'utilisateur sur ce message du coup non ? 

Dispo via slack audio si besoin :)
