### ISSUE TITLE
Passer un event « privé » en « public  » suite à un changement d'email user

### ISSUE THREAD

**Issue by Octaviedebs** [MTES-MCT/Docurba#996]
**Frise** : https://docurba.beta.gouv.fr/frise/def7b4c4-c1a8-421d-8306-f90bc87b4fdc

**A faire** : passer l'event Délibération de prescription du conseil municipal ou communautaire  en « public » et non « privé ».
L'utilisatrice ne peut plus le faire car elle a changé de compte

**Contexte** : 
- l'utilisatrice avait initialement un compte avec communaute-de-communes@mussidan.fr 
- elle avait ajouté un event 
<img width="1395" alt="Capture d’écran 2024-11-26 à 13 39 56" src="https://github.com/user-attachments/assets/a60ed909-393c-4045-ae56-c2b890f3d161">
- elle a changé d'email => du coup elle a du refaire un compte
- elle ne peut plus modifier cet event qu'elle a envie de passer en public
- je n'ai pas la possibilité de le faire 

TO DO Octa : prévenir Lucie LAVERGNE ccicp@ccicp.fr  cf spark

**Comment by Octaviedebs** [comment]
@rik

**Comment by Octaviedebs** [comment]
@rik pour info avec Célia on a l'habitude de close les issues quand on a fait nos TO DO (prévenir les users concernés)
Donc quand ce sera géré tu pourras juste me pinguer et je m'occuperai de la prévenir avant de close l'issue (je l'ai eu au tel à l'instant, elle est en attente, je lui ai dit « cette semaine » mais n'hésite pas si tu as un contre temps que je la prévienne

Merci !

**Comment by Octaviedebs** [comment]
Je souhaitais faire un petit message de suivi pour qu'elle sache où cela en est.
Je peux temporiser sans souci mais je voulais juste avant les vacances lui donner de la visibilité. 
merci à toi par avance !

**Comment by Octaviedebs** [comment]
<img width="1427" alt="Capture d’écran 2024-12-17 à 16 28 27" src="https://github.com/user-attachments/assets/76329d15-ab65-440a-9a4e-e2a388107798" />

Je me trompe peut être mais l'événement est toujours en Privé je crois - sauf si tu l'as fait en dev ?

**Comment by rik** [comment]
Ah pardon, j'ai pas changé le titre. J'ai juste changé l'owner, ce qui lui permettra de changer la visiblité de l'event. Comme on s'était dit [la semaine dernière](https://github.com/MTES-MCT/Docurba/issues/996#issuecomment-2531024584).

**Comment by Octaviedebs** [comment]
D'acc ! Je pensais qu'au passage on changerait aussi la visibilité de l'event pour lui éviter une autre action _(en plus de changer l'owner)_ mais 0 souci elle s'en occupera ! Email fait CT prévenue ✅ je close 

Merci bcp en tt cas
